### ISSUE TITLE
enhancement of printGalleryIndexURL()

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1000]
hi
there is a suggestion of enhancement of printGalleryIndexURL() in template-function.php.

for my themes (but maybe for other one), I use custom index page (gallery.php), but I dont't want to display full breacrumb (home url >> gallery url) in gallery, albums and images pages (home link is displayed elsewhere).

I suggest you to add a bool (default is true) to display (or not) full breacrumb. 

```
/**
 * If a custom gallery index page is set this first prints a link to the actual site index (home page = index.php)
 * followed by the gallery index page link. Otherwise just the gallery index link
 * 
 * @since 1.4.9
 * @param string $after Text to append after and outside the link for breadcrumbs
 * @param string $text Name of the link, if NULL "Gallery" is used
 * @param bool $printHomeUrl In case of custom gallery index, display breadcrumb with home link (default is true)
 */
function printGalleryIndexURL($after = NULL, $text = NULL, $printHomeUrl = true) {
	global $_zp_gallery_page;
	if(is_null($text)) {
		$text = gettext('Gallery');
	} 
	$customgalleryindex = getOption('custom_index_page');
	if($customgalleryindex && $printHomeUrl) {
		printSiteHomeURL($after);
	}
	if ($_zp_gallery_page == getOption('custom_index_page').'.php') {
		$after = NULL;
	}
	if(!$customgalleryindex || ($customgalleryindex && in_array($_zp_gallery_page, array('image.php', 'album.php', 'gallery.php')))) {
		printLinkHTML(getGalleryIndexURL(), $text, $text, 'galleryindexurl'); echo $after;
	}
}
```

**Comment by acrylian** [comment]
We will take a look. These functions are of course meant to be generic. For specific usages you can always build your own part using the separate `getGalleryIndexURL()` function, too.

**Comment by vincent3569** [comment]
hi Malte,
in fact I created my own version of zp_printGalleryIndexURL with code above

**Comment by acrylian** [comment]
Yeah, I understand, will take a look later but your suggestion might make sense. A bit short on time currently.
