### ISSUE TITLE
403 Forbidden after save image options in admin panel

### ISSUE THREAD

**Issue by thommycgn** [zenphoto/zenphoto#1001]
Trying to save the Options of Images in admin panel (admin-options.php?page=options&tab=image) results in an 403 Forbidden Error Message.
Nothing in the Logfiles.... 
Other Options can be saved without problems.

Using Zenphoto 1.4.12, new installation on Apache server.

**Comment by fretzl** [comment]
Are file/folder permissions correct ?
http://www.zenphoto.org/news/permissions-for-zenphoto-files-and-folders

**Comment by fretzl** [comment]
Continued on the forum http://www.zenphoto.org/support/topic.php?id=1409438
