### ISSUE TITLE
RSS Comment feeds for news and pages fail - Class 'news' not found in class-feed.php

### ISSUE THREAD

**Issue by cbraymen** [zenphoto/zenphoto#1003]
I was getting an rss feed error from the "Subscribe to comments" feed link at the bottom of a ZenPage news article.  The php code that generates that link is at line 405 in file \zp-core\zp-extensions\comment_form.php:    

       printRSSLink("Comments-news", "", gettext("Subscribe to comments"), "");

The error that I received from accessing the feed URL was:

<b>Fatal error</b>:  Class 'news' not found in <b>zp-core/class-feed.php</b> on line <b>456</b><br />

The problem is line 456 of class-feed.php tries to new a class using the name of the item 'type', which is either 'news', or 'pages' at that point.  I believe the intent was to new a ZenpageNews, or a ZenpagePage class instead.  I changed the code on my site to the following and the problem went away:

					//CGB $obj = new $item['type']($titlelink);
					if ($item['type'] == 'news')
						$obj = new ZenpageNews($titlelink);
					else
						$obj = new ZenpagePage($titlelink);

Hope this is helpful to you, and thanks for a cool product!
-Chris

Zenphoto version 1.4.12 [c1d7e8900b] (Official build)
Current locale setting: en_US.UTF8
Current gallery theme: Libratus
PHP version: 5.6.19

**Comment by acrylian** [comment]
Oh, yes, indeed. Thanks!
