### ISSUE TITLE
RSS image comments are adorned with language and length tags

### ISSUE THREAD

**Issue by cbraymen** [zenphoto/zenphoto#1005]
When receiving RSS feeds of comments on images, the album name is pre-pended to the image name, but the album name sometimes has extraneous info in it, looking something like "a1: {s5: 'en_us' s11: 'Hello World''}.  

To correct this, I think _zp-core\class-feed.php_, line 434:

   $category = $item['albumtitle'];

should be:

   $category = get_language_string($item['albumtitle']);

This decodes the album name in the same way way it is decoded just below at line 443, for the comments on albums.

Thanks!
-Chris

**Comment by acrylian** [comment]
Indeed, that one must have escaped us and no one noticed for years… Thanks again!
