### ISSUE TITLE
Googlemap fails to display if a marker title contains double-quote

### ISSUE THREAD

**Issue by cbraymen** [zenphoto/zenphoto#1006]
If I have a title on a geo-tagged photo that contains a double quote, such as: 

"The Bean" at night

then the google map extension will fail to display, and you'll see an error on the google chrome console that says "Uncaught SyntaxError: Unexpected identifier".    

Because CodeIgniter-Google-Maps-V3-API\Googlemaps.php::**add_marker()** ultimately uses the title within a quoted string (line 278), I think the title needs to have quotes escaped before passing it to add_marker().

My fix is in GoogleMap.php::**addGeoCoord()**, after line 251, adding two new lines:

>> 251		$marker['title'] = $coord['title'];
>>		$marker['title'] = str_replace('\"', '"', $marker['title']);
>>		$marker['title'] = str_replace('"', '\"', $marker['title']);			

That fixes the issue for me.  Perhaps there is a more official escaping method you like?  Anyway,hope this helps.  

Really loving ZenPhoto..thanks again!
-Chris

**Comment by acrylian** [comment]
For slashes PHP has `addslashes()` that probably would do this.
