### ISSUE TITLE
Unpublished news still appear

### ISSUE THREAD

**Issue by offrench** [zenphoto/zenphoto#1007]
Unpublished news appear normally on homepage and on the full news list.
Tested with 1.4.12 with the Zenpage theme.

**Comment by fretzl** [comment]
Are you sure you're not logged in ?

**Comment by offrench** [comment]
Woops. No, I was logged in. I even tested on two websites, but was logged in on both. 
I had not had seen this for some time, sorry.

**Comment by fretzl** [comment]
Happens to all of us ;-)
