### ISSUE TITLE
printLatestComments() can return unclosed html tags from the truncated comment

### ISSUE THREAD

**Issue by cbraymen** [zenphoto/zenphoto#1008]
I'm using the TinyMCE4 plugin with the comment_form plugin.  This lets me add html links (and other html tagged data?)  into the comment data.  Cool, right?

I'm also using Libratus theme which can be configured to display the "Latest Comments" in the footer section of the site pages.  It does this by calling _printLatestComments()_ from _zp-core\zp-extensions\comment_form\functions.php_.  That function truncates the comment text in order to show a short excerpt of the comment.  But the truncation doesn't take html tags into consideration, so sometimes it can cause an unclosed tag to appear in the comment excerpt.   In my case, an unclosed anchor tag is causing some text later on the page to appear as a link. (See "Latest Images" in the attached screenshot which should not be a link)

![lastestcomments](https://cloud.githubusercontent.com/assets/19520317/15993234/4cb5f134-309c-11e6-8e83-6fdc70bfcaa8.JPG)

Since other themes use the same _printLatestComments()_ function, I don't believe this is a problem specific to Libratus.

Here is an example where the comment has been truncated after the target attribute but before the closing of the anchor.  This leaves the anchor open to affect the subsequent text:

`<li><a href="/photoalbum/2014/20140830-Cedar%20Bluffs/P1020522.JPG" class="commentmeta">20140830-Cedar Bluffs: P1020522 by Chris</a><br />
<span class="commentbody"><p>From <a href="http://www.campfontanelle.com/Docs/Original-Camp-Fontanelle-Development-Plan-1959.pdf" target="_blank"...</span></li>`

What is the right solution here?  To strip out all html tags from the excerpts printed by _printLatestComments()_?

Thanks! - Chris

Zenphoto version 1.4.12
Current gallery theme: Libratus

**Comment by fretzl** [comment]
Thanks!
I guess there are two possibilities.
1) In /zp-extensions/comment_form/functions.php: line 812, use *strip_tags()* on $comment['comment'].
2) In /zp-extensions/comment_form/functions.php: line 812, replace *truncate_string()* with *shortenContent()*

**Comment by cbraymen** [comment]
Great..thank you!  strip_tags() makes it work perfectly!
-Chris

		$shortcomment = truncate_string(strip_tags($comment['comment']), $shorten);

**Comment by fretzl** [comment]
We decided to incorporate option 2 in the build and introduce an extra parameter ($shortenindicator)
This means that *printLatestComments()* now preserves HTML and "..." is appended to the truncated string by default.
