### ISSUE TITLE
v1.4.12: Gibberish in Comments RSS Feed Titles.

### ISSUE THREAD

**Issue by MarkRH** [zenphoto/zenphoto#1010]
My Comments RSS Feed had item titles like: `a:1:{s:5:"en_US";s:13:"Misc Pictures";}: Healthy Lungs by jamie thompson`

Went poking around in **/zp-core/class-feed.php** and changed line 434 from:
`$category = $item['albumtitle'];`
to:
`$category = get_language_string($item['albumtitle']);`
This made the title: `Misc Pictures: Healthy Lungs by jamie thompson`

**Comment by acrylian** [comment]
I believe this is a duplicated of #1005 already fixed. Please try the support build therefore.

**Comment by MarkRH** [comment]
Ahh, OK. I will grab it then.  Yes, the latest support build does correct it. Closing this.

**Comment by acrylian** [comment]
No problem! Official update coming soon as well. We are/were a bit sidetracked by vacation times and also non ZP stuff currently sadly…
