### ISSUE TITLE
Slideshow2 with "linkSlides" option creates bad links.  (double-encodes the link URL)

### ISSUE THREAD

**Issue by cbraymen** [zenphoto/zenphoto#1011]
In zp-core/zp-extensions/slideshow2.php, on line 358 the anchor link for the slide is created by calling pathurlencode($imgobj->getLink()).   I believe that Image::getLink() already urlencodes the image path, so I get a link that has been double encoded and doesn't work.

For example:
- I  have an image that resides in my site at "photoalbum/albums/2016/20160622-Chicago Trip/20160625_111700.jpg".   
- Calling $imgobj->getLink() on that image returns "/photoalbum/2016/20160622-Chicago%20Trip/20160625_111700.jpg" which correctly encodes the space in the album name.
- But calling pathurlencode() on the already encoded image path then returns "/photoalbum/2016/20160622-Chicago%2520Trip/20160625_111700.jpg", where it has now encoded the "%" sign as %25 and the link no longer works.

For me, things seem to work correctly if I just use the return value from getLink() directly (2 edits):  

```
if ($carousel) {
   // on the carousel this means fullimage as they are always linked anyway
   if ($linkslides) {
      $url = pathurlencode($imgobj->getFullImageURL());
   } else {
      //CGB $url = pathurlencode($imgobj->getLink());
      $url = $imgobj->getLink();
   }
   $slidecontent .= '<a href="' . $url . '">' . "\n";
} else if (!$carousel && $linkslides) {
   //CGB $slidecontent .= '<a href="' . pathurlencode($imgobj->getLink()) . '">' . "\n";
   $slidecontent .= '<a href="' . $imgobj->getLink() . '">' . "\n";
}
```

Hope this is helpful, and thanks for all your work!
-Chris

**Comment by fretzl** [comment]
Thanks! I can confirm this.

**Comment by fretzl** [comment]
There are a few more occurences that probably need to be changed:
.../zp-extensions/externalFeed.php: line 340
.../zp-extensions/image_album_statistics.php: line590
.../zp-extensions/mobileTheme.php: lines 172 and 175

**Comment by fretzl** [comment]
..and thanks again Chris ! Your finds are much appreciated.
