### ISSUE TITLE
Text bug in printHomeLink method

### ISSUE THREAD

**Issue by jvanderb** [zenphoto/zenphoto#1012]
When you use the printHomeLink method, any text entered in the argument for "before" is displayed as "before" instead of the text passed in the argument.

On line 1496 of template-functions.php there is a typo.

The current line reads:
`echo '<span class="beforetext">' . html_encode(before) . '</span>';`

and should be changed to:
`echo '<span class="beforetext">' . html_encode($before) . '</span>';`

**Comment by acrylian** [comment]
Indeed, thanks!
