### ISSUE TITLE
getRandomImagesAlbum rare pdo error

### ISSUE THREAD

**Issue by coach777** [zenphoto/zenphoto#1014]
1.  Create album (ftp directory).
2.  Create subalbum (ftp directory) and make it unpublished.
     Subalbum must be only one in album.
3. Open gallery directly from URL in another browser (unlogged),
   There is a sql error.

SELECT `folder`, `filename` FROM `np_images`, `np_albums` WHERE `np_albums`.folder!="" AND `np_images`.albumid = `np_albums`.id AND `np_albums`.id IN) AND `np_images`.show=1 ORDER BY RAND() ;

Hotfix:
Change template-functions.php:: getRandomImagesAlbum() line 3331 
from
`$albumInWhere = prefix('albums') . ".id IN (";`
to
`$albumInWhere = prefix('albums') . ".id IN (0, ";`

**Comment by acrylian** [comment]
Thanks, perhaps the better fix will be to skip the `in ()` part if there is nothing for it at all.
