### ISSUE TITLE
Update colorbox plugin to latest version

### ISSUE THREAD

**Issue by viktorzen** [zenphoto/zenphoto#1015]
Would be cool to update colorbox with every zenphoto release.

**Comment by acrylian** [comment]
We also welcome contributions via pull requests ;)

**Comment by viktorzen** [comment]
ok, I need to set up a test environment and the github client first in order to contribute code. this will take some time ;)

**Comment by fretzl** [comment]
Fixed via 1cd75fd8d1d7ee32bd83c84a38f90273cb3eec63
