### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by viktorzen** [zenphoto/zenphoto#1016]
PHP 7 adds a lot of performance improvements to php which also zenphoto can benefit from. I have briefly tested zenphoto with php 7 and run into some errors, which need to be fixed. Also update the requirements page on the homepage to reflect when zenphoto is php 7.x compatible.

**Comment by acrylian** [comment]
We did only test briefly on PHP 7 but development is on 5.6 for some time already. If you already know actual errors with PHP 7 it would be actually helpful and save us time to add them here.

**Comment by acrylian** [comment]
The support build works with PHP 7. There might be issues hidden somewhere so we are dependent on proper reports on this.  Use a new ticket for that if needed.
