### ISSUE TITLE
admin rights on news doesn't work as it should be

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1017]
hi,

as discussed on zenphoto's forum (http://www.zenphoto.org/support/topic.php?id=1409548), admin rights on news doesn't work as it should be.

I have unpublished news with published category.
I have unpublished news with unpublished category (without password).
I have unpublished news with unpublished category (with a password).

In the two last cases, a user with no rights on news can't see unpublished news categories in news list, but can see unpublished news.

**Comment by acrylian** [comment]
Indeed, I can reproduce that. Apparently we missed something. It works correctly if not logged in as far as I can see but not for logged in users. Can you confirm that?

**Comment by vincent3569** [comment]
Yes I confirm.
The issue concerns only logged in users with no right on news.
As far I can see, there is no issue on unpublished pages and users with no right on pages. In that cas, users can't see these pages.

**Comment by acrylian** [comment]
Not fully fixed sadly, we are aware of it…
