### ISSUE TITLE
Typos in template-functions.php

### ISSUE THREAD

**Issue by sphoto** [zenphoto/zenphoto#1019]
Found typos at line 3715 of the current version:

<code>echo "<li" . $cl . "><a href=\"" . html_encode(getSearchURl('', $datekey, '', 0, array('allbums' => $albumlist))) . "\">$month ($val)</a></li>\n";</code>

should be:

<code>echo "<li" . $cl . "><a href=\"" . html_encode(getSearchURL('', $datekey, '', 0, array('albums' => $albumlist))) . "\">$month ($val)</a></li>\n";</code>

**Comment by acrylian** [comment]
Thanks, please next time maybe mark the actual part in bold or something so we don't have to look several times to spot it ;-). And there are pull requests, too ;-)

**Comment by sphoto** [comment]
Sorry but my git knowledge is very limited. I did make a fork of zenphoto 3 years ago and made ~20 pull requests. In the meantime zenphoto was changed a lot and my fork is outdated. How can I do a pull request from my 3 years old forked repository? I did not find a way to update it. It would be nice if you could explain it, maybe as an article on zenphoto.org?!

**Comment by acrylian** [comment]
Not a big deal actually as long as it is such small things like typos. 

Basically you have to keep your fork updated with the original repository. I think explaining it will exceed zenphoto.org as it is not directly zenphoto related. I am sure GitHub has some documentation about that. When I have some time I will see if I can find anything there or elsewhere (In case you fear the command line, there are GUI tools as well that I use, too)
