### ISSUE TITLE
Nginx + PHP 7.0.8 - MySQL Not Installed

### ISSUE THREAD

**Issue by joecasanova** [zenphoto/zenphoto#1020]
Hi all... I'm trying to set up and demo on my server an install of ZenPhoto 1.4.13.  My server is running the following:

Ubuntu 16.04
Nginx 1.10.0
PHP 7.0.8

MySQL is installed and works with many other PHP apps on this server.

Attached are PDF prints from the Zenphoto install on my server and the PHP page.
[phpinfo().pdf](https://github.com/zenphoto/zenphoto/files/637403/phpinfo.pdf)
[Zenphoto install.pdf](https://github.com/zenphoto/zenphoto/files/637404/Zenphoto.install.pdf)

What else can I provide to help?

**Comment by acrylian** [comment]
The error on the install pdf might indicate some file/folder permission issue. If you cannot fix that you need to do what the message tells. For running PHP 7 please try the support build (master here from GitHub)and not the official release.
