### ISSUE TITLE
include twentytwenty

### ISSUE THREAD

**Issue by ingbife** [zenphoto/zenphoto#1023]
I would like to have several before-after photos displayed in a gallery with twentytwenty. Can this be included?

**Comment by fretzl** [comment]
We have no intention of incuding that in the Zenphoto release.
Anything is possible but you will have to code it yourself.

**Comment by fretzl** [comment]
3rd party plugins are always welcome.
You could possibly use subalbums with only two images.
Just a thought ;-)
