### ISSUE TITLE
Missing the Zenpage Plugin - News Homepage

### ISSUE THREAD

**Issue by AlexL777** [zenphoto/zenphoto#1024]
Hello Developers,

I am a long friend of Zenphoto and have with me under http://fotos.alexl.eu/news/ the theme Libratus in the employment. Unfortunately the news is missed, so that the categories and the Adsense banner slipped down.

I've already tried other themes, the same result everywhere.

I do not know whether it is specifically Zenpage or something else.

Please take a look at this and how can I solve the problem?

Thanks in advance. The latest ZenPhoto version is installed.

**Comment by fretzl** [comment]
I cannot reproduce any of this.
But I can see that something is seriously wrong in your Libtratus theme. (misplaced HTML elements)
I suggest you delete the theme and then upload a fresh one again.

**Comment by AlexL777** [comment]
I could solve the problem. You are not allowed to display more than 5 article teasers on the news page. 

With 10 article teasers you shattered the layout. That was the whole problem. I have only set 5 news in the Zenpage options and everything is back in order.

**Comment by fretzl** [comment]
Glad you figured it out ;-)
