### ISSUE TITLE
Easier tags/title maintenance via new plugin ?

### ISSUE THREAD

**Issue by ceejayemm** [zenphoto/zenphoto#1026]
I have recently found ZenPhoto and have successfully installed it to display my 11000+ image library. Unfortunately few of my images have titles and no have tags I can use. I have looked at the existing way of adding titles and tags and it seems a bit long winded.

Having experimented with the Comments plugin, would it be possible to create a 'Title/Tags' plugin that allows a logged in user (ie admin or other nominated user) to add titles and tags whilst viewing the normal Gallery items in much the same way as Comments can be added ? This would give the ability to see a large or full screen image and add the necessary metadata as you work your way through the gallery.

Thanks

Chris

**Comment by fretzl** [comment]
Please see the answer on the forum.
http://www.zenphoto.org/support/topic.php?id=1409646#post-1978486
