### ISSUE TITLE
"Your Setup scripts are not protected"

### ISSUE THREAD

**Issue by thany** [zenphoto/zenphoto#1027]
Every now and then, this yellow message pops up on the admin panel.

Two things here that could be improved:
1) The action required to resolve the issue, could be performed automatically just fine. It doesn't seem to break anything, and it doesn't seem to be something that needs to take very long. And it does seem like something everybody should do. So why must we do it manually?
2) The message says, at the end, _Use the Setup » protect scripts button in the Admin section of the Utility functions._ - Every time i read that, I have to read it three times before I understand what it is referring to. It's very confusing. If nothing else, please make this bit a link to the required action directly, instead of tediously describing the location of the button.

**Comment by acrylian** [comment]
Good thoughts actually. I am currently more or less away for personal reasons so may take some time I am able to look into.

**Comment by thany** [comment]
That's alright, it's not a huge problem after all :)

**Comment by thany** [comment]
Think of it this way: what is the disadvantage of protecting the setup scripts?
If the answer is nothing, then don't bother the admin. Just do it.

**Comment by acrylian** [comment]
It's on the list and will be done some time. Just no priority right now though.
