### ISSUE TITLE
unprotected pages is not working

### ISSUE THREAD

**Issue by sammichael** [zenphoto/zenphoto#1029]
hello zenphoto team!

i am using 1.4.14 [f5b47da] and since a view updates i can't use the contact.php or register.php
my gallery is marked as privat and this two pages as unprotected.

but always i get asked for the password.

br
michael

**Comment by acrylian** [comment]
What exactly do you mean with "since a view updates"? From 1.4.13 to 1.4.14 nothing changed on this handling. We will have to take a look.

**Comment by sammichael** [comment]
i don't know exactly since which version it doesn't work any more, maybe 1-2 years ago. never had time to take care of.

**Comment by acrylian** [comment]
I sadly cannot reproduce this.

**Comment by sammichael** [comment]
thx for checking, so its not a common issue.
