### ISSUE TITLE
Graphic overhaul of the administrator interface

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1031]
Can you make a graphic overhaul of the administrator interface with a more modern, reactive and airy interface with fewer borders like this for example: http://preview.themeforest.net/item/flatkit-app-ui-kit/full_screen_preview/13231484?ref=cirvitis

**Comment by acrylian** [comment]
A rework of the backend is scheduled and in the works (but non public yet) for the next big release. See #191. And before you ask we sadly cannot say when this will be released.
