### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by Bozeken** [zenphoto/zenphoto#1032]
My company is the admin of a larger companies media hosting page, which uses zenphoto. We haven't had need to access it in quite a while, but we were informed this morning that none of their clients are able to access their files. It seems we are getting this error:

**Zenphoto encountered an error
MySQL Error: Zenphoto received the error mysqlnd cannot connect to MySQL 4.1+ using the old insecure authentication. Please use an administration tool to reset your password with the command SET PASSWORD = PASSWORD('your_existing_password'). This will store a new, and more secure, hash value in mysql.user. If this user is used in other scripts executed by PHP 5.2 or earlier you might need to remove the old-passwords flag from your my.cnf file when connecting to the database server.**

However, both our clients link as well as the admin link give the same error, so we can't even log in on the backend to try to fix this problem.

What is this and what can be done to solve this ASAP?

-Kevin

**Comment by sbillard** [comment]
You must change the password using a MySQL tool like your provider's control panel. Once changed you will need to change the password recorded in the zenphoto configuration file to whatever you selected above. The error message you got pretty well tells you what needs to be done.
