### ISSUE TITLE
Google adsense

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1034]
I have a zenphoto gallery and I want to monetize my site to pay the fees (domane name, hosting, maintenance ...) but when I searched on zenphoto.org there is no plugin to insert Ad site for google adsense. Can you integrate it into the development please to make my site live. Thank you

**Comment by acrylian** [comment]
Sorry, we will probably not do a plugin just for this. Maybe a plugin for adding general JS. But it is really easy to add that code snippet to your theme files yourself.

**Comment by acrylian** [comment]
I will close this as we won't create an actual plugin for this.
