### ISSUE TITLE
Flat Design

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1035]
Development of flat design theme because it is the current standard on the web.

**Comment by acrylian** [comment]
There will be a least a new theme – not necessarily "flat design"… though as standard change any time and are in the eye of the beholder – with the next major release (whenever that will be exactly as mentioned). 

But besides that you are always welcome to create a 3rd party theme using  flat design yourself and provide it to the Zenphoto community to use. As any open source project we need 3rd party contributions, we can't do everything.
http://www.zenphoto.org/news/general-contributor-guidelines/#providing-themes-and-plugins

**Comment by zorodimanche** [comment]
thx
