### ISSUE TITLE
Optimize the URLs

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1037]
Hi, Optimize urls for better SEO in search engines after several analyzes some osclass url are not seo friendly.
 
 Here are for example the urls that are not seo friendly :

- http://mywebsite.com/?locale=de_DE
- http://mywebsite.com/?locale=en_US
- http://mywebsite.com/?locale=ja_JP
- http://mywebsite.com/?locale=nl_NL

**Comment by acrylian** [comment]
It is suggested to use subdomains if you need to provide several language versions of your site. Zenphoto does not determine the language versions in the url (it just switches) although you can do that using the `seo_locale` plugin. Additionally use the html_meta_tags plugin to get an canonical url. 

Please take a look here: 
http://www.zenphoto.org/news/multi-lingual-sites/
