### ISSUE TITLE
Meta description

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1038]
Integrate into the theme the possibility of integrating a meta description
![sans titre](https://cloud.githubusercontent.com/assets/25553946/23118168/6eb2b3ac-f753-11e6-8adc-1a61df5aa049.png)

**Comment by acrylian** [comment]
Use the html_meta_tag plugin and it will use the gallery description for the index and on item (albums, images, news, pages) types the description respectively the content.
