### ISSUE TITLE
email notification

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1040]
Send an email when someone replies to a comment.

**Comment by fretzl** [comment]
The _comment_form_ plugin has an option (_Enable comment notification_) to notify the admin when someone posts a new comment.

**Comment by acrylian** [comment]
Additionally you can subscribe to an rss feed of comments.

**Comment by zorodimanche** [comment]
Not what I mean is not the notification for the administrator but for a registered user.
For example Mr A comments on a picture and Mr B replies to the comment of Mr A. Then Mr A receives an email telling him that Mr B answered his comment

**Comment by acrylian** [comment]
You can use RSS to subscribe to comments to get notified of anyone else commented. Internally there is actually no "reply" to a comment, just a new one. So a user would get mails for any new ocmment

But actually, sorry to say, there are no plans to add this right now.

**Comment by zorodimanche** [comment]
OK, thanks @acrylian

**Comment by acrylian** [comment]
We'll keep it in mind for later.
