### ISSUE TITLE
Bug Upload image

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1042]
When I load the images on zenphoto the script returns me this error whereas when I used another script like piwigo I did not have this problem.

![sans titre](https://cloud.githubusercontent.com/assets/25553946/23127497/8af871f0-f77b-11e6-9511-44703904fd0c.png)

**Comment by fretzl** [comment]
Looks like an issue with file/folder permissions.
Please check http://www.zenphoto.org/news/permissions-for-zenphoto-files-and-folders/

**Comment by zorodimanche** [comment]
OK but the permissions of the files and folders appear to be correct

**Comment by acrylian** [comment]
Is the user/owner as well? Some servers use different users for e.g. ftp and script execution that will cause such issues as well.

**Comment by zorodimanche** [comment]
Is it not the corruption of the metadata ?

**Comment by acrylian** [comment]
May also be corrupted meta data, a broken image file or anything else. Not easy to tell without an actual error message.

**Comment by zorodimanche** [comment]
I have another error message: Request Timeout
![sans titre](https://cloud.githubusercontent.com/assets/25553946/23134179/2099e6ea-f794-11e6-874f-ff46f486cfd3.png)

As a solution I found this : http://stackoverflow.com/questions/3829403/how-to-increase-the-execution-timeout-in-php

**Comment by acrylian** [comment]
You should really look into server based error logs as those message above are quite generic.

It may very well be related to corrupt meta data or the image being just to big to be processed for various reasons (see our user guide about that). So it could be a combination of several things. You could also try to limited the exif/meta data fields to be read (options > image).

**Comment by zorodimanche** [comment]
Ok @acrylian thank you that is actually ca because the default value was too high 3000 now there is no more error
