### ISSUE TITLE
Check requirement before upgrade ZenPhoto

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1043]
Implement a "pre-upgrade" check. On at least PHP and MySQL versions.

**Comment by acrylian** [comment]
Not sure what you mean, setup does check for that. Otherwise you need of course to look if your server supports the new version before you upload all the files.

**Comment by zorodimanche** [comment]
I've just lived a very bad experience with upgrade of another web application (let's call it webApp), but it could have happened to Zenphoto too! I'm using PHP 5.4 on this environement. The requirement for WebApp 2.16.5 was PHP version 5.3 and WebApp proposed me to upgrade to version 2.17. I agreed and the upgrade started. Unfortunately, WebApp 2.17 now requires PHP 5.5. My installation of WebApp is frozen.

**Comment by acrylian** [comment]
Since you have to upload manually currently, you need to check the release posts for requirement changes before uploading. We would note any requirement change there and it is most likely not happening on small release like 1.x or 1.4.x.

**Comment by zorodimanche** [comment]
Noted

**Comment by acrylian** [comment]
If we ever manage a one-click-update – which is not that trivial – there surely will be such a check (that is on the long list of things we want to do anyway…).
