### ISSUE TITLE
Details on the upload progression

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1045]
Instead of:

gif upload

Let's give more details:

Photo 4 of 11 (36% of 11MB, estimated time remaining 5 minutes)

**Comment by acrylian** [comment]
The jquery uploader actually displays a general progress bar. It is an adapted script and I don't know right now if it provides this info at all.

**Comment by zorodimanche** [comment]
No it don't provides this info

**Comment by acrylian** [comment]
We may switch to another uploader in the future anyway. So I will close this and will see when we get to this if it provides anything for this.

**Comment by zorodimanche** [comment]
Is what it will be replaced by this script because it displays the progress with the information: https://blueimp.github.io/jQuery-File-Upload/index.html

**Comment by acrylian** [comment]
Actually that is the script we use, although an quite older version. An update of the script is on the list. And we actually do show the upload progress per item as a bar.
