### ISSUE TITLE
Change album

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1046]
Ability to change album to category. Because I want to build a site background with categories: City, Mountain, Car, Nature ...
The album name does not mean anything.

**Comment by acrylian** [comment]
Sorry, I don't understand what you mean. Zenphoto is file system based (differently than Piwigo or other systems):  album = physical folder on the filesystem with image (or other files) and/or further folders. You can use dynamic albums instead but those are so called "saved searches" in so you cannot manually sort for example.

I think this is rather a support question belonging to the forum. Also please take the time to read a bit on our user guide to get familiar with some ZP internals.
