### ISSUE TITLE
Custuming zenphoto admin panel

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1047]
See : https://drive.google.com/file/d/0B-KuM2qoXls5VUdQd3RPUnNnYUU/view?usp=sharing
https://drive.google.com/file/d/0B-KuM2qoXls5YUh3Q0dvTHhOVnc/view?usp=sharing

**Comment by acrylian** [comment]
Sorry, I really have no time to look at such CSS files. Please tell what you mean.

**Comment by acrylian** [comment]
If you like to modify the backend look, you can do that by replacing the main admin.css file. But you will have to do it again on any update. I don't know offhand but it might be possible via a filter to write a plugin to allow this.

But we won't ever built in any official options for that as it causes serious support issues if not everyone sees the same.

Also we will not change anything on the backend right now as we are reworking it behind the scenes (that is a major work causing a lot of time).
