### ISSUE TITLE
Improve sorting

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1049]
Allow sorting of videos, gif, photo and add statistical information.

**Comment by acrylian** [comment]
You can sort by all sorts of fields and even add files not on the selector on the backend album pages:
![bildschirmfoto 2017-02-24 um 12 34 46](https://cloud.githubusercontent.com/assets/2474309/23302115/abb121ac-fa8d-11e6-9676-06ebc7bcb0b9.jpg)

What do you mean with "add statistical information"? Please elaborate.

Sidenote: We appreciate your tickets. But also please really think if your tickets are issues or feature suggestions. Some of your recent tickets were actually rather support questions for which the forum is better suited.

**Comment by zorodimanche** [comment]
What do I mean by "adding statistical information"? Is to add statistics by video file type, gif

**Comment by acrylian** [comment]
Are you talking about backend or frontend? What statistics where? You know you can sort manually on the backend already.  

Please a be more specifiic.

**Comment by zorodimanche** [comment]
In backend statistic gallery

**Comment by acrylian** [comment]
So this ticket is actually about two different things as sorting and the backend gallery statistics are two really different things?

Please in the future one topic per ticket and a bit more detailed from the beginning. I will close this ticket therefore.
