### ISSUE TITLE
Mail queue

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1050]
Notifications (on albums or on new content) may send hundreds of email at once. That is too much and might result in blacklisting sender or the whole server.

A part of the solution could be to manage a "mail queue". Instead of sending 200 emails at once, Zenphoto could send an email, wait for a few seconds, send another email...

**Comment by fretzl** [comment]
Can you please explain what you mean with "notifications (on albums or on new content)"?
Where and when does this happen?

**Comment by zorodimanche** [comment]
I just noticed on the forum that zenphoto does not allow user notification for example when a photo is published a mail is sent to all those who have provided the email address. Zenphoto has only rss

**Comment by fretzl** [comment]
That's why we ask you to get familiar with Zenphoto first before submitting all kinds of invalid issues.
Please take some time to explore everything. And yes, that means a lot of reading ;-)
