### ISSUE TITLE
Fatal error getEmail() lib-auth.php 952

### ISSUE THREAD

**Issue by RiderDavis** [zenphoto/zenphoto#1051]
Using the latest release Zenphoto 1.4.14 (Jan 28, 2017) when attempting to log in with an invalid username and "I forgot my User ID/Password", the following error is thrown;

> Fatal error: Call to a member function getEmail() on a non-object in /public_html/Zenphoto/zp-core/lib-auth.php on line 952

I have verified this behavior on multiple different sites found through the ZP showcase.

Randomly Selected Example;
![Random Example](https://puu.sh/ujW0w/23949c1a54.png)

**Comment by fretzl** [comment]
Make sure you have supplied a valid e-mail address in your user credentials.

**Comment by RiderDavis** [comment]
@fretzl As mentioned, this is when an **_INVALID_** username is entered.

All valid users are verified as having accurate, working e-mails and I really don't think that would be relevant if the username being entered is invalid anyways which is when this error is thrown.

**Comment by fretzl** [comment]
Sorry ! I can indeed reproduce the error. We'll have to look into this.

**Comment by RiderDavis** [comment]
@fretzl Showcase listing #4 is Campania Photo Gallery

You can reproduce this error on that site by visiting;
http://foto.portanapoli.com/zp-core/admin.php?logon_step=challenge&ref=nonexistentid

![Image of the error](https://puu.sh/upYAs/2818cbeaf7.png)
