### ISSUE TITLE
Improve tinymce4

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1052]
Hello it would be interesting to add in the extension the possibility of choosing the location of the link either in the header or in the footer.
As I tried to create these pages Privacy Privacy Status Help
And the problem is that it appears in the header while logically these pages must be in the footer

**Comment by acrylian** [comment]
Sorry, I really don't understand what you mean. What location of what link and what has tinyMCE to do with the location of links at all?

**Comment by zorodimanche** [comment]
Please look at my illustration:

![aaa](https://cloud.githubusercontent.com/assets/25553946/23341545/d7e07bde-fc49-11e6-813a-982983076b00.png)

**Comment by zorodimanche** [comment]
Please look at my illustration: 
![aaa](https://cloud.githubusercontent.com/assets/25553946/23341566/458d29e8-fc4a-11e6-9c7d-f65f40be7c18.png)

**Comment by petervanderdoes** [comment]
Do you mean a link to the Privacy Page should appear in the footer of the site in general? Like in the below image?

![1](https://cloud.githubusercontent.com/assets/380071/23341600/a6df2a02-fc18-11e6-920f-b75a9031b53d.png)

**Comment by zorodimanche** [comment]
Yes Peter

**Comment by zorodimanche** [comment]
Yes Peter

**Comment by acrylian** [comment]
That is not what this editor is supposed to be used for. Tinymce is not a tooklit for your overall theme, it is for formatting the content.

You rather want an extra menu in the footer. Then you have to use/setup/create a theme that provides this.

Official themes mostly use automatic standard menus creating items automatically as the default in one location. For example the Zenpage theme does this but uses the menu manager if enabled so you can customize the menu. But the Zenpage theme has only one menu location. If you need more, create or modify a theme to do so. 

Sorry this is really a support question for the forum. Please take the time to get a bit more into Zenphoto and use the forum for support questions if you don't know how to do anything.

**Comment by zorodimanche** [comment]
OK I will use the forum the next time to improve the referencing of zenphoto

**Comment by acrylian** [comment]
Okay, please understand that most things regarding layout generally need to be done via the theme.
