### ISSUE TITLE
Improve the administration panel

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1053]
Hello when you modify an album and want to change it in all languages ​​you have to go down vertically with the mouse to change any languages. The best way is to have the languages ​​horizontally.

Please look my illustration:
![aq](https://cloud.githubusercontent.com/assets/25553946/23355562/9aa93da4-fcd6-11e6-9ed6-c49efcdca28e.png)
![sans titre](https://cloud.githubusercontent.com/assets/25553946/23355569/9ed6cf0e-fcd6-11e6-9e4c-bbda3603f3b8.png)

**Comment by fretzl** [comment]
That is something that will be taken care of in the next major release.

**Comment by zorodimanche** [comment]
Tanks @fretzl
