### ISSUE TITLE
GoogleMap clusters causing security warning on HTTPS

### ISSUE THREAD

**Issue by thany** [zenphoto/zenphoto#1054]
My site runs on HTTPS, and now that browsers have come to their senses when it comes to mixed content, they (at least Firefox) are showing a ⚠ in the address bar on pages with a GoogleMap with a marker cluster.

Related errors in the console:
```
Loading mixed (insecure) display content "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m1.png" on a secure page
Loading mixed (insecure) display content "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m2.png" on a secure page
```
They should load from HTTPS, or ideally use a protocol-agnostic url (like `//google-maps-utility-library-v3.googlecode.com/...`)

This is with zenphoto 1.4.9.
I haven't yet had a chance to check with the latest version.

**Comment by acrylian** [comment]
Please always use the latest release if reporting possible issues to be sure it really still exists. 

In this case however it is surely the same. I think we should use https if that script is available via it. However I wonder why we actually load these two images externally at all and then even from an old google code repository. We should have these locally instead… (I personally never really use this plugin I have to admit…)

**Comment by fretzl** [comment]
Please try 1.4.14
The GoogleMap plugin has been updated and is also responsive by default now.
Those marker cluster images you mention are now stored locally.
