### ISSUE TITLE
getAlbumLinkURL and printAdminToolbox deprecation problems

### ISSUE THREAD

**Issue by bizmate** [zenphoto/zenphoto#1056]
I am currently stuck because upgrade instruction/code is acting in a very unexpected way

1- i had to delete the zp-data config files to go through setup while upgrading. This is missing from instructions on http://www.zenphoto.org/news/installation-and-upgrading/
2 - i see the deprecation messages as per subject. In details

> The Zenphoto object you are requesting cannot be found.
> Album: page/6/Warning getAlbumLinkURL (called from index.php line 35) is deprecated use getAlbumURL() You can disable this error message by going to the deprecated-functions plugin options and un-checking getAlbumLinkURL in the list of functions. in path ../zp-core/zp-extensions/deprecated-functions.php on line 154
> Page: index

and

> Warning: printAdminToolbox (called from 404.php line 44) is deprecated This feature is now done by a "theme_body_close" filter. You can remove the function call. You can disable this error message by going to the deprecated-functions plugin options and un-checking printAdminToolbox in the list of functions.
> in ./zp-core/zp-extensions/deprecated-functions.php on line 154

suggestions?

**Comment by fretzl** [comment]
1) There is no need to delete the config files. What the reason is you had to do that I cannot say without more information.
2) The theme you're using should be updated. The warnings you get also tell what should/can be done.

**Comment by acrylian** [comment]
For the future please one issue/topic per ticket only. Much better overview for us.

1. Usually file/folder permissions issues. Some hosts/server sometimes behave strange so Zenphoto is not allowed to edit them. But hard to tell without any proper error message from server logs.

**Comment by bizmate** [comment]
@fretzl @acrylian the two above are issues that happen even if a user does follow the upgrade instructions correctly. 
I was first stuck because of this error - http://www.zenphoto.org/support/topic.php?id=1083303 - and fixed it by removing the config files in zp-data. If this is reasonable i assume it should be written in the upgrade instructions. The same for the template error. Rm and cp the new theme folders should be required in my opinion unless users have custom themes.

As these instructions are not checked in a git document (but available only on  http://www.zenphoto.org/news/installation-and-upgrading) I let you work out if you would like to add them to the documentation to avoid the problem for other users

**Comment by acrylian** [comment]
Okay, I understand. The issue with the config file is surely not usual. I see you encountered it. Somehow I personally never encountered it on various hosts where I upgraded installs… 

> As these instructions are not checked in a git document

They are linked in the repo's readme actually as all documentation is on our site to avoid double work maintaining in two places.

**Comment by bizmate** [comment]
@acrylian thanks for the reply. I just wanted to contribute to better the documentation. As you confirmed

`They are linked in the repo's readme actually as all documentation is on our site to avoid double work maintaining in two places.`

Several project use open source documentation so everyone can contribute. Here is an example, using rst, for your own benefit - https://github.com/sonata-project/SonataNewsBundle/tree/3.x/Resources/doc

**Comment by acrylian** [comment]
Contribution is certainly welcome even if it is not "open source". We don't like to have everything tied to GitHub or other external services. As we stand for "independent self hosting" ;). We might change that later but that would require some extra work to combine that with our site we currently have no resources to.
