### ISSUE TITLE
Remove extensions

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1060]
Add the ability to remove extensions that are not used by the administrator to free up space and accelerate the loading of the gallery.

**Comment by sbillard** [comment]
Isn't that what the enable of the extension is for? Disabled extensions are not loaded at all, not on the front end nor the backend unless you specifically fisit its option page.

**Comment by zorodimanche** [comment]
Yes @sbillard , certainly when the extensions are deactivated they do not consume any resources but it is to liberate space.

**Comment by sbillard** [comment]
So you are concerned about the space on disk that the extension takes? That is hardly much in this day of terabyte storage. But if that is a problem you can delete the file using FTP. Besides you did mention "accelerate the loading of the gallery" so I did not presume that the disk space was the issue. The enable/disable takes care of that.

So what is it that you want to accomplish?

**Comment by acrylian** [comment]
I really don't think this is any issue. The full release is around 32 mb only.

**Comment by zorodimanche** [comment]
I just opened this ticket because I find it interesting to remove extensions that are not used in addition this is integrate into other cms like piwigo.

**Comment by acrylian** [comment]
I understand why. But CMS like Piwigo or WordPress have a central plugin repository to easily re-download them. If anyone reconsiders about a removed plugin later he would have to re-upload it via ftp. So in that case you can delete it via ftp in the first place if you really need to.
