### ISSUE TITLE
Duplicate detection

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1061]
When loading two files with the same name: forest.jpg and forest.jpg zenphoto writes the first file and on the second it adds a number : forest_1489854432.jpg

Improvement: The script should display a message prompting you to rename one of the files.

**Comment by sbillard** [comment]
Suggest you use the elFinder upload feature if you need duplicate detection. Renaming of the files in the other two scripts happens on the server where there is no recourse for interaction with the user.

**Comment by zorodimanche** [comment]
Ok tank you @sbillard
