### ISSUE TITLE
Create group of tags

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1062]
Create group of tags. For example tags {country:France, country:Germany, weather:sunny, weather:cloudy} will create groups {country, weather}.

**Comment by sbillard** [comment]
Tags are by definition individual. 

But the functionality you want can already be achieved. You can do grouping, for instance, in a search by using boolean expressions. For instance weather & sunny.

**Comment by acrylian** [comment]
Tags are not hierachical and we have no plans to change that, sorry.
