### ISSUE TITLE
Protecting young children from shocking images

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1063]
It would be interesting to add a plugin to display a message in a popup to report shocking content (weapon, religion ...)

**Comment by zorodimanche** [comment]
HTML FILE:
<h1>Popup/Modal Windows without JavaScript</h1>
<div class="box">
	<a class="button" href="#popup1">Let me Pop up</a>
</div>

<div id="popup1" class="overlay">
	<div class="popup">
		<h2>Here i am</h2>
		<a class="close" href="#">&times;</a>
		<div class="content">
			Thank to pop me out of that button, but now i'm done so you can close this window.
		</div>
	</div>
</div>

**Comment by zorodimanche** [comment]
HTML FILE:
<h1>Popup/Modal Windows without JavaScript</h1>
<div class="box">
	<a class="button" href="#popup1">Let me Pop up</a>
</div>

<div id="popup1" class="overlay">
	<div class="popup">
		<h2>Here i am</h2>
		<a class="close" href="#">&times;</a>
		<div class="content">
			Thank to pop me out of that button, but now i'm done so you can close this window.
		</div>
	</div>
</div>

**Comment by sbillard** [comment]
Zenphoto already has such a plugin--the colorbox_js plugin allows themes to pop-up anything they choose. So it is just up to you to provide the content in your theme. Many themes already use this to to show an image by clicking on the thumbnail. So you could quite easily substitute a warning thumbnail for the image and you would have your solution.

**Comment by zorodimanche** [comment]
resolved
