### ISSUE TITLE
Add special pages

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1065]
Add to the theme supported by the zenphoto team: the best pictures, the most recent images, the most viewed, random picture. Which can enrich the themes because one has the impression that they are poor. Because for a big cms like zenphoto it is a pity not to have these pages.

**Comment by acrylian** [comment]
You can add any kind of pages to your theme as you like. Functions for that are all available via the image_album_statistics plugin. Ready made themes can never match everyone's requirements as there is never a single kind of usages.  

And yes current themes are not that good and they for sure will not live forever. Therefore they will not get any significant updates anymore. Future releases might include even less themes than currently.

**Comment by zorodimanche** [comment]
I opened this post because in the software piwigo all the theme by defau have these pages and yet they are used by everyone.

**Comment by acrylian** [comment]
I do understand but we are not Piwigo ;-) Zenphoto can be used in different ways. We might add such things in one or the other way later.

**Comment by acrylian** [comment]
Just because I didn't mention it specifically you can also use dynamic albums to create for example an dynamic album for all images sorted by id to get a "latest" page.
