### ISSUE TITLE
Headless install of Zenphoto?

### ISSUE THREAD

**Issue by deanmoses** [zenphoto/zenphoto#1067]
I'm the developer of the [JSON REST API](https://github.com/deanmoses/zenphoto-json-rest-api) plugin.  I want to run a suite of tests against my plugin using a continuous integration server ([Travis CI](https://travis-ci.org/) to be specific), but I'm having a hard time figuring out how to script an install of Zenphoto.  

If I can script an install, then I can automatically run the tests against different versions of Zenphoto and different combinations of other plugins (like the Zenpage pages plugin), and stick the passing/not passing information right on the plugin's Github page so people know what it works with.

The first part I scripted very easily:  download `https://github.com/zenphoto/zenphoto/archive/zenphoto-1.4.13.tar.gz` via `curl` and create a `zenphoto.cfg.php` with the right values.  The problem is then doing whatever the setup page does when you click GO!, which I believe is mainly creating the database tables.  

I'm considering scripting a headless browser to click the setup page's GO! button, but I thought I'd ask you guys if there was a better way.

**Comment by acrylian** [comment]
There is no way to install Zenphoto except that described on our installation page. Setup does quite a bit more than just creating the database tables, it is required to be run if installing or updating.

There is also no need to support different versions of Zenphoto, just support the latest (1.4.14 currently). Best test against the latest and the support build for any changes.

**Comment by sbillard** [comment]
If everything is setup correctly, you can script setup with an "autorun" parameter. It will go to completion unless there is an error discovered.

http://domain/zp-core/admin/setup.php?autorun

**Comment by deanmoses** [comment]
Awesome, thanks!

This is especially useful in my case because I run automated tests of how the security works on different types of domains, and scripting the install environment for multiple hosts was turning out  to be a major pain.
