### ISSUE TITLE
Change the structure of zenphoto files/folder

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1069]
This post is a suggestion if you disagree you can close it directly.
Change the structure of zenphoto files to simplify the software aborescence for the future large update.
Zp is the abbreviation for zenphoto.

Zp-admin

Zp-includes

Zp-content
 -plugins (rename extension)
 -themes
 -uploads
 -languages (rename local)

**Comment by acrylian** [comment]
I will indeed close it as there are no plans to this. I realize where you got the idea from though (not everything is gold there - too much nesting folders can be inconvenient as well;-)). `zp-core` is really everything needed. There might be some restructuring within "zp-core" in the future
One thing we indeed might do sometime in the future is abandon having two extensions folders `zp-core/extensions` and `plugins`. 

A lot smaller suggestions may cause more work in the end than it looks on first sight. Please understand that we are working on a few things already. We need to be a bit pragmatic. Opening a "flood of tickets" with suggesions -  even if we welcome it generally - will not really help at the moment ;-)

**Comment by zorodimanche** [comment]
You say that "we are working on a number of things already" what will be the novelties? just a small preview

**Comment by acrylian** [comment]
Be a little patient please ;-)
