### ISSUE TITLE
How to activate Spell Check in Zenphoto Articles

### ISSUE THREAD

**Issue by AlexL777** [zenphoto/zenphoto#1071]
Hello Developers,

How can I work with Spell Checker when writing articles in Zenphoto? It is nowhere in the TinyMCE editor to see and in the Chrome browser is not supported.

At least I can not find it.

Thanks in advance.

**Comment by acrylian** [comment]
You need to create your own tinymce4 configuration file to enable plugins and/or feature not included in the official ones: 
http://www.zenphoto.org/news/how-to-create-custom-tinymce-configurations/

**Comment by sbillard** [comment]
Or you could try ZenPhoto20 which supports the "NanoSpell" plugin. ZenPhoto20 repository is on GitHub: https://github.com/ZenPhoto20/ZenPhoto20 or the website: ZenPhoto20.us.

**Comment by acrylian** [comment]
Let's keep **Zenphoto** tickets to Zenphoto. Thanks.

**Comment by sbillard** [comment]
Well, of course this is a Zenphoto ticket. It is the CMS without any built in spell checker.

**Comment by acrylian** [comment]
Zenphoto != Zenphoto20

**Comment by AlexL777** [comment]
Thanks for your hints and tips.

I have already activated the Browser SpellCheck. I did not create an individual configuration of the TinyMCE plugins, but I inserted it directly in the config.

Because only "spellchecker" and the line with the browser Spellcheck had to be added.

**Comment by acrylian** [comment]
Sure, you can do that. But you will have to remember to re-add it on every update. Thus an individual config file is better.

**Comment by AlexL777** [comment]
Ok, I remember that for the future and try to take the guidance on Zenphoto.org. Since it was well described how I can create an individual configuration of the TinyMCE plugin.

I saved the TinyMCE plugin and uploaded it after the Zenphoto update. This is only a temporary solution.
