### ISSUE TITLE
issue on googleMap.css

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1075]
hi,

There was a commit to make googlemap responsive.
I have an issue when googlemap is initially hidden: the map don't have the right width.

I have a look on the css, I think to have found the issue:

.hidden_map {
	position: absolute;
	left: -50000px;
	width: 600px;    <-- should be width: 100%;
	height: 400px;
}

**Comment by fretzl** [comment]
Thanks Vincent!
The fix you suggest works in your case but it doesn't in (for example) the basic and zenpage themes.
I will have to investigate some more.
For now I suggest you add an override in your own theme css.
