### ISSUE TITLE
Backup files accessible with http request

### ISSUE THREAD

**Issue by simonrash** [zenphoto/zenphoto#1076]
With the backup plug in installed and a backup taken I found that these files are stored within the web area. With a bulk standard install of Apache you can gain access to these backups if you know the path and file name or Apache will list them for you within the backup directory.
Other than the password that is encrypted all other data is stored in clear text within these files.
Right or wrong I have added a .htaccess to this directory preventing any file being served.

**Comment by acrylian** [comment]
Thanks, the plugin probably should have a note about where it stores its data. Actually servers/webhosts should be configured to not allow directory listing. htaccess is a good solution and file access could also be prevented by that. But it will only work on Apache servers. 

We probably could offer an option to use a backup folder above the web root via the config file.
