### ISSUE TITLE
improvement on user_login-out plugin

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1077]
Hi

To perform a new release of zp_Boostrap (in my midnight time...), I wish you add a specific class in a `<a>` item in `printUserLogin_out()`. 

so could you add `class="logoutlink"` (as there is a `class="logonlink"` on login form) on (line 180), like that:
`<a href="<?php echo $logoutlink; ?>" class="logoutlink" title="<?php echo $logouttext; ?>"><?php echo $logouttext; ?></a>`

thanks in advance

**Comment by acrylian** [comment]
Even if we add this right now it will not be officially release to match your theme release.

**Comment by vincent3569** [comment]
of course it's not only for my needs :-)
it's more consistent to have a class on this attribute as there is a class on logout link.
after all, everybody do what they want with them ;-)

**Comment by acrylian** [comment]
Of course ;-)

**Comment by vincent3569** [comment]
sorry to reopen this issue
to be consistant, all <a> should have a class

could you also add `class="logonlink"` on line 171 (for `$showLoginFormoption = 0`), like that:
`<a href="<?php echo $loginlink; ?>" class="logonlink" title="<?php echo $logintext; ?>"><?php echo $logintext; ?></a>`

thanks in advance

**Comment by acrylian** [comment]
Thanks, somehow missed that one. Done.
