### ISSUE TITLE
issue during wrong login process

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1080]
hi

when you are on index and you connect yourself with a wrong login, there is an error message on login form. well.
when you are on other pages (albums, images, news, pages, contact,..) and you connect yourself with a wrong login, there is no error message, the page is refreshed and nothing else append.

tested with zenpage, garland and effervescence.

**Comment by acrylian** [comment]
I assume you are referring to the user_login_out plugin? Otherwise there is just the password form which is rather independent from front end page. We will take a look.

**Comment by vincent3569** [comment]
yes, of course, I speak about user_login_out plugin.
