### ISSUE TITLE
"Unsaved" data on most admin pages

### ISSUE THREAD

**Issue by thany** [zenphoto/zenphoto#1081]
On most admin pages, when I navigate away to any other page, I get this popup:

*This page is asking you to confirm that you want to leave - data you have entered may not be saved.*

This happens even when I haven't touched any fields at all. I'm using the latest Firefox, and I don't have any plugins that autofill any form fields.

I really wish this clunky popup would only appear if there's legimitaly unsaved data. If it pops up absolutely every time, its impact reduces to zero. That's an elementary rule of UX.

Also note that this problem has existed for **years**, and has never been solved, although I do believe a couple of attempts have been made. My workaround has always been to remove the script responsible for this. However, with the newest version, that now breaks the upload, reverting it to default browser upload fields :(

**Comment by thany** [comment]
So, my current *working* workaround then...

Replace the contents of the file `jquery.dirtyforms.min.js` with this:

```javascript
$.fn.dirtyForms = function() { return this; };
```

Done. Clunky behaviour is gone. Please have this fixed proper at some point, or make it so that reverting to these intrusive measures aren't necesary to begin with.

**Comment by acrylian** [comment]
We had discussions about this before and I am sure there was already a ticket somewhere. Sadly we cannot reproduce this behaviour and I only get it when it makes sense. Sorry.

**Comment by thany** [comment]
I couldn't find that ticket either. But what would you need from me to get it reproduced?

**Comment by acrylian** [comment]
Since it seems to be "specifially you" to encounter this issue, we need your help to find out what for whatever reason apparently modifies forms so this script triggers (we btw had even changed the script doing this a while back). Any info helps like: What browser do you encounter this or is it all? Any specific extensions that might interfere here?

**Comment by thany** [comment]
It would help me in return if I can figure out which exact field(s) the script thinks have been changed. Without knowing that, it's a shot in the dark for me as well.

I'm using Firefox, latest version. *If* I have any extension that modifies a field, I wouldn't know about it. Which is why I need to know which field triggers the script.

**Comment by acrylian** [comment]
Yes, that is the detail we need to find out. The script actually just observes if any form fields change on a page and then sets the form as "dirty". 

So you mention you get that on "most admin pages". For a start a list about which exactly would probably help to narrow it a bit down.

**Comment by vincent3569** [comment]
this issue is linked with an old issue, never realy solved: https://github.com/zenphoto/zenphoto/issues/934
I still have this weird behavior on albums admin page and pages admin page.

**Comment by acrylian** [comment]
On the main album list and pages list or the individual album and page edit pages? I really need it exact because as said I never encounter this. Do you have an form autocomplete regarding passwords on? Also which browser do you encounter this.

**Comment by vincent3569** [comment]
For both:
In individual album in admin/albums tabs
In individual page in admin/pages tabs

Album guest user is auto filled with my user name.
I use FF ESR 45.9.0

**Comment by acrylian** [comment]
Ok, then you have autocomplete on in your browser and the browser ignoring the `autocomplete="off"` attribute we set on password fields. I have autocomplete off in all browser for security and privacy reasons as I don't want it to remember or autofill anything.

We could only exclude password fields. Then there will be no warning if you forget to save and possibly wonder afterwards why a password does not work.

**Comment by thany** [comment]
Most likely.

It seems to be triggering on a hidden (as in not visible, not as in type=hidden) field with `id=user_name`.

**Comment by acrylian** [comment]
You think this script is silly and unnecessary but other "normal users" do not and are greatfull to be warned on unsaved data. Please do not always take your personal opinion as the base for all. In my opinion having password completion enabled in browsers is a bad idea. You don't. So each his own. Thanks.

Anyway, it should not cause trouble in this way. So your both reports confirm my suspicion that it is password form related as those are initially hidden. The script has ways to exclude specific elements and we will add that as soon as we get to it.

**Comment by thany** [comment]
When I say "silly and unneccesary" I mean it because if it's really so important not to loose data, it is much better to save data instantly. Like in google docs, if you will. With that sort of implementation, none of this issue would ever be.

**Comment by acrylian** [comment]
That would be a way of course. We might do that in the future, but we just can't work on everything at the time (we don't have Google's resources naturually). But even with that there might be a time frame where data is unsaved as you surely don't save every sec.

**Comment by acrylian** [comment]
Please try the changes and report since we can't reproduce it.

**Comment by vincent3569** [comment]
it solve the weird behavior execpt on admin/pages.

**Comment by acrylian** [comment]
I didn't yet because that is not directly related to the actual dirty form warning (as some browser ignore it anyway). It has to work with that new setting of the script. I am sure I added the related class to admin/pages as well. Hm, sure you got the right support bulid as that was a follow up?

**Comment by vincent3569** [comment]
yes I am sure :-)
you miss a `class="dirtyignore"` on user (line 506 of zenpage/admin-edit.php)

**Comment by acrylian** [comment]
Thanks ;-)

**Comment by vincent3569** [comment]
seems to be OK for me
