### ISSUE TITLE
Tag is capped to 32 characters

### ISSUE THREAD

**Issue by thany** [zenphoto/zenphoto#1082]
The *Location* tag seems to be capped to 32 characters. Can this limitation please be removed? In Lightroom we can enter much more text than that, so why the arbitrary restriction?

For reference, the location tag I entered in Lightroom was `Restaurant Kaisen Sushi Ichiba Uogashi (海鮮鮨市場魚がし)` and after import into zenphoto it got shortened to `Restaurant Kaisen Sushi Ichiba U`, which is a suspiciously programmery amount of 32 characters.

It gets worse though.

When I overwrite the tag **in zenphoto** with the original text, it does appear to be stored fully and correctly. But in the front-end it's *still* capped to 32 characters. I know for a fact the theme isn't doing any trimming, because I built it myself. So there has to be some magic going on, spewing a maximum of 32 characters of any one metadata tag to a theme. And that's just weird.

**Comment by sbillard** [comment]
So the problem seems to be with the metadata processing? What exact EXIF/IPTC field is Lightroom using?

There are:
IPTCSubLocation : defined by the IPTC specification as being 32 characters
IPTCLocationName : defined as being 64 characters
XMPLocationName : defined as a string

So probably you are putting the data in the wrong tag. One would think it should go in one of the "location name" tags.

**Comment by thany** [comment]
I don't really know. Whichever tag the "Location" field reads. And whichever tag Lightroom writes to.

Anyhow, where is the limitation being actually applied? Clearly within zenphoto at least.

**Comment by acrylian** [comment]
I don't think there is such a limit. But the field Lightroom writes to would be good to know. Things is with this EXIF that it is sort of a loose standard not every one follows and XMP is an Adobe invention. What surey would help:

1. Could you please try such a tag without Japanese characters at the end so we can be sure it is not a weird encoding issue causing this? 
2. Also a link to a full image to reproduce would help as I have no lightroom.

**Comment by acrylian** [comment]
Close because of no feedback activi
