### ISSUE TITLE
jscript to move in zenphoto.js

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1083]
Hi,

there is a little script loaded everytime by each page of zenphoto:

`			<script type="text/javascript" src="/zp-core/js/zenphoto.js"></script>
				<script type="text/javascript">
			// 
		</script>`

this script should be included in zenphoto.js for more efficiency

**Comment by sbillard** [comment]
The problem, of course, is if loaded in JS the language strings are an issue. Maybe not everyone will want the French version of the strings. When loaded by  PHP they are translated by gettext(). The script should only be being loaded if you are logged in as an admin.

**Comment by acrylian** [comment]
The script is printed inline so it does not cause no extra http request for this. So this is not necessary for efficiency. Despite the already mention issue with translatable strings. To have a kind of gettext in js as well is really overcomplicated.

**Comment by vincent3569** [comment]
Hi
I don't understand what happend.
Before validate this issue, I had a flah:this script couldn't be in a js as there was translated string with php gettext() in it.
I thought I leave the page without validation, but it seems not.
Sorry for disturbing

**Comment by acrylian** [comment]
No problem. Such quibbles happen.
