### ISSUE TITLE
follow up #1078

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1084]
Hi

This commit https://github.com/zenphoto/zenphoto/commit/25b15f499657bf3d7c075331fc407eacb3bb279a breaks login form style on the front end.

I prefer like that, with no impact:
- line 958
`								<a onclick="window.location ='<?php echo WEBPATH . '/' . ZENFOLDER; ?>/admin.php?logon_step=captcha&amp;ref='+$('#user').val();" href="#">
									<?php echo gettext('Request reset by e-mail'); ?>
								</a>`

- line 1038
`							<a onclick="window.location ='<?php echo WEBPATH . '/' . ZENFOLDER; ?>/admin.php?logon_step=challenge&amp;ref='+$('#user').val();" href="#">
								<?php echo gettext('I forgot my <strong>User ID</strong>/<strong>Password</strong>'); ?>
							</a>`

**Comment by vincent3569** [comment]
Hi

This commit https://github.com/zenphoto/zenphoto/commit/25b15f499657bf3d7c075331fc407eacb3bb279a breaks login form style on the front end.

I prefer like that, with no impact:
- line 958
`								<a onclick="window.location ='<?php echo WEBPATH . '/' . ZENFOLDER; ?>/admin.php?logon_step=captcha&amp;ref='+$('#user').val();" href="#">
									<?php echo gettext('Request reset by e-mail'); ?>
								</a>`

- line 1038
`							<a onclick="window.location ='<?php echo WEBPATH . '/' . ZENFOLDER; ?>/admin.php?logon_step=challenge&amp;ref='+$('#user').val();" href="#">
								<?php echo gettext('I forgot my <strong>User ID</strong>/<strong>Password</strong>'); ?>
							</a>`

**Comment by acrylian** [comment]
Yes, you have to update your theme styles to match it. General rule of accessibility: If a link leads nowhere a link is not the proper semantic html element but a button is. This will be changed in a lot of places in the future. Sorry, this will not be reverted.

**Comment by acrylian** [comment]
On review you are actually right.  In this case these are links actually leading somehwere. However the original concept coverin the url within an onclick event is flawed. This needs other changes.

**Comment by vincent3569** [comment]
hi malte, you should remove the "won't fix" tag ;-)

**Comment by acrylian** [comment]
Indeed ;)
