### ISSUE TITLE
issue on search page of zenpage theme

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1088]
hi

there is a issue somewhere on search page of zenpage theme.
the html flow is broken. not sure but it seems linked with "Show more results" behavior.

see picture:
![screenshot009](https://user-images.githubusercontent.com/1224809/28415724-3649e87c-6d51-11e7-9c98-f9cae4dc26ba.png)

**Comment by acrylian** [comment]
Sorry, I cannot reproduce that. Link to the site where this happens please.

**Comment by vincent3569** [comment]
use this instance of zenphoto: http://dev.vincentbourganel.fr/
the the word "vercors" as search key.

**Comment by fretzl** [comment]
Can you please check the the album description of the album http://dev.vincentbourganel.fr/evenements-familiaux/20140824-randonnee-familiale-vercors/ ?
The page source code shows some weird formatting that may cause the page to break.

**Comment by vincent3569** [comment]
I have changed the included link in the album description (it follows zenphoto object model: "/news/randonnee-avec-un-ane-dans-la-reserve-naturelle-du-vercors/" ): the issue still exists.
I remove the included link: the issue desapears.

this is not weird text, as it is possible to add a link to a zenphoto object in album description!

**Comment by sbillard** [comment]
Can you change the zenpage functions.php line 46 to add a space between the quote mark and HREF

`	<a class="<?php echo $option; ?>_showmore"href="javascript:toggleExtraElements('<?php echo $option; ?>',true);"><?php echo gettext('Show more results'); ?></a>`

That is the only thing Firefox flags as being bad.

**Comment by acrylian** [comment]
On such missing spaces browser often are quite forgiving. The link/truncation seems to cause the issue. The best for these short excerpts is probably to just strip html anyway since you normally move from this page to the actual one.
