### ISSUE TITLE
improvement of printRandomImages()

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1089]
hi,

printRandomImages(n,...) allow to print n pictures of the whole gallery or of selected album.
but in some cases, the n pictures may be the same ones (if you want 5 random pictures from an album with only one picture for example !).

it would be a nice improvement that the n pictures are randomly selected but can't be the same ones (sorry, in french, it is mean "tirage aléatoire sans remise", but I can't find the right words in english).

there a limit: that mean that n is the max of displayed pictures and not only the exact number of displayed pictures.
in fact the number of displayed pictures may be less if you choose n pictures from an album with m pictures, with m<n. 
in that case the function returns the m pictures.

**Comment by acrylian** [comment]
Have you tried the similar function of the image_album_statistics plugin?

**Comment by vincent3569** [comment]
I start to write a new version of the function as a draft:

[printRandomImages.txt](https://github.com/zenphoto/zenphoto/files/1173343/printRandomImages.txt)

**Comment by acrylian** [comment]
Why? Please try the plugin as it gets all `n images` in one go from the database which is quite different to the function above.

**Comment by vincent3569** [comment]
ok, getImageStatistic() and printImageStatistic() seems to do the job in another way.
if an album have less pictures than requested by printImageStatistic(), only the number of pictures of this album are randomly (if selected option) displayed.

the 2 functions (printImageStatistic() and printRandomImages()) have not the same behavior.
it is a litlle bit confusing for newbees (and for others :-) )

maybe have a look on my improvement, you have the last word.

**Comment by acrylian** [comment]
> if an album have less pictures than requested by printImageStatistic(), only the number of pictures of this album are randomly (if selected option) displayed.

Yes, it can only choose from what is there ;-)

Which is why we probably will have only one randomimages functions in the future ;-) Random was added to the statisticcs because it was too easy to not do it and fitted to the plugin. I rarely use `printRandomImages()` myself and a prime speciality is generally this "picture of the day" random image. I will review your function when I get the chance. Sorry, dozens of things on my list and this was not ;-)

**Comment by acrylian** [comment]
We will probably rework these functions later on as some are a bit counter intuitively named anyway.
