### ISSUE TITLE
update of mobile_dectect.php

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1090]
hi

can you update mobile_dectect.php in mobileTheme plugin ?
zenphoto have  2.8.12 release and actual is 2.8.25.
http://mobiledetect.net/

**Comment by acrylian** [comment]
Sure, you are also welcome to provide a pull request if you notice that (given you tested it still works and does not cause any issues)

**Comment by vincent3569** [comment]
merged via pull request

**Comment by vincent3569** [comment]
merged via pull request
