### ISSUE TITLE
site_upgrade messages in wrong log

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1092]
hi
I think messages from site_upgrade functionality are redirected in wrong log.
they are writed in debug log and should be in security (or install) log.

` {229143:Mon, 31 Jul 2017 08:36:03 GMT}
Updating the configuration file
storeConfig called from setSiteState (site_upgrade.php [36])
from site_upgrade.php [16] 
`

**Comment by sbillard** [comment]
Site_upgrade is actually not part of the setup function. It is the plugin that lets you close and open your site. So it is debateable where the message should be logged. But I think a better solution is not to have the message at all. It provides no useful information.

The opening and closing of the site is logged in the security log.
