### ISSUE TITLE
Album description not saved with certain characters

### ISSUE THREAD

**Issue by thany** [zenphoto/zenphoto#1094]
Album description is not saved when it contain certain characters. I tested it with an emoji, but there are likely other characters that reproduce this behaviour.

What happens:
The form is submitted completely correctly, and the response to this POST is a completely valid HTTP 302 back to the edit page, followed by a GET which results in a HTTP 200. However, the album description remains empty. Not only the character it chokes on is gone, the WHOLE description is dumped into the void.

This is what we call a **silent fail**. These are the very worst of them all. This is also a **data loss** bug, moreso because hitting the back button does not bring back the text entered, presumably because of zenphoto's extremely aggressive cache busting.

Just try it with a pile of poo: 💩
You'll see it will disappear after saving, together why any and all other text in the same field.

I suspect the root cause lies somewhere along the lines of something being unable to handle more than 2 bytes for a character (ridiculous, since this was never the limit in any version of the unicode spec, nor in any unicode encoding spec). Mathias Bynens has written an in-depth [article](https://mathiasbynens.be/notes/javascript-unicode) about this, attacking javascript on this regard. PHP and MySQL suffer from similar problems. All of them completely and easily solvable.

I suspect album description isn't the only field that suffers from this issue.

**Comment by acrylian** [comment]
All content fields may suffer from that. So if it is that easy to fix and you apparently already know it, just provide the fix via pull request.
