### ISSUE TITLE
Run setup for a minor update?

### ISSUE THREAD

**Issue by thany** [zenphoto/zenphoto#1095]
Really?

> Zenphoto has detected a change in your installation.
> 
> * Your database software has changed from MySQLi 5.7.18 to MySQLi 5.7.19.
> 
> The change detected may not be critical but you should run setup at your earliest convenience.

Run setup for such a small change? Why? What needs setting up then?

**Comment by acrylian** [comment]
It's just that internally that is include in the overall install signature so setup wants to run. Might need review but "normal webhosts" don't update that often at all (sadly I guess…)
