### ISSUE TITLE
issue with printRandomImages()

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1099]
in template_functions.php, line 3424 and  following, there is something going wrong:
in case of "2" only image name (and album name with parenthesis) are displayed.

				case 2:
					$sizes = getSizeDefaultThumb($randomImage);
					//$html = '<img src="' . html_encode(pathurlencode($randomImage->getThumb())) . '" width="' . $sizes[0] . '" height="' . $sizes[1] . '" alt="' . html_encode($randomImage->getTitle()) . '" />' . "\n";
      $html = $randomImage->filename." (".$randomImage->album->name.")";
					break;

**Comment by acrylian** [comment]
There is indeed code commented out. Just looked quickly and it seems that is so for some versions already. Don't remember why that is, but seems to make no sense at all…

**Comment by vincent3569** [comment]
yes I have a look too. and the issue is since 2014.

**Comment by acrylian** [comment]
Interesting, maybe it was debug code forgotten and no one noticed…
