### ISSUE TITLE
issue with latitude and longitude metadata

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1101]
Hi all,

I think there is an issue with latitude and longitude metadata.
actually there is two pairs of data:
- Longitude and Longitude Reference
- Latitude and Latitude Reference

both of data are mandatory to have a correct geo coordinate values (ie : 40.689169 N, 74.044553 W to locate Liberty Island, New York City).
but in admin/options/image/metadata, we can allow Longitude and disallow Longitude Reference.
It makes a wrong value of Longitude if we are in W (or S for Latitude). And in that case, Liberty Island is located in the middle of Kirghiztan!

so I think only one data should be displayed andmanaged on admin (Latitude / Longitude). 
Then Zenphoto manage 2 fields all together (Longitude AND Longitude Reference, Latitude AND Latitude  Reference).

**Comment by acrylian** [comment]
Not really using this I have to admit I didn't even know there exists two of these values…  Since I assume this is actually causing an issue with maps plugins those probably should have a doc note about these fields required to be enabled.

Each field is a field (column) in the db so we probably won't add any exception here as it unnecessarily complicates some internal stuff.

**Comment by vincent3569** [comment]
Yes, googlemap plugin shows me my mistake on data configuration.
You are probably right, a note in admin/options/images/metadata may be enough.
Maybe like that:
If you use a plugin to geolocalize your pictures (googlmap plugin or other one), you should use (enable or hide), both Longitude and Longitude Reference, Latitude and Latitude Reference, Altitude and Altitude Reference metadata, to have a correct result.

**Comment by sbillard** [comment]
The "ref" fields are now linked to their respective base field so that enabling/disabling happens from the base field. (Their disable radio button is disabled.)

**Comment by acrylian** [comment]
No, they are not.
