### ISSUE TITLE
issue with printZenpageItemsBreadcrumb and archive view

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1102]
hi

when you choose a month in news archives page, the news breadcrumb is wrong.
for exemple, with zenpage theme, for april 2015, it diplays only:

Home » » April 2015

You can see the issue on the demo site: http://demo.zenphoto.org/news/archive/2015-04/

**Comment by acrylian** [comment]
Thanks, we'll take a look.
