### ISSUE TITLE
unneeded script loaded in printZenJavascripts()

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1103]
hi,

the printZenJavascripts() function loads unneeded script as it is impossible to suppress an album from front-end (no item on admintoolbox menu).
 
`		<script type="text/javascript">
			// 
		</script>
`

**Comment by acrylian** [comment]
Indeed, but it does not harm and does not cause any overload.

**Comment by vincent3569** [comment]
compared to unneeded scripts in all pages (as googlemap), I agree.
it is a follow up of this issue https://github.com/zenphoto/zenphoto/issues/1083.

as a member of zenphoto (github rights), I can do the update, if you agree.

**Comment by acrylian** [comment]
Sure, do the change if you like!

> compared to unneeded scripts in all pages (as googlemap), I agree.

Well, we talked about browser caching and that this is not a real issue :-)
