### ISSUE TITLE
new feature : hasNextNewsPage() / hasPrevNewsPage() in news loop

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1105]
hi

there are `hasNextPage()` and `hasPrevPage()` functions which return if there is a next/prev page in gallery and albums pages.
the same functions (i.e named `hasNextNewsPage()` and `hasPrevNewsPage()` ) are missing in news single loop context (and maybe in news context in general).

**Comment by acrylian** [comment]
Actually you can already use `getNextNewsPageURL()` and `getPrevNewsPageURL()` for that purpose.

**Comment by vincent3569** [comment]
Envoyé de mon iPhone

**Comment by acrylian** [comment]
Changed my mind as for the news loop a separate makes sense to add those. I didn't add equivalents for single article prev/next as that would really just double the existing `getPrev/NextNewsURL()` IMHO.
