### ISSUE TITLE
Problem in refreshing thumbnails in wordpress with zenphoto press

### ISSUE THREAD

**Issue by edbelize** [zenphoto/zenphoto#1108]
Hi,

I asked several of my friends to check my website to understand why the thumbnails are not showing up in the page. It looks like a random problem, sometimes ok sometimes not... I don't know if its a server problem or a plugin problem...

Thank you

bluegreenbelize.com

**Comment by acrylian** [comment]
Sorry, that is a third party tool not supported by us and we are not familiar with it and what it does internally at all. Best you contact its maintainer.
