### ISSUE TITLE
Watermarks not showing on thumbnails and preview images, BUT on original/download-image

### ISSUE THREAD

**Issue by MYITWORKS** [zenphoto/zenphoto#1110]
Zenphoto-Version 1.4.14 [f5b47da52f] (Offizielle Version)
PHP-Version: 7.0.25
MySQLi Version: 5.7.19

Website:
http://wirk-licht.de

Problem:
When i re-ran setup-script after a change in MySQLi Version the watermarks vanished from thumbnails and preview images
like here:
http://wirk-licht.de/Florales/
and here:
http://wirk-licht.de/Florales/-Ohne-Titel-1.jpg

there are not watermarks although they are configured (i tried configuring them global only or in every album - doesnt matter)

When i open the original picture the watermark is showing AND when i change the watermark picture the change is reflected here too. See here:

http://wirk-licht.de/zp-core/full-image.php?a=Florales&i=-Ohne-Titel-1.jpg&q=93&wmk=Logo_wirkLicht_3-14_2-3trans&dsp=Protected%20view&check=794591ee5c8fb7d3a3f0f1ea1c159dd68de23db4

I deleted image cache, hmtl cache, etc. via gui and on ftp too. Cleared cache on my browsers too. Tried with different browsers (chrome, IE, Edge)

So what to do next?

Cheers,
Alex

**Comment by fretzl** [comment]
I see watermarks on all thumbnails and images.
Looked with FireFox, Safari and Chrome.
Sure it's not a cache thing ?

**Comment by MYITWORKS** [comment]
I see them now too. Did not change anything on my computer since...

i can change the watermarks now too... maybe it is a cache-thing with the shared hoster (alfahosting.de) ?

**Comment by acrylian** [comment]
Might very well be that that hoster applies some very persistent server side caching.
