### ISSUE TITLE
Database update error

### ISSUE THREAD

**Issue by JimBrown** [zenphoto/zenphoto#1111]
Every time I run setup, I get the following error in the setup log:
```
Begin database creation and update
Query Failed: ALTER DATABASE rcairg2_zen-rcairgallery CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci; 
 Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-rcairgallery CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci' at line 1
```

PHP version is 5.4.34.
MySQL version is 5.6.14.
(I am not allowed to upgrade these.)

No issues with running the site.

Thanks.

**Comment by sbillard** [comment]
Hi, Jim:

Is this really supposed to be a ZenPhoto20 issue? I did not think that vanilla zenphoto supported utf8mb4.

Anyway, MySQL 5.6.14 should support this character set and the syntax shown seems correct. Do you have access to phpMyAdmin on the database? If so can you try setting character sets on the database and see what works.

Probably you should open this issue on the ZenPhoto20 repository if that is where it really belongs.

**Comment by JimBrown** [comment]
Yes, I put it in the wrong place...
