### ISSUE TITLE
1.4.14: Bulk Actions on Images Edit Ignores Changes in Image Descriptions

### ISSUE THREAD

**Issue by MarkRH** [zenphoto/zenphoto#1112]
I was making changes to various image descriptions in an album and then checked the "Check All" box for bulk actions and selected "set to published" and hit Apply.  All it did was change the published status. None of the changes I made in the description boxes were saved.  I don't think this is intended behavior and if so, some warning should be present.

**Comment by acrylian** [comment]
Thanks, that's not intended, I will take a look as soon as I can.

**Comment by MarkRH** [comment]
Thanks for the update!
