### ISSUE TITLE
improvement of "News article text length"

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1115]
hi

"News article text length" is an option of zenpage plugin, set in admin>options>plugin>zenpage with a default value.

But sometimes, according to news content, we need a shorter or longer value,
So it would be a nice improvement to enable to set a specif value fr each news, in admin>news.
That allows to adjust value if there is an inelegant breakpoint.

**Comment by sbillard** [comment]
I am presuming you are wishing to deal with specific articles rather than to unique placements of articles. If so you can use page breaks to indicate convenient truncation points. 

To handle inelegant breakpoints you may insert page breaks into the content. When there is a page break the truncation will occur at the nearest page break not greater than the truncation length.

**Comment by vincent3569** [comment]
in the news list loop, depending on the content of the news, the text is sometimes cut at the wrong place and I wish I could adjust where the cut is made.

my default length is 800. sometimes I would like the exerpt to be 650, sometimes 814, for more readability.

I am not sure to have to insert a page break: I do not want my content to be changed, only that the size of the exerpt can be adjusted.

btw: how can I insert a page break?

**Comment by acrylian** [comment]
You can insert the pagebreak via tinymce:

![bildschirmfoto 2017-12-18 um 11 53 53](https://user-images.githubusercontent.com/2474309/34102646-325044ae-e3ea-11e7-950b-6f8c34ea81b6.jpg)

Or manually with `<!-- pagebreak -->`

I just spot that apparently the default config files of TinyMCE except "classic" and "full" don't have this plugin enabled accidentally. I will change that.

**Comment by vincent3569** [comment]
ok, thanks.

one question: what is the "Truncate at pagebreak" check box for?

and also, I noticed that when I insert à `<!-- pagebreak -->`, there is no more `(...) read more` in news loop, but only `read more` link.

**Comment by acrylian** [comment]
1. "Truncate at pagebreak" does what it says. Otheriwse there is no truncation ;-)
2. Yes, because you most likely truncate on a paragraph and not in the middle of a sentence so the part shown is "complete" technically like a kind of intro/preface. This follows general practice on sites.

**Comment by vincent3569** [comment]
1. Of course if I ask the question it is because I can't have this behavior on my website :-)
I insert a `<!-- pagebreak -->` in a news, without checking "Truncate at pagebreak" in that news.
In my news loop, the news is troncated at the `<!-- pagebreak -->`.

2. I have few tests:
-breakpage at the end of paragraph
```<p>La randonnée raquette en mars dernier au <a title="Randonnée au Pas Enardant et Rocher du Playnet" href="/news/randonnee-au-pas-enardant-et-rocher-du-playnet/">Pas Enardant et Rocher du Playnet</a> m'avait laissé sur ma faim car les sommets étaient restés dans le brouillard.<br />Le secteur étant intéressant, et la météo étant au beau fixe, j'y suis donc retourné en toute confiance, à la recherche de belles lumières du soir et du matin.<!-- pagebreak --></p>```

-breakpage at the middle of paragraph
```<p>La randonnée raquette en mars dernier au <a title="Randonnée au Pas Enardant et Rocher du Playnet" href="/news/randonnee-au-pas-enardant-et-rocher-du-playnet/">Pas Enardant et Rocher du Playnet</a> m'avait laissé sur ma faim car les sommets <!-- pagebreak -->étaient restés dans le brouillard.<br />Le secteur étant intéressant, et la météo étant au beau fixe, j'y suis donc retourné en toute confiance, à la recherche de belles lumières du soir et du matin.</p>```

-breakpage at the middle of a word
```<p>La randonnée raquette en mars dernier au <a title="Randonnée au Pas Enardant et Rocher du Playnet" href="/news/randonnee-au-pas-enardant-et-rocher-du-playnet/">Pas Enardant et Rocher du Playnet</a> m'avait laissé sur ma faim car les som<!-- pagebreak -->mets étaient restés dans le brouillard.<br />Le secteur étant intéressant, et la météo étant au beau fixe, j'y suis donc retourné en toute confiance, à la recherche de belles lumières du soir et du matin.</p>```

in all tests, I have no `(...)`

**Comment by acrylian** [comment]
1. I will try to reproduce this. You should only get a pagebreak truncation if the checkbox is set. Otherwise of course the normal truncation will apply.

2. Yes, as said as intended. The pagebreak does not "know" where it is applied and there is no truncation indicator. The "read more" already does this.

**Comment by acrylian** [comment]
All is working as expected for me.

- If "truncate at pagebreak" is set, the article is truncated at pagebreak in the loop. 
- If not set, the normal truncation as set on the plugin option is used.

**Comment by vincent3569** [comment]
in the 2nd one, you have an `<!-- pagebreak -->` in your news?

if so, what's going wrong on my website?

**Comment by acrylian** [comment]
Yes, same article with the pagebreak comments. I cannot answer what is wrong with your site. I tried Zenpage theme so it might be your theme doing thing differently. So best search for differences.

**Comment by vincent3569** [comment]
have a try with latest and zenpage theme.
I can't reproduce this behavior and no difference between two themes: both call `printNewsContent();` in news loop...
what are your parameters for zenpage ?

**Comment by acrylian** [comment]
Pretty default:

![bildschirmfoto 2017-12-18 um 15 56 07](https://user-images.githubusercontent.com/2474309/34112172-0a852b7a-e40c-11e7-8765-5e3330810fec.jpg)

**Comment by vincent3569** [comment]
ok works as expected.
I did not know this function very useful for the layout of the news !

**Comment by acrylian** [comment]
It's actually in Zenpage quite since the beginning. It's currently limited to Zenpage items but generally you can use the function `getContentShorten()` on any text. So technically you can use it for images and albums on loops as  well. (Btw, in the future there will also be another option for loops similar to this)

**Comment by vincent3569** [comment]
I haven't seen it before but it's really a good news for my because without it, I can't manage the breakpoint of news excerpt in my news loop, and often, this breakpoint was at the wrong place!

**Comment by acrylian** [comment]
Yes, the automatic truncation is sort of lazy fallback that can be a bit "brutal" ;-)

I think I might move the `getShortenContent()` function to the general core so all items can use it independently of Zenpage (or maybe Zenpage should be moved itself ;-))
