### ISSUE TITLE
issue with 'Truncate at pagebreak' checkbox and '<!-- pagebreak -->' inserted in text

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1116]
Hi

I noticed that `Truncate at pagebreak` checkbox and `<!-- pagebreak -->` seems to break html flow.
In my case, it brokes my infinit scroll behavior and I can't use the script no more.

you can see 3 tests case for a news of mine.
see news loop : http://test.vincentbourganel.fr/news/2/ (news called "Photo du mois - Janvier")
see news : http://test.vincentbourganel.fr/news/photo-du-mois-janvier-2017/

-  "Truncate at pagebreak" checked and `<!-- pagebreak -->` in text content : does'nt works well and a `</p>` and a `</div>` are missing at the end of the news excerpt html code (before `</div><!--/.post-content -->`)

```
<div class="list-post margin-bottom-double clearfix">
	<div class="post-date">
		<span class="month">janv.</span>
		<span class="day">15</span>
		<span class="year">2017</span>
	</div>
	<h4 class="post-title">
		<a href="/news/photo-du-mois-janvier-2017/" title="Photo du mois - Janvier">Photo du mois - Janvier</a>
	</h4>
	<div class="post-meta clearfix">
		<ul class="nav nav-pills">
			<li><a href="/news/category/photo/" title="Photo">Photo</a></li>
	</ul>
	</div>
	<div class="post-content clearfix">
		<div class="row">
			<div class="col-xs-12 margin-bottom-double">
				<p>Cette fois, ça y est : Winter is coming, avec de la neige et un épisode de grand froid cette semaine.</p>
				<p>Alors pour rester dans le thème, voici la photo que je vous propose pour ce mois de janvier.</p>
			</div>
			<div class="col-sm-7 col-md-8 margin-bottom">
				<a title="Janvier" href="/albums/images/photos-du-mois/img_6404.jpg" data-fancybox="images"><img class="img-responsive center-block" src="/cache/images/photos-du-mois/img_6404_500.jpg" alt="img_6404.jpg" /></a>
			</div>
			<div class="col-sm-5 col-md-4">
				<p><em>Cette photo a été prise en janvier 2016 dans la réserve naturelle du Vercors.</em></p>
				<p><em>Ce pin remarquable, appelé « arbre taillé », est complétement isolé au milieu de plaine de la Queyrie.
				<p class="readmorelink"><a href="/news/photo-du-mois-janvier-2017/" title="Lire la suite">Lire la suite</a></p>
	</div><!--/.post-content -->
</div><!--/.list-post -->
```

-  "Truncate at pagebreak" checked and no  `<!-- pagebreak --> ` : works well
```
<div class="list-post margin-bottom-double clearfix">
	<div class="post-date">
		<span class="month">janv.</span>
		<span class="day">15</span>
		<span class="year">2017</span>
	</div>
	<h4 class="post-title">
		<a href="/news/photo-du-mois-janvier-2017/" title="Photo du mois - Janvier">Photo du mois - Janvier</a>
	</h4>
	<div class="post-meta clearfix">
		<ul class="nav nav-pills">
			<li><a href="/news/category/photo/" title="Photo">Photo</a></li>
		</ul>
	</div>
	<div class="post-content clearfix">
		<div class="row">
			<div class="col-xs-12 margin-bottom-double">
				<p>Cette fois, ça y est : Winter is coming, avec de la neige et un épisode de grand froid cette semaine.</p>
				<p>Alors pour rester dans le thème, voici la photo que je vous propose pour ce mois de janvier.</p>
			</div>
			<div class="col-sm-7 col-md-8 margin-bottom">
				<a title="Janvier" href="/albums/images/photos-du-mois/img_6404.jpg" data-fancybox="images"><img class="img-responsive center-block" src="/cache/images/photos-du-mois/img_6404_500.jpg" alt="img_6404.jpg"></a>
			</div>
			<div class="col-sm-5 col-md-4">
				<p><em>Cette photo a été prise en janvier 2016 dans la réserve naturelle du Vercors.</em></p>
				<p><em>Ce pin remarquable, appelé « arbre taillé », est complétement isolé au milieu de plaine de la Queyrie.</em></p>
				<p><em>Il fournit un excellent point de repère aux randonneurs parcourant le secteur et un excellent 1er plan pour les photographes tentant de restituer la grandeur du panorama.</em></p>
			</div>
		</div>
	</div><!--/.post-content -->
</div><!--/.list-post -->
```

-  "Truncate at pagebreak" not checked and no  `<!-- pagebreak --> ` : works well
```
<div class="list-post margin-bottom-double clearfix">
	<div class="post-date">
		<span class="month">janv.</span>
		<span class="day">15</span>
		<span class="year">2017</span>
	</div>
	<h4 class="post-title">
		<a href="/news/photo-du-mois-janvier-2017/" title="Photo du mois - Janvier">Photo du mois - Janvier</a>
	</h4>
	<div class="post-meta clearfix">
		<ul class="nav nav-pills">
			<li><a href="/news/category/photo/" title="Photo">Photo</a></li>
		</ul>
	</div>
	<div class="post-content clearfix">
		<div class="row">
			<div class="col-xs-12 margin-bottom-double">
				<p>Cette fois, ça y est : Winter is coming, avec de la neige et un épisode de grand froid cette semaine.</p>
				<p>Alors pour rester dans le thème, voici la photo que je vous propose pour ce mois de janvier.</p>
			</div>
			<div class="col-sm-7 col-md-8 margin-bottom">
				<a title="Janvier" href="/albums/images/photos-du-mois/img_6404.jpg" data-fancybox="images"><img class="img-responsive center-block" src="/cache/images/photos-du-mois/img_6404_500.jpg" alt="img_6404.jpg"></a>
			</div>
			<div class="col-sm-5 col-md-4">
				<p><em>Cette photo a été prise en janvier 2016 dans la réserve naturelle du Vercors.</em></p>
				<p><em>Ce pin remarquable, appelé «&nbsp;arbre taillé&nbsp;», est complétement isolé au milieu de plaine de la Queyrie.</em></p>
				<p>(...)</p>
			</div>
		</div>
		<p class="readmorelink"><a href="/news/photo-du-mois-janvier-2017/" title="Lire la suite">Lire la suite</a></p>
	</div><!--/.post-content -->
</div><!--/.list-post -->
```

**Comment by vincent3569** [comment]
also, you see in the very last test, that the encoding is not the same.

in the 2 firt cases, you have `« arbre taillé »`, but in the last one, you have `«&nbsp;arbre taillé&nbsp;»`.

**Comment by acrylian** [comment]
The page break truncates where you place it. If you place it so it invalides html it literally does this. Unless you have the php tidy functionality that tries to "repair" broken html. Broken html will of course cause any js to throw errors, too.  TinyMCE by default always puts `<p>` around texso you might need to use a custom config file and disable this. This has of course other problems as then formatting will be off and you have to set paragraphs manually.


I think I don't see the encoding issue you mention. Neither if I set the site to French manually or the - for me - default English. But what you posted looks like it is html encoded.

**Comment by acrylian** [comment]
Regarding the pagebreak killing html, could you please create a custom tinymce config file (or jsut edit an existing) and add the `pagebreak_split_block` parameter?
https://www.tinymce.com/docs/plugins/pagebreak/

I can't test myself right now so this would help. If it does we add that to all item config files.

**Comment by vincent3569** [comment]
there is the html code of my news (there is no tab with tinyMCE and I add them for readability)
 
```
<div class="row">
	<div class="col-xs-12 margin-bottom-double">
		<p>Cette fois, ça y est : Winter is coming, avec de la neige et un épisode de grand froid cette semaine.</p>
		<p>Alors pour rester dans le thème, voici la photo que je vous propose pour ce mois de janvier.</p>
	</div>
	<div class="col-sm-7 col-md-8 margin-bottom"><a title="Janvier" href="/albums/images/photos-du-mois/img_6404.jpg" data-fancybox="images"><img class="img-responsive center-block" src="/cache/images/photos-du-mois/img_6404_500.jpg" alt="img_6404.jpg" /></a></div>
	<div class="col-sm-5 col-md-4">
		<p><em>Cette photo a été prise en janvier 2016 dans la réserve naturelle du Vercors.</em></p>
		<p><em>Ce pin remarquable, appelé « arbre taillé », est complétement isolé au milieu de plaine de la Queyrie.<!-- pagebreak --></em></p>
		<p><em>Il fournit un excellent point de repère aux randonneurs parcourant le secteur et un excellent 1er plan pour les photographes tentant de restituer la grandeur du panorama.</em></p>
	</div>
</div>
```

I have to manually edit this code to be compliant and responsive with bootstrap framework.
The `<!-- pagebreak -->` is added with page break button of tinyMCE and in fact, with tinyMCE, page break is allways inside html tag.

So, if I add a page break at the end of the line with tiny MCE, the revelant code will be  `<p><em>my text<!-- pagebreak --></em></p>`. 
If necessary, I can manually edit code to put it ouside html tag like that `<p><em>my text</em></p><!-- pagebreak -->`, to avoid block split.

**Comment by acrylian** [comment]
Please try my suggestion above. If I understand the tinymce doc correctly it prevents pagebreak being enclosed in paragraphs - since tinymce does this on the fly - and therefore no html breaks should occur.

**Comment by vincent3569** [comment]
results of tests:

- with page break added by tinyMCE and `pagebreak_split_block: false`
The `<!-- pagebreak -->` is added with page break button of tinyMCE allways inside html tag.
So, if I add a page break at the end of the line with tiny MCE, the revelant code will be  `<p><em>my text<!-- pagebreak --></em></p>`. 

```
<div class="post-content clearfix">
	<div class="row">
		<div class="col-xs-12 margin-bottom-double">
			<p>Cette fois, ça y est : Winter is coming, avec de la neige et un épisode de grand froid cette semaine.</p>
			<p>Alors pour rester dans le thème, voici la photo que je vous propose pour ce mois de janvier.</p>
		</div>
		<div class="col-sm-7 col-md-8 margin-bottom">
			<a title="Janvier" href="/albums/images/photos-du-mois/img_6404.jpg" data-fancybox="images"><img class="img-responsive center-block" src="/cache/images/photos-du-mois/img_6404_500.jpg" alt="img_6404.jpg" /></a>
		</div>
		<div class="col-sm-5 col-md-4">
			<p><em>Cette photo a été prise en janvier 2016 dans la réserve naturelle du Vercors.</em></p>
			<p><em>Ce pin remarquable, appelé « arbre taillé », est complétement isolé au milieu de plaine de la Queyrie.
			<p class="readmorelink"><a href="/news/photo-du-mois-janvier-2017/" title="Lire la suite">Lire la suite</a></p>
</div><!--/.post-content -->
```
html flow is broken and a </p> and </div> are missing


- with page break manually added after </p> and `pagebreak_split_block: false`
```
<div class="post-content clearfix">
	<div class="row">
		<div class="col-xs-12 margin-bottom-double">
			<p>Cette fois, ça y est : Winter is coming, avec de la neige et un épisode de grand froid cette semaine.</p>
			<p>Alors pour rester dans le thème, voici la photo que je vous propose pour ce mois de janvier.</p>
		</div>
		<div class="col-sm-7 col-md-8 margin-bottom">
			<a title="Janvier" href="/albums/images/photos-du-mois/img_6404.jpg" data-fancybox="images"><img class="img-responsive center-block" src="/cache/images/photos-du-mois/img_6404_500.jpg" alt="img_6404.jpg" /></a>
		</div>
		<div class="col-sm-5 col-md-4">
			<p><em>Cette photo a été prise en janvier 2016 dans la réserve naturelle du Vercors.</em></p>
			<p><em>Ce pin remarquable, appelé « arbre taillé », est complétement isolé au milieu de plaine de la Queyrie.</em></p>
			<p class="readmorelink"><a href="/news/photo-du-mois-janvier-2017/" title="Lire la suite">Lire la suite</a></p>
</div><!--/.post-content -->
```
html flow is broken and only a </div> is missing.


- with page break added by tinyMCE and `pagebreak_split_block: true`
not sure of the result :-(
it seems `<!-- pagebreak -->` is added by tinyMCE outside html tag.
but after save the news, it brokes my news content: I can't access to the whole html code of the news :,-(

```
<div class="post-content clearfix">
	<div class="row">
		<div class="col-xs-12 margin-bottom-double">
			<p>Cette fois, ça y est : Winter is coming, avec de la neige et un épisode de grand froid cette semaine.</p>
			<p>Alors pour rester dans le thème, voici la photo que je vous propose pour ce mois de janvier.</p>
		</div>
		<div class="col-sm-7 col-md-8 margin-bottom">
			<a title="Janvier" href="/albums/images/photos-du-mois/img_6404.jpg" data-fancybox="images"><img class="img-responsive center-block" src="/cache/images/photos-du-mois/img_6404_500.jpg" alt="img_6404.jpg" /></a>
		</div>
		<p class="readmorelink"><a href="/news/photo-du-mois-janvier-2017/" title="Lire la suite">Lire la suite</a></p>
</div><!--/.post-content -->
```

**Comment by acrylian** [comment]
I just tried myself and I don't get broken html. But I do have the tidy php extension on my server. Sorry, there is no easy answer for now other than disabling the automatic paragraph creation or editing in the source of the text.

**Comment by vincent3569** [comment]
I did the test again with page break added by tinyMCE and `pagebreak_split_block: true`.
Really strange behavior...

The `<!-- pagebreak -->` tag is added by tinyMCE outside html tag.

before saving, I can see this in source code:
```
<div class="row">
<div class="col-xs-12 margin-bottom-double">
<p>Cette fois, ça y est : Winter is coming, avec de la neige et un épisode de grand froid cette semaine.</p>
<p>Alors pour rester dans le thème, voici la photo que je vous propose pour ce mois de janvier.</p>
</div>
<div class="col-sm-7 col-md-8 margin-bottom"><a title="Janvier" href="/albums/images/photos-du-mois/img_6404.jpg" data-fancybox="images"><img class="img-responsive center-block" src="/cache/images/photos-du-mois/img_6404_500.jpg" alt="img_6404.jpg" /></a></div>
<div class="col-sm-5 col-md-4">
<p><em>Cette photo a été prise en janvier 2016 dans la réserve naturelle du Vercors.</em></p>
<p><em>Ce pin remarquable, appelé « arbre taillé », est complétement isolé au milieu de plaine de la Queyrie.</em></p>
<!-- pagebreak -->
<p><em>Il fournit un excellent point de repère aux randonneurs parcourant le secteur et un excellent 1er plan pour les photographes tentant de restituer la grandeur du panorama.</em></p>
</div>
</div>
```

but after saving, something goes wrong: the page break is not at the same place and I lost some code in source code.

with firebug, I can see this new content
```
<div class="row">
	<div class="col-xs-12 margin-bottom-double">
		<p>Cette fois, ça y est : Winter is coming, avec de la neige et un épisode de grand froid cette semaine.</p>
		<p>Alors pour rester dans le thème, voici la photo que je vous propose pour ce mois de janvier.</p>
	</div>
	<div class="col-sm-7 col-md-8 margin-bottom">
		<a title="Janvier" href="/albums/images/photos-du-mois/img_6404.jpg" data-fancybox="images" data-mce-href="/albums/images/photos-du-mois/img_6404.jpg"><img class="img-responsive center-block" src="/cache/images/photos-du-mois/img_6404_500.jpg" alt="img_6404.jpg" data-mce-src="/cache/images/photos-du-mois/img_6404_500.jpg"></a>
		<br data-mce-bogus="1">
	</div>
	<img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" class="mce-pagebreak" data-mce-resize="false" data-mce-placeholder="">
</div>
```

and in source code, I have only
```
<!-- pagebreak -->
```

I don't know anything about tidy, but it really seems that actual 'Truncate at pagebreak' behavior doesn't manage html structure in new content (as needed by some framework for making responsive content).

**Comment by acrylian** [comment]
I did try as well and indeed also lost content after the pagebreak on the backend. No idea what TinyMCE thinks here. But the pagebreak functionality itself is independent of TinyMCE actually.

`tidy` is a php extension that needs to be installed on the server. It is not generally part of the standard php package so it is an extra that some hosts do install and some not. My local system MAMP does as does our live server. http://php.net/manual/de/book.tidy.php

We actually do have a cleanHTML function as a fallback but apparently that is not working correctly. I might have found another library that may be able to help here. I will see that if I can try that the next days.

**Comment by vincent3569** [comment]
tidy is installed on my server.

if it may help you, I found theses php tools:
http://htmlpurifier.org/
http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/

**Comment by acrylian** [comment]
If you have tidy installed I wonder why you don't see what I see… As should already fix the broken html elements actually. Could you try some direct text tests using this snippet:

`
$html = "Some broken html"; 
if (class_exists('tidy')) {
   $short = zpFunctions::tidyHTML($html);
} else {
   $short = trim(cleanHTML($html));
}
echo $short;`

That's from `functions.php::shortenContent()` lines 210++. Just to see if what your server actually used. 

Yes, I have been looking at these libraries, especially the 2nd one as it is much smaller and is not said to have that much overhead like the other one.

**Comment by vincent3569** [comment]
I have this test in a codeblock of a page (a </p> and a </div> are missing as in my very first test case):

```
<?php
$html = '<div class="post-content">
	<div class="row">
		<div class="col-sm-7">
			<p>Cette fois, ça y est</p>
			<p>Alors pour rester dans le thème</p>
		</div>
		<div class="col-sm-5">
			<p><em>Cette photo a été prise en janvier 2016</em></p>
			<p><em>Ce pin remarquable, appelé « arbre taillé »
			<p class="readmorelink">Lire la suite</a></p>
</div>';

if (class_exists('tidy')) {
   echo 'tidy';
   $short = zpFunctions::tidyHTML($html);
} else {
   $short = trim(cleanHTML($html));
}
echo $short;
?>
```

the result is (with tidy):
```
<div class="post-content">
	<div class="row">
		<div class="col-sm-7">
			<p>Cette fois, ça y est</p>
			<p>Alors pour rester dans le thème</p>
		</div>
		<div class="col-sm-5">
			<p><em>Cette photo a été prise en janvier 2016</em></p>
			<p><em>Ce pin remarquable, appelé « arbre taillé »</em></p>
			<p class="readmorelink"><em>Lire la suite</em></p>
		</div>
	</div>
</div>
```

**Comment by acrylian** [comment]
So it appears to be working as intended… Then I have no idea what happens on your site.

**Comment by vincent3569** [comment]
the issue is on this news.
http://test.vincentbourganel.fr/news/photo-du-mois-janvier-2017/

but on this one, I have no issue:
http://test.vincentbourganel.fr/news/photo-du-mois-fevrier-2017/

you can have a look on html code of this page
http://test.vincentbourganel.fr/news/

**Comment by acrylian** [comment]
I have to admit I don't see what is wrong on those two… In the source it looks correct as well.

What I do notice is that you have a js error as piwik.js is not loaded.

**Comment by vincent3569** [comment]
it makes me mad!

Can you have a look on source code from your browser?
I have a look on source code from firebug and I agree, the missing tags are added.
But in source code from my browser, I still have the issue.

Ii disabled piwik

**Comment by acrylian** [comment]
Of course browser try themselves to fix broken code so they can display something at all. 
I actually did look via Safari similar to Firebug and didn't spot anything.

I did understand that the issue is where news are truncated ;-) And I see now that the footer is misplaced.

But I think I see other invalid code on the footer now that I look again:
![bildschirmfoto 2017-12-20 um 16 12 02](https://user-images.githubusercontent.com/2474309/34213828-b1f8621a-e5a0-11e7-9294-e856f9f7961e.jpg)

`<footer>` is invalid within `<em>`. `<em>` is phrasing content and may not contain `<footer>` and `<div>` which are flow content.

**Comment by vincent3569** [comment]
hmm, it seems safari doesn't the same things as firefox...
and it seems to be linked with my issue.

my footer (as I can see on my firefox) is simply
```
	<footer id="footer" class="footer">
		<div class="container">
			<div id="copyright">
				[VB] Photo | <a href="/page/archive/"  title="Archives">Archives</a>			</div>
			<div>
				Galerie gérée par <a href="http://www.zenphoto.org" title="Un album photo plus simple"><span id="zen-part">Zen</span><span id="photo-part">PHOTO</span></a> & <a href="http://getbootstrap.com/" target="_blank" title="Bootstrap">Bootstrap</a>
			</div>
		</div>
	</footer>
```

with no `<em>` and `</em>` to wrap it.

**Comment by acrylian** [comment]
You are right. My bad. Safari has two ways, full source code and element view. I see it on the latter only.
But on full code view tells where the `<em>` comes from:

`<p><em>Cette photo a été prise en janvier 2016 dans la réserve naturelle du Vercors.<p class="readmorelink"><a href="/news/photo-du-mois-janvier-2017/" title="Read more">Read more</a></p>`

Apparently the browser tries to fix it unsuccessfully in that element view. 

That's of course is your truncating issue we discuss…

**Comment by vincent3569** [comment]
the good question is "why this one, and not others?"

**Comment by sbillard** [comment]
So, you probably don't want to hear this but....

The legacy zenphoto shorten methods do not really work properly.

It attempts to match paragraph marks, but not any other html. So it stands a high probability of leaving "bad" html depending on where they break falls.  HTMLtidy() is supposed to somehow fix these issues, but maybe it is failing.

A proper implementation would consider only visible content in the shortening--after all it is the visible presentation that you are  trying to control. This is what is implemented in ZenPhoto20 for the very reasons you are citing.

**Comment by vincent3569** [comment]
hi
yes, I agreee, it is allways better to treat the causes than the consequences.
HTMLtidy() treat the consequences (try to repear broken HTML).
Shorten methods seems to be the main cause (it seems to break html that sometimes HTMLtidy failed to repear).

a search gives some links to read:
https://stackoverflow.com/questions/16583676/shorten-text-without-splitting-words-or-breaking-html-tags
https://stackoverflow.com/questions/1193500/truncate-text-containing-html-ignoring-tags
https://github.com/pathable/truncate
http://www.the-art-of-web.com/php/truncate/
https://www.npmjs.com/package/html-truncate
https://www.pjgalbraith.com/truncating-text-html-with-php/

**Comment by acrylian** [comment]
I have added htmlawed as a fallback if tidy is not present. Please try `$html = htmlawed($html)` if it fixes the broken html issue. 

Shorten by value (= just where the value set applies - some CMS for this reason only truncate by word, not by character btw) is really different than shortening by pagebreak (= defined place).

**Comment by vincent3569** [comment]
I will test as soon as possible.

I disagree for truncation. Of course inputs are differents (truncate at the number of characters or words, truncate at the defined place), but the result should be the same regarding respect of html structure/tree.

**Comment by acrylian** [comment]
The html returned should be valid but it must not be exactly the same IMHO.

**Comment by vincent3569** [comment]
are you sure about your commit?
it seems that the lib-htmLawed.php file is missing.

**Comment by acrylian** [comment]
Thanks, indeed. Sorry got lost accidentally. Should be there now.

**Comment by vincent3569** [comment]
hi

I have this test:
```
<?php
$html = '
<div class="row">
	<div class="col-xs-12 margin-bottom-double">
		<p>Cette fois, ça y est : Winter is coming, avec de la neige et un épisode de grand froid cette semaine.</p>
		<p>Alors pour rester dans le thème, voici la photo que je vous propose pour ce mois de janvier.</p>
	</div>
	<div class="col-sm-7 col-md-8 margin-bottom">
		<a title="Janvier" href="/albums/images/photos-du-mois/img_6404.jpg" data-fancybox="images"><img class="img-responsive center-block" src="/cache/images/photos-du-mois/img_6404_500.jpg" alt="img_6404.jpg" /></a>
	</div>
	<div class="col-sm-5 col-md-4">
		<p><em>Cette photo a été prise en janvier 2016 dans la réserve naturelle du Vercors.</em></p>
		<p><em>Ce pin remarquable, appelé « arbre taillé », est complétement isolé au milieu de plaine de la Queyrie.
		<p class="readmorelink"><a href="/news/photo-du-mois-janvier-2017/" title="Lire la suite">Lire la suite</a></p>
	</div>
';

echo htmLawed($html);
echo htmLawed($html, array('tidy'=>'2s2n'));
?>
```

1- htmLawed well repairs my broken html
2- the parameter gives more readable html (have a look http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/htmLawed_README.htm#s3.3.5)

btw:
1- a zpFunctions::tidyHTML($str); remains inf file functions-common.php, line 353. 
2- maybe this library may used, not as a fallback inf tidy is no here
3- if the html sent to browser may be globaly filtered by htmLawed, after being generated by the server, it gives a very clean html (more easy to read by a human, if needed :) )

btw

**Comment by acrylian** [comment]
Thanks for testing!

> 1- of course, I have to hack core, to avoid use to tidy

Of course that's why I mentioned to use the function directly. 

> 2- maybe this library may used, not as a fallback if tidy is not here

That was indeed my idea ;-)

> 3- if the html sent to browser may be globaly filtered by htmLawed, after being generated by the server, it gives a very clean html (more easy to read by a human, if needed :) )

Not really my concern as browsers tend to format as well  ;-) Especially it might make sense to actually even us compact html in the static cache files (= a bit smaller files)

> 4- I have a lot of warning in my debug log

Thanks, it's just a warning so all works. I will fix that as soon as I get to it.

**Comment by vincent3569** [comment]
>> 1- of course, I have to hack core, to avoid use to tidy

>Of course that's why I mentioned to use the function directly. 

directly use of htmLawed() was not enougth, because of this code in functions.php

```
if(!class_exists('tidy')) {
	require_once dirname(__FILE__) . '/lib-htmLawed.php';
}
```
as tidy was existing, lib-htmLawed was not loaded and  htmLawed() function was not defined

**Comment by acrylian** [comment]
Of course. Sorry forgot that you had tidy actually. That happens if you work on several (unrelated) things at the time…

**Comment by vincent3569** [comment]
hi Malte.

after a night thinking about the issue I really think we are following a wrong direction.

of course `htmLawe` works better than `cleanHTML` and can be used as a fallback if `tidy` missing.

but `tidy` works well (and often better than `HTMLawe`).
for example, after tests, tidy rebuilt very well my test case just above (and `<p class="readmorelink">` is kept).

so for me, the initial issue is with shorten methods as suggested by Stephen.
and it seems to be a serious "mic-mac" in these functions, between `News article text length` option, `Truncate at pagebreak` checkbox and `<!-- pagebreak -->` tag.

**Comment by acrylian** [comment]
Did you mean that htmlawed worked better than tidy? Actually you mentioned that tidy didn't work for you at all as it was implemented.

Yes, text length truncation and pagebreak are of course different. One is truncated around the length you set. It is not exact as it counts all chars. Truncate at pagebreaks, well, truncates at pagebreak where you set it. There is no counting involved naturally.

I am not sure if parsing the whole text for html just to not count it isn't some overhead especially in loops. As said other cms truncate at words so are not really exact in length as well

I may investigate that sometime but I don't see it a pressing need right now. No one - except you ;) - complained about this for years.

**Comment by sbillard** [comment]
Vincent:

Since this seems unimportant to the Zenphoto team, why not try ZenPhoto20. I think you will find it does just what you want.

**Comment by acrylian** [comment]
@sbillard Why not contribute something useful instead?

**Comment by sbillard** [comment]
Well, I really thought that a solution to Vincent's problem was useful, but if you don't think so, that is your opinion. Why are you not interested in solving his issue? The solution is simple. Implement a proper shortenContent algorithm. Such an algorithm exists in ZenPhoto20 which is GPL, so there is no reason why it could not be adopted by zenphoto other than your arrogance.

**Comment by vincent3569** [comment]
@acrylian:
it'sa little bit confused to me. so I have to do some other tests.
my previous tests show that on an html text with errors (used in a blockcode of a page), tidy rebuilds better than htmlawe, for example by preserving existing tags.
and in fact, it seems to me very clear that the problem comes from the shorten methods and the sequence of the 2 functions (shorten and tidy).
in order to understand and test properly, can you explain exactly what zenphoto is supposed to do:
1- with only `News article text length` option used,
2- `Truncate at pagebreak` checkbox and `<!-- pagebreak -->` tag are used
3-  what happens if both are used


@sbillard 
Well, I tried zenphoto20 of course.
There are some very good things that would be useful to me (search context preserved when navigating between news), other things that I do not like (too many plugin, the change of the back end interface).
I do not want to get into the game.
I have always said that, seen from my side, and without knowing you personally, nobody is all white or black in your disputes.
and as a user, I regret that you have not managed to applanir your different

**Comment by acrylian** [comment]
If you miss features you are welcome to suggest them. As usual I cannot promise when or if I will look into something. 

It is not our concern what the fork does or not, we don't know or follow it. Really have not time or motivation for that. This is not the place to discuss about it either.

To the truncation: 
1. The function counts the chars to match the number set and truncates when reached. That involves all text so includes code and code comments. It naturally may result in broken html since the function does not "understand" what it truncates. So if you say 100 chars you may not get that exactly for the actual text. As said I will investigate that sometime but I don't consider this a major issue right now. 
2. The functions search for the pagebreak comment and then truncates when it finds it. This of course also leads to broken html for the same reason.
3. It's either truncate by pagebreak or not, you cannot use both.

**Comment by vincent3569** [comment]
with all commits and pull request, it works well for now for the test cases above.
i close the issue even if we may have a look on tinyMCE configuration.

**Comment by acrylian** [comment]
Thanks, we can re-open if needed. Will try to look at the tinymce config soon.
