### ISSUE TITLE
unable to delete items from toolbox menu

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1118]
hi

"enable gallery sessions" is checked and on all zenphoto/zenpage items (albums, images, news or pages), I can see a link "Delete item" on toolbox menu.
but this menu does not work and items are never deleted.

**Comment by acrylian** [comment]
Have to admit I never use gallery sessions and you even just reminded me that then there is a delete link… The reason is surely a XSRF token mismatch between front and backend. Have to take a look when I can.

**Comment by acrylian** [comment]
The reason seems to be a js error about two undeclared js variables (containing the message if you really want to delete). Those are declared on the backend and therefore are missing on the frontend.

**Comment by acrylian** [comment]
I did fix that part so you should see a dialog window on clicking. Deleting does not work yet as you probably get a XSRF token mismatch. I will investigate that.

**Comment by vincent3569** [comment]
hi
not sure that all commits fix the issue...

my test case.
- I enable gallery sessions (after apply change, I have to login myself and after that, I stay in admin tabs)
- I go to the front end (I use zenpage theme): then I appear as not loggued in (that behavior is allways the same when I go to Front End from Admin Back End) 
- I login myself on the Front End and naviguate to news page, then I appear as not loggued (that behavior is allways the same when I naviguate on my website)
I never saw these behaviors before and I don't have these behaviors on my prod site when I enable sessions (I am not with latests commits).

- After I login myself on a news item, I try do delete it: then I go to the Back End and I have an error message and news is not deleted.
![screenshot014](https://user-images.githubusercontent.com/1224809/35091102-fb99dcc6-fc3b-11e7-8015-fc24eabfeeff.png)

**Comment by acrylian** [comment]
With this change you don't need to enable gallery sessions at all anymore to get delete links. Please try that. I will look after gallery sessions itself then.

Actually I am thinking of removing the gallery session option anyway. Even the option comment does mention that cookies are the preferred way. I personally never use or used gallery sessions as I see no benefit in doing so. So removing basically non recommended options is surely a good idea usabilitywise as it simplifies.

**Comment by vincent3569** [comment]
OK, it works without session enabled.
I am not self confident with security issue, so are you sure to allow this with cookies enabled?
i remember that some ajax functionnalities (remove of items) had been removed from front end, because of security issue.

**Comment by acrylian** [comment]
> I am not self confident with security issue, so are you sure to allow this with cookies enabled?

Actually yes, because the backend always sets up a session no matter if gallery sessions are enabeled or not as its session id is required for the XRSF token checks to work properly. 

But only on the backend so usages on the front end like the toolbox (which is basically part of the backend if you will) do not work. So if you are logged in now there is always a session setup as it is on the backend itself.

**Comment by acrylian** [comment]
@vincent3569 Please try gallery sessions again, they should now again work as well.

**Comment by vincent3569** [comment]
ok, it works fine, with cookies and sessions.

**Comment by acrylian** [comment]
Thanks!
