### ISSUE TITLE
site_upgrade: if site is closed AND requested URL IS NOT home page -> infinite redirect loop

### ISSUE THREAD

**Issue by bic-ed** [zenphoto/zenphoto#1122]
Hi, I found this issue running in site upgrade mode, when site is closed and you try to visit a page different from the home page. Then zenphoto redirects indefinitely, adding every time a new `plugins/site_upgrade/closed.php` string to the requested URL.
`http://localhost/zenphoto/lavoro/plugins/site_upgrade/plugins/site_upgrade/closed.php/...`
**Note that this behavior does not happens in test mode when not logged in as administrator.** 
Looking into it I found a sort of redundancy between **index.php** and **site_upgrade.php**, so that if I delete the redirection code from **index.php** everything seems to work just fine. The code I deleted from index.php is the following:
`		if (@$_zp_conf_vars['site_upgrade_state'] == 'closed') {
		if (isset($_zp_conf_vars['special_pages']['page']['rewrite'])) {
			$page = $_zp_conf_vars['special_pages']['page']['rewrite'];
		} else {
			$page = 'page';
		}
		if (!preg_match('~' . preg_quote($page) . '/setup_set-mod_rewrite\?z=setup$~', $_SERVER['REQUEST_URI'])) {
			if (file_exists(dirname($_zp_script) . '/plugins/site_upgrade/closed.php')) {
				header('location: plugins/site_upgrade/closed.php');
			}
			exit();
		}
	}
`

Of course I have no idea if this affects some others scenarios somehow.

**Comment by acrylian** [comment]
Please try the support build, this should be fixed already.

**Comment by bic-ed** [comment]
Thanks acrylian, I'll have a look and post report here.

**Comment by bic-ed** [comment]
I've checked the support build and I confirm it's working. Thanks again!

**Comment by acrylian** [comment]
Thanks!
