### ISSUE TITLE
There is no Code Styling on the TinyMCE Editor

### ISSUE THREAD

**Issue by AlexL777** [zenphoto/zenphoto#1130]
Hi Developers,

The TinyMCE editor has no style for code output.

When I use "preformatted text", it is only displayed bold in the frontend, but not as a code.

How can I solve it via CSS or something?

Thanks in advance.

**Comment by acrylian** [comment]
TinyMCE itself has no styles at all. It is the job of the theme to style the output as needed. So you need to add some CSS to the theme you are using.

Btw. for code display you should use `<pre><code>your code</code></pre>`. Preformatting itself semantically does not mean code.
