### ISSUE TITLE
zenphoto redirects to http from https at install. 

### ISSUE THREAD

**Issue by ananttickoo** [zenphoto/zenphoto#1131]
Zenphoto redirects to http from https. 
While installing zenphoto with https i am being redirected to http. 

http://<domain>/gallery/zp-core/setup/index.php?autorun=gallery

curl  example 

```
root@odroid:/var/www/<domain>/public_html/gallery# curl --proxy <proxy_server> -k https://<domain>/gallery/ -v
*   Trying <proxy_server>...
* Connected to <proxy_server> (<proxy_server>) port 10001 (#0)
* Establish HTTP proxy tunnel to <domain>:443
> CONNECT <domain>:443 HTTP/1.1
> Host: <domain>:443
> User-Agent: curl/7.47.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification SKIPPED
*        server certificate status verification SKIPPED
*        common name: odroid (does not match '<domain>')
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: CN=android
*        start date: Sun, 03 Jul 2016 16:47:19 GMT
*        expire date: Wed, 01 Jul 2026 16:47:19 GMT
*        issuer: CN=android
*        compression: NULL
* ALPN, server accepted to use http/1.1
> GET /gallery/ HTTP/1.1
> Host: <domain>
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 302 Found
< Date: Fri, 26 Jan 2018 16:58:49 GMT
< Server: Apache/2.4.18 (Ubuntu)
**< Location: http://<domain>/gallery/zp-core/setup/index.php?autorun=gallery**
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
<
* Connection #0 to host <proxy_server> left intact

```

**Comment by acrylian** [comment]
Please check if you config file in `/zp-data/zenphoto.cfg.php` has the `server_protocol` set to `https`. After you changed it re-run setup. Then also check the options on the backend (Options > Security) if the server protocol is there correct as well (which it should).

I cannot directly test myself because I sadly currently have no https server available.

**Comment by ananttickoo** [comment]
Hi Acylian

```server_protocol``` is set to ```https```.

**Comment by acrylian** [comment]
I don't see right now where this url uses any protocol, it should use what the server tells. 

Did you check if this is not the server itself doing this accidentally? Did you try to install it via http and then switch to https afterrwards. Does the install itself work then?

Sadly can't investigate right now as we have evening over here already.

**Comment by ananttickoo** [comment]
Hi 

i was going though the index.php which i downloaded, ver  1.4.14, has lines missing which are present in recent code

``` $protocol = explode('/', strtolower($_SERVER['SERVER_PROTOCOL']));
 $root = $protocol[0] . '://' . $_SERVER['HTTP_HOST'] . str_replace('index.php', '', $_SERVER['SCRIPT_NAME']);```

after adding the lines in index.php 
redirect has moved to ```https```

**Comment by acrylian** [comment]
Ok, can you try the support build (master from github) then please? (Be sure to backup if it is an important site,although you should not get any real trouble).

If it works there we might have fixed that issue already.

**Comment by ananttickoo** [comment]
That did not fix the issue.

**Comment by ananttickoo** [comment]
found the issue 

issue is with reconfigure.php 
the location is hard coded to http. 

`$location = "http://" . $_SERVER['HTTP_HOST'] . $dir . "/" . ZENFOLDER . "/setup/index.php?autorun=$where";`

**Comment by acrylian** [comment]
Thanks for looking. But that line is not in the support build/master) reconfigure.php anymore.

**Comment by ananttickoo** [comment]
yes, i will try that today, i was trying to figure out issue with the installed one.  

I will close this thread.

thanks for helping
