### ISSUE TITLE
create resize and thumbs by edit images, not "on the fly"

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1133]
It's a wish:
My Gallery is well visited.. With "on the fly" stores anyway after a short time all.
Since I edit each image after the "put online" (adding title, description and tags), it would be enough if the resizes and thumbs were saved immediately when calling the "edit images" backend webpage. With this call of the "edit images" backend webpage, the thumbs for the backend will be created anyway. Maybe this could be inserted as an option, not as a standard? I would be happy about that.
Think about it.

**Comment by vincent3569** [comment]
maybe I don't understand: there is a plugin cache_manager that offers that behavior.
You can choose "cache album images" in a specific album or choose "cache manager" in admin>overview.
this plugin allows you to cache all requested pictures in the selected theme (thumbnails, sized images,...).

of course it is not for each images when you edit them, but you can manage cache for a whole album.

**Comment by acrylian** [comment]
I lengthly explained why Zenphoto works the way it does on the forum. The default sizes are NOT the measure for everything. Themes I do basically never use these… If you need to pre-generate (pre-cache) you can use the cachemanager plugin as Vincent mentioned. It will cover default sizes right away. If your theme uses custom sizes you need to register them properly. There are examples available.

Sorry, this core principle will not be changed.

**Comment by vincent3569** [comment]
@mebels:
to properly use cache_manager with your own theme, you cas see an example with my own theme (that is responsive by the way): https://github.com/vincent3569/zpBootstrap
in https://github.com/vincent3569/zpBootstrap/blob/master/themeoptions.php, I defined picture thumbnails sizes and images size, and I defined the images to cache.
then I can pre-cache image as described above
