### ISSUE TITLE
MENU_TRUNCATE_STRING is undefined

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1135]
Hi,
I noticed this error log
```
 REMARQUE : Use of undefined constant MENU_TRUNCATE_STRING - assumed 'MENU_TRUNCATE_STRING' dans /home/[...]/zenphoto/zp-core/zp-extensions/zenpage/zenpage-template-functions.php à la ligne 1462
printNestedMenu called from printAllNewsCategories (zenpage-template-functions.php [825])
from include (sidebar.php [16])
from include (gallery.php [94])
from include (index.php [10])
from include (index.php [130])
from index.php [31] 
```

it seems this commit https://github.com/zenphoto/zenphoto/commit/3672cda4acacfb6ca99464209aeb04819e2d9278 created this bug in zp-core/zp-extensions/zenpage/zenpage-class.php
if menu_manager and print_album_menu plugins are disabled, then MENU_TRUNCATE_STRING is undefined.

**Comment by acrylian** [comment]
Thanks for the find. I think actually since it is used by different plugins the define should be rather in the core already than repeated in individual plugins.
