### ISSUE TITLE
Basic responsive theme (only inspiration)

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1137]
I have created a responsive theme from the Basic Theme light.
It's only for inspiration.
changes are in files:
album.php
image.php
index.php
styles/light.css
Read the README.txt.
https://github.com/mebels/zenphoto/tree/master/themes/basic-responsiv

**Comment by acrylian** [comment]
If you like create a separate repository and provide it for others. We will not put much work into the existing themes anymore (especially not this as it has no Zenpage support). Probably all will be abandoned and replaced at least with one general purpose theme.

**Comment by mebels** [comment]
That would be better, but I will not do it that way. So I will not design a complete new theme. It's just for inspiration.

Of course it would be nice if ZenPhoto included such a simple basic responsive theme as standard in the package.

The basic is well suited for a basic responsive. Only a few changes have to be made. My fork, however, contains more changes. (prev / nex thumb, etc.)

**Comment by acrylian** [comment]
Of course your choice, we welcome third party themes even if "just" modifications of existing themes.
