### ISSUE TITLE
issue on matomo plugin

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1138]
hi,

I have my own matomo/piwik plugin and after an install, I have an issue on mine (reset of some options).
I read the core code of matomo plugin and I saw this issue, line 54 and following: 

```
		if (getOption('piwik_id')) {
			setOption('matomo_id', getOption('piwik_url'));
			purgeOption('piwik_url');
		}
```
of course you should use previous `piwik_id` and purge it.

on my plugin I will change the name of my options to avoid purge on each install.

**Comment by acrylian** [comment]
Actually the matomo plugin should migrate the old options to the new ones and then purge them. See the option class constructor. But perhaps you are right, it is better to directly check that always.

**Comment by acrylian** [comment]
Ah, sorry, I somehow didn't see the actual typo! Thanks.

What is different on your plugin to ours?

**Comment by vincent3569** [comment]
hi
the main difference is about multilingual. two languages are allowed on my web site, but I only want to track items in one language, mine.

I wish to know where my visitors are coming from, I wish to know what items they visit, but I don't to have duplicate tracking count, if a visitor from france visits the news called "Nouvel album «Voyage à New York» " in french and another from UK visits the same news called "New album «Travel to New York City» " in english.

maybe it would be a good improvement for the plugin and I can give you the code.

**Comment by acrylian** [comment]
I have a far memory about that discussion. Yes, please send the code, I'll take a look asap.

**Comment by vincent3569** [comment]
this is the code of my plugin
feel free to use it or not

[piwik.php.txt](https://github.com/zenphoto/zenphoto/files/1780467/piwik.php.txt)
