### ISSUE TITLE
folder and image scanning

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1139]
Hello,
I noticed something strange that is not really a problem but strange.

If a complete folder with subfolder and images in subfolders via FTP is copied to /albums and then the /zp-core/admin-edit.php page is called, some will be scanned, but not everything.

All subfolders will be scanned.
But, only the images in subfolders that seem to have the latest timestamp are scanned. All other images in subfolders will not be scanned.
I saw that in the database entries.

If two subfolders have the same timestamp, then they are not sorted alphabetically and "z" is taken. What sorted here I do not know. Only one is scanned.

For the "newest" subfolders, the colums "updatedate" and "thumb" (1) are filled out in the database-table "albums", in all others "NULL".

**Comment by acrylian** [comment]
I never noticed this. As mentioned on the forum even on the backend it is on request. But if you think something is not in sync use the database refresh button on the overview page. That will scan everything and should correct everything.

**Comment by mebels** [comment]
In the Album Edit Page is a dropdown "Show X album levels" on the right. That is in connection with it.
