### ISSUE TITLE
Separation of backend text language and editing language(s)

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1140]
Hello,
It is not really a problem, but it is problematic for me.

I'll start from the beginning.

When new images are scanned, the file name without file extension is saved as image title as an string in the database. It's good.
If the image title is changed in the backend then it is saved as an array, even if multi-lingual is disable. I find that problematic.

So it should be correct: If multi-lingual is disable then save image title and description (and metadata) as an string in the database. Is multi-lingual enable, then as an array (logical).

My problem is: I want to migrate an existing gallery to Zenphoto. I have different options. But, I will not save the image title and description in an array but as an string. The problematic thing in the future is that all new image title and description will be stored as an array. I then have a very messy database, once string, once array. I find that very bad.

The best way is to make it as an setup option. The user can choose during the installation if he wants a multi-lingual Zenphoto or not. Later change in options is bad. If enabled, languages ​​can be selected arbitrarily at any time in the options.

If it were correct, I would find it better (logical):
Multi-lingual disable: string
Multi-lingual enable: array

**Comment by acrylian** [comment]
> If it were correct, I would find it better (logical):
Multi-lingual disable: plaintext
Multi-lingual enable: array

I did explain why it is not this way. Sorry, if you need it differently, my any means hack it. But we will not change this. Sorry, please understand I will not discuss this any further by now.

Besides if you just add the title or any other multilingual  capable field as a string in the database itself via a migration script that will work as well, it will stay that way until you save from the backend.

**Comment by mebels** [comment]
> I did explain why it is not this way.

You just do not have it. They are very good at ending a discussion right at the beginning. Point for you.

I quote you from the forum:
> Actually multilingual capable strings are always stored as serialized strings. That way you never loose multilingual strings if you switch between disabling and enabling multilingual. It was done this way years ago and did cause content loss.
> 
> Sorry, you will have to live with this.

So it's more of a problem to have the option in the settings instead of the setup. You admit it yourself. Point for me.

The image data (title, desc, ...) will be saved to the first scan anyway only as a string. So saving as a string can not be a problem if multi-lingual is disabled in the setup(!).

So this option is better in the setup than in the settings. Fact.

Much more is a database incompatible, which has once stored string and once array. That is currently the case.

It is also completely useless to save the image data in an array if multi-lingual is disabled.

The problem lies in the placement of the multi-lingual enable/disable option. This is better a part of the installation setup, not the settings. And already all problems are solved.

If you do not like it being a problem then that's your problem, not mine.

Core hacks are possible, but avoid. If core hacks are necessary, then the CMS is not perfect.

It is her zenphoto. You can continue to do so. But do not expect that someone will find it good. Maybe they lack the vision. I'm dealing with a lot of different stuff, and currently with migration. And this is very bad for migration. Bad Points for Zenphoto. And I remember I having mentioned that many years ago in the forum.

**Comment by acrylian** [comment]
> So it's more of a problem to have the option in the settings instead of the setup. You admit it yourself. Point for me.

I did not admit that. I said there would surely have been different ways to handle multilingual and we choose this way. Again, it is to ensure nothing gets lost if switching modes. Which can happen on changing modes otherwise. Again we had it this way years ago and changed it because users were complaining.

> Core hacks are possible, but avoid. If core hacks are necessary, then the CMS is not perfect.

Please understand how some of your posts sound to us. You are new  and come from a different system and constantly find things not like you are used to. That natural and we understand that. But you really have to accept that we will not change things working for years (back) just because  they don't work for you. You cannot expect that. Sorry.

I don't really see the real issue on migration. It is really simple to read the array, sort out what you need and migrate that to another database (you don't even know yet…)  On migrating you have to restructure data anyway, you most likely will not be able to use the database as it is directly.

**Comment by mebels** [comment]
They understand that completely wrong. In German one says, you got that in the wrong neck.

It is not about me. I can write core hacks, even if that is not nice. This is about Zenphoto. If I switch to Zenphoto then Zenphoto should have a future and be able to compete against new upcoming Gallery CMS. This will be difficult with these (small) problems (see Zenphoto20). You're lucky enough to switch to Zenphoto now because Gallery3 is hibernating. That's why Gallery3 is no better than Zenphoto at the moment.

They also exaggerate a bit. So far, there have only been 2 things that disturb me about Zenphoto. URLs with image file extension and this one. Everything else was just questions.

Sometimes you just have to admit a mistake and have the competence to change it.

In this multi-lingual issue, I come across logical mistakes. If multi-lingual disable, then no array is necessary. Fact. The first scan does not save to the array. Fact and good! But, since they have probably responded to odd requests from users who are undecided, the option had to be in the settings rather than in the setup. That was a mistake. Such an option is too comprehensive for it to be just a setting. This is almost as similar as the decision of a character encodings. Changing that afterwards is a problem. If someone wants to activate multi-lingual afterwards, then he has to do a new setup. and then all of them are stored in arrays. otherwise not. That's the only logical way.

I made a little core hack and it's about to fix. My core hack is not a general solution but only for me. For a general solution only one if rule would have to be installed. if (multi-lingual = 1) save as an array, else save as an string. This is very simple and does not break anything in Zenphoto. It would even be something like a bugfix. But they think Zenphoto will work completely different. That is her problem.

**Comment by acrylian** [comment]
Sorry, I feel we need to agree here that we disagree on this.

> PS: aaaaaaaaaaaaaaarrrrrrrrrrr! Another problem is that the Backend language change not independently!!!
For sure not if you are logged in and have a language set. Or http accept language and your browser does request something.

**Comment by mebels** [comment]
> For sure not if you are logged in and have a language set. Or http accept language and your browser does request something.

What? With multi-lingual disable, which I write all the time, the image data (title, desc, ...) are stored as an array with the set language.
```a:2:{s:5:"en_US";s:11:"Hallo Welt!";}```

So, and I have the backend language on en_US, but my image title and description is in deutsch (german). Now I must have to necessarily because of this multi-lingual enable. Then I have two input fields and textareas everywhere, one for en_US and one for de_DE, but I just fill one anytime. This is completely superfluous, since I only use one language for saving, that is, for the frontend anyway. For the backend only no image title and desc are stored, only for the frontend.

Language settings must always be separate between backend and frontend.

If the language setting were separate from the backend (single lingual) and frontend (multi-lingual / single-lingual), that would be better. The backend language does not require a multi-lingual, just a single lingual change option.

But that's just a problem that arises from the topic problem. If all data were stored as strings, if multi-lingual is disabled, the problem would not exist at all. Understand it! Do not resist it.

**Comment by acrylian** [comment]
> Editing for the frontend must be independent of the backend admin area language. Is that so hard to understand?
If you edit on the backend it is for the frontend… And again in single language mode it does not matter anyway…

Also please mind your tone even if you don't agree.

**Comment by mebels** [comment]
Sorry! Do I write so incomprehensibly?
I do not have to live with it because I have a core hack, but you and everyone else have to live with it. And I guess the problem is not good for Zenphoto. You can do it better, even better!

The language selection during editing has nothing to do with the system language. Both must be independent of each other.
System language: always single lingual
Editing language: single or multi-lingual

In addition, you can still separate backend system language setting and frontend system language setting.

Currently, however, system language is linked to editing language. That is problematic.

If both are cleanly separated then there are no problems. And it is doable!
OK, that's off-topic right now, but it's part of it.

My topic is that it is very simple that if multi-lingual disable, not an array, but string is saved. It is simple possible!

**Comment by acrylian** [comment]
> Sorry! Do I write so incomprehensibly?

Yes, sorry you did. Because now I finally get what you mean ;-) You were too hooked on this array vs string part that it was hard to understand what you actually meant.

On a separate language setting for just the backend texts we can indeed agree. The language arrays however will stay as they as they will not be an issue then. If the backend language is English but editing is German (single lang mode) the strings will be the array matching the editing language. We'll put this on the list. I have renamed the ticket a bit…

**Comment by mebels** [comment]
I do not know how flexible you are and how complicated you should be, so do not be too complicated. But, the best thing would be if all can be set separately.
Backend-System-Language (single)
Frontend-System-Language (single or multi)
Editing Languages (single / multi)

However, my topic persists. He wants something else.
if multi-lingual disable, then save as an string, not as an array.
It is very easy to solve and there are no dangers or problems. In the first scan, the data is anyway stored as a string. For many users, only strings are stored anyway.

**Comment by acrylian** [comment]
> Backend-System-Language (single)
Frontend-System-Language (single or multi)
Editing Languages (single / multi)

The frontend is always single language as you can only view in one language at the time. But frontend languages and backend languages are always tied because the frontend can only show what the backend has entered. 

Sorry, on the array point we will not come together. Once you edit it is an array. Topic on this part is closed.

**Comment by mebels** [comment]
Frontend-System-Language does not mean image data (title, desc, ...) but Zenphoto texts like login, logout, etc.

A shame because of the string / array save because it would be very easy to solve.

**Comment by sbillard** [comment]
Maybe I can be of help here:

Editing language:  This is the "multi-lingual" option. Reset it and there is only one editing language. Set it and you can create strings for as many languages as you choose. The "default" language will be that of the administrator.

Front-end language: The software will try to provide the user with his "preferred" language. Modern browsers will tell us what that is. Or if the appropriate plugin is enabled, the visitor can choose his language. Of course theme/plugin strings (editing language) can only be provided in his language if you have chosen to create them. Zenphoto strings depend on some translator having made the language translation. Default is English. If you really want to run in only one language disable all other languages in the language option. Your viewers may not get what they want but you will.

As to the storage of the theme/plugin strings that needs to stay an array. The reason the strings are stored as an array is to prevent discarding translations if the multi-lingual option gets reset. Perhaps you would not care if countless hours of work were lost by accidentally resetting the option. But others are not so cavelear. It may not your choice, but then why do you not use the get_language_string() function to retrieve the strings? Then you will have only a single string (no array) as you request. This is of course why the function exists.

**Comment by acrylian** [comment]
> Frontend-System-Language does not mean image data (title, desc, ...) but Zenphoto texts like login, logout, etc.

Those are actually frontend, the admin toolbox would be backend on the frontend. But this only applies to logged in users anyway. Let's not make it more complicated than necessary…

**Comment by mebels** [comment]
I do not mean the (backend) Admin Toolbox on the frontend with frontend system language, because that is from the backend. right.

OK, Zenphoto has almost no frontend system texts, such as "Title:", "Description:", "Search result": that translate it for a visitor (at least in the Basic Theme). But maybe system pages (404, update) or similar with texts that are translated?

**Comment by acrylian** [comment]
All static texts are done by the translation file, no matter if backend, in official themes or plugins. There are two kinds of translation, the static ones and the ones within content the user has to do himself. 

Anyway, as said backend lang and edit lang I can agree on (which is basically always multilingual because you otherwise don't see which edit lang you currently have). It is meaningless for visitors and an loggin user can decide what he wants to use and switch any time. If he is loggedin the front end sort of part of the backend. Overcomplication to further divide that.

**Comment by mebels** [comment]
Yes, I meant that it can be too complicated.

One should differentiate between
- System Language
-- Backend
-- Frontend (for visitors)
- Content-Language (for visitors)

I do not know Zenphoto yet, but are there really no themes that have a lot of system texts in the frontend for the visitors? Since it would be nice if the admin has the opportunity for the backend en_US and for the visitors in the frontend de_DE select. Or a visitor can choose independently of the backend system language itself. This could involve linking System-Language-Frontend and Content-Language. So there is only one separation.

1.)
- System language
- Backend

2.)
- System Language
-- Frontend (for visitors)
- Content-Language (for visitors)

So the distinction is with admin / visitor.
An admin sets only one language for his backend (without live switch buttons en / de / fr / it / ...).
For the Visitor there can be a live language selection (multi-lingual with live switch buttons en / fr / it / ...).
(A logged in admin in the frontend is also a visitor, excluding the Amdin-Bar)

OK. It's hard to understand at first, but it makes sense once you understand it.

**Comment by acrylian** [comment]
"frondend (for visitors") and "content language (for visitors) " is really the same. Either a visitor switched to e.g. German or not. Then all content and static strings (so they are available) will be shown in German (or fallback to English).

> (A logged in admin in the frontend is also a visitor, excluding the Amdin-Bar)

Technically but he generally switches to the language he is editing in. His language setting only applies if he is logged in. Otherwise it is separate as for any normal visitor.
