### ISSUE TITLE
cacheManager plugin does not generate uncropped thumbnails

### ISSUE THREAD

**Issue by JatB** [zenphoto/zenphoto#1141]
The cacheManager plugin does not recognize the crop setting for thumbnails. It will only generate cropped thumbnails even if cropping is turned off in Options - Theme.

So for the Basic theme, if you run the Cache manager with everything set to default you get 100x100 pixel thumbs and 595 pixel images-

> Refreshing cache for Gallery
> 
> Apply 100_cw100_ch100_thumb
> Apply 595
> 
> 2 cache sizes to apply.

Turning cropping off for thumbnails, but leaving everything else at default, you will still get the same cropped sizes when you run Cache manager (after doing a Purge Image cache)-

> Refreshing cache for Gallery
> 
> Apply 100_cw100_ch100_thumb
> Apply 595
> 
> 2 cache sizes to apply.

Leaving cropped off for thumbnails, but changing the thumb size to 200 pixels gets you 200x200 cropped thumbnails-

> Refreshing cache for Gallery
> 
> Apply 200_cw200_ch200_thumb
> Apply 595
> 
> 2 cache sizes to apply.

If you change the image size, say to 895, that will get generated. So the only problem is when cropping is turned off for thumbnails.

It looks like the issue is on line 38 of themeoptions.php in the theme folder, where it is coded to get the cropped width and height for the thumbnail instead of seeing if cropped is turned on or off (of course, I could be wrong)-

`cacheManager::addThemeCacheSize($me, getThemeOption('thumb_size'), NULL, NULL, getThemeOption('thumb_crop_width'), getThemeOption('thumb_crop_height'), NULL, NULL, true, NULL, NULL, NULL);`

Thanks, as always, for your time.

**Comment by acrylian** [comment]
Thanks, seems you indeed sadly found a bug in that registering :-) We'll look into this asap.

**Comment by vincent3569** [comment]
as far I can see, global options grayscale on images or thumbs, and watermark on images or thumbs are not used too in all  themeoptions.php of all official themes.

**Comment by sbillard** [comment]
Of course there is also the option to create custom caching registrations.

**Comment by vincent3569** [comment]
Of course I agree.
But I think these first registrations for images and thumbs for theme should take care about all defined options on images and thumbs. Else, these registrations are useless and cache_manager create useless cache images.
You may have other needs for your site (pictures elsewhere than gallery but allways with the same size, specific thumbs for albums,...) and other registrations may used for that.

**Comment by sbillard** [comment]
Of course you are right.

**Comment by acrylian** [comment]
@vincent3569 Please feel free to send a pull request with an update regarding this if you can.
