### ISSUE TITLE
function returnDefaultSizedImage() img id and title

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1147]
Please put in the HTML img tag an id and the title in the function ```printImageThumb()```. The id is necessary for a modalbox/lightbox fullsize image view.
<pre><code>function returnDefaultSizedImage($alt, $class = NULL, $id = NULL) {
	global $_zp_current_image;
	if (is_null($_zp_current_image))
		return;
	if (!$_zp_current_image->getShow()) {
		$class .= " not_visible";
	}
	$album = $_zp_current_image->getAlbum();
	$pwd = $album->getPassword();
	if (!empty($pwd)) {
		$class .= " password_protected";
	}
	if (isImagePhoto()) { //Print images
		$html = '&lt;img id="themeimgid" src="' . html_encode(pathurlencode(getDefaultSizedImage())) . '" alt="' . html_encode($alt) . '" title="' . html_encode($alt) . '" width="' . getDefaultWidth() . '" height="' . getDefaultHeight() . '"' .
						(($class) ? " class=\"$class\"" : "") .
						(($id) ? " id=\"$id\"" : "") . " /&gt;";
		$html = zp_apply_filter('standard_image_html', $html);
		return $html;
	} else { // better be a plugin class then
		return $_zp_current_image->getContent();
	}
}</code></pre>

**Comment by sbillard** [comment]
`$html = '<img id="themeimgid" src="' . html_encode(pathurlencode(getDefaultSizedImage())) . '" alt="' . html_encode($alt) . '" title="' . html_encode($alt) . '" width="' . getDefaultWidth() . '" height="' . getDefaultHeight() . '"' .
						(($class) ? " class=\"$class\"" : "") .
						(($id) ? " id=\"$id\"" : "") . " />";`

You realize that you may end up with two "id" tags with this proposal? Better would be to pass the ID in the first place or default $id to whatever you think best `default:`
`function returnDefaultSizedImage($alt, $class = NULL, $id = 'themeimgthumb') {`

**Comment by sbillard** [comment]
Of course this (and your proposal) will end up with duplicate IDs which is not good. So needs a little work.

**Comment by acrylian** [comment]
If you really want to open a modal box on clicking on the thumb I would really recommend to wrap it within a `<button>` (or if you really must a `<a>` although that should not be used if the link does not lead to any location). That would be semantically and accessibility wise much better.

**Comment by mebels** [comment]
Oooops, im a little bit confused. There is always an id, but not used. I must only delete the ```= NULL```.

I had to copy & paste the function printDefaultSizedImage() anyway, because I need a return and no echo print, because of a str_replace in the theme, for img src with symlinks. very complicated.

```function returnDefaultSizedImage($alt, $class = NULL, $id) {```

```returnDefaultSizedImage(getImageTitle(), "", "themeimgthumb")```

Thanks for the hint sbillard!

@acrylian, please do not mess things up with the ID and the TITLE. They are two separate things. It would be nice if you could also put a TITLE in the images.

**Comment by mebels** [comment]
@acrylian , not for thumbs, for the resize image in the themes image.php. The basic theme use a &lt;a&gt; link with the plugin "colorbox_js", but that is too much and not realy fine for mobile devices. Here my simple solution for fullsize view.

PHP/HTML
<pre><code>&lt;div id="fullsizelightboxback" class="lightboxback"&gt;
&lt;div id="fullsizelightbox" class="lightbox"&gt;
&lt;img id="fullsizeimgid" class="lightbox-content" alt="" width="" height=""&gt;
&lt;/div&gt;
&lt;script&gt;
var lightbox = document.getElementById('fullsizelightbox');
var lightboxback = document.getElementById('fullsizelightboxback');
var img = document.getElementById('themeimgthumb');
var lightboxImg = document.getElementById("fullsizeimgid");
img.onclick = function(){
    lightbox.style.display = "block";
	lightboxback.style.display = "block";
    lightboxImg.src = "&lt;?php echo html_encode(pathurlencode($fullimage)); ?&gt;";
}
var span = document.getElementsByClassName("lightbox")[0];
span.onclick = function() { 
    lightbox.style.display = "none";
    lightboxback.style.display = "none";
}
&lt;/script&gt;</code></pre>
CSS
<pre><code>.lightbox {
    display: none;
    position: absolute;
    z-index: 2100;
    top: 0;
    left: 0;
	right: 0;
    width: 100%;
    overflow: auto;
    cursor: pointer;
}

.lightboxback {
    display: none;
    position: fixed;
    z-index: 2000;
    top: 0;
    left: 0;
	right: 0;
    width: 100%;
    height: 100%;
    overflow: auto;
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
    cursor: pointer;
}

.lightbox-content {
    margin: 0 auto;
    display: block;
    max-width: 100%;
}

.lightbox-content {    
    -webkit-animation-name: zoom;
    -webkit-animation-duration: 0.6s;
    animation-name: zoom;
    animation-duration: 0.6s;
}

@-webkit-keyframes zoom {
    from {-webkit-transform:scale(0)} 
    to {-webkit-transform:scale(1)}
}

@keyframes zoom {
    from {transform:scale(0)} 
    to {transform:scale(1)}
}</code></pre>

source: https://www.w3schools.com/howto/howto_css_modal_images.asp

**Comment by acrylian** [comment]
> There is always an id, but not used. I must only delete the = NULL.
`null` is really a common default of not set. Just pass a proper value if you want to use it… We talked about this before and it is a common way to set "empty" defaults.

w3schools is generally not always the best source…

> @acrylian , not for thumbs, for the resize image in the themes image.php. The basic theme use a <a> link with the plugin "colorbox_js", but that is too much and not realy fine for mobile devices. Here my simple solution for fullsize view.

Sorry I don't agree. If you want something clickable use the proper semantic html element. I don't understand why a link is not fine for mobile  devices.

Besides remember you can always use the `get` version of functions (or the object model) to build whatever you specifially need.

**Comment by acrylian** [comment]
You can use `get` functions to create your own version and to replace anything in urls if needed.
