### ISSUE TITLE
function printImageThumb() with img title tag

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1148]
Please put the img title tag in the function ```printImageThumb()```. Or make it as an option.
<pre><code>function printImageThumb($alt, $class = NULL, $id = NULL) {
	global $_zp_current_image;
	if (is_null($_zp_current_image))
		return;
	if (!$_zp_current_image->getShow()) {
		$class .= " not_visible";
	}
	$album = $_zp_current_image->getAlbum();
	$pwd = $album->getPassword();
	if (!empty($pwd)) {
		$class .= " password_protected";
	}
	$url = getImageThumb();
	$sizes = getSizeDefaultThumb();
	$size = ' width="' . $sizes[0] . '" height="' . $sizes[1] . '"';
	$class = trim($class);
	if ($class) {
		$class = ' class="' . $class . '"';
	}
	if ($id) {
		$id = ' id="' . $id . '"';
	}
	$html = '&lt;img src="' . html_encode(pathurlencode($url)) . '"' . $size . ' alt="' . html_encode($alt) . '" title="' . html_encode($alt) . '"' . $class . $id . " /&gt;";
	$html = zp_apply_filter('standard_image_thumb_html', $html);
	echo $html;
}</code></pre>

**Comment by acrylian** [comment]
Why not use the `alt` attribute (it's a attribute not a tag!) for this purpose?
