### ISSUE TITLE
function printAlbumThumbImage() with img title tag

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1149]
Please put the img title tag in the function ```printAlbumThumbImage()```. Or make it as an option.
<pre><code>function printAlbumThumbImage($alt, $class = NULL, $id = NULL) {
	global $_zp_current_album, $_zp_themeroot;
	if (!$_zp_current_album->getShow()) {
		$class .= " not_visible";
	}
	$pwd = $_zp_current_album->getPassword();
	if (!empty($pwd)) {
		$class .= " password_protected";
	}

	$class = trim($class);
	if ($class) {
		$class = ' class="' . $class . '"';
	}
	if ($id) {
		$id = ' id="' . $id . '"';
	}
	$thumbobj = $_zp_current_album->getAlbumThumbImage();
	$sizes = getSizeDefaultThumb($thumbobj);
	$size = ' width="' . $sizes[0] . '" height="' . $sizes[1] . '"';
	if (!getOption('use_lock_image') || $_zp_current_album->isMyItem(LIST_RIGHTS) || empty($pwd)) {
		$html = '&lt;img src="' . html_encode(pathurlencode($thumbobj->getThumb('album'))) . '"' . $size . ' alt="' . html_encode($alt) . '" title="' . html_encode($alt) . '"' . $class . $id . ' /&gt;';
		$html = zp_apply_filter('standard_album_thumb_html', $html);
		echo $html;
	} else {
		echo getPasswordProtectImage($size);
	}
}</code></pre>

**Comment by acrylian** [comment]
Please see my answer on #1148.

**Comment by sbillard** [comment]
It is an option as $id is passed as a parameter to the function.
