### ISSUE TITLE
getSearchWords() is empty by search result 0

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1150]
The getSearchWords() function returns an empty string if the search result is 0. I can not find the place where the search string is removed.

`getSearchWords()`
->
`$_zp_current_search->codifySearchString()`
->
`$this->getSearchString()`
->
`$this->words`
->
`zpFunctions::removeTrailingSlash(strtr(sanitize($_REQUEST['words'], 4), array('__23__' => '#', '__25__' => '%', '__26__' => '&', '__2F__' => '/')))`

The last is not empty.

I will display: 0 results for [searchstring]

**Comment by sbillard** [comment]
Can you provide more details? I just tried a search that finds nothing and the words are certainly present and correct.

To see, visit http://testalbum-2.sbillard.org/zenphoto, be sure the effervescence+ theme is active,  and type in the search "nothing & no_one" You will get the result back "Sorry, no matches for nothing AND no_one. Try refining your search." Clearly the search words were retained.

**Comment by acrylian** [comment]
You didn't say which theme. The Zenpage theme does indeed clear the search words on its search.php in line 35 if no results are found. I don't remember why this was done but since you just searched you might still remember what you searched for…  And keeping the word is less important since it makes no sense to search within no results if that option is set…

**Comment by sbillard** [comment]
The normal search behavior for themes made by the zenphoto developers is that if you do a search from the results of a search page the search will be a "refinement" of the previous search. That is it will search only within the results of the prior search. As acrylian notes above, doing this if the prior search failed to find anything would be fruitless. For this reason the search context is cleared so any new search would be global (as the user would expect.)

**Comment by mebels** [comment]
Pah! Thanks for the hint.
I completely overlooked that.
The clearSearchWords() function jumped across the screen in some PHP file in /zp-core, but at the time I was so engrossed in the files in /zp-core/ that I missed it.

Theme basic search.php line 21.

I have disabled "within".

I also want to show the search string at result 0, because if it's a complicated one, it's nice to see it again and maybe refine it.

**Comment by sbillard** [comment]
The effervescence theme does show the search words when the result is 0. It just captures the value before the clearSearchWords() function call, see circa line 55. From a design standpoint that would be a better choice than removing the clear. Who knows, maybe someday you will want to re-enable the "within."
