### ISSUE TITLE
Problem with quotation marks by the search

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1151]
There is a problem with quotation marks in searchstrings.

The first problem is that quotation marks removed from searchstrings and new quotation marks are set (first/last position).
String matching: pattern
Treat spaces as space
Description: ... Hello "World" Today ...
Searchstring: Hello "World" Today
`var_dump($_POST); //array(2) { ["words"]=> string(13) "Hello "World" Today" ["search_within"]=>string(1) "1" }`
`echo $_REQUEST['words']; // Hello "World" Today`
`echo getSearchWords(); // "Hello World Today"`

It removes the original quotation marks and sets new ones for more than one word.
String matching: pattern
Treat spaces as space
Searchstring: "World"
`var_dump($_POST); //array(2) { ["words"]=> string(7) ""World"" ["search_within"]=>string(1) "1" }`
`echo $_REQUEST['words']; // "World"`
`echo getSearchWords(); // World`
In the last case aren't putting quotation marks at first/last position.
Searchstring: World Today
`var_dump($_POST); //array(2) { ["words"]=> string(13) "World Today" ["search_within"]=>string(1) "1" }`
`echo $_REQUEST['words']; // World Today`
`echo getSearchWords(); // "World Today"`
In the last case are putting quotation marks at first/last position.

The next problem are with quotation marks in the titles and descriptions.
String matching: pattern
Treat spaces as space
Description: ... Hello "World" Today ...
Searchstring: Hello "World" Today -> no result.
Searchstring: Hello "World" -> no result.
Searchstring: "World" Today -> no result.
Searchstring: Hello World Today -> no result.
Searchstring: Hello World -> no result.
Searchstring: World Today -> no result.
Searchstring: Hello Today -> no result.
Searchstring: "Today" -> result.
Searchstring: Today -> result.

First, I want to display the original search string.
Next, the problem with quotation mark in title and description will not find anything.

**Comment by acrylian** [comment]
As mentioned the original search string is processed when the searc hobject is setup.

`Hello "World" Today` does not makes much sense as a search string because the quotes are meant to group several words together (as you know it from other search engines).

Please also check the various options for search.

**Comment by mebels** [comment]
OK, I had forgotten to mention a setting.
`Treat spaces as space`
That means something like an exact search, similar to a search string in quotation marks?

The source code mentions "atomic search", but I did not find anything about that term.    

With `Treat spaces as AND` the entries are found only when remove the quotation marks.    
String matching: pattern
Treat spaces as AND
Description: ... Hello "World" Today ...
Searchstring: Hello "World" Today -> no result.
Searchstring: "Hello "World" Today" -> no result.
Searchstring: Hello World Today -> result.

With `Treat spaces as OR` is the result too big.

Of course, a quoted word makes no sense in a search string, but it is written in the image description.    
In other search engines, like Google, a single word in quotation marks means that this must happen.
    
For complicated search strings, it is nice if they were displayed in the original.

**Comment by acrylian** [comment]
Of course Zenphoto's search can by no means compete with Google ;-) 

> The source code mentions "atomic search", but I did not find anything about that term.

I think my former colleague means that they are treated as an entity.

> Treat spaces as AND / Searchstring: Hello "World" Today -> result. 

Makes sense as that is actually what you want to search. Did you try to actually use `&` (as you used `|`) in the search itself? Then you would directly request your search term.

**Comment by mebels** [comment]
The problem is, if there is a word in quotes in the haystack, it will be difficult to find a coherent search string with that word.

Description (Haystack): ... Hello "World" Today ...
Find: Hello "World" Today (coherently)
Find: Hello World Today (coherently)

String matching: pattern
Treat spaces as space
Searchstring: Hello "World" Today -> no result.
Searchstring: Hello World Today -> no result.
Searchstring: "Hello "World" Today" -> no result.
Searchstring: "Hello World Today" -> no result.

String matching: pattern
Treat spaces as AND
Searchstring: "Hello "World" Today" -> no result.
Searchstring: "Hello World Today" -> no result.

In fact, quotes are used to find a coherent string, but here it is just the opposite.

Searchstring: Hello "World" Today -> result.
Searchstring: Hello World Today -> result.

But, that's just a coincidence in my test. If there were more descriptions in which all words occur, others would be found as well, such as:
Today Hello "World"
"World" Today Hello
"World" Hello Today
Today "World" Hello
But it's just an (Treat spaces as ) AND in the searchstring.
Correct searchstrings are:
"Hello "World" Today"
or
"Hello World Today"
But no results.

Treat spaces as OR is out of the question here. The result is too big, since each occurrence of the words is searched individually.

**Comment by sbillard** [comment]
As posted on your forum thread, if you want a literal quote in your search string then put it into quotes. E.g. 

Hello '"'World'"' Today

Quotation marks in search strings are meant to cause the enclosed characters to be taken literally. That is not to recognize search operators, etc. within the strings. Maybe it is easy to recognize that with "World" _World_ does not need to be treated literally but that is the simple case. When parsing search strings, Search does not try to evaluate the strings enclosed in quotations to see if there are any operators, escape sequences like such as _\n_ for new line, etc. To do so is really an AI problem, if implemented would be computationally prohibited, and in most cases does not matter.

After all, if someone is visiting your site they are unlikely to guess that the word _World_ should be in quotes in the first place, so would not enter that string. Your best resolution for this is to fix your target data to use expected nomenclature.

**Comment by acrylian** [comment]
Have to agree…
