### ISSUE TITLE
Login page bugs

### ISSUE THREAD

**Issue by kalyan4786** [zenphoto/zenphoto#1152]
Whenever a user enters a **wrong password**, it prompts that the **username or password is wrong** but after that when the **user enters correct password and submits it**, the site reports that user **didn't entered any password**. If the user **reloads the login page** and try to login with **correct password** again then the user is **logged in**. Fix this issue.

**Comment by acrylian** [comment]
Try the support build please.

**Comment by acrylian** [comment]
Due to lacking feedback closed.
