### ISSUE TITLE
issues with "Data privacy usage notice" and "Data privacy policy page" fields

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1157]
hi

there is 2 issues on these fields.

1- Data privacy usage notice : we can't edit this filed with TinyMCE as other textarea data (as gallery description for example)

2- the textarea/input of these fields don't fill the cell raw (see the picture)
![capture](https://user-images.githubusercontent.com/1224809/40530193-101703a2-5ff8-11e8-822c-75d412df9451.PNG)

**Comment by acrylian** [comment]
This is really meant for a short one liner notice without formatting and not for a full data privacy statement. For that you should use a separate page.

The width should be the same as on all other multilingual fields. Does not look that way for me and only if you have your browser window very wide.

![bildschirmfoto 2018-05-25 um 09 04 03](https://user-images.githubusercontent.com/2474309/40530878-b1d4a3a0-5ffa-11e8-8e56-26d890aea83e.jpg)
