### ISSUE TITLE
debug.log: imagecreatefromjpeg() failed

### ISSUE THREAD

**Issue by kochs-online** [zenphoto/zenphoto#1158]
I noticed a couple of entries in the `debug.log` file that are related to uploading invalid JPEG images, I think. I'm running Zenphoto version 1.4.14.

Without further ado – here are the `debug.log` entries:
```
{31636:Thu, 10 May 2018 21:16:49 GMT}
  WARNING: imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error:  in /home/www/zenphoto/zp-core/lib-GD.php on line 91
  imagecreatefromjpeg called from zp_imageGet (lib-GD.php [91])
    from cacheImage (functions-image.php [197])
      from i.php [165]
{31636:Thu, 10 May 2018 21:16:49 GMT}
  WARNING: imagecreatefromjpeg(): '/home/www/zenphoto/albums/example-album/invalid.jpg' is not a valid JPEG file in /home/www/zenphoto/zp-core/lib-GD.php on line 91
  imagecreatefromjpeg called from zp_imageGet (lib-GD.php [91])
    from cacheImage (functions-image.php [197])
      from i.php [165]
{31636:Thu, 10 May 2018 21:16:49 GMT}
  WARNING: Cannot modify header information - headers already sent by (output started at /home/www/zenphoto/zp-core/lib-GD.php:91) in /home/www/zenphoto/zp-core/functions-image.php on line 30
  header called from imageError (functions-image.php [30])
    from cacheImage (functions-image.php [200])
      from i.php [165]
{31636:Thu, 10 May 2018 21:16:49 GMT}
  WARNING: Cannot modify header information - headers already sent by (output started at /home/www/zenphoto/zp-core/lib-GD.php:91) in /home/www/zenphoto/zp-core/functions-image.php on line 31
  header called from imageError (functions-image.php [31])
    from cacheImage (functions-image.php [200])
      from i.php [165]
{31636:Thu, 10 May 2018 21:16:49 GMT}
  WARNING: Cannot modify header information - headers already sent by (output started at /home/www/zenphoto/zp-core/lib-GD.php:91) in /home/www/zenphoto/zp-core/functions-image.php on line 32
  header called from imageError (functions-image.php [32])
    from cacheImage (functions-image.php [200])
      from i.php [165]
```

Nothing major, but error handling might be improved here because it took me quite some time to figure out why the image didn't show up.

**Comment by acrylian** [comment]
We'll take a look.

**Comment by kochs-online** [comment]
Server error log reads: `Not a JPEG file: starts with 0x48 0x42`

For clarification: I'm not expecting Zenphoto to work magic on a garbled JPEG file, but being silent on the frontend and only throwing a bunch of warnings in the `debug.log` file isn't helpful for an end user.

**Comment by acrylian** [comment]
I understand and agree.  There should have been a default image indicating a broken image indicating some image processor error:
![err-failimage](https://user-images.githubusercontent.com/2474309/40588886-b953a450-61e4-11e8-8a74-d766a228e981.png)

But it might be that the error comes earlier so it doesn't get that far. Can you provide one of the images to produce (feel free to mail directly if you cannot or want link in public).

**Comment by kochs-online** [comment]
I don't have that particular file anymore, but I think you can use any random file that is not a valid JPEG (or image in case GD-lib is that fault-tolerant).

Here is a 16 KiB file that was generated using [random.org](https://www.random.org/bytes/):
![invalid.jpg](https://user-images.githubusercontent.com/17382358/40604743-5eb9e76c-6260-11e8-8945-b2c5927479b2.jpg)

**Comment by acrylian** [comment]
Thanks, I figured that probably an simple text file pretending to be a jpg should trigger the same issue.

**Comment by acrylian** [comment]
I tried with a text file with jpg suffix and I do get the above image indicating an issue with the image used as intended.

**Comment by kochs-online** [comment]
Sorry, it took me a while to try again. I'm not getting that image. Neither in back- nor in frontend (see screenshot).
Zenphoto is only trying to load the damaged image and puts those messages into `debug.log`.
![screenshot_0](https://user-images.githubusercontent.com/17382358/41201025-db39e67a-6cb0-11e8-995a-79c022aaf457.png)

**Comment by acrylian** [comment]
What does the PHP error log say? Without any more info I can only suggest to check 
- the server configuration regarding graphics library
- PHP memory and file size of the images,
- the images itself for corrupt meta data
- file/folder permissions

Something is not working correctly on your setup.

**Comment by kochs-online** [comment]
The Apache error log only shows: `Not a JPEG file: starts with 0x33 0xd1`

This is what `phpinfo()` tells me about GD lib:
```
GD Support: enabled
GD Version: bundled (2.1.0 compatible)
FreeType Support: enabled
FreeType Linkage: with freetype
FreeType Version: 2.5.2
GIF Read Support: enabled
GIF Create Support: enabled
JPEG Support: enabled
libJPEG Version: 8
PNG Support: enabled
libPNG Version: 1.2.50
WBMP Support: enabled
XPM Support: enabled
libXpm Version: 30411
XBM Support: enabled
Directive gd.jpeg_ignore_warning: 0 (Local Value & Master Value)
```

PHP memory limit is 256 MiB. I used the image file [provided above](#issuecomment-392455738) which is 16 KiB in size.

The example image itself is consisting of random bytes and as such obviously corrupt. I made no effort to add metadata.

Folder permissions are `0755`. File permissions are `0644`. The web server process user is owner of the folder/file.

What do you refer to with your last point?
> image sizes set on the options

(I cannot remember setting any image size options.)

The file provided above can be used to reproduce this behaviour (at least for me).

**Comment by acrylian** [comment]
Sorry, I forgot somehow that this ticket is not about not working images but about that you don't get a hint about it. Well, you do as the debuglog tells about it.

So I retired. A text file pretending to be an image and the invalid image posted above cause the broken image locally. On our live site both literally kill the album. I can only assume that this is a difference how servers are setup. 

But such really corrupt image is meant to cause trouble and kills the whole album on our own site with the same errors you got. This might be rather core PHP level issue.

Is this really an issue as you surely normally don't want to use corrupt images?

**Comment by kochs-online** [comment]
Well, not a huge issue for me (anymore). I'm not planning on using corrupt/invalid images. ;-)
But it took me some time to figure it out when it happened the first time. So I thought it might be worth telling you about it.
But I understand it's a rather small nuisance than a real issue lots of people are facing.

**Comment by kochs-online** [comment]
This issue is fixed for me if I surpress the error from `imagecreatefrom()` by adding `@` in front of the instruction. Maybe you can give it a go on your server too (as behavior differed).
