### ISSUE TITLE
issue with option `zpcookieconsent_header` of plugin cookieconsent

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1159]
hi

I found an un-needed option on new plugin coockieconsent.

In fact, with cookieconsent js, there are 2 templates options: `layouts` (object with 3 data 'basic', 'basic-close' and 'basic-header') with and `layout : basic`.
each layout uses some `content` and `elements` objects.

as default values of cookieconsent js are used by the zenphoto plugin, `basic-header` layout is not used, `header content` and `header element` are never used too.

so `zpcookieconsent_header` is useless, because cookieconsent js never uses and displays it.

see here https://cookieconsent.insites.com/documentation/javascript-api/

**Comment by acrylian** [comment]
Not sure I can follow you. The `theme` option is used as documented
![bildschirmfoto 2018-05-28 um 12 12 53](https://user-images.githubusercontent.com/2474309/40609893-7841a156-6270-11e8-8898-bc740d64bf5a.jpg)
The layout ones are for custom stuff which the plugin for simplicity does not cover. You can do you own js define if you really need that.


The option `zpcookieconsent_header` is very well used. It is setup in line 143 and then used in line 189 within the `content` part as documented on the site you referenced.
 
![bildschirmfoto 2018-05-28 um 12 14 05](https://user-images.githubusercontent.com/2474309/40609938-a4670a00-6270-11e8-93a1-580592355db2.jpg)

**Comment by vincent3569** [comment]
compliance (object) lists 3 different behaviors of the js script
type (string) gives the compliance default value : 'info'
![screenshot011](https://user-images.githubusercontent.com/1224809/40613556-3fd6dcdc-627f-11e8-9bdc-e44d0688b37b.jpg)

layouts (object) lists 3 different layout of the js script
layout (string) gives the layout default value : 'basic'

elements (object) lists html template of each elements of the layout.
as you can see, 'basic' layout only displays 'messagelink' and 'compliance' elements, and never uses 'header' element.
![screenshot012](https://user-images.githubusercontent.com/1224809/40613793-488a32a6-6280-11e8-8b1f-8e538c8e8698.jpg)

so, after testing each options, be sure, zpcookieconsent_header option and relevant code is useless because with default options of cookieconsent js are never overwrited by the plugin and header is never used.


so these codes is useless
````
				gettext('Header') => array(
						'key' => 'zpcookieconsent_header',
						'type' => OPTION_TYPE_TEXTBOX,
						'order' => 0.5,
						'multilingual' => 1,
						'desc' => gettext('Text for the popup header by the plugin. Leave empty to use the default text.')),
````

and

````
		$header = gettext('Cookies used on the website!');
		if (getOption('zpcookieconsent_header')) {
			$header = get_language_string(getOption('zpcookieconsent_header'));
		}
````

and

````
						"header": "<?php echo js_encode($header); ?>",
````



and in the same way, as 'zpcookieconsent_buttondecline' option is not used by cookieconsent js, so this code is useless: 

````
 		$decline = gettext('Decline');
		if (getOption('zpcookieconsent_buttondecline')) {
			$decline = get_language_string(getOption('zpcookieconsent_buttondecline'));
		}
````

and 

````
					"deny": "<?php echo js_encode($decline); ?>",
````

**Comment by acrylian** [comment]
All right, thanks for clearing up. Apparently I didn't keep track with the changes in their script. If you like send a pull request with the changes.

**Comment by vincent3569** [comment]
ok, I will do that shortly
