### ISSUE TITLE
openstreetmap: add control layer option

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1161]
hi

It would be a nice improvement if you could implement control layer option.
see documentation of leafletjs here:
https://leafletjs.com/reference-1.3.0.html#control-layers
https://leafletjs.com/examples/layers-control/

to be more clear, I wish to have a selector on the map (on the front end) to allow visitors to choose on what tiles they want to see markers.
As I don't want to enable all tiles used by the plugin, maybe a checkbox to select what tiles to use in front end is a good idea,
I have a look on core code, and admin/options/general/languages seems to be the right way to have both the selected tiles to display and the tile to use by default.

you can see the html result I wish to have here: http://plnkr.co/edit/d4ycVbdVRGoxE9h8svQe
note there is an issue because the loaded map is not selected by default on the control and I requested for help on stackoverflow: https://stackoverflow.com/questions/50586842/how-to-use-layers-control-with-leaflet-and-leaflet-provider

**Comment by vincent3569** [comment]
I had an answer from stackoverflow and I understood where was the mistake.

here is an example of code that could be generated by the plugin, with the requested improvement:

````
	<script>
		var map = L.map('osm_map', {
                    zoomControl: false,
                    zoom: 4,
                    minZoom: 2
                });
		var defaultBaseMap = L.tileLayer.provider('OpenTopoMap').addTo(map);
		var baseMaps = {
            'HikeBike.HikeBike': L.tileLayer.provider('HikeBike.HikeBike'),
            'OpenTopoMap': defaultBaseMap,
            'OpenStreetMap.France': L.tileLayer.provider('OpenStreetMap.France'),
        };
		defaultBaseMap.addTo(map);
		L.control.zoom({position: 'topleft'}).addTo(map);
		L.control.layers(baseMaps, null, {position: 'topright'}).addTo(map);
		L.marker([57.150,-6.100]).addTo(map);
		L.marker([57.500,-6.450]).addTo(map);
		map.fitBounds([
			[57.150,-6.100], [57.500,-6.450]
		]);
	</script>
````

works well on this standalone htlm page: http://test.vincentbourganel.fr/test_osm_map.html

**Comment by acrylian** [comment]
Thanks, I had used these layers in the past and will look into it as soon as I can.

**Comment by acrylian** [comment]
Yes, of course those options are the template. I would suggest the following:
- Option to enable this feature in general (not everyone might want it)
- Checkbox list for selecting the tiles to provide
- The standard tile selector we already have could just act as the default one to save yet another option

**Comment by vincent3569** [comment]
I have a look on languages management option and, of course, this not a standard behavior for plugin and theme options.

So you are in the right way to use several options. And, according to me, only 2 options are enought:
- Checkbox list for selecting the tiles to provide (optionnal)
- The existing tile selector as the default one (mandatory)

If no checkbox are choosen in the 1st option, that means that admin doesn't want to use this behavior (layer control is not displayed and only default tile is displayed)
maybe, one thing is missing (well managed with languages management options : the default tile should be in the checked tiles list, but a notice may explain the behavior.

**Comment by acrylian** [comment]
That would work probably, too. A general enable option had the advantage that you can switch it on/off without changing the set of tiles. But probably you don't do that often so not needed.

We could automatically add the tile set in the standard selector as the default to the control layers. So the checkbox list would be for additional layers technically. If it is also selected there we can just check that to avoid it twice.

**Comment by vincent3569** [comment]
Hi Malte,
I have a related question on openstreetmap plugin:

What is the purpose of file zp-extensions/openstreetmap/
tile-definitions.js ?
As far I can see, this file is never used.

**Comment by acrylian** [comment]
Obsolete, just  forgotten to be removed on moving from repo to zp when switched to the plugin for the tile defines.

**Comment by vincent3569** [comment]
Hi Malte,

I worked on this feature based on this demo page: http://test.vincentbourganel.fr/test_osm_map.html

I have a headache on some points:
-selected layers are not saved
-how can I use these seleted layers to create the control
[openstreetmap.php.txt](https://github.com/zenphoto/zenphoto/files/2251679/openstreetmap.php.txt)

I you can point me in the right direction I will appreciate.

**Comment by acrylian** [comment]
Well, if I had time I would already have worked on it ;) I have not forgotten it. Cache stuff come first.

If I remember right off hand it requires a quite (JS) different setup to use this layer control.

Will take a look later why options might not save. Don't think there are defaults needed for these extra layers as they are off by default anyway.

**Comment by vincent3569** [comment]
hi Malte
I have another version of my file 
[openstreetmap.php.txt](https://github.com/zenphoto/zenphoto/files/2252789/openstreetmap.php.txt)
you can have a look with my pull request.

now, some layers are stored, but not all, and I don't understand where is the mistake.

my other need:
how to generate an array of selected layers stored with in options osmap_layer_*?

I am leaving for 3 weeks for hollydays.
cheers

**Comment by acrylian** [comment]
Will take a look at it all as soon as I get to it! 

Have a nice vacation! If all works out (cache issues primarily) we might have 1.5.1 out meanwhile ;-)

**Comment by vincent3569** [comment]
hi Malte
I am coming back from my hollidays.

you had time to have a look on my code?
I am unable to understand why layers list is stored for some layers but not for all selected list.

**Comment by acrylian** [comment]
Hi Vincent,

sorry, I haven't, currently busy with some other stuff regarding image cache that is more important right now. I will look at this as soon as I can.

**Comment by vincent3569** [comment]
hi
please note I only want a help on the code that I wrote.
I am unable to understand how OPTION_TYPE_CHECKBOX_UL woks and how to store and read options managed by this value.
If you can point me in the right direction, it may be enought...

**Comment by acrylian** [comment]
I know and I appreciate it.  I quickly looked.  OPTION_TYPE_CHECKBOX_UL is actually the same principle like all other option groups like OPTION_TYPE_SELECTOR.

Look at `getOptionsSupported()`. At the beginning the list of the tiles a is fetched:
`$providers = array_combine(openStreetMap::getTitleProviders(), openStreetMap::getTitleProviders());`

That is used for the option select list: 
`	gettext('Map tiles') => array(
						'key' => 'osmap_maptiles',
						'type' => OPTION_TYPE_SELECTOR,
						'order' => 7,
						'selections' => $providers,
						'desc' => gettext('The map tile provider to use. Only free providers are included.'
										. ' HERE, Mapbox and Thunderforest map tiles require access credentials and Esri requires registration.'
										. ' More info on <a href="https://github.com/leaflet-extras/leaflet-providers">leaflet-providers</a>')),`

Since every option is still standalone, they are not grouped in the database, the option names neeed to be suffixed so they are separated. Probably the `getTileProviders()`method should be extended with a parameter to do this before returning everything.

**Comment by fretzl** [comment]
The scriptless-socialsharing plugin is a nice example of its use.

**Comment by vincent3569** [comment]
Hi
I found the main issue: zenphoto options don't like to use a "." in it.

there is my code for the improvement :
https://github.com/vincent3569/zenphoto-dev/commit/a5343dda3f3f22defe0b8977c8c798f738c2416f

tested on my test website: https://test.vincentbourganel.fr/pages/map-osm/

if you can revue the code, I will make a pull request.

**Comment by acrylian** [comment]
Thanks! Looks good. I was not aware that dots are not allowed in option names but I assume it perhaps more a mysql things. I took a quick look - will look closer later - but one thing could be streamlined. You do this at least twice:
`$provider_dbname = str_replace(".", "_", $provider);
			$layerslist[$provider] = 'osmap_layer_' . $provider_dbname;`

I would suggest to create a separate mthod that internally does this conversion and already returns the whole array as needed for the layerlist.

**Comment by vincent3569** [comment]
why not...
I need some tips:
- it should be a static function ?
- in which class: openStreetMapOptions or openStreetMap?

**Comment by acrylian** [comment]
Yes, a static method just like `openStreetMap::getTitleProviders()` which it would call internally and therefore in the `openStreetMap` class. The other one is really only for specific option stuff. And having it within the main class adds to flexibility using the class (whatever someone does with it possibly).

**Comment by vincent3569** [comment]
there is my new code for the improvement:
https://github.com/vincent3569/zenphoto-dev/commit/07fbf5a149514d9f92fba44eea05bfe86e5f6b29
I hope it's enough for you.

you have to accept my first pull request (update of leaflet).
then I can make a pull request for this new feature of osm plugin.

**Comment by acrylian** [comment]
Just commented a bit ;)

**Comment by vincent3569** [comment]
final commit for the new feature.
feel free to accept or not, to change something or not, but I don't want to change anything now
https://github.com/vincent3569/zenphoto-dev/commit/91300ce0a2e3d1c512e4e670e737d6645463e557

I don't know why all my commits are added to the pull request.

**Comment by acrylian** [comment]
Thanks, again your work is appreciated. Just trying to help to improve and get it consistent! Will take a look later today and surelly pull it in.

**Comment by vincent3569** [comment]
https://github.com/zenphoto/zenphoto/pull/1191
