### ISSUE TITLE
publish recursively

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1167]
Hello,
i can't publish albums with subalbums and images recursively.
My modding standard is all new albums, subalbums and images are unpublished. (images in image-pages are blocked with a PHP code rule in the theme.) After adding a title and description to all of them, I want to publish them all at once recursively. At this time i can't publish all photos in one album with one command.

**Comment by acrylian** [comment]
There is a plugin called publishContent for that task.

**Comment by mebels** [comment]
OK, thanks for the tip, it seems to be a useful plugin. I will test it.
