### ISSUE TITLE
Problem with getLink() by getRandomImages()

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1168]
Hello,
i use the getRandomImages() function and this break my website, but not every time, coincidence.

<pre><code>
{32368:Fri, 22 Jun 2018 18:24:04 GMT} Zenphoto v1.5
  EXCEPTION (0): Call to a member function getLink() on null in /var/www/virtual/xxx/html/themes/basic/image.php on line 270
</code></pre>

<pre><code>
$randomimage_a = getRandomImages();
$randomimage_b = getRandomImages();
$randomimage_c = getRandomImages();

echo $randomimage_a->getLink()
echo $randomimage_a->getThumb()

echo $randomimage_b->getLink()
echo $randomimage_b->getThumb()

echo $randomimage_c->getLink()
echo $randomimage_c->getThumb()
</code></pre>

If the first has an error, then it breaks off already.

**Comment by acrylian** [comment]
You have to check if the function really returns an image object. It may not so this of course fails.

**Comment by mebels** [comment]
What means "May be NULL if none exists" exactly?
NULL = no images in the folders?
NULL = no images in the database?
In both images exists.
Is there a problem with unpublished images?

I have tested yet this:
`<?php echo printRandomImages(); ?>`
OK, no breaks, but randomly 0 to 5 images are displayed. not perfect. I search for a solution to display always 3.

Is there a problem with the MySQL command?
`'SELECT `folder`, `filename` ' . ' FROM ' . prefix('images') . ' INNER JOIN ' . prefix('albums') . ' ON ' . prefix('images') . '.albumid = ' . prefix('albums') . '.id ' . ' INNER JOIN (SELECT CEIL(RAND() * (SELECT MAX(id) FROM ' . prefix('images') . ')) AS id) AS r2 ON ' . prefix('images') . '.id >= r2.id ' . ' WHERE ' . prefix('albums') . '.folder!="" ' . $imageWhere . ' ORDER BY ' . prefix('images') . '.id LIMIT 1'`

**Comment by acrylian** [comment]
It may return no image object if the one picked is one that is not allowed for the visitor to see for example. You cannot do this with a plain query because of inheritance. This function is an very old one and a bit off structured with it's daily option built in (and despite the name it returns one image and not "images", too). 

The image_album_statistics plugin contains an alternative for random images which I personally prefer for plain random images without that daily option (which this one eventually will be reworked to use internally).

**Comment by mebels** [comment]
I overlooked the:
`$imageWhere = " AND " . prefix('images') . ".show=1";`
So only images that are published are queried.
In my installation, only I am and currently not logged in. There are published and unpublished photos, but no kinda protected ones. So theoretically only images in the random would have to be published. Where then the NULL?
