### ISSUE TITLE
Please don't use "button" in CSS

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1170]
Please don't use the HTML tag "button" to style buttons via CSS.
There is no way to style buttons back to default style.
At least in the theme basic in ZenPhoto v1.5 it is like that still on two points in the ```commons.css```.

```
/* standard buttons */
button:hover,.buttons a:hover {
	text-decoration: none;
	background-color: #dff4ff;
	border: 1px solid #CBCBCB;
	color: #FF8A00;
}
```

```
/* positive buttons */
button.positive,.buttons a.positive {
	text-decoration: none;
	color: #529214;
}
```

https://forum.zenphoto.org/discussion/1410012/button-css-in-themes

**Comment by acrylian** [comment]
The point here is that buttons don't have the default style to match those of plugins without adding loads of specific classes. 

We had discussed this 
> Be assured any new theme made will not do this. 

You surely read on the 1.5. release post:

>  But all included themes are now labeled deprecated. 

Meaning they will not be further developed or significantly updated.

As usual, you can always create your own theme if you need things differently.

**Comment by mebels** [comment]
That's easy to say. I have no idea which button with this style is meant to check that. I would have to check all buttons. How should I find the button? It can be any button.

**Comment by thany** [comment]
This is in the basic theme. I don't see why it would not be okay to style elements in a theme. If such style was being pushed from the backend in some way, you'd be right, but if you need a different style for your buttons, don't use the basic theme then. Just write your own - you obviously know web tech so I'm sure you can. I also don't see why you'd want the default style specifically. The default button style is undesirable in most cases *because* it's different from browser to browser.

@mebels What exactly are you trying to achieve?

**Comment by mebels** [comment]
@acrylian OK, the info in your first passage makes sense. I had not seen it like that before.

Unfortunately, everything except buttons can be styled back.

I have included a JavaScript that works with a button. I do not like this button style. It does not look like a button.

@thany Your info in your first passage also makes sense. I had not seen it like that before. I like the basic and have already redesigned it, but just added CSS rules. I like to be original with little adjustments rather than something completely new. Because of the Button Style I have to change the original.

For buttons, the recognition as a button is important to me. Newly styled buttons are not always recognized as buttons.

Hint: Many HTML elements can be designed like buttons, but the HTML button does not have to be redesigned globally.

Maybe I'm just too conservative here. I will think again.

Thus, the misunderstanding should be clarified. Thanks for the discussion.

**Comment by acrylian** [comment]
> Newly styled buttons are not always recognized as buttons.
Visually yes, but not semantically.

> Hint: Many HTML elements can be designed like buttons, but the HTML button does not have to be redesigned globally.

There is of course no need to re-style any element since all have browser defaults. Proper HTML should make sense without any styling ;-) But that is a bit very bare bones nowadays and those defaults differ by browser and system. So you it is good UX to have a general UI that is the same everywhere.

**Comment by thany** [comment]
The reason to style buttons globally is to make them look the same everywhere, so the user/visitor can recognize any button without thinking.

You should probably only make small variations in a buttons, such as colour or size, and that *could* be achieved generically with CSS4 variables ([browser support](https://caniuse.com/#search=variables) for that is excellent if you ignore IE).

**Comment by mebels** [comment]
For buttons there is no "default" style on which buttons could be reset. That's the big problem with buttons. Style buttons with CSS `"button {}`, then there is no back to browser defaults.
Buttons are difficult.
...
style a HTML `<p>` Element as a Button:
```p {
    color: #ffffff;
    text-shadow: 0 0 1px #000;
    cursor: pointer;
    border-radius: 5px;
    background-image: linear-gradient(#e8e8e8,#808080 50%,#585858 50%,#292929);
    background-image: -o-linear-gradient(#e8e8e8,#808080 50%,#585858 50%,#292929);
    background-image: -ms-linear-gradient(#e8e8e8,#808080 50%,#585858 50%,#292929);
    background-image: -moz-linear-gradient(#e8e8e8,#808080 50%,#585858 50%,#292929);
    background-image: -webkit-linear-gradient(#e8e8e8,#808080 50%,#585858 50%,#292929);
    background-color: #a7a7a7;
    border-style: solid;
    border-width: 1px;
    border-color: #000;
}```

**Comment by thany** [comment]
@mebels Vendor prefixes for linear gradient have been obsolete for [a long very long time](https://caniuse.com/#feat=css-gradients) ;)

**Comment by acrylian** [comment]
"won't fix" refer to this theme. As said in future themes we will try to avoid direct element if possible.
