### ISSUE TITLE
2 CSS Errors in 1.5

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1171]
Also affects master 1.5.

```/themes/basic/common.css```
"margin-left" only without "auto".
```
#loginform {
...
	margin-left: 0 auto;
...
}
```
```/zp-core/zp-extensions/openstreetmap/leaflet.css```
"behavior" is unknown.
```
.lvml {
	behavior: url(#default#VML);
	display: inline-block;
	position: absolute;
	}
```

**Comment by acrylian** [comment]
This is third party css used as is from leaflet. We generally don't modify these. 

I can't say what this property does therefore. It seems it at least was a valid one once and is probably included from some IE backward compatibility.

**Comment by acrylian** [comment]
For the future: Please create separate issues of referring to separate components (like theme and plugin here). If reporting several issues list them as task list: https://help.github.com/articles/about-task-lists/
