### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by thany** [zenphoto/zenphoto#1172]
SQLite support, or support for some other portable DB, would be desirable for easier casual development.

Why?

I'm trying to set up a way that I can fire up a zenphoto instance with 1 command. From absolutely nothing to a running zenphoto, with 1 command. Nothing more. This would involve a portable webserver (can be done with Node.js) and a portable PHP (easy enough, it's just an executable), and a portable DB (not so easy at all with mysql, since it *has to* be a server).

I can then transfer the *whole* package to any other computer (provided that it has Node.js installed, which is extremely common in the world of frontend development) and run that one command to fire it up again.

**Comment by acrylian** [comment]
Sorry, not planned. There was once support but it was dropped: 

> SQLite support has been removed. This database is not capable of supporting some of the needed functions now used in Zenphoto.

https://www.zenphoto.org/news/zenphoto-1.4.3/

No idea if this has changed since, well, I don't use it I will not provide any effort. If you like to contribute a handler for it based on the existing ones, feel free.

**Comment by thany** [comment]
Is zenphoto written to use *only* mysql? Because then in practice it'll be nearly impossible to rewrite it to any other DB. If zenphoto uses some kind of middleware to talk to DB's, there's at least a chance :)

**Comment by sbillard** [comment]
Zenphoto presumes mySQL functionality and uses Query statements. But it is possible to transform these statements into a different dialect. Each supported database provides functions to process the requests. When SQLite was supported that is the means used. But it became unreasonable to continue to use SQLite because the feature mapping was too complex and sometimes not achievable.

Anyway, most WEB hosting facilities have an implementation of mySQL. If you know of a fully featured portable database, consideration could be made to support it.

**Comment by acrylian** [comment]
Well, MariaDB will also work since it is compatible ;-) So basically yes, Zenphoto is made for "standard webhosting" using MySQL.

**Comment by thany** [comment]
Webhosting is exactly what you cannot reasonably use when developing on zenphoto. You don't expect folks to upload files to their host constantly while working on a theme or plugin? That's mental! Which is why a "portable" instance of zenphoto is much more sensible, at least in my head it is, hence the request for a portable DB.

SQLite is a bit underfeatured as compared to MySQL, so perhaps that's not the way to go. Unfortunately, I don't know any other serverless SQL engines.

**Comment by acrylian** [comment]
> You don't expect folks to upload files to their host constantly while working on a theme or plugin? 
For that there are local server systems like WAMP, LAMP or MAMP. 

I will close this ticket.

**Comment by thany** [comment]
WAMP-like servers are a pain to set up. It still requires a lot of configuration before it actually works. Not very portable at all. This is why serverless is so populair nowadays. Any node.js serverside application for example, is a server in and of its own, and can be run anywhere. Databases don't have this luxury, but SQLite is one of the ones that does.

If there's anyone out there who'd like to comment on how to make it easier to se up a developer environment for those theme developers, please do.

**Comment by acrylian** [comment]
Well, I use MAMp and there is nothing complicated to setup. I don't use and never used node.js.

**Comment by thany** [comment]
Sorry to bump an old topic, but I found time to start working on it again...

Tried MAMp and it's absolute poop. It refuses to start MySQL and I can't figure out for the life of me how to actually access the website I have to put in the htdocs dir.

To me this is just another nail in the coffin for not supporting any form of portable database system. Getting a webserver with PHP to run is bad enough as it is, but adding another system that desperately wants to be its own server, nope. This isn't working, sorry.

**Comment by acrylian** [comment]
> Tried MAMp and it's absolute poop. It refuses to start MySQL and I can't figure out for the life of me how to actually access the website I have to put in the htdocs dir.

You access your website using http://localhost/folderofyourinstallation. MAMP is really pretty bullet proof and simple.

**Comment by thany** [comment]
I guess it's an extreme case of YMMV...
