### ISSUE TITLE
sitemap-extended missing <url> tag

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1173]
there is a problem with the plugin sitemap-extended.

I have set the value for "Sitemap processing chunk" to 1, so that for each album a separate sitemap.xml file is created. Now I have 11 errors with Google webmaster tools because I have 11 parent albums where sitemap.xml is broken because there is no <url> in it, just <urlset>. So there is a problem with parent albums in the first level.

why "Sitemap processing chunk" = 1?
because I want to make the sitemap with a stylesheet human-readable, which I have not come to yet.

> This required tag is missing. Add it and resubmit the data.
> Parent Tag: urlset
> Tag: url

**Comment by acrylian** [comment]
Does it happen only if the chunk is set to 1 or with other values as well?

> because I want to make the sitemap with a stylesheet human-readable, which I have not come to yet.

Why since the sitemap is meant for machines? If you open it in a browser it will also have some formatting applied.

**Comment by mebels** [comment]
Yes, actually only for machines, but they are XML files that can be styled by stylesheet. It will be difficult anyway, because the sitemap files are not created by album tree structure, but by database order.

With "Sitemap processing chunk" = "11" there are no errors.

**Comment by acrylian** [comment]
Okay, that is at least a hint. Will take a look as soon as I can.

**Comment by acrylian** [comment]
I am sorry, so far I have not been able to reproduce this no matter what chunk value I set. All generated sitemaps for albums are complete with all tags.

So something must be special about those albums. Please stated some details about these. Also review your server error log after running the sitemap generation.
