### ISSUE TITLE
Missing shorten indicator when pagebreak is set manually in tinymce 

### ISSUE THREAD

**Issue by bic-ed** [zenphoto/zenphoto#1179]
As seen in the following screenshots, if pagebreak is set before the default shortening length (pic 2), then shorten indicator is not shown. 

![no-pagebreak](https://user-images.githubusercontent.com/2939831/43004545-6e7c84c6-8c30-11e8-8397-27e89ac1de29.jpg)
![pagebreack](https://user-images.githubusercontent.com/2939831/43004547-6ea24ef4-8c30-11e8-9c98-7d1f4ae7464e.jpg)

**Comment by acrylian** [comment]
Will review. Might be on purpose because on manual shortening you won't just "cut" into a sentence that may be incomplete but choose a meaningful excerpt. The "read more" is actually quite clear that it is not all :-) But I agree that it is a bit inconsistent.

**Comment by acrylian** [comment]
Please give it a try in the support build.

**Comment by bic-ed** [comment]
Thanks acrylian, now it works if (and olny if) the option `truncate at pagebreak` is selected. Otherwise manual truncation doesn't work anymore even if text is shortened before the default value.

**Comment by acrylian** [comment]
Hm, I am not sure I can reproduce that. I get a truncation at page break with or without the "truncate at pagebreak" option being set on the articles.

I actually question that option. I mean if you set a pagebreak you want truncation so why enable it additionally… At least it is rather counter intuitive.

**Comment by acrylian** [comment]
Nope, just retried and works for me. Or I just don't understand what you see ;-)

**Comment by bic-ed** [comment]
I suppose that the purpose of "truncate at pagebreak" option is to override the default truncation length to set the break manually  at some point beyond the default length itself. If the truncation occurs before the default one than that option is (was) not taken into account at all.
Anyway, I'm making some further tests, because the new behavior is not totally clear to me at the moment. Keep in mind that I'm using bilingual news, that can possibly have an impact too, somehow.
I'll be back asap.

**Comment by acrylian** [comment]
> I suppose that the purpose of "truncate at pagebreak" option is to override the default truncation

Probably that was the thought back then but a bit overcomplicated. I mean "pagebreak = always override default truncation" sounds much more intuitive to me.

> Keep in mind that I'm using bilingual news, that can possibly have an impact too, somehow.
I'll be back asap.

I don't think this should make any difference as text is text actually. Only the current language text is used in those functions and not the whole bilingual one.

But tests are appreciated.

**Comment by bic-ed** [comment]
Can I ask you why you also changed lines 218 and 219 in your commit? I've noticed some weird behavior after that in my tests, with break occurring before `<!-- pagebreak -->`  sometimes, quite randomly, depending, in a way unclear to me, on html tags in the new. I've tried rolling back those two lines and leaving only your change in line 216, where you added ` || $forceindicator`, and everything seems to work properly with just that change.
Forgive me if I what I say is a bit confusing, I'm confused too. ;)

**Comment by acrylian** [comment]
I did change that becuase of issues with elements. If you truncate  automatically you may "break" html elements (e.g. within a paragraph). These lines fix that broken html and append the shortenindicator at the end within that element. With manualy truncation you generaly truncated after the last element so nothing needs to be fixed and the shortendinidicator would go to the next line. This is what fixed this for me to be the same.

Note however that I have the tidy extension. It may behave differently if you don't have that so the replacement library included is used.

**Comment by acrylian** [comment]
Interestingly I now get some broken encoding on some invisible "non breaking space" taht I didn't get yesterday. Apparently tinymce is inserting that.

But besides that it works for me as you can see here:
![bildschirmfoto 2018-07-22 um 19 45 54](https://user-images.githubusercontent.com/2474309/43048450-ee037796-8de7-11e8-9724-9cb5a74fc31f.jpg)

**Comment by bic-ed** [comment]
I also get broken encoding on accented characters like "à". Beside this, the following screenshots came from the same new, with page break manually set at exactly the same position, that is after words "...sono state". The first one is taken with only line 216 changed like in your commit. The second one is taken with also lines 218 and 219 changed.

![correct-break](https://user-images.githubusercontent.com/2939831/43063313-c2df3c48-8e5b-11e8-8564-22117dbb1d1c.jpg)
![failing-break](https://user-images.githubusercontent.com/2939831/43063312-c2bbc2d6-8e5b-11e8-80c0-915a6b359bd3.jpg)

**Comment by bic-ed** [comment]
About the broken encoding, it is not present in older versions of zenphoto, for instance 1.4.11. Furthermore it is not present in single new's pages but only in the loop page, so it might have something to do with the truncation algorithm.

**Comment by acrylian** [comment]
There have been some changes to the truncation handling.So does your server has the tiny extension installed? Do you also have the mbstring (multibyte) extension?

**Comment by bic-ed** [comment]
Do you mean php_tidy? No, but I can enable it
mbstring is here:
![mbstring](https://user-images.githubusercontent.com/2939831/43070764-fa731660-8e70-11e8-8b9f-f83a784126b8.jpg)

**Comment by bic-ed** [comment]
Enabling php_tidy the broken encode disappears

**Comment by acrylian** [comment]
Good, if you have tidy it is the preferred and best way regarding this char stuff. The htmlawed libary is not as sophisticated.

**Comment by bic-ed** [comment]
> 
> 
> I did change that because of issues with elements. If you truncate automatically you may "break" html elements (e.g. within a paragraph). These lines fix that broken html and append the shortenindicator at the end within that element. With manualy truncation you generaly truncated after the last element so nothing needs to be fixed and the shortendinidicator would go to the next line. This is what fixed this for me to be the same. The pagebreak truncation actually happens before the text string is passed to this function.

I've made further test on this, and it turned out that now often the page break occurs much before the desired place. For instance, if the article has two paragraphs, and the second one ends much beyond pagebreak, the page break always occurs at the end of first paragraph, no matter where you placed the shorten indicator inside the second paragraph.
I'm not sure why we really need to take care about closing html tags, since I suppose that tidyHTML function is there for this purpose. 
The way it was before changing lines  218 and 219, was correctly treating just the very special case in which automatic pagebreak occurred inside an html tag, between `<` and `>` .

**Comment by acrylian** [comment]
I don't have the  details present current anymore about those lines. There was a reason for this as we tested this a lot back then. One problem is that not everyone has the tidy extensoon which does the actual proper html fixing. 

Indeed it truncates on the previous paragraph and not the exact space. No idea why it does that right now. (Truncation on paragraphs is of course not a bad idea for redability ;-))

**Comment by bic-ed** [comment]
Of course it happens also whit other html tags, like img, strong, em etc. So that at the moment is totally random the place where page break occurs. I have some articles starting whit an image, so that no text at all remains before truncation, even with automatic truncation set to 500 characters.

I see that in the code there is a fallback for servers without tidy extension in line 168 (htmLawed).
I found workaround using some fake `strong` tags around commas or points, so I can live without a proper fix for this, but I really think that it was better before changing those two lines (218 & 219).

**Comment by bic-ed** [comment]
Furthermore, at the moment, as far as I understand, the truncation occurs anyway leaving an open html tag, cutting out text before the closing tag.
`			$open = mb_strrpos($short, '</');
			if ($open) {
				$short = mb_substr($short, 0, $open);
			}
`

**Comment by acrylian** [comment]
Okay, thanks for some investing. I will review lines 218 & 219 again.

**Comment by acrylian** [comment]
The html fixing part is the part that causes all the issues here.  It all relates to these older tickets as well: #1116,  #1115

**Comment by bic-ed** [comment]
I see, quite a long thread to study. :-)
But after all what broke the expected behavior was changing those to line (218 & 219) here. I suppose that the older code was tested longer than this one, so may be the fastest solution now is just to revert it to as it was before, leaving just the fix (that is working properly) for the missing shorten indicator.
I already tested it locally, but I could test it also on my live site if there is a way to get rid of the annoying SIGNATURE_HASH alert. then, if everything works, I can make a pull request here.

**Comment by bic-ed** [comment]
Ok, I realized that I just needed to run setup to get rid of the signature hash alert, so I'm testing it live now.

**Comment by acrylian** [comment]
If you change core files that warning always appears. You can click it away but it nevertheless will come back ;-)

If I recall right one of the problems was to only get the shorten indicator if actually anything has been truncated.

**Comment by bic-ed** [comment]
> If you change core files that warning always appears. You can click it away but it nevertheless will come back ;-)

Yes, but after running setup it's not coming back anymore. 
 
> If I recall right one of the problems was to only get the shorten indicator if actually anything has been truncated.

Right, I opened this issue - that is solved properly whit your fix in line 216 - for that reason. Then we started talking about broken encoding and missed the other point. After updating, for you know what reason, I noticed missing text in news loop, so I came back here again. I'm quite sure that rolling back the told lines everything should work properly, anyway I'll keep testing for a few days more.

**Comment by acrylian** [comment]
Okay, thanks for the clarification. I will do some tests as well.

**Comment by acrylian** [comment]
I have taken a quick look and the change was over a year ago in 1.5. New is a library that handles the shortening if there is no native php tidy available.  The tidy config in `tidyHtml()` (which replaces the old `cleanHTML()`) had been updated a bit.

**Comment by acrylian** [comment]
I tried with two paragraphs and the last one was always skipped instead of being "repaired" regarding its missing closing elements. 
 
![Bildschirmfoto 2019-04-05 um 19 40 42](https://user-images.githubusercontent.com/2474309/55646171-ccaeb700-57da-11e9-82b7-c9f5c54b164d.jpg)

The reason was not `tidy` or the change but the rather old lines before that:

```$open = mb_strrpos($short, '</');
			if ($open) {
				//$short = mb_substr($short, 0, $open);
			}
`
If you remove/comment out these it properly repairs the broken last paragraph:

![Bildschirmfoto 2019-04-05 um 19 40 57](https://user-images.githubusercontent.com/2474309/55646186-d59f8880-57da-11e9-8d34-d437b738065e.jpg)

**Comment by bic-ed** [comment]
This is what I was saying from the beginning. This change was made on July 2018, there is no need to comment those two lines, just revert them to what they were before. That was useful I suppose, because auto shortening could fall inside an html tag. I mean, really inside, between '<' and '>'. Il 5 apr 2019 19:41, Malte Müller <notifications@github.com> ha scritto:I tried with two paragraphs and the last one was always skipped instead of being "repaired" regarding its missing closing elements.

The reason was not tidy or the change but the rather old lines before that:
			if ($open) {
				//$short = mb_substr($short, 0, $open);
			}
`
If you remove/comment out these it properly repairs the broken last paragraph:

![Bildschirmfoto 2019-04-05 um 19 40 57](https://user-images.githubusercontent.com/2474309/55646186-d59f8880-57da-11e9-8d34-d437b738065e.jpg)

**Comment by acrylian** [comment]
Ah, yes, you are totally right… Don't remember the reason for the change but there was surely one. Perhaps more complicated html than just a paragraph or so. I guess this needs more tests.

**Comment by bic-ed** [comment]
We don't remember because it was not related with this issue. It was some tail of something else. Anyway the new code removes the last html tag found in the excerpt (and everything beyond it), so it's probably useless for any purpose I can imagine.

**Comment by acrylian** [comment]
I was apparently blind yesterday or ready for home time…

> so it's probably useless

That is exactly what I was wondering. At least when tidy is available it seems not to be of any use. But we need to test if it is with the htmlawed fallback perhaps.

**Comment by acrylian** [comment]
As far as I can see both tidy and htmlawned fallback perfectly fix a broken paragraph without these lines.

**Comment by bic-ed** [comment]
Same here, I tested locally whit tidy disabled and everything seems ok. Anyway I'm testing with the old code:
218 `$open = mb_strrpos($short, '<');`
219 `if ($open > mb_strrpos($short, '>')) {`
I would revert these lines to the above, to avoid broken tags.

**Comment by acrylian** [comment]
I did test without those lines at all. But only manual truncation. The use case for those lines is surely in case the automatic truncation accidentally hits the middle of a element itself. Manually you probably never manage that.

**Comment by bic-ed** [comment]
Yes, that's the point! Automatic truncation could fall exactly inside `<` and `>` or `</` and `>`. I don't know if tidy or htmlawned can take care of such an unlucky case.

**Comment by acrylian** [comment]
Change is done now. Thanks for your help.

**Comment by bic-ed** [comment]
Thanks acrylian, I was about to open a pull request, but my internet connection went down. :-)
