### ISSUE TITLE
issue with contact_form and options Require confirmation + Data usage confirmation

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1181]
hi

as discuted here https://github.com/zenphoto/zenphoto/commit/2c3b6c2487e3aa82d7892938d111462f239db9f7, I think here is an issue with contact_form, when options `Require confirmation` and `Data usage confirmation` are enabled.

in that case:
- we have to check the agreement checkbox in contact form
- in confirmation page, the agreement checkbox is not checked
- when you confirm the sending od the message, the message is sent, whatever the value for agreement (checked or not) in that confirmation page.

according to me, zenphoto should not ask to agree again in the confirmation page.
so, the checkbox should be checked (as we check it before) and disabled (so we can't change the given agreement) 

tested with basic and zenpage themes.

**Comment by acrylian** [comment]
Okay, probably I misunderstood your mentioning of the "confirmation" page there. I agree it should be checked on the confirmation page.
