### ISSUE TITLE
Zenphoto not redirecting to https when https option turned on

### ISSUE THREAD

**Issue by JatB** [zenphoto/zenphoto#1187]
I know people are having issues with this because they have recently been posted-

https://forum.zenphoto.org/discussion/1410124/changed-site-from-http-to-https-but-it-doesnt-show
https://forum.zenphoto.org/discussion/1409839/ssl-https-password-page-question

With all major hosting companies now supporting free https and Google making it an issue in Chrome with regular http sites this last month, many users will be looking to use https with Zenphoto, if they haven’t already.

I also know the official stance is that Zenphoto does not handle the https redirect and it should be added by the user.

The reason I feel that Zenphoto should handle the redirect is because-
1. The option to use https instead of http makes it seem like Zenphoto will force https to be used.
2. Zenphoto already creates .htaccess files if it is installed in a folder. If you delete the .htaccess file in the zenphoto folder and re-run setup with the https option selected, Zenphoto will add the .htaccess file back with other redirects but not https.
3. This adds confusion to the user and no explanation is given why.
4. There is already a strict warning when turning on the https option. The only problem is that it says, “Login from the front-end user login form is secure only if _https_ is selected.” But even if it is selected it will not be used if the visitor types in a regular address or comes from an old http link, unless the _user_ adds a redirect in the .htaccess file.

![zenphoto admin options-security](https://user-images.githubusercontent.com/10157440/43894731-d837ee80-9b87-11e8-99dd-43c44486710b.png)

I would like to propose a basic redirect is added to htaccess for https, or an option is added to add it when https is turned on. Or at the very least, text is added when turning on https explaining that the user needs to add the redirect and they should contact their hosting provider for more info.

**Comment by acrylian** [comment]
Sorry, I don't agree, force redirect is something the server should handle or be added manually. Not all require htaccess. For example on your server this is a server setting on setting up the certificate.

The option text is actually wrong (an old legacy one) and has already been changed in the support build (which  you should try to help not introduce new bugs in 1.5.1 ;-)). You don't need to modify the database at all (the value was stored but never used), you just need to change the define in the config file.

(Sidenote: The "secure admin" option is completely obsolete and will be removed. If you have https anyway there is really no good reason to not use it back and frontend).
