### ISSUE TITLE
If Zenphoto resets a log, they are recreated with less restrictive permissions

### ISSUE THREAD

**Issue by JatB** [zenphoto/zenphoto#1188]
For example, I ran setup with no security warnings. I then reset the debug log, and it recreated the file with 0644 permissions instead of 0600. A security warning was then given when I ran setup again, and I had to go manually set the file permissions for the log file.

![zenphoto setup log security warning](https://user-images.githubusercontent.com/10157440/43896008-2cd352dc-9b8c-11e8-811d-26df83844ccb.png)

**Comment by acrylian** [comment]
Thanks, will take a look.
