### ISSUE TITLE
Don't trim meta data fields after 32 characters

### ISSUE THREAD

**Issue by HaraldWalker** [zenphoto/zenphoto#1192]
Many exif/IPTC fields are being trimmed after 32 characters.
For example:
```
'IPTCSource' => array('IPTC', 'Source', gettext('Image Source'), false, 32, true, 'string'),  
'IPTCSubLocation' => array('IPTC', 'SubLocation', gettext('Sub-location'), false, 32, true, 'string'),
```

The MySQL database has no problems storing larger values (fields use TINYTEXT or TEXT). 
This is causing incorrect display or errors if meta data contains values like an URL (my use case, where images have external links that I want to show on the image page).

Unless there is a technical reason for 32 characters this value should be increased, so that the data stored in Zenphoto is identical to the metadata in the uploaded image.

After upload it is possible to enter larger values in the UI. Mentioned trimming rules only effects file uploads.

Zenphoto version: 1.5 (latest from master)
Php version: 7.2.7

**Comment by acrylian** [comment]
Thanks, I have to admit I don't remember why this is limited to 32 characters. It's quite old code there since forever. Perhaps it was because of an now outdated spec or something… Of course MySQL has no problems with longer text. We'll review this.

**Comment by acrylian** [comment]
I did a very quick research and it seems that  some fields are indeed limited in length by the (more or less consistent) standards. Of the example the IPTCSource field which I assume is this:
https://www.iptc.org/std/photometadata/documentation/userguide/index.htm#!Documents/rightsinformation.htm.
There it reads:
> BE AWARE: this field is limited by the IIM format to about 32 characters. In XMP there is effectively no character limit.
Not found out yet what the "IIM format" is though…

So I can only assume the lengths that were set quite some years ago follow this somehow so the db fields are just fitting that and images are to expected to not have longer entries. That naturally for db effectiveness regarding the fields. 

But probably we can just make all the small meta data fields at least indeed TINYTEXT or TEXT.

**Comment by HaraldWalker** [comment]
I tried to change it myself in core but wasn't able to get a longer value for source or location.  There might also be an issue with the PHP function used to read it (I've read a lot of criticisme on the exif support PHP offers). So, I just tried the same in Piwago and see the same issue. 

Of course I verified that the image files exported with Lightroom have the longer metadata. When I check the files with Exiftool, they are being shown correctly, e.g.:
Source: Imagesource123456789012345678901234567890
Country: Imagecountry123456789012345678901234567890
State: Imagestate123456789012345678901234567890
City: Imagecity123456789012345678901234567890
Location: Imagesublocation123456789012345678901234567890
Credit: Imagecreditline123456789012345678901234567890

Result in PHP (output from readexif plugin in Piwigo, but same as in Zenphoto):
IPTC Fields:
2#115 = Imagesource123456789012345678901
2#101 = Imagecountry123456789012345678901234567890
2#095 = Imagestate1234567890123456789012
2#090 = Imagecity12345678901234567890123
2#092 = Imagesublocation1234567890123456
2#110 = Imagecreditline12345678901234567

https://github.com/plegall/Piwigo-exiftool_keywords/blob/master/main.inc.php
uses the exiftool to read the metadata, so that might be a possible solution.

For me right now this is blocking. The photo management features are not user friendly enough add the data in the web-application.

**Comment by acrylian** [comment]
Our database fields for metadata are limited in size so they most likely truncate that since the are already. I just The define code you cited above alone does not change anything, setup must be run. But I doubt it will change existing database fields (never tried this and I didn't wrote it ;-)). 

Metadata is not meant to be edited manually on the backend as it will not be stored with the image and it is assumed to be taken from the image itself and can be overwritten by refreshing metadata.

Zenphoto actually does not use PHP's `read_exif_data()` function at all. We have library called Exifer (zp-core/exif/) that does the reading. I have to review if this truncates on reading perhaps.

In any case we will at this time not change any library. Otherwise we will never get our next major release done.
