### ISSUE TITLE
errors during setup

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1198]
hi
as discussed here https://forum.zenphoto.org/discussion/1410172/errors-during-setup, there are errors during setup and `max_user_connections` is not enought for setup process.

according to me, there are 2 ways to explore:
- core functions seems to not manage error given by this limit
for now, it gives this exception `EXCEPTION (0): Call to a member function query() on boolean in /.../public_html/zenphoto__test/zp-core/functions-db-MySQLi.php on line 73`

- setup process should take care about this limit and goes slowly if necessary (serialize database updates, maybe one after one)

**Comment by acrylian** [comment]
Follow up to the forum: Is this a new issue actually or did you get it before?

**Comment by vincent3569** [comment]
this is an old one, but I never saw bad consequences before.
i.e: https://forum.zenphoto.org/discussion/comment/1980599
