### ISSUE TITLE
Setup restores old setup files after FTP upload

### ISSUE THREAD

**Issue by bic-ed** [zenphoto/zenphoto#1200]
I was facing various problems during setup, then I realized that my setup files were not updated. The reason is that those files are normally protected with a dummy extension, so that the new files don't override them during FTP upload. Then the "unprotection" routine* silently overrides the new files, restoring the old ones.

*`unprotectSetupFiles()`, line 229 in `reconfigure.php`

**Comment by acrylian** [comment]
If you update you have to replace the whole `zp-core` folder. It is a setting of your FTP client how it handles existing folders and their contents. From our update page:

> 4. Download the latest version and upload the following files and folders. Since FTP clients tend to mess overwriting, especially folders with lots of files, best practice is to delete the old files first and then upload the new files

https://www.zenphoto.org/news/installation-and-upgrading/#--upgrading

**Comment by bic-ed** [comment]
I can't believe I always missed that point. Thanks!

**Comment by acrylian** [comment]
Yeah, a detail easily missed, I know. Setup should actually also complain about the protected files as they won't match the file catalog.

**Comment by bic-ed** [comment]
Anyway, in my case was not a problem due to protected files or to how my FTP client handles existing folders and their contents. It was just that setup files in setup folder were not replaced by the new ones because they didn't exist at all with php extension but with xxx extension instead. I always looked my FTP client report to see if all files have been replaced properly. But after the upload, when protecting or unprotecting setup scripts, the new file get lost. From now on I'll always delete zp-core folder before updating (or at least setup folder), but I suppose that this behavior can trap in error other users too, because the temptation to skip the deleting process for so many files can be very strong. :)

**Comment by acrylian** [comment]
Yes, it just added the files ;) I know that uploading with deleting takes more time but it is really better to do it fresh. Files are also changed or renamed so you might end up with some unnecessary orphaned ones. Although again especially Setup and also Zenphoto itself should warn about files that should not be in zp-core.

**Comment by acrylian** [comment]
The check is by name if it exists in the zenphoto.package file catalogue and also by filetime if it does not match the general package filetimes. So if you modify a existing file and upload it two days later it should also complain.

There is a "signature hash" stored on some selected files but there is no individual file comparison currently. Something to think about for later I guess. But in case of the protected setup these are not part of the package catalogue in any case.

**Comment by bic-ed** [comment]
>  But in case of the protected setup these are not part of the package catalogue in any case.

Just an hint: while backup is running setup files are obviously unprotected, so that setup itself might be able to detect an older filetime with respect to the rest of zp-core files.

**Comment by acrylian** [comment]
> so that setup itself might be able to detect an older filetime with respect to the rest of zp-core files.

Not sure what you mean. That is what setup also does when it warns about files? You mean when you use a backup to re-setup? Yes, that involves setup to make sure all is correct.

**Comment by bic-ed** [comment]
I never got any warning about **outdated setup files** during setup, even if I've been running outdated setup files many many times. For some reasons setup detects useless files everytime everywhere (because I never deleted zp-core folder before uploading new versions of Zenphoto via FTP) but not in setup folder itself.

**Comment by acrylian** [comment]
Well, you should not have had outdated setup files ;) But well, I see there is room for improvements probably ;-)

**Comment by bic-ed** [comment]
Of course, I'll never do it again :)
It was just to avoid other people make the same mistake.

Perhaps it could be enough to specify better in the upgrading guide that it's mandatory (not just best practice) deleting at least the setup folder before upgrading. Otherwise you could always find someone else like me, trusting his FTP client and hence skipping the deleting process. ;)

**Comment by acrylian** [comment]
> it's mandatory (not just best practice)

Well, since it depends on the FTP client setting, it is "best practice" ;-) My client (Transmit) for example does ask. But we'll add something to make it more clear.

**Comment by bic-ed** [comment]
Even if your FTP client asks (mine does it too) files in setup folder are very likely in protection mode during FTP upload, so **there is nothing to ask**! 

New *.php files are regularly uploaded. No error from the client, no asks whatsoever. But as soon as you visit the admin panel, new files are replaced silently with old ones. So you end up whit running setup with old setup files. That's why I'm so boring today, insisting on this! :)
Deleting setup folder should really be requested as mandatory.

**Comment by acrylian** [comment]
Ah, I see what you mean. Strangely I indeed never encountered this on any site I updated. Even on our own and I just let the client replace the whole zp-core folder every time. Well, where would be the fun if everything was the same everywhere…

**Comment by bic-ed** [comment]
Me too, I've upgraded a tons of times, but I never noticed this problem until I tried to change files permissions during upgrade, ending whit a messed up config file and the site totally broken!

**Comment by acrylian** [comment]
Oh yes, trying to change permissions manually can cause all sorts of fun…

**Comment by acrylian** [comment]
Locally I mostly have them unprotected anyway. And yes, the live ones are fine, too. Apparently my ftp client replaces everything when I tell it to do, no matter of the protected suffix.

**Comment by sbillard** [comment]
So if you want the real answer, it depends on how you run setup after you upload the files. Reading this it seems that bic-ed is running setup from the admin pages. I suspect acrylian is simply going to .../zen-folder/setup/

Anyway, there really should be a check to see if there is a .php file already present before renaming the .xxx files--that is what has been done for who knows how long in netPhotoGraphics.

**Comment by bic-ed** [comment]
Can I add this to Zenphoto?
@sbillard ?
@acrylian ?

**Comment by acrylian** [comment]
I haven't looked and we don't look or adapt from the fork since I neither care nor have the time to do so. There is not collaboration or contribution anyway.

But feel free to adapt and contribute it, the fork should still be GPL v2 or later as well. Although some years ago when I looked I remember some non compatible copyright notices on code parts.

**Comment by sbillard** [comment]
Or just try netPhotoGraphics itself. You might like it.
