### ISSUE TITLE
issue with contact_form and option Data usage confirmation

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1201]
hi

maybe a follow up of this issue https://github.com/zenphoto/zenphoto/issues/1181

I think here is an issue with contact_form, when option Data usage confirmation is enabled.

if you send a message without checking "By using this form you agree with the storage and handling of your data by this website", an error message is displayed and the contact form is emptied.
with other controls (valid email for example, we only have an error message and the contact form is not emptied.

tested with zenpage theme.

**Comment by acrylian** [comment]
Will take a look.

**Comment by vincent3569** [comment]
ok, it works fine
