### ISSUE TITLE
v1.5.1 Security Options Server Protocol always shows http.

### ISSUE THREAD

**Issue by MarkRH** [zenphoto/zenphoto#1204]
I noticed with v1.5.1 that the Security Options Server Protocol indicator always shows **http**, even after selecting **https**.  The actual value in **zenphoto.cfg.php** does change though when toggling between them.

While the config files shows:
```php
// Server Protocol

$conf['server_protocol'] = "https";
```
The UI shows:
![image](https://user-images.githubusercontent.com/8035962/50614009-18cd2100-0ea5-11e9-93be-99b0bcd7b7ba.png)

Now, I do have forced redirection active in the .htaccess file so I'm not sure what the internal effect really is with this option.

**Comment by acrylian** [comment]
Thanks, confusing indeed. Will take a look. Actually it should not cause any issues since the config definition is what counts. We have a server side (non htaccess) redirection and all works as expected.
