### ISSUE TITLE
Issues with pagination during search

### ISSUE THREAD

**Issue by wongm** [zenphoto/zenphoto#1206]
Run search for something. Example from my site:
https://railgallery.wongm.com/page/search/test

I got 11 pages of results - one of albums, 10 pages of images.

Click link through to first album.
https://railgallery.wongm.com/em100/

I get 10 pages of results, not the three I expect to see.
Reload page, and the number of pages available to select is now correct.
Interesting fact - the 'search' link in the breadcrumb works fine.

I'm running version 1.5.2a on my local dev machine, and am seeing the same behaviour with the default Zenphoto theme and a different set of images.

Having a go fixing it now - hopefully a pull request will be headed your way soon.

**Comment by wongm** [comment]
I've having trouble consistently replicating the issue locally - it appears that after an initial page view the page numbers are correct, and will stay correct no matter how many times the initial search is reloaded. But deleting the contents of the `search_cache` table results in the buggy pagination reappearing on albums.

**Comment by wongm** [comment]
Problem seems to lie in `getParentAlbums()` of `template-functions.php`

When pagination is broken:
- in_context(ZP_SEARCH_LINKED) = 32
- in_context(ZP_ALBUM_LINKED) = 0

When pagination is correct:
- in_context(ZP_SEARCH_LINKED) = 32
- in_context(ZP_ALBUM_LINKED) = 64

**Comment by acrylian** [comment]
The search cache can cause a difference if the values stored are different. I admit I have it always disabled (also on our site). We're actually had been thinking of removing it in the future…

Did/could you compare if the results itself are correct and just the pagination is wrong?

**Comment by acrylian** [comment]
The 2nd link is a dynamic album, right? Is that really using the same settings as the general search does? They may behave differently.

**Comment by wongm** [comment]
In my testing all albums are physical ones - in my 'real' site I have dynamic albums, but in my dev testing I only have physical albums.

I've tracked down to the `ZP_ALBUM_LINKED` context setting to this line in `functions.php`:

```$search_album_list = $_zp_current_search->getAlbums(0);
			$_zp_loggedin = $save_logon;
			foreach ($search_album_list as $searchalbum) {
				if (strpos($albumname, $searchalbum) !== false) {
					if($searchparent == 'searchresults_album' && $_zp_last_album == $albumname) {```

The values `_zp_last_album` values are coming from the `zenphoto_last_album` cookie - seems to be some context switching going on, which causes things to get confused.

**Comment by acrylian** [comment]
If it only happens with the search cache enabled the issue might also be there, e.g. storing the results not correctly or not using them correctly.

**Comment by wongm** [comment]
> Did/could you compare if the results itself are correct and just the pagination is wrong

Only pagination is wrong, images contained in the album is correct.

**Comment by wongm** [comment]
Finally got some better repro steps, without needing to clear search cache.

Clear cookies.
Run search for that returns two albums.
Open album A.
See zp_getCookie('zenphoto_last_album') empty
See that pagination is incorrect.
See that 'return to search' is displayed.

Go back to search page.
Reopen album A.
See zp_getCookie('zenphoto_last_album') is 'album-a'
See that pagination is correct.

Go back to search page.
Open album B.
See zp_getCookie('zenphoto_last_album') album-a
See that pagination is incorrect.
Refresh page.
See that pagination is correct.

Reopen album A.
See zp_getCookie('zenphoto_last_album') album-b
See that pagination is incorrect.
Refresh page.
See that pagination is correct.

**Comment by acrylian** [comment]
If refreshing pages does the trick it might be a browser cache issue. Just pushing back in the browser is not the same than refreshing the page because the first in any case serves from the browser cache. So this will not reset the cookie as needed. And browser caches are nowadays overly persistent than in older days (in some browser you can't even disable them easily). 

The cookie is of course generally needed to keep the search context as otherwise you never can know if all is within search results or the real album structure…

**Comment by wongm** [comment]
I've found a new scenario that appears to be caused by the same logic:

Create dynamic album, containing multiple albums but zero images
View dynamic album.
Click link to album A.
Zero images are displayed.
Refresh page.
Expected images are displayed.

Looks like logic rendering album A is seeing the 0 image count for the dynamic album, so decided to not show any images.

What purpose does `ZP_ALBUM_LINKED` serve, so I can test that any fix I make doesn't break it?

**Comment by acrylian** [comment]
ZP_ALBUM_LINKED refers to visits to albums in search context so Zp knows it is outside of the actual album structure. This is quite inconvenient stuff. I sadly don't have the time to investigate and reproduce it right now. But I will try and look at your possible fix. Hopefully on the weekend.

**Comment by wongm** [comment]
My quick fox only addresses my two specific scenarios - I suspect that it will cause issues elsewhere. I also think it leaves behind a lot of dead code that is no longer needed.

-----Original Message-----

**Comment by acrylian** [comment]
Yes, it needs to be tested. What dead code are you referring to specifially?

**Comment by wongm** [comment]
My change deletes a check of two variables, if the variables aren't used anywhere else, then they can also be deleted

**Comment by acrylian** [comment]
Okay, I hadn't looked at the code. The global`$_zp_last_album` for sure is there for a specific reason and can probably not easily be remove. This search stuff is not the easiest part ;)

**Comment by acrylian** [comment]
As far as we can see your fix seems to work without side effects. Please send a pull request (so you get the pure credit ;-)).
