### ISSUE TITLE
PHP Fatal Error under PHP 5.4

### ISSUE THREAD

**Issue by kochs-online** [zenphoto/zenphoto#1208]
I had a config issue with my web server and for some reason it was running PHP 5.4 which resulted in this PHP Fatal Error when trying to setup Zenphoto 1.5.1:

    Fatal error: Can't use function return value in write context in [zenphoto-dir]/zp-core/functions-basic.php on line 1760

I know PHP 5.4 is hopelessly deprecated and no longer meeting the requirements for Zenphoto, but I think at least setup should come up and show a hint. A fatal error will require the user to research the issue on his/her own. This might keep someone from using Zenphoto especially when this happens even before they were able to run setup.

**Comment by kochs-online** [comment]
Not sure if this is related or if it happened after I switched to PHP 7.2, but I found this in the Zenphoto debug log:

    NOTICE: A non well formed numeric value encountered in [zenphoto-dir]/zp-core/setup/class-setup.php on line 315
    setup::versionCheck called from index.php [614]

`setup/index.php [614]` checks the PHP version…

**Comment by acrylian** [comment]
Setup actually should warn if you are on anything older than 5.6 and recommend 7+. I will not investigate this.

For the setup issue please try the support build aka 1.5.2a to see if this is fixed there (you should do this always). There had been some work on setup.

**Comment by kochs-online** [comment]
> Setup actually should warn if you are on anything older than 5.6 and strongely recommend 7+. I will not investigate this any further.

Setup isn't even coming up. When I tried to open `/zenphoto/zp-core/setup.php` it only showed the Fatal Error message. It didn't get far enough to show any warning.

> For the setup issue please try the support build aka 1.5.2a to see if this is fixed there (you should do this always). There had been some work on setup.

I will have a look when the changes for _[image change dates](https://forum.zenphoto.org/discussion/1410122/sorting-by-change-date)_ are included.

**Comment by acrylian** [comment]
> Setup isn't even coming up.

That might of course happen if there is a serious issue with an old PHP version. We don't know as we don' test it :)

The issue is related to the newly introduced cURL function. Didn't notice that on 7.2+ so far so might be the version.

> I will have a look when the changes for _[image change dates](https://forum.zenphoto.org/discussion/1410122/sorting-by-change-date)_ are included.

Okay ;)

**Comment by kochs-online** [comment]
I took a second look at this. It's not cURL that's causing the issue, but the problem hides in this statement:

	if (empty(trim($curl_exec)))

And this I found in the PHP documentation of [empty()](https://php.net/manual/en/function.empty.php#refsect1-function.empty-parameters):

> **Note:**
> Prior to PHP 5.5, `empty()` only supports variables; anything else will result in a parse error. In other words, the following will not work: `empty(trim($name))`. Instead, use `trim($name) == false`.

So this behavior could easily be fixed following the example given above.

**Comment by acrylian** [comment]
Could but since we recommend at least 5.6 and the road is leading to 7.2… Better upgrade your server instead ;-)

**Comment by kochs-online** [comment]
That was just a misconfiguration on my side. Server is running 7.2 currently. So I'm not affected by this issue.

Nevertheless I think it would be nice to keep at least the setup backwards compatible so the checks can be run and tell prospective users what needs to be done to run Zenphoto. Right now I will just crap itself when setup is called. :wink:

Just imagine you're new to Zenphoto, trying to set it up and the first thing you see is some weird Fatal Error that you have to sort out all by yourself. Would this increase your confidence in that new piece of software you just installed?

**Comment by acrylian** [comment]
Well, before you install anything need to check the requirements. At some time it will not work in any case. On PHP 4 it will also toltally break. Btw on the 1.5. release post we stated already:

> By now we actually develop and test on PHP 7.2 so we raised requirements. Although the code will probably will still work on older PHP versions we neither test it nor make any effort to make things work below PHP 5.6. Although we simply can't and won't rewrite all code into "pure" PHP 7+ only unless really needed.

We actually wanted to make 5.6. mandatory already but we kept older for convenience…

We actually forgot to mirror that change on https://www.zenphoto.org/news/installation-and-upgrading/ which I just did.

**Comment by acrylian** [comment]
Since we are a light democracy my colleague talked me into adding this fix ;-)

**Comment by kochs-online** [comment]
I'll try to remember to test this when installing the next release. Now that I know where to look in the hoster's admin panel I can switch PHP versions back to 5.4 pretty easy. :wink:

**Comment by acrylian** [comment]
Better switch forward ;-)
