### ISSUE TITLE
Can't get into the forum

### ISSUE THREAD

**Issue by thany** [zenphoto/zenphoto#1211]
First of all, my login no longer works. I'm using a password manager, and the website is mocking me for having forgotten my password. I haven't, you have. What happened?

Secondly, creating a new account doesn't work. My old username isn't available, so it must still exist. However, a password reset link never arrives. So I make a new username. After correcting the the first release year question and re-checking the "I'm not a robot" question and hitting Sign Up, I get punished again: _The captcha was not completed correctly. Please try again._
What captcha? The checkbox? I clicked it.

Until this is sorted, I think I'll abuse github to ask questions 😊

**Comment by acrylian** [comment]
> My old username isn't available, so it must still exist.
Of course since we don't delete any user accounts unless they are spamming.

So what is your old user name so we can take a look? Perhaps the mail address is wrong or some mail provider filter blocks the mail or whatever. Besides some small updates nothing has changed and all works for me.

**Comment by thany** [comment]
Oh sorry, same as my github name: thany

**Comment by acrylian** [comment]
That account still exists and all looks fine. Mailaddress is thany81@youprobablyknowwhatcompany.

**Comment by thany** [comment]
That just leaves the extremely unforgiving signup form.

**Comment by acrylian** [comment]
If you have any blocking plugins active in your browser try if it works without them. Generally not our software so we have no hand in such things.

**Comment by thany** [comment]
Most likely reCaptcha is the problem. It seems like a good idea, but it's actually horrible. It's extremely punishing to extactly the ones that shouldn't be punished. Bots are being blocked pretty well, but so are a lot of users who just give up on it.

**Comment by acrylian** [comment]
I don't really like having ii either but sadly we have no choice unless we want to spend our times fighting spam or moderate everything manually. Tha would cause delays of hours until things appear. Sadly the only other antispam plugins available are even less compatible with the GDPR.

**Comment by thany** [comment]
It's a toss-up, I guess.

One thing you can do is place the reCaptcha on top of the form. It punishes the user for clicking the submit button too soon after checking the box. And that is very easy to do.

**Comment by acrylian** [comment]
Well, since it is not our forum software and not our plugin either, we can't just move a check box…

I have now set a new password manually for you (mathing your user name). So please try to get in and change it immediately if you can.

**Comment by acrylian** [comment]
So did you get in again? I have now send a password reset request.

**Comment by thany** [comment]
Yeah, seems to work.
