### ISSUE TITLE
How to enable openstreetmap

### ISSUE THREAD

**Issue by thany** [zenphoto/zenphoto#1212]
Since google basically nuked Maps for websites, I need an alternative. [openstreetmap](https://www.zenphoto.org/news/openstreetmap/) seems like a fair option. No idea if it actually works, because I can't get the darn thing enabled. Where is it?

I'd expect it to be on `/zp-core/admin-plugins.php?page=plugins&tab=all&subpage=2` but it's not there, nor on any other page. The site clearly states it's included in the official zenphoto release, and it's existed since 2015. I'm running 1.4.14, which sure enough, was released some time after 2015.

It's also not on the Media tab, or the Misc tab. I'm not sure if those tabs are like filters, or if they reveal additional plugins (extensions?) but as I feared, it's not there, nor on any other tab.

So how do I enable openstreetmap?

**Comment by acrylian** [comment]
It is included in the current Zenphoto release which is 1.5.1. It is not included in 1.4.14 since it has been added in 1.5. All stated on the release post: https://www.zenphoto.org/news/zenphoto-1.5/

**Comment by thany** [comment]
Oh there's a new version! The admin panel didn't notify me of this fantastic news! I hope that too, is fixed in 1.5.

Will try it out shortly 😀

**Comment by acrylian** [comment]
> I hope that too, is fixed in 1.5.

The check_for_update plugin works as intended on a 1.4.14 install here and notify on the overview page.

> Will try it out shortly

Then better try the support build (1.5.2a) right away.

**Comment by thany** [comment]
> The check_for_update plugin works as intended on a 1.4.14 install here and notifies on the overview page. And the zenphoto_news plugin also works.

Oh it's a plugin. It's not easy to know which things are plugins, and which are baked-in features... I guess maybe I had that one disabled or something. No matter.

> Then better try the support build (1.5.2a) right away.

You know what the next question is, right? 😃
Where is 1.5.2a?

**Comment by acrylian** [comment]
> Where is 1.5.2a?

You should actually know that he support build is the master on Github ;-) There is even a link on our download page ;)

**Comment by thany** [comment]
I did see the link on the website tot 1.5.1, so I guessed maybe the 1.5.2 build is a super secret special friends build that's put somewhere before pushing it to the repo. Who knows, right? 😅

**Comment by acrylian** [comment]
> super secret special friends

Although that exists indeed for the next major release - which for lots of reasons is way behind everything - this is not it ;-)
