### ISSUE TITLE
cache manager: counters are not working in "classic" mode

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1213]
hi
when using cache manager in "classic" mode, counters are not working: Image cache sizes generated (and Image cache sizes failed ?) remain to 0.

works well with "cURL" mode.

**Comment by acrylian** [comment]
Yes, it doesn't since the classic mode just prints images no matter if the actual generation is successfull (which is often isn't if you process lots of images - thus the cURL addition). There is no way to check if they are generated or not as with cURL.
