### ISSUE TITLE
Cannot start on XAMPP 7.2

### ISSUE THREAD

**Issue by thany** [zenphoto/zenphoto#1214]
The current master won't start on XAMPP 7.2

In the log:
```
[Tue Feb 26 23:44:14.891337 2019] [php7:warn] [pid 10312:tid 1972] [client 127.0.0.1:54527] PHP Warning:  Use of undefined constant PROTOCOL - assumed 'PROTOCOL' (this will throw an Error in a future version of PHP) in D:\\xampp\\htdocs\\zp-core\\reconfigure.php on line 36
```

And the response is:
```
HTTP/1.1 302 Found
Date: Tue, 26 Feb 2019 22:44:14 GMT
Server: Apache/2.4.38 (Win32) OpenSSL/1.1.1a PHP/7.2.15
X-Powered-By: PHP/7.2.15
Location: PROTOCOL://localhost/zp-core/setup/index.php?autorun=gallery
Content-Length: 0
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
```

So `PROTOCOL` is a constant I guess, that probably needs to be replaced with... something that resolves to `"http"` or `"https"`. I guess.

**Comment by thany** [comment]
[Culprit commit be here](https://github.com/zenphoto/zenphoto/commit/5986d2db9475e0840913a88eede53a6f37a70b3b)

**Comment by thany** [comment]
This workaround appears to be working so far. Add this line to the top of index.php:
```php
define('PROTOCOL', 'http');
```

Defining your contsants is important, gentlemen 😃

**Comment by acrylian** [comment]
This is fixed in the support build already.

**Comment by acrylian** [comment]
Correction, Indeed we missed one define. The workaround is too simple though as thte definition should be used from the config file once it exists.

**Comment by thany** [comment]
That's why it's a workaround, and not a solution :)

**Comment by acrylian** [comment]
Should be fixed now anyway.
