### ISSUE TITLE
Support WebP

### ISSUE THREAD

**Issue by thany** [zenphoto/zenphoto#1217]
Can we please have support for outputting pictures as WebP?

It's smaller at a similar quality level, or provides higher quality at the same filesize. Or a combination of both. It's supported by Chrome, Firefox, and Edge. Both mobile and desktop browsers. Only Safari and IE don't support them.

If zenphoto would support outputting WebP, themes can decide to display WebP with JPEG fallback using a `<picture>` element.

See also: https://caniuse.com/#feat=webp

I think the time is right 😎

**Comment by acrylian** [comment]
Already under consideration for the next major release. Processing ability would be dependent on the graphics library (version) used. 

The <picture> fallback complicates a lot of things and requires a lot of extra processing as all sizes required would be needed in native webp and in the jpeg fallback. So surely not in 1.x.

But if you want it right now you can write your own filetype handler plugin already.

**Comment by thany** [comment]
> Processing ability would be dependent on the graphics library (version) used.

Correct. But all graphics processing is already specific to the library used. I do know PHP can write WebP natively (I think PHP 5.x needs to be compiled with WebP support, whereas PHP 7.x comes with WebP by default?) and ImageMagick has been able to write WebP for a very long time. I don't know any specifics, but I'm pretty sure someone in the world has done it before ;)

> The fallback complicates a lot of things and requires a lot of extra processing as all sizes required would be needed in native webp and in the jpeg fallback.

It does need a whole lot of extra horsepowers. Just a lot more (cache) storage. Only when you feel the need to "warm up the caches" you do need double the processing time. But mind you, the browser will download only one of the two, which means it only requires the same amount for the JPEG fallback, or less processing time for the WebP version. That's assuming WebP encoding is faster than JPEG, which I seem to recall it is.

> But if you want it right now you can write your own filetype handler plugin already.

I'm not sure I'm PHP-compentent enough for that, but maybe I'll give it a go :)

**Comment by acrylian** [comment]
The GD library at least has a function for it since PHP 5.4 but I never tried it. http://php.net/manual/de/function.imagewebp.php 
I actually don't even have any graphics tool that can export webp files. 

Look at the `class-*` plugins for examples.

**Comment by thany** [comment]
You don't even have GIMP?
There's loads of software out there that supports it. Most decent graphics tools can export them, and most decent viewers (and browsers) can display them.

WebP is nowhere near as widespread as WebP, but it definitely seems to be gaining more traction than PNG when it got released.

**Comment by acrylian** [comment]
I don't have GIMP installed and don't use it indeed, I use Photoshop and Affinity actually. But the files are not the problem.  We are looking into having native support as far as possible but without fallback. Our live server seem to support webp at least for the GD library.

**Comment by thany** [comment]
Most servers oughta have support for encoding webp, unless they are running exceedingly outdated software, which is always a bad idea. You'd be suprized how well supported webp is ;)

Fallback is needed for browsers, not neccesarily for servers.

**Comment by acrylian** [comment]
Native support is implemented now in the support build. Our server does only support it with GD but my colleague reports that on his it works in GD and Imagick.

We will not implement a browser fallback anytime soon. You could do with your plugin. WebP is still a nice format.

**Comment by thany** [comment]
Excellent. And I agree on the fallback. What's more, I don't think zenphoto should output a browser fallback. The fallback is HTML only, so it oughta go into the themes. Which is another good reason to postpone it to 2.0, which will probably not be compatible with 1.x themes?

**Comment by acrylian** [comment]
> postpone it to 2.0, which will probably not be compatible with 1.x themes?

Actually no, the theme structure will not change and the plan is to keep everything generally compatible as much as possible. Although a few things may change and require work by theme authors. Depends on what the theme does as there will and might be (quite) some internal core changes.
