### ISSUE TITLE
openstreetmap pimping

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1219]
A little pimping for a function in openstreetmap extension.

The returned JavaScript Array was not a realy array (with inside JS Object).
There is a little bit difference among PHP array and JS array.

Old:
```
geodata[0] = {
lat : "00.000",
long : "00.000",
title : "bla bla ...",
desc : "lorem ipsum...",
thumb : "<a href='/summer/2015/PICT0000'><img src='/cache/summer/2015/PICT0000_150_thumb.jpg' alt='' /></a>",
current : "0"
}; geodata[1] = {
lat : "00.000",
long : "00.000",
title : "bla bla ...",
desc : "lorem ipsum...",
thumb : "<a href='/summer/2015/PICT0000'><img src='/cache/summer/2015/PICT0000_150_thumb.jpg' alt='' /></a>",
current : "0"
}; geodata[0] = {
...
```

New:
```
geodata = [{
lat : "00.000",
long : "00.000",
title : "bla bla ...",
desc : "lorem ipsum...",
thumb : "<a href='/summer/2015/PICT0000'><img src='/cache/summer/2015/PICT0000_150_thumb.jpg' alt='' /></a>",
current : "0"
},
{
lat : "00.000",
long : "00.000",
title : "bla bla ...",
desc : "lorem ipsum...",
thumb : "<a href='/summer/2015/PICT0000'><img src='/cache/summer/2015/PICT0000_150_thumb.jpg' alt='' /></a>",
current : "0"
},
{
...
];
```

Pimping function:
```
	function getGeoDataJS() {
		if (!is_null($this->geodatajs)) {
			return $this->geodatajs;
		}
		$geodata = $this->getGeoData();
		if (!empty($geodata)) {
			$js_geodata = '';
			$js_geodata .= ' geodata = [';
			foreach ($geodata as $geo) {
				$js_geodata .= '{
                  lat : "' . $geo['lat'] . '",
                  long : "' . $geo['long'] . '",
                  title : "' . js_encode(shortenContent($geo['title'], 50, '...')) . '",
                  desc : "' . js_encode(shortenContent($geo['desc'], 100, '...')) . '",
                  thumb : "' . $geo['thumb'] . '",
                  current : "' . $geo['current'] . '"
                },
				';
			}
			$js_geodata .= '];';
			return $this->geodatajs = $js_geodata;
		}
	}
```

**Comment by acrylian** [comment]
Thanks, that indeed was not correct. Best you send a pull request.

**Comment by mebels** [comment]
I have no idea how to send a pull request. And no time...

The $count was still superfluous. Have I just edited / deleted.

**Comment by acrylian** [comment]
> I have no idea how to send a pull request. And no time...

Of course, we don't either. Perhaps learn it as it saves us time (even if this is a small change).

I did review the code and it is correct as it is.
`array[index] = { … }; ` is a complete valid way to add indices to an array. That array is defined empty in the method `printMap()` here so in case there is no data submitted it still is an array. This is on purpose as markers are optional.

![Bildschirmfoto 2019-03-11 um 09 58 27](https://user-images.githubusercontent.com/2474309/54111577-7ff6dc80-43e4-11e9-9e50-f934e9e11c9a.jpg)

So this fix is actually obsolete and not helping anything
