### ISSUE TITLE
openstreetmap var $geodatajs

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1220]
Have you forgotten the $geodatajs?
i'ts not inside:
`function printOpenStreetMap($geodata = NULL, $width = NULL, $height = NULL, $mapcenter = NULL, $zoom = NULL, $fitbounds = NULL, $class = '', $mapnumber = NULL, $obj = NULL, $minimap = false) {`

But here used:
```
	function getGeoDataJS() {
		if (!is_null($this->geodatajs)) {
			return $this->geodatajs;
		}
```
I'm a little bit confused. I have generated the (PHP) array for $geodata, but the extension make out of that a new (JS) array.  Since I can just create a JS array and pass. Saves work? I have not understood it yet.

**Comment by acrylian** [comment]
That's a sort of class cache so that it can be reused and does not have to be regenerated every time. The plugin is meant to be flexible beyond the standard template function via the class directly.

`printOpenStreetMap()` is a convenience template function wrapper for the actual class setup. You can do everything (and more like stuff outside images/albums) with the class directly.

**Comment by mebels** [comment]
I still do not understand.
There seems to be the possibility of transferring a finished JS array. But I see no way to pass the JS array. I only see the pass of $geodata, not $geodatajs.

My data come from a MySQL Query. All visible photos.
https://github.com/mebels/zenphoto-osm-fotomap

It is a performance problem. I have a large amount of photos. If I first create a PHP array with PHP, and then re-code it with PHP into a JS array, that's twice as much work.

**Comment by acrylian** [comment]
The extension is PHP so it feels wrong to pass a js array string to that template wrapper function. Especially then there is no way to chekc if that is setup correctly.

But that is why this all is based on a class for flexility. So use the class directly. Don't pass any geodata to the class construtor parameer and then before calling the `printMap()` method replace its property `$geodatajs` with your prepared js array and you have it. You might also need to set the `$mode` parameter so it behaves as intended. See the documentation of the properties what to set.
