### ISSUE TITLE
Menu Manager : issue with 'Custom Theme Page'

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1223]
hi,

I think there is an issue on menu manager.
when I try to add a menu item with `custom theme page`, I can choose a page of the current theme, but I can't set a title to the menu item.
when I apply, there is an error and then I can add a title to the menu item.
I can add other informations, but it seems a little bit confusing (list of albums, list of pages, list of news catergories)

![Capture1](https://user-images.githubusercontent.com/1224809/55138086-e3963f00-5132-11e9-995c-6fbceee80ae3.JPG)
![Capture2](https://user-images.githubusercontent.com/1224809/55138087-e42ed580-5132-11e9-97b0-997dc90f7b6a.JPG)

**Comment by fretzl** [comment]
I get the same.

**Comment by acrylian** [comment]
This should be fixed in the supprt build already of today (forgot to reference this ticket in the commit).
