### ISSUE TITLE
issue with googlemap (support build)

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1229]
hi

I have an issue with plugin googlemap on support build.

First, if I use it on albums page, there is no error in debug log but the zoom level is wrong, and I don't know why.

Beside of that, I have a page with all localized pictures.
The code of this page works well with official 1.5.1 but doesn't work with support build.
I have this error in debug log:
>EXCEPTION (0) : Class 'Googlemaps' not found dans /home/avbo7291/public_html/zenphoto__test/zp-core/zp-extensions/GoogleMap.php à la ligne 387

I have a look on previous commits, and I found a revert commit that deals with `zp-extensions/GoogleMap.php` but I am unable to understand what is the matter.

**Comment by vincent3569** [comment]
in fact, after some test, the issue is the same with official 1.5.1

**Comment by acrylian** [comment]
`Googlemaps` is the class from `/GoogleMap/CodeIgniter-Google-Maps-V3-API/GoogleMaps.php`. That should be loaded actually. To my knowledge there has been no change in this area for "ages".

**Comment by vincent3569** [comment]
oups...
it seems to be two issues of zpBootstrap :-(
I found the fix for the 2nd one but the 1st one is a mystery.
maybe a conflic with bootstrap accordeon script and googlemap script.
I have to look for.

**Comment by acrylian** [comment]
That class is PHP actually so a JS error should not affect it. But the library is loaded via the theme_head filter that also loads scripts.
