### ISSUE TITLE
Error installing Zenphoto 1.5.2

### ISSUE THREAD

**Issue by prbt2016** [zenphoto/zenphoto#1238]
Hello,

I  tried manual installation of Zenphoto version 1.5.2(zip version) downloaded from official website. I  was trying to install the script on the following environment:

OS-Centos 6.4 Final
Web server-Apache 2.2.34
PHP version- 5.6
MYSQL - 5.5.54

However the setup doesn't start after hitting http://{{url}}/zp-core/setup.php. The following is thrown in error log by Apache i.e : 

[Tue May 28 13:26:02 2019] [error] PHP Notice:  Use of undefined constant FULLWEBPATH - assumed 'FULLWEBPATH' in /{{path}}/{{to}/{{zenphoto}/zp-core/functions-basic.php on line 1829

[Tue May 28 13:26:02 2019] [error] PHP Notice:  Constant PROTOCOL already defined in /{{path}}/{{to}/{{zenphoto}/zp-core/functions-basic.php on line 149

[Tue May 28 13:26:02 2019] [error] PHP Notice:  Undefined index: mysql_prefix in /{{path}}/{{to}/{{zenphoto}/zp-core/functions-basic.php on line 161

[Tue May 28 13:26:02 2019] [error] PHP Notice:  Use of undefined constant FULLWEBPATH - assumed 'FULLWEBPATH' in /{{path}}/{{to}/{{zenphoto}/zp-core/functions-basic.php on line 1829

[Tue May 28 13:26:02 2019] [error] PHP Warning:  fileperms(): stat failed for /{{path}}/{{to}/{{zenphoto}/zp-data/zenphoto.cfg.php in /{{path}}/{{to}/{{zenphoto}/zp-core/functions-basic.php on line 177

[Tue May 28 13:26:02 2019] [error] PHP Notice:  Use of undefined constant FULLWEBPATH - assumed 'FULLWEBPATH' in /{{path}}/{{to}/{{zenphoto}/zp-core/functions-basic.php on line 1829

[Tue May 28 13:26:02 2019] [error] PHP Fatal error:  Call to undefined function db_quote() in /{{path}}/{{to}/{{zenphoto}/zp-core/functions.php on line 2002

Even debug.log under /zpdata folder throws these notices:

{19490:Tue, 28 May 2019 13:26:02 GMT} Zenphoto v1.5.2
NOTICE: Use of undefined constant FULLWEBPATH - assumed 'FULLWEBPATH' in /{{path}}/{{to}/{{zenphoto}/zp-core/functions-basic.php on line 1829
redirectURL called from reconfigureAction (reconfigure.php [44])
from require_once (functions-basic.php [125])
from require_once (admin-globals.php [12])
from setup.php [2]

{19490:Tue, 28 May 2019 13:26:02 GMT}
NOTICE: Constant PROTOCOL already defined in /{{path}}/{{to}/{{zenphoto}/zp-core/functions-basic.php on line 149
define called from require_once (functions-basic.php [149])
from require_once (admin-globals.php [12])
from setup.php [2]

{19490:Tue, 28 May 2019 13:26:02 GMT}
NOTICE: Undefined index: mysql_prefix in /{{path}}/{{to}/{{zenphoto}/zp-core/functions-basic.php on line 161
require_once called from require_once (admin-globals.php [12])
from setup.php [2]

{19490:Tue, 28 May 2019 13:26:02 GMT}
NOTICE: Use of undefined constant FULLWEBPATH - assumed 'FULLWEBPATH' in /{{path}}/{{to}/{{zenphoto}/zp-core/functions-basic.php on line 1829
redirectURL called from reconfigureAction (reconfigure.php [44])
from require_once (functions-basic.php [167])
from require_once (admin-globals.php [12])
from setup.php [2]

{19490:Tue, 28 May 2019 13:26:02 GMT}
WARNING: fileperms(): stat failed for /{{path}}/{{to}/{{zenphoto}/zp-data/zenphoto.cfg.php in /{{path}}/{{to}/{{zenphoto}/zp-core/functions-basic.php on line 177
fileperms called from require_once (functions-basic.php [177])
from require_once (admin-globals.php [12])
from setup.php [2]

{19490:Tue, 28 May 2019 13:26:02 GMT}
NOTICE: Use of undefined constant FULLWEBPATH - assumed 'FULLWEBPATH' in /{{path}}/{{to}/{{zenphoto}/zp-core/functions-basic.php on line 1829
redirectURL called from reconfigureAction (reconfigure.php [44])
from require_once (functions-basic.php [191])
from require_once (admin-globals.php [12])
from setup.php [2]

What could be causing the above issue? . I even checked on other PHP  environment(i.e PHP 7.1 and PHP 7.2) as well, but still setup doesn't start. Could you please replicate this issue at your end and fix this?.

**Comment by acrylian** [comment]
Thanks for the report. I sadly can reproduce this. It's not related to your environment, it's just an embarrassing oversight in the order of necessary constant defines.. We will fix this as soon as possible.

**Comment by prbt2016** [comment]
We'll that's great. Thanks for your prompt reply.

**Comment by acrylian** [comment]
Please try the support build (GitHub master) if this fixes it for you as well.

**Comment by fretzl** [comment]
Inconsistent results for a fresh install:

These are entries in the log:


EXCEPTION (0): Call to undefined function sanitizeRedirect() in .../zp-core/functions-basic.php on line 1830

  WARNING: Use of undefined constant FULLWEBPATH - assumed 'FULLWEBPATH' (this will throw an Error in a future version of PHP) in .../zp-core/functions-basic.php op regel 1829
  redirectURL called from reconfigureAction (reconfigure.php [44])
    from require_once (functions-basic.php [125])
      from require_once (functions.php [18])
        from include (index.php [14])
          from index.php [44]

  NOTICE: Constant PROTOCOL already defined in .../zp-core/functions-basic.php op regel 147
  define called from require_once (functions-basic.php [147])
    from require_once (functions.php [18])
      from include (index.php [14])
        from index.php [44]

  NOTICE: Undefined index: mysql_prefix in .../zp-core/functions-basic.php op regel 161
  require_once called from require_once (functions.php [18])
    from include (index.php [14])
      from index.php [44]

  WARNING: Use of undefined constant FULLWEBPATH - assumed 'FULLWEBPATH' (this will throw an Error in a future version of PHP) in .../zp-core/functions-basic.php op regel 1829
  redirectURL called from reconfigureAction (reconfigure.php [44])
    from require_once (functions-basic.php [167])
      from require_once (functions.php [18])
        from include (index.php [14])
          from index.php [44]

  WARNING: fileperms(): stat failed for .../zp-data/zenphoto.cfg.php in .../zp-core/functions-basic.php op regel 177
  fileperms called from require_once (functions-basic.php [177])
    from require_once (functions.php [18])
      from include (index.php [14])
        from index.php [44]

  WARNING: Use of undefined constant FULLWEBPATH - assumed 'FULLWEBPATH' (this will throw an Error in a future version of PHP) in .../zp-core/functions-basic.php op regel 1829
  redirectURL called from reconfigureAction (reconfigure.php [44])
    from require_once (functions-basic.php [191])
      from require_once (functions.php [18])
        from include (index.php [14])
          from index.php [44]

**Comment by prbt2016** [comment]
@acrylian That support build (GitHub master) works fine without any issues.

**Comment by acrylian** [comment]
Thanks for the feedback and confirmation!
