### ISSUE TITLE
Error setting up plugins on install

### ISSUE THREAD

**Issue by wongm** [zenphoto/zenphoto#1239]
For  Zenphoto v1.5.1 install, the `debug.log` contains multiple references to:

``` WARNING: curl_getinfo() expects at least 1 parameter, 0 given in /var/www/html/zenphoto.wongm.com/zp-core/functions-basic.php on line 1761

curl_getinfo called from curlRequest (functions-basic.php [1761])

from setup::defaultOptionsRequest (class-setup.php [765])

from require (setup-option-defaults.php [92])

from index.php [2525]

{21688:Tue, 25 Dec 2018 06:47:47 GMT}

NOTICE: cURL request not successful. NULL

{21688:Tue, 25 Dec 2018 06:47:47 GMT} 
```

Updating to 1.5.2 doesn't help.

```
 {13371:Tue, 28 May 2019 20:50:36 GMT}

NOTICE: cURL request not successful. array(26) {

["url"]=>

string(85) "http://zenphoto.wongm.com/zp-core/setup/setup_themeOptions.php?theme=basic&returnmode"

["content_type"]=>

NULL

["http_code"]=>

int(301)

["header_size"]=>

int(340)

["request_size"]=>

int(255)

["filetime"]=>

int(-1)

["ssl_verify_result"]=>

int(0)

["redirect_count"]=>

int(0)

["total_time"]=>

float(0.364623)

["namelookup_time"]=>

float(2.5E-5)

["connect_time"]=>

float(0.172663)

["pretransfer_time"]=>

float(0.172742)

["size_upload"]=>

float(0)

["size_download"]=>

float(0)

["speed_download"]=>

float(0)

["speed_upload"]=>

float(0)

["download_content_length"]=>

float(-1)

["upload_content_length"]=>

float(0)

["starttransfer_time"]=>

float(0.364545)

["redirect_time"]=>

float(0)

["redirect_url"]=>

string(86) "https://zenphoto.wongm.com/zp-core/setup/setup_themeOptions.php?theme=basic&returnmode"

["primary_ip"]=>

string(13) "SNIP"

["certinfo"]=>

array(0) {

}

["primary_port"]=>

int(80)

["local_ip"]=>

string(14) "SNIP"

["local_port"]=>

int(47854)

} 
```

I'm running Cloudflare over the top of the virtual private server that Zenphoto is installed on - maybe that is the cause of curl failing to make web requests back to the Zenphoto server?

**Comment by wongm** [comment]
curl request to the URL failing in the logs:

`curl -I  http://zenphoto.wongm.com/zp-core/setup/setup_themeOptions.php?theme=basic&returnmode`

Returns HTTP 301.

```
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Cache-Control: max-age=3600
Expires: Tue, 28 May 2019 22:01:52 GMT
Location: https://zenphoto.wongm.com/zp-core/setup/setup_themeOptions.php?theme=basic
Server: cloudflare
```

Access it via HTTPS instead:

`curl -I  https://zenphoto.wongm.com/zp-core/setup/setup_themeOptions.php?theme=basic&returnmode`

And I receive an image from the server.

```
Content-Type: image/png
Content-Length: 268
Connection: keep-alive
Server: cloudflare
```

Looks like a server config issue - 'external' users access site via HTTPS and Cloudflare, while the web server itself is only running HTTP. 

When Zenphoto install tries to load the HTTP version, it hits Cloudflare, which does HTTP 301 redirect to HTTPS version of the site, which `curl` is not configured to follow.

The -L flag instructs cURL to follow any redirect so that you reach the eventual endpoint.  Will adding that cause issues with Zenphoto code elsewhere?

**Comment by wongm** [comment]
Extra note - setting the "Server protocol" option to https doesn't work - it results in website doing an endless redirect loop, because https isn't actually exposed on the server: only at Cloudflare.

More detail on that here:

https://support.cloudflare.com/hc/en-us/articles/115000219871-Why-does-Flexible-SSL-cause-a-redirect-loop-

```
The Flexible SSL option within the Cloudflare Crypto app encrypts traffic between the browser and the Cloudflare network over HTTPS. However, when the Flexible SSL option is enabled, Cloudflare sends requests to your origin web server unencrypted over HTTP. Redirect loops occur if your origin web server is configured to redirect all HTTP requests to HTTPS when using the Flexible SSL option.
```

**Comment by acrylian** [comment]
> Extra note - setting the "Server protocol" option to https doesn't work

This is already fixed in the just released 1.5.2 respectively in the follow up update 1.5.3 coming soon. Please try the support build therefore.

Generally if your server is capable of SSL/https there is really no reason to still use https anyway. This is also to avoid mixed content which can break. We still have a "admin https only" option that will be removed some time in the future therefore.

I don't neither use  Cloudfare nor I am familiar with it or what you are doing exactly. Zenphoto is meant for hosting on the server it is installed and tested as such.

> The -L flag instructs cURL to follow any redirect so that you reach the eventual endpoint. Will adding that cause issues with Zenphoto code elsewhere?

Well, it probably could end in a lot of redirections of redirections ;-)

**Comment by acrylian** [comment]
I will try adding the `CURLOPT_FOLLOWLOCATION`  locally and report back if all works. cURL is primarily used on setup and for the cachemanager (if enabled).

**Comment by acrylian** [comment]
Seems to work fine with `CURLOPT_FOLLOWLOCATION` set. I additionally limited the redirections to 3. If yours just one actually then this should cover this. It's in the support build already.
