### ISSUE TITLE
v1.5.3b: /zp-core/locale/es_BO/LC_Messages/ has incorrect path case

### ISSUE THREAD

**Issue by MarkRH** [zenphoto/zenphoto#1240]
Didn't notice until installing at webhost since Windows is not case sensitive when it comes to file and path names. 

Code has:

`$po = file_get_contents(SERVERPATH . "/" . ZENFOLDER . "/locale/" . $dirname . '/LC_MESSAGES/zenphoto.po');`

The actual directory structure is: 
`/zenphoto/zp-core/locale/es_BO/LC_Messages/zenphoto.po`

The "LC_MESSAGES" should be changed to "LC_Messages".   I got this in the PHP error log:

[01-Jun-2019 17:04:35 America/Chicago] PHP Warning: file_get_contents(/(path)/zenphoto/zp-core/locale/es_BO/LC_MESSAGES/zenphoto.po): failed to open stream: No such file or directory in /(path)/zenphoto/zp-core/setup/setup-option-defaults.php on line 581

**Comment by MarkRH** [comment]
I also found this in /zp-core/admin-options.php on line 727:
`$po = file_get_contents(SERVERPATH . "/" . ZENFOLDER . "/locale/" . $dirname . '/LC_MESSAGES/zenphoto.po');
`
Looking at other language directories, they are all named LC_MESSAGES.  So looks like just the physical directory name under es_BO needs to be changed to LC_MESSAGES and that fixes it.

**Comment by acrylian** [comment]
Thanks, good find and my bad I didn't check when the user submitted these.
