### ISSUE TITLE
False forward after admin login

### ISSUE THREAD

**Issue by UDZGuru** [zenphoto/zenphoto#1242]
I installed zenphoto in pics.mydomain.tld. 

After upgrading to 1.5.3 when I go to pics.mydomain.tld/admin I am being redirected to pics.mydomain.tld/zp-core/admin.php. 

When I enter my credentials the admin login forwards to pics.mydomain.tldzp-core/admin.php -> which of course produces an error.

I guess somewhere the / in the domain got lost. 

1.5.2 did function fine and I followed the official upgrade instructions. 

If there are any questions just answer here :)

**Comment by UDZGuru** [comment]
I researched a little bit and the generated HTML code when calling pics.mydomain.tld/zp-core/admin.php has the problem in the form action:

`<form name="login" action="https://pics.mydomain.tldzp-core/admin.php" method="post">`

Notice the missing / in the form action.

Unfortunately I am not good in PHP and was not able to locate the piece of code in admin.php where this portion of the output HTML is generated.

**Comment by acrylian** [comment]
Thanks, we will take a look to reproduce it and possible slip through.

**Comment by acrylian** [comment]
Please try the support build (master).

**Comment by UDZGuru** [comment]
Just to give feedback regarding the fix: 

Works flawless with the support build from github master.

**Comment by acrylian** [comment]
Thanks for confirming!
