### ISSUE TITLE
Redirection issue when login in ZenphotoCMS 1.5.3

### ISSUE THREAD

**Issue by GaneshKandu** [zenphoto/zenphoto#1243]
Hi,

I am Getting Redirection issue when login
it Redirect to wrong url that causing 404 Error

this is my login page 
http://domain.com/manual/zenphoto153/zp-core/admin.php
after login redirects to
http://domain.commanual/zenphoto153/zp-core/admin.php

after debug i found issue in ```zp-core\functions-basic.php``` file ```sanitizeRedirect``` function
```sanitizeRedirect``` function returns wrong url

> Note: installed in sub directory

**Comment by acrylian** [comment]
Thanks, but already reported and  fixed in master. Please try. https://github.com/zenphoto/zenphoto/issues/1242
