### ISSUE TITLE
Too many languages activated

### ISSUE THREAD

**Issue by tw2003** [zenphoto/zenphoto#1244]
I just did the update to version 1.5.3. 
During the first test i found the following langauges being activated
![grafik](https://user-images.githubusercontent.com/11540163/59501863-bbe68580-8e9c-11e9-9f9f-92e16f5b8c58.png)
I only had german and english activated before (version 1.5)
I think theses are the newly added languages that are active by default with this version.

**Comment by acrylian** [comment]
Thanks, will take a look what might happen here.

**Comment by acrylian** [comment]
Tried to reproduce this locally by only enabling German and English and then running setup. The option did not change.

**Comment by tw2003** [comment]
Did you only ran setup again?

I followed the instructions so removed themes and zp-core folder as well as index.php

Maybe that's the correct sceanrio to reproduce.

 

Gesendet: Freitag, 14. Juni 2019 um 12:29 Uhr
Von: "Malte Müller" <notifications@github.com>
An: zenphoto/zenphoto <zenphoto@noreply.github.com>
Cc: tw2003 <tw2003@web.de>, Author <author@noreply.github.com>
Betreff: Re: [zenphoto/zenphoto] Too many languages activated (#1244)


Tried to reproduce this locally by only enabling German and English and then running setup. The option did not change.

**Comment by acrylian** [comment]
Yes, of course I did re-run setup (as I wrote above). But I will re-try with overwriting files. But this should not make any difference.

**Comment by tw2003** [comment]
It‘s not a big deal. Just disabled the languages in admin area.

T. Wenzel

Am 14.06.19 um 13:07 schrieb Malte Müller

**Comment by acrylian** [comment]
Okay, but it should not happen nevertheless.

**Comment by acrylian** [comment]
It is indeed reproducable. Setup does enable new translation that have no option yet. While that is perhaps okay on fresh installs it is indeed not so on existing install.
