### ISSUE TITLE
v1.5.3: If album thumb is from a video, it's scaled to the size of video.

### ISSUE THREAD

**Issue by MarkRH** [zenphoto/zenphoto#1246]
I have an album where the thumbnail is set to "most recent" which happens to be a MP4 video.  On the album page, while it is using the 100x100 thumbnail, it is scaling it to 640x360.  Here's the source code being generated:

```php
																					<div class="album">
												<a class="albumthumb" href="/planetary-society-and-seti/" title="View album:  Planetary Society and SETI">
													<img src="/cache/planetary-society-and-seti/The_Planetary_Society-LightSail_100_cw100_ch100_thumb.jpg?cached=1546379560" alt="Planetary Society and SETI" width="100" height="100">												</a>
												<div class="albumdesc">
													<h3>
														<a href="/planetary-society-and-seti/" title="View album:  Planetary Society and SETI">
															Planetary Society and SETI														</a>
													</h3>
													<br>
													<small>12/19/2003</small><br>
                                       <small>Views: 4530</small>
												</div>
												<p style="clear: both;"></p>
											</div>
																						<div class="album">
												<a class="albumthumb" href="/humorous/" title="View album:  Humorous Images">
													<img src="/cache/humorous/staying-alive-in-the-data-center_100_cw100_ch100_thumb.jpg?cached=1546380080" alt="Humorous Images" width="640" height="360">												</a>
												<div class="albumdesc">
													<h3>
														<a href="/humorous/" title="View album:  Humorous Images">
															Humorous Images														</a>
													</h3>
													<br>
													<small>07/06/2007</small><br>
                                       <small>Views: 5609</small>
												</div>
												<p style="clear: both;"></p>
											</div>
```
How it looks:
![image](https://user-images.githubusercontent.com/8035962/59901662-8fad9600-93c1-11e9-9485-692bd032deb3.png)

**Comment by MarkRH** [comment]
Actually, it's the size of the video file, not what's set as the jplayer plugin size.  For now, I can get it to appear normal if I edit my theme's **album.php** (based on Garland) file at line 66 from:
```
<?php printCustomAlbumThumbImage(getAlbumTitle(), MRH_ALBUMTHUMB_SIZE, NULL, NULL, MRH_ALBUMTHUMB_SIZE, MRH_ALBUMTHUMB_SIZE); ?>
```
To:
```
<?php printCustomAlbumThumbImage(getAlbumTitle(), MRH_ALBUMTHUMB_SIZE, MRH_ALBUMTHUMB_SIZE, MRH_ALBUMTHUMB_SIZE, MRH_ALBUMTHUMB_SIZE, MRH_ALBUMTHUMB_SIZE); ?>
```

**Comment by acrylian** [comment]
It seems that Garland is indeed using a wrong setting for this. It uses this:

`<?php printCustomAlbumThumbImage(getAlbumTitle(), 85, NULL, NULL, 85, 85); ?>`

This would not create a cropped image at all.  It should be using this call like the Zenpage theme (which it is largely based on):

`<?php printCustomAlbumThumbImage(getBareAlbumTitle(), NULL, 85, 85, 85, 85); ?>`

$size is technically not needed for a cropped image anad $cropx/$cropy (the last two) are also not.

**Comment by acrylian** [comment]
This is fixed in the support build.

**Comment by fretzl** [comment]
Weird, I don’t see any problems at all.

> It should be using this call like the Zenpage theme (which it is largely based on):
> 
> <?php printCustomAlbumThumbImage(getBareAlbumTitle(), NULL, 85, 85, 85, 85); ?>
> 

BTW: You committed 	<?php printCustomAlbumThumbImage(getAlbumTitle(), 85, 85, 85, 85, 85); ?>

**Comment by acrylian** [comment]
> Weird, I don’t see any problems at all.

Well, I could directly reproduce this issue ;)

> BTW: You committed 	<?php printCustomAlbumThumbImage(getAlbumTitle(), 85, 85, 85, 85, 85); ?>

I did but $size is just ignored even if set if you have set width/height so it does not matter.
