### ISSUE TITLE
No login possible after upgrade to 1.5.4

### ISSUE THREAD

**Issue by UDZGuru** [zenphoto/zenphoto#1247]
I was running 1.5.4a as a result of #1242 and decided to upgrade to 1.5.4 stable. 

When I enter my credentials I am just redirected to the login form (with empty fields for username/password). 

I tried entering wrong credentials. Here I get an error as supposed to be. 

As I was wondering if I _really_ entered the correct credentials I decided to reset my password. So I clicked the link and was asked to answer my security question which I entered correctly. After that I was forwarded to another form where I could **set** and **save** a new password. 

So back to the login page and entering the username and the freshly set password. Again I am just being redirected to an empty login form and not able to access the admin-interface. 

Unfortunately I am not sure on what technical input might be needed. So if you need something, just let me know and I will try to provide what is needed to clarify this situation.

**Comment by acrylian** [comment]
Please check the logs in `/zp-data/` for any errors (and if you can your server's PHP error log). Also check to be sure that your browser really has cookies allowed and that no adblocker or similar plugin is interfering accidentally. This is really strange as actually nothing has changed regarding the  login procedure itself from 1.5.4a to 1.5.4 at all.

**Comment by UDZGuru** [comment]
It seemed weird to me as well. 

I just re-uploaded 1.5.4. and now it is working again. There seems to have been an issue when I uploaded the upgrade initially. 

Bug closed!

**Comment by acrylian** [comment]
Okay, thanks for the follow up. Sometimes too persistent cookies are a problem in browser that still interfere although actually cleared. SOmehow a browser cache related issue of sorts. Safari is notorious for these things for example.
