### ISSUE TITLE
Installer warns about needing PHP >= 5.6 when using 5.6

### ISSUE THREAD

**Issue by matthijskooijman** [zenphoto/zenphoto#1250]
I just unpacked Zenphoto (v1.5.4) and opened the setup page. It says:

> PHP version 5.6.30-0+deb8u1
> Warning!
>
> PHP Version 5.6.0 or greater is required. Version 7.1.0 or greater is strongly recommended. Use earlier versions at your own risk. Zenphoto is developed on PHP 7.1+ and in any case not tested below 5.6. There will be no fixes if you encounter any issues below 5.6. Please contact your webhost about a PHP upgrade on your server.

Given that I'm using PHP >= 5.6.0, should this warning be displayed? Is the setup perhaps a bit confused about the Debian version number format?

**Comment by sbillard** [comment]
You get the warning because of the recommendation for version 7.1.  BTW, according to the PHP site, versions in the 5.6 and 7.0 range stopped went end-of-life as of 1 January 2019, so maybe the warning is a good thing? Support for 7.1 goes away at the end of the year as well. You might want to get to a newer version of PHP.

**Comment by matthijskooijman** [comment]
Thanks for clarifying. Maybe the wording of the warning should be revised then. How about:

> PHP version 7.1.0 or greater is strongly recommended. Use earlier versions at your own risk. Zenphoto is developed on PHP 7.1+ and in any case not tested below 5.6. There will be no fixes if you encounter any issues below 5.6. Please contact your webhost about a PHP upgrade on your server.

That would make it clearer the warning is shown because PHP is < 7.1.

> You might want to get to a newer version of PHP.

This is certainly true, but I still have some code that runs on the mysql extension (rather than mysqli), which is blocking this upgrade unfortunately...

**Comment by acrylian** [comment]
The text is correct as we recommend 7.1+ and develop and test on 7.2+ already. 5.6 is sort of lowest common denominator and it even should generally even run on older versions. However although we don't have strict PHP 7 only code we neither test nor will add fixes for anything below 7 anymore. A lot of hosts already disabled everything below 5.6 and soon will surely do the same of it.

> This is certainly true, but I still have some code that runs on the mysql extension (rather than mysqli), which is blocking this upgrade unfortunately...

But this not really our problem, isn't it? ;-) Zenphoto runs with either database extension. Perhaps check if you host allows older PHP versions per directory or domain. Sooner or later you will run into this problem so this code will need to be updated regardless.

**Comment by matthijskooijman** [comment]
> The text is correct as we recommend 7.1+ – this is pretty clear to me 

It was a bit confusing to me, but that's not really a big problem of course. Closing this issue seems fine to me, thanks for your responses so far :-)

> But this not really our problem, isn't it? ;-)

Nope, just giving some background why I ran into this in the first place :-)

**Comment by acrylian** [comment]
All right ;-) Your feedback is appreciated in any case.
