### ISSUE TITLE
How can I get updating zh_Hans_CN

### ISSUE THREAD

**Issue by edouardlicn** [zenphoto/zenphoto#1251]
I checked the po file and donnt know what need to be update.

**Comment by acrylian** [comment]
You find all info here: https://www.zenphoto.org/news/translating-tutorial/

**Comment by edouardlicn** [comment]
I know how to use git but I dont know translations ,like Chinese, at what part needs to be update.Seems that they all up to date.

**Comment by acrylian** [comment]
I don't understand. You don't need to register on our site, except for the forum, and especially not for translations (I indeed see that we still link to the Google translators mail group, this is actually not used anymore at all). 

The page I linked above is a complete tutorial how to do translations. What exactly didn't you understand?

**Comment by edouardlicn** [comment]
But that translation is unavalable on the newest version,and I need it to be update to use on my site.I want to know if I use github to get update the translation,how can I know which string needs to be update?

**Comment by acrylian** [comment]
Both Chinese variants are available in the latest release just not current:
https://github.com/zenphoto/zenphoto/tree/master/zp-core/locale/zh_Hans_CN
https://github.com/zenphoto/zenphoto/tree/master/zp-core/locale/zh_Hant_TW

> I want to know if I use github to get update the translation,how can I know which string needs to be update?

Sorry, but the above linked tutorial tells all that…

**Comment by edouardlicn** [comment]
That tutorial is too long to tell the most important things.Why not make a crowdin project?

**Comment by acrylian** [comment]
The tutorial tells the most important things… But here the basics for you: 

- Use Poedit or any other editor to parse the files of Zenphoto for new gettext strings to translate and update the translation.
- Submit the updated translation with the correct catalogue settings (Zenphoto version etc.) via a GitHub pull request.

**Comment by edouardlicn** [comment]
OK,in order to save my time(and I  dont have pro version of poedit),I make a private project to translate on crowdin.

**Comment by acrylian** [comment]
You don't need the pro version of Poedit.

**Comment by edouardlicn** [comment]
but 
I need those suggestion.

**Comment by acrylian** [comment]
> but I need those suggestion.

Okay, I found them and the automatic translation facility not that useful as mostly not that fitting anyway (at least for the German translation I maintain). 
You can use whatever tool you like of course. But don't forget to re-parse the files or however crowdin does this so the translation has all strings that need translation. Be aware this will be a lot of work.
