### ISSUE TITLE
Installation problems - upload not show

### ISSUE THREAD

**Issue by cienfu** [zenphoto/zenphoto#1252]
Hello,

I make a new installation but i don't know if something is wrong, becouse when i access to admin panel i can create albums and subalbums but i can't see the upload button to start uploading photos and videos.. some help? thanks.

Screenshots:
https://ibb.co/QKXVKCR
https://ibb.co/6W5D7Mm
https://ibb.co/pbp4Rdt

**Comment by acrylian** [comment]
It is really not necessary to open a forum topic and a ticket at the same time. This is for bugs and this is not one for sure. I will reply on the forum.

**Comment by cienfu** [comment]
Thanks, sorry.
