### ISSUE TITLE
Upload images via jQuery not working in Zenphoto version 1.5.5

### ISSUE THREAD

**Issue by prbt2016** [zenphoto/zenphoto#1255]
Hello,

After successful manual installation of Zenphoto version 1.5.5, when I visit Upload->Images(Jquery), images are not being uploaded after clicking on Start upload. The following error is shown in the console window. Installed it on the following environment:

PHP VERSION - 5.6.40
MYSQL - 5.5.62
Apache - 2.2.34

![error_zen](https://user-images.githubusercontent.com/17871448/67384891-a7836980-f5af-11e9-941b-ed1b6d394b83.png)

This worked fine in earlier version i.e 1.5.4. Could you please check this at your end and fix this?

**Comment by acrylian** [comment]
Thanks, we will take a look.
