### ISSUE TITLE
POSTing sort array is broken when more than 1000 elements in the album!

### ISSUE THREAD

**Issue by adrav** [zenphoto/zenphoto#1256]
When user is changing the picture order via admin console and post it to save:

POST /zp-core/admin-albumsort.php?page=edit&album=xxxx&saved&tab=sort

If there are more than 1000 elements not all entries are being sent via POST by php limit:

max_input_vars | 1000

https://www.php.net/manual/en/info.configuration.php#ini.max-input-vars

It ends with not saving order of pictures at 999+ position.

Possible solution - change the way how the order is being sent via POST, or at least check this php parameter in the setup checker.

**Comment by acrylian** [comment]
Yes, this is one of several server side limitations that can cause problems. Actually I would recommend to divide albums with that much images into several albums currently. We'll keep this in mind for the future and for now consider a setup warning.

**Comment by acrylian** [comment]
Yes, this is one of several server side limitations that can cause problems. Actually I would recommend to divide albums with that much images into several albums currently. We'll keep this in mind for the future and for now consider a setup warning. 
I would probably recommend to divide albums with that much images anyway.

**Comment by adrav** [comment]
Pls add setup warning to let user know about possible problem.
Unfortunately I can not divide album.

**Comment by adrav** [comment]
Pls reopen this as there are unnecessary line:
 					echo "<pre>"; print_r($_GET); echo "</pre>";

**Comment by acrylian** [comment]
Has already been removed, no need to re-open a ticket as the issue is fixed as much as possible. After all this is not yet a finished release.
