### ISSUE TITLE
getNewsContent() returns an empty string if news article contains an emoji

### ISSUE THREAD

**Issue by viktorzen** [zenphoto/zenphoto#1258]
Hello, I have found a weird behavior of the getNewsContent() template function on zenpage news articles.

If the news article contains an UTF8 emoji (like this one 💖) entered via the Windows emoji input box (Windows + .), the zenpage template function getNewsContent() returns an empty string.

Can you please take a look why this is happening?

ps. tested on the latest 1.5.6 stable build

**Comment by acrylian** [comment]
Same emoji issue as on the other ticket. You currently have to use encoded emojis.

**Comment by viktorzen** [comment]
thx, hope this will be fixed soon, because emojis are quite ubiquitous nowadays ;)

**Comment by acrylian** [comment]
"Soon" I cannot promise anything ;-)
