### ISSUE TITLE
"HTTP header inspector" throws debug errors

### ISSUE THREAD

**Issue by viktorzen** [zenphoto/zenphoto#1259]
Clicking on the "HTTP header inspector" on the admin panel, throws some debug errors and does not display any header information:

(tested on zenphoto 1.5.6)

Debug errors:
{6042:Thu, 19 Dec 2019 16:30:53 GMT}

WARNING: get_headers(): This function may only be used against URLs in .../zp-core/utilities/http_header_inspector.php on line 42

get_headers called from http_header_inspector.php [42]

{6042:Thu, 19 Dec 2019 16:30:53 GMT}

WARNING: get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in .../zp-core/utilities/http_header_inspector.php on line 46

get_headers called from http_header_inspector.php [46]

{6042:Thu, 19 Dec 2019 16:30:53 GMT}

WARNING: get_headers(): This function may only be used against URLs in .../zp-core/utilities/http_header_inspector.php on line 46

get_headers called from http_header_inspector.php [46]

{6042:Thu, 19 Dec 2019 16:30:53 GMT}

WARNING: Invalid argument supplied for foreach() in .../zp-core/utilities/http_header_inspector.php on line 54

{6042:Thu, 19 Dec 2019 16:30:53 GMT}

WARNING: Invalid argument supplied for foreach() in .../zp-core/utilities/http_header_inspector.php on line 54

**Comment by acrylian** [comment]
I cannot reproduce this neither on local installs nor our own site.

But one of your errors actually tells what is happening:

> https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in 

Your server does not allow using https urls to get the headers. All others are downstream warning.

**Comment by acrylian** [comment]
I will see to do a check for this so at least show a message.

**Comment by viktorzen** [comment]
thx, a short notice would be cool :)

**Comment by acrylian** [comment]
The support build/1.5.7b has a fix for this now possibly. Please try you should get a message now.

**Comment by viktorzen** [comment]
tried the new update, but still getting the warnings,

and there is also an unnecessary "?>" at the end of file (line 74)

```
WARNING: Invalid argument supplied for foreach() in .../zp-core/utilities/http_header_inspector.php on line 54

{4470:Thu, 19 Dec 2019 22:10:09 GMT}

WARNING: get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in .../zp-core/utilities/http_header_inspector.php on line 44

get_headers called from http_header_inspector.php [44]

{4470:Thu, 19 Dec 2019 22:10:09 GMT}

WARNING: get_headers(): This function may only be used against URLs in .../zp-core/utilities/http_header_inspector.php on line 44

get_headers called from http_header_inspector.php [44]

{4470:Thu, 19 Dec 2019 22:10:09 GMT}

WARNING: get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in .../zp-core/utilities/http_header_inspector.php on line 48

get_headers called from http_header_inspector.php [48]

{4470:Thu, 19 Dec 2019 22:10:09 GMT}

WARNING: get_headers(): This function may only be used against URLs in .../zp-core/utilities/http_header_inspector.php on line 48

get_headers called from http_header_inspector.php [48]

{4470:Thu, 19 Dec 2019 22:10:09 GMT}

WARNING: Invalid argument supplied for foreach() in .../zp-core/utilities/http_header_inspector.php on line 56

{4470:Thu, 19 Dec 2019 22:10:09 GMT}

WARNING: Invalid argument supplied for foreach() in .../zp-core/utilities/http_header_inspector.php on line 56
```

**Comment by acrylian** [comment]
> and there is also an unnecessary "?>" at the end of file (line 74)
Yes, but that's neither an issue nor an error.

Please user the native php function `stream_get_wrappers()` and tell what array values it returns on your server. Your server is trying to use a "https" url with `get_headers()` which your server does not allow somehow. But then "https" should not be within the array `stream_get_wrappers()` returns and you should not even get to that `get_headers()` call.

**Comment by viktorzen** [comment]
my stream_get_wrappers() output:

```
Array
(
    [0] => https
    [1] => ftps
    [2] => compress.zlib
    [3] => compress.bzip2
    [4] => php
    [5] => file
    [6] => glob
    [7] => data
    [8] => http
    [9] => ftp
    [10] => phar
    [11] => zip
)
```

**Comment by acrylian** [comment]
Then I don't understand how you get this error as you naturally then get past this check:

`$streamwrappers = stream_get_wrappers();
if(in_array(PROTOCOL, $streamwrappers)) { … } `

What is the value of the PROTOCOL constant on your install? That should be "https" if your install is set to that.

**Comment by viktorzen** [comment]
PROTOCOL is "https", not sure but I think get_headers fails because allow_url_fopen is set to off

**Comment by acrylian** [comment]
Indeed, there needs to be a check for that as well.

**Comment by acrylian** [comment]
Should be even simpler as  `get_headers()` returns false if it fails. Please try the new version. The log warnings will still appear for now.

**Comment by viktorzen** [comment]
now the error message ist correctly displayed,
but there is still the unopened php close tag at the end of file, line 73
https://github.com/zenphoto/zenphoto/blob/6019ee6ccb735830a8dbaad3a867afa406310227/zp-core/utilities/http_header_inspector.php#L73

**Comment by acrylian** [comment]
Good. The log warnings will be kept so the site owner gets a clue. About the unopened tag, that I meant to have removed but apparently on resetting the file re-added it.

**Comment by viktorzen** [comment]
ok, cool 👍 (trying an emoji here)
