### ISSUE TITLE
Slideshow2 fails when linked from My Favorites

### ISSUE THREAD

**Issue by angeltek** [zenphoto/zenphoto#1260]
There is a small typo bug in extension **slideshow2** of Zenphoto version 1.5.6 (Official build) that  causes sideshows linked from the Favourites extension (via a custom template page) to fail.  

Line 576 of /zp-core/zp-extensions/slideshow2.php within function printSlideShowLink() is missing a trailing slash on the url rewrite path "/slideshow" - it should be "/slideshow/", as in: 

`$slideshowlink = rewrite_path(_PAGE_ . '/slideshow/', "index.php?p=slideshow");`

Without this explicit trailing slash the user's browser has it forcefully added by a rewrite rule in /.htaccess, however that then seems to destroy the $_POST data send by the hidden form that printSlideShowLink() generates.  This in turn causes printSlideShow() to throw an error because it has no passed parameters.  

I have manually patched the file my end and it is now working fine.

**Comment by acrylian** [comment]
Thanks for finding this. Looks true. I guess both definitions should rather use the `getCustomPageURL()` function instead of the `rewrite_path()` base one. We'll review that asap.

**Comment by acrylian** [comment]
Please try the fixes in the support build. In this rare case you can just try the file but a general test is always appreciated. One rewrite_path() usages needed to be kept as it is special but I replace two other instances.
