### ISSUE TITLE
[security] XSS in /page/search/

### ISSUE THREAD

**Issue by gwen001** [zenphoto/zenphoto#1262]
**Description:** The parameters `SEARCH_*` are not sanitized when displayed in the logout link in the search page when the user is connected.

**Environment:**

Version: 1.5.6
OS: Ubuntu 16.10
Web server: Apache 2.4.18
PHP: 7.4.2
Database: MySQL 5.7.28
URL: /page/search/

**Payload:**
```/page/search/?SEARCH_xxx=xxx"></div><u><svg/onload=alert(1)>xxx```

![zenphoto-1 5 6-xss-search](https://user-images.githubusercontent.com/5347721/74107399-cc581880-4b6f-11ea-8fa0-99fc91c93a09.png)

**Comment by acrylian** [comment]
Thanks but next time please think a little before you post a security issue in public. Also see https://github.com/zenphoto/zenphoto/blob/master/contributing.md

**Comment by gwen001** [comment]
I swear I'll do my best !

**Comment by gwen001** [comment]
Perfect!
