### ISSUE TITLE
Albums will not auto publish if both future publish date and an expiration date are set

### ISSUE THREAD

**Issue by imrayzor** [zenphoto/zenphoto#1263]
When creating albums or republishing expired albums, if both a future publish date and expiration date are set albums will not auto publish when the publish date is reached. If only a future publish date is set the albums auto publish correctly. This has been an issue for the past couple of releases. This is not an issue for news articles. They will publish correctly.

Zenphoto version 1.5.6 (Official build)	
PHP version: 7.3.14

**Comment by acrylian** [comment]
> This has been an issue for the past couple of releases.

I don't remember any report about this issue…

> will not auto publish when the publish date is reached. If only a future publish date is set the albums auto publish correctly

I assume that the expire date is not before the future publish date as that would be expected ;-)

> republishing expired albums

Does that album still have the (reached) expired date set? Then this would be of course normal behaviour. Any already reached expired date needs to be removed if you wish to republish. 

Just asking to be sure that we use the same conditions to reproduce.

**Comment by imrayzor** [comment]
> I don't remember any report about this issue…

I didn't report it before. I figured someone else would. When I first noticed the issue back in 2018, I thought it was happening because I would go back to the album to edit something before it published and did not recheck the publish box. I started making sure I rechecked the box each time I would edit pre-publish date but the issue persisted. I have tried various ways to resolve the issue thinking it was something that I was doing wrong since it wasn't reported but now I think maybe I use the feature in ways others do not that brought out the bug. I have been using ZenPhoto for around 10 years but just started using the autopublish and expire features in 2018.

> I assume that the expire date is not before the future publish date as that would be expected ;-)

You are correct. For instance today's album was created in January (I create albums a month or more in advance) It was set to publish 2020-02-21 with an album date of 2020-02-21 and an expiration date of 2020-03-21. I then check the publish box and press apply. The page refreshes with the Publish box unchecked and the statement in red that says future publishing date. This morning when I checked the gallery it was unpublished. As was yesterday's and all the galleries that were published last week that had expiration dates (I have been going back weekly and manually fixing unpublished galleries). The non expiring galleries published just fine. BTW, because I don't know if it would be part of the issue, I upload galleries via FTP and in the gallery settings I set all images to be published by default but galleries to be unpublished by default. That way I don't have to set each image to publish in a gallery when I set up the publish dates. I also create news articles and link a photo to the album which allows viewers to see the album contents but since the album didn't publish it will not show in the album list in the gallery itself.

> Does that album still have the (reached) expired date set? Then this would be of course normal behaviour. Any already reached expired date needs to be removed if you wish to republish.

When I republish albums I change the publish date, album date, and expiration date. I use a combination of manual sorting in the main gallery (ie Travel comes before Scenery), descending date order (sub albums), and filename ascending (image pages)

**Comment by acrylian** [comment]
Thanks, It is not really necessary to change the album date itself as that is independent from the other to (e.g. file system date or else). 

Anyway, seems we are able to reproduce the issue.  News (and pages) by the way work completely different here as they use the actual article date for this and also require to be set to "published" already to be scheduled. This is actually counterintuitive, I see no reason why they can't just be unpublished until they are not. All items types should generally work the same way here for conistency

**Comment by imrayzor** [comment]
> they use the actual article date for this and also require to be set to "published" already to be scheduled.

Yes, if I make a mistake and do not click publish when I hit apply the system does warn that you must set it to publish in order for it to actually publish as expected.

**Comment by acrylian** [comment]
Exactly, and IMHO this should be aligned with the albums way: future date > scheduled publishing and the article is forced to be unpublished until then just like albums and images are.

**Comment by acrylian** [comment]
Sorry it took a while. We have tested the feature and it is working as expected. You can also have publishdate and expiredate at the same time. Naturally the expired date must be later than the publishdate as otherwise the item expires before it was even published naturally. 

For scheduled future publishing to work the item must be published already. The function does not publish unpublished items, it just temporarily unpublishes them internally (= does not change the publish/show value in the db) until the schedule is reached (Expired items are in fact really unpublished). In fact the unchecked "publish" checkbox is because of that. 

We have made some interface changes to better reflect this "published/unpublished" status  both on the single edit page and the list display with some new icons.

**Comment by imrayzor** [comment]
Thank you for your attention to this matter. I installed version 1.5.7b and it is working for me as well. I like the new icons and verbiage that explains what is what as far as published, unpublished, future publish, and expiring. It is much clearer with the checkboxes checked and showing publishing scheduled.

**Comment by acrylian** [comment]
Thanks for the feedback! That we hoped to achieve with those changes.
