### ISSUE TITLE
basic questions. Is there a manual?

### ISSUE THREAD

**Issue by richb201** [zenphoto/zenphoto#1264]
I have a site that is up and running on AWS. The site deals with tax data and has little to do with images. The login an security is already controlled by the main application. I have a need to allow users to upload images to their own private repositories. I run MySQL in a docker container on my laptop, but hope to upload this to my AWS site. My app is written in PHP. 

The part of my app that I am working on uses Jaspersoft server to run reports. Jaspersoft can access images in mySQL to include in a report. A single table in Mysql will hold numbers clients images and i use index fields to limit access to specific images. 

Is there a way to control the zenphoto UI from my PHP program (or from my Javascript extension)? Is there a mnaul that details this type of interaction?

**Comment by acrylian** [comment]
Please don't use tickets for such general questions, use the forum on https://forum.zenphoto.org instead. So please let's proceed over there. There is no "manual" as the backend explains a lot. You find general info also here: https://www.zenphoto.org/news/category/user-guide/
