### ISSUE TITLE
issue with printCustomMenu()

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1266]
hi
issue formerly discussed on the forum: https://forum.zenphoto.org/discussion/1410602/issue-with-printcustommenu

classes in the function parameters ($css_class_topactive, $css_class, $css_class_active) are not applied correctly to menu items.
this means that the css rules cannot be applied correctly (basically, for my 3rd party theme, I need a top-level menu item with an 'active' css rule to highlight this menu item).

**Comment by acrylian** [comment]
I will take a look when I get the chance. If it can easily be changed, I might do it. Otherwise it has to wait.

**Comment by acrylian** [comment]
Please check the support build for an update on this
