### ISSUE TITLE
Undefined index: mysql_port error in PHP strict mode

### ISSUE THREAD

**Issue by wongm** [zenphoto/zenphoto#1269]
I'm running PHP 7.4 in strict mode, and it complains about the new `mysql_port ` functionality.

```
 {16879:Fri, 05 Jun 2020 00:40:29 GMT} Zenphoto v1.5.7
NOTICE: Undefined index: mysql_port in [snip]/zp-core/functions-db-MySQLi.php on line 30
db_connect called from require_once (functions-basic.php [194])
from require_once (admin-globals.php [12])
from admin-logs.php [8] 
```

Release notes say `$config['mysql_port']` is optional and code does a fallback to default port, so no functional issues. But these warning messages are annoying in my logs.

**Comment by wongm** [comment]
Adding `$config['mysql_port']` to my config file also resolves the issue.

**Comment by acrylian** [comment]
Yes, we already discussed this on the forum (https://forum.zenphoto.org/discussion/1410610/upgrade-to-zp-1-5-7#latest). Sadly some default got lost that was supposed to be there…

**Comment by acrylian** [comment]
Follow up: Although the undefined index appears once (which it actually should not of course), isetup adds the missing define to the config file when running. So it will no re-appear afterwards.

**Comment by acrylian** [comment]
Fixed in https://github.com/zenphoto/zenphoto/commit/e306a2e9cc5aa0af64f9924ad60cc5302b7b5f08
