### ISSUE TITLE
1.5.7 themes editor - too few arguments to function isTextFile()

### ISSUE THREAD

**Issue by avicarmi** [zenphoto/zenphoto#1270]
EXCEPTION (0): Too few arguments to function isTextFile(), 1 passed in /zenphoto/zp-core/admin-themes-editor.php on line 45 and exactly 2 expected in /zenphoto/zp-core/admin-themes-editor.php on line 23

**Comment by avicarmi** [comment]
solved, added "$ok_extensions" to isTextFile() function calls

line 45:	if (isTextFile($file, $ok_extensions)) {

and line 59
	if (!in_array($file_to_edit, $themefiles) or ! isTextFile($file_to_edit, $ok_extensions) or filesize($file_to_edit) == 0) {

**Comment by acrylian** [comment]
Thanks, fixed now, I just skipped the extra parameter and moved the extensions definition into that local function.
