### ISSUE TITLE
Exception introduced by updateLastVisit() when in search context

### ISSUE THREAD

**Issue by bic-ed** [zenphoto/zenphoto#1276]
If `zenphoto_search_params` cookie is present, a fake `$_zp_loggedin` is created to check if the album is within the search context:
https://github.com/zenphoto/zenphoto/blob/082fa516b052ecc356edc50a356914f48de3a054/zp-core/functions.php#L942
hence updateLastVisit() is called on a non existing `$_zp_current_admin_obj`
https://github.com/zenphoto/zenphoto/blob/082fa516b052ecc356edc50a356914f48de3a054/zp-core/functions.php#L2366
leading to, from debug log:
` EXCEPTION (0): Call to a member function updateLastVisit() on null in [...]\zp-core\functions.php on line 2366 `

**Note:** I'm not able to reproduce this issue with official themes (i.e. zenpage theme) because for some reasons the `zenphoto_search_params` cookie is immediately deleted after displaying the search results. On the other end, once the cookie is deleted the search context is not preserved anymore, tush it's impossible to navigate properly between search results. Every image opened from search results is displayed in its own album. I don't know if this is an intended behavior or not, but I think to remember that it was not so with earlier versions of Zenphoto. 

I've noticed this issue because I use a custom theme that preserves the search cookie when opening an image from search results.

**Comment by acrylian** [comment]
I never saw this issue even with some custom site themes I created incl. our own site's. `zenphoto_search_params` stores the most recent search request. The search cookies are to keep the search context if you are within results and are not really related to being loggedin.

> If zenphoto_search_params cookie is present, a fake $_zp_loggedin is created to check if the album is within the search context:

I did not know this indeed…I expected $_zp_loggedin to be consequently false if not logged in. Thus there is a simple check only… Usual drawback of globals that you don't always easily find where and when they are actually set to what… I have added an additional check if a user object actually exists. Please try if that works for you.

**Comment by bic-ed** [comment]
With the additional check the exception is of course gone. Perhaps it works also with the latter condition alone:
`if($_zp_current_admin_obj) ` 

I know that `zenphoto_search_params` stores the most recent search request, by the way, I've reported the line ` $_zp_loggedin = $_zp_loggedin | VIEW_ALL_RIGHTS; ` because I made a test with that line commented out and the exception was gone too. So if the search cookie is present `$_zp_loggedin` (and `zp_loggedin()` function return value also) is/are not zero, null, false or whatever anymore, even if user is not logged in. When I console log `$_zp_loggedin` before the exception it has the value of 1792.

**Comment by acrylian** [comment]
> With the additional check the exception is of course gone. Perhaps it works also with the latter condition alone:
if($_zp_current_admin_obj)

That should work, too. I'll leave the double check for now as it should not hurt either ;-) I see that $_zp_loggedin may not be "false" because of the rights constant. Didn't not expect that we have that condition actually. Lots of old code and I surely don't know everything ;-)

**Comment by bic-ed** [comment]
Last thing:
> I never saw this issue even with some custom site themes I created incl. our own site's.

Keep in mind that if `Do not return album matches` is checked in search options you don't get the issue either, because that $_zp_loggedin manipulation happens in album search routine.
