### ISSUE TITLE
authorize lang attribute

### ISSUE THREAD

**Issue by RolandTi** [zenphoto/zenphoto#1277]
Hello,
by default you can't specify lang attribute to a paragraph. Zenphoto will cut it everytime you save.
Maybe the default install could add `p => (class=>() id=>() style=>() lang=>())` (and the same for html tag using lang attribute).

**Comment by acrylian** [comment]
The option is editable for any extra attribute you may need for this reason and there are certailnly more we don't cover by default. Sure, we can add that to the defaults. Although in "normal usage" you don't really need it as a site is normally in a single language at the time even in multilingual mode. A main language attribute is already set on the HTML element (if the theme used is setup correctly). I guess your use case is to use to mix different languages in one text?

**Comment by RolandTi** [comment]
Yes like blockquote / cite or resume in english. But I understand you can't add every attributes. Maybe a solution should authorize administrator to use any html element ? But I'm maybe missing the point ^^' Thanks anyway !

**Comment by acrylian** [comment]
> Maybe a solution should authorize administrator to use any html element ?

This setting is also used for various other filtering occasions and not only on the backend when entering text. I think we cover all elements you might need for actual text editing. If you use TinyMCE it also does its own filtering additionally.
