### ISSUE TITLE
themes editor don't work

### ISSUE THREAD

**Issue by Sunvulle** [zenphoto/zenphoto#1278]
When I want to edit, page is blank, I have zenphoto 1.5.7

**Comment by acrylian** [comment]
As mentioned on the forum install the support build/1.5.8b or wait until the final release.

**Comment by Sunvulle** [comment]
Where can I find it? I did already a search

**Comment by acrylian** [comment]
Right on the homepage on the right from the download buttons where it reads "Support build".
