### ISSUE TITLE
Bug in slideshow2

### ISSUE THREAD

**Issue by michael-selig** [zenphoto/zenphoto#1279]
This error occurs when going into Options > Theme for certain themes such as zpbase using slideshow2:

`Call to undefined function getCurrentTheme() in ..../zp-core/zp-extensions/slideshow2.php on line 487`

and most of the options do not appear.

I fixed this by replacing line 487 with:
```
global $_zp_gallery;
$theme = $_zp_gallery->getCurrentTheme();
```
I hope that this is the correct fix!

**Comment by acrylian** [comment]
Thanks, seems that is the right fix.
