### ISSUE TITLE
Empty results for comments feed

### ISSUE THREAD

**Issue by bic-ed** [zenphoto/zenphoto#1280]
Latest comments are always returning an empty feed.
I guess the problem is here somehow, because `$this->options['type']` returns **_image, album_**, etc and not **_images, albums_**, etc and furthermore _**gallery**_ is missing at all.
https://github.com/zenphoto/zenphoto/blob/a0b6622cab5bf2f1a21d320156bf462cb1f424de/zp-core/class-feed.php#L289

On the other hand, if I try to change the above, removing the _**s**_, I get of course a fatal error here:
https://github.com/zenphoto/zenphoto/blob/a0b6622cab5bf2f1a21d320156bf462cb1f424de/zp-core/class-feed.php#L305

So I'm not able to easily figure out a solution

**Comment by acrylian** [comment]
I have not got time to test myself. But you need to enable the RSS plugin to actually get a feed and the commentform also should be enabled.

**Comment by bic-ed** [comment]
Of course they have both beeb enabled. I've tested different rss links also, no one works for comments. Actually I don't use rss feeds myself, I was testing them just to add rss links to multiverse theme, but I'll try to look for a fix anyway if nobody else can do it easily.

**Comment by acrylian** [comment]
Just wanted to be sure… I have just tested and can reproduce that the comments feed seems to be broken. (btw, I don't really use comments myself ;-))

**Comment by bic-ed** [comment]
As a hint I can confirm, after some more tests, that the issue floats around the two functions quoted in the first comment, because of the ambiguity between _**type**_ and _**table names**_. But there is something else wrong somewhere, since if I skip validation on line 293 and add the missing _**s**_ to table names, I get the proper feed for a single image comments but not for a single page comments.
I'll try to find a proper fix, but I'm not sure if I'll be able to and when...

**Comment by acrylian** [comment]
Thanks for your tests. I don't think it is the type as that is quite old. There had been some light restructuring in the RSS plugin if I recall correctly some time ago that might have broken it here accidentally. it works for the general other types. I will look at it as soon as I can later today.

**Comment by bic-ed** [comment]
Ok, then just keep in mind that restructuring also involved the core file `class-feed.php` as you probably know better than me.

**Comment by acrylian** [comment]
Please try the fix that seems to work for me.

**Comment by bic-ed** [comment]
I'm afraid it's not enough. Your fix works to shows a feed with latest comments from all the site of course, but not for latest comments on a single image, new, page or album. The RSS link placed under the comment form was originally meant to return a feed with new comments on the specific image, page, new or album where the form is presented. Now it also returns a feed with comments from all over the site.

I still guess that there is something to do on the functions I mentioned when opened this issue, and perhaps somewhere else too that I I'm not able to figure out so far.

**Comment by acrylian** [comment]
Okay, that was what Fred and I came up quickly. We'll review again and I repopen this.

**Comment by acrylian** [comment]
Just tried and the image feed does work for me, sort of. Strange is that it also lists the comment of it's album feed which it should not do.

**Comment by bic-ed** [comment]
Yes, it works for me too but like I said listing the comment from all over the site (not only from album)

**Comment by bic-ed** [comment]
While I was there, I noticed that the RSS link under the comment form is displayed even if comments are disabled for an item, that is a nonsense I suppose, so I'm creating a pull request to change that behavior.

**Comment by acrylian** [comment]
Please wait with any pull requerst as I am working on this area right now. That leads to mismatch issues unnecessarily.

Well, that is actually correct. Closing comments means no new are possible but existing are still shown. RSS has to be disable on the rss plugin.

**Comment by bic-ed** [comment]
Ok, but that can be easily done in `comment_form.php` also, without affecting anything of what you are working on right now. Perhaps it's even less likely to create problems elsewhere.

**Comment by bic-ed** [comment]
Let me know if you want to see that pull request. You can always reject it.

**Comment by bic-ed** [comment]
> 
> 
> > of the ambiguity between type and table names.
> 
> And you were correct here. RSS had a lot inconsistent parameter query namings and indeed type and table are connected which they should not have been probably to avoid these kind of issues. Well, 10+ years grown stuff…

Aaah! Thanks for looking on it carefully!

**Comment by acrylian** [comment]
I think it is actually fine as it is…

But I noticed that the "gallery" comments feed option does the same as "all". Again inconsistent naming as "gallery" is a term for images and albums but actually we use "gallery" to refer to the whole site including news and pages if available as well…

**Comment by bic-ed** [comment]
> 
> 
> I think it is actually fine as it is…

 Sorry I didn't get it then when you said

> Well, that is actually correct. Closing comments means no new are possible but existing are still shown. RSS has to be disable on the rss plugin.

I'm not sure. Of course existing comments are still shown, but what's the point in subscribing a comment feed on a single item where nothing new is going to happen? Then is probably better to have an RSS link for comments from all over the site, that is not the reason why that item based link is there. Anyway I don't care because like I said I don't use feed on my own website. Just saying.

> But I noticed that the "gallery" comments feed option does the same as "all"(getLatestComments does not the a "gallery" option at al. but the base class does.). Again inconsistent naming as "gallery" is a term for images and albums but actually we use "gallery" to refer to the whole site including news and pages if available as well…

I'm sorry to be pretty helpless here, like you said 10+ years of growing stuff. I'm quite happy to have been able of providing some hints. ;-)

**Comment by acrylian** [comment]
> I'm not sure. Of course existing comments are still shown, but what's the point in subscribing a comment feed on a single item where nothing new is going to happen? 

Well, they could be temporarily closed for moderation or something only. So it might make sense. We really have it divided into separate plugins.

Meanwhile I hope I found it, please try.

**Comment by acrylian** [comment]
But thinking again about it I think you are actually right. If closed they subscribe link should not be shown… Fairly easy change as far as I can see. I will add that once you confirmed the fix hopefully…

**Comment by bic-ed** [comment]
> Meanwhile I hope I found it, please try.


Well, it works if the item is an album or an image, it doesn't if the item is a page or a news. Sorry :-(
Same strange behavior that I experimented this morning making some simple tests 

>  ... But there is something else wrong somewhere, since if I skip validation on line 293 and add the missing s to table names, I get the proper feed for a single image comments but not for a single page comments.

**Comment by bic-ed** [comment]
> 
> 
> But thinking again about it I think you are actually right. If closed they subscribe link should not be shown… Fairly easy change as far as I can see. I will add that once you confirmed the fix hopefully…

I'm ready with that, look at the pull request and eventually reject it or change it as you wish.

**Comment by acrylian** [comment]
Ah, didn't test Zenpage items I admit as it was the same code wise actually. Will dig again then…

Thanks, saw the PR. We'll see if the pull request still can be merged when this is fixed ;-)

**Comment by bic-ed** [comment]
And an unwanted commit appeared in my pull request too, I'm wandering what it is. So I'll close it and open another one later.

**Comment by acrylian** [comment]
No problem, I will just take care of that addition later on, no need for a new pull request.

I just tested. News article feed does work for me but page does not. 

But while looking I found that getLatestCommens() allows setting a number of feed items to get  and it's even set on the call using the class methodt getComments(). But actually wrong because that does not even support that…

**Comment by bic-ed** [comment]
> 
> 
> I just tested. News article feed does work for me but page does not.

You are right, it works for news article here too. Before I tested the wrong article by mistake (empty comments)

**Comment by acrylian** [comment]
Pages do now work as well, one missed table name vs comment feed type name only…  I noticed that my RSS feed programm does some internal caching (the RSS cache in ZP is off here) so sometime I have to newley subscribe to see a change.

**Comment by acrylian** [comment]
I meant please try the fix I committed ;-)

**Comment by bic-ed** [comment]
> I think it is actually fine as it is…
> 
> But I noticed that the "gallery" comments feed option does the same as "all"(getLatestComments does not the a "gallery" option at al. but the base class does.). Again inconsistent naming as "gallery" is a term for images and albums but actually we use "gallery" to refer to the whole site including news and pages if available as well…



>  I noticed that my RSS feed programm does some internal caching (the RSS cache in ZP is off here) so sometime I have to newley subscribe to see a change.

Opera does the same, that's why I'm testing the raw pages in Firefox. 
I'll test the new fix asap, at the moment I'm coding a pizza dinner for my sons. Sorry :)

**Comment by acrylian** [comment]
> I'll test the new fix asap, at the moment I'm coding a pizza dinner for my sons. Sorry :)

No problem, that's way more fun to code ;-)

I am using a specific RSS program named ViennaRSS (Mac only). And generally all browsers have quite persistent caches nowadays, quite annoying,

**Comment by bic-ed** [comment]
Everything is working as expected now. Tanks!

PS
My pizza was very good too. :-)

**Comment by acrylian** [comment]
Great, will look at the RSS link detail later today.

**Comment by bic-ed** [comment]
Ok, I might suggest to keep the RSS link inside `div#commentcontent`, like in my yesterday's aborted pull request, so that it's easier to keep things together for styling. Even though this can affect existing themes in some way, so I understand if you decide otherwise.

**Comment by acrylian** [comment]
Yep, did it that way.
