### ISSUE TITLE
config file value for mysql_prefix is incorrectly changed to 'zp_' if it is set and empty

### ISSUE THREAD

**Issue by djerius** [zenphoto/zenphoto#1284]
Commit e306a2e9cc5aa0af64f9924ad60cc5302b7b5f08 inserts default values into `$_zp_conf_vars` for keys which are either not set, or,  set and empty.

However, it is valid for the `mysql_prefix` value to be set and empty, as that indicates that a `mysql_prefix` is not required.

The new behavior changes an empty value for  `mysql_prefix` to `zp_`, which breaks existing installations which don't have a prefix, leading to errors such as:
```
  USER ERROR: MySQLi Error: ( SHOW FULL COLUMNS FROM `[prefix]albums` ) failed. MySQLi returned the error Table 'sqf_zenphoto.zp_albums' doesn't exist in /var/www/zenphoto/zp-core/functions-db-MySQLi
.php on line 95
  trigger_error called from query (functions-db-MySQLi.php [95])
    from db_show (functions-db-MySQLi.php [321])
      from db_list_fields (functions-db-MySQLi.php [332])
        from lookupSortKey (functions.php [287])
          from Gallery->getAlbumSortKey (class-gallery.php [153])
            from Gallery->getAlbums (class-gallery.php [202])
              from admin-users.php [527]
```

**Comment by acrylian** [comment]
Thanks, that is indeed incorrect.
