### ISSUE TITLE
Database server outage results in Zenphoto reinstalation

### ISSUE THREAD

**Issue by wongm** [zenphoto/zenphoto#1286]
I'm running Zenphoto 1.5.7 with MySQL as the database server.

If the database server goes down, any attempt to load my Zenphoto gallery results in a redirect to the 'Zenphoto reinstall' page at `/zp-core/setup/index.php?autorun=admin` , with "an unable to connect to database" message.

This redirect occurs even if a user is not logged into Zenphoto.
Unauthenticated user have the option to enter new database server name / username / password / database name / database prefix.
This overwrites the existing values in `zp-data\zenphoto.cfg.php` file, meaning that even if the database server comes back online,  Zenphoto will be non-functional until the correct values are entered.

Is this a scenario that you have considered before?

I'm considering putting a patch together to try and prevent this 'Zenphoto reinstall' redirect from happening.
I forever it would need logic to ensure that out of the box install flow on a new server still works as expected.

**Comment by wongm** [comment]
My current hack is to replace this redirect to the setup page:

\zp-core\functions-basic.php

```
if (!$data && OFFSET_PATH != 2) {
	require_once(dirname(__FILE__) . '/reconfigure.php');
	reconfigureAction(3);
}
```

To return a HTTP 500.

```
	header("HTTP/1.1 500 Internal Server Error");
	echo "DATEBASE CONNECTION FAILURE";
	die();
```

**Comment by acrylian** [comment]
I have not encountered this scenario.

> Unauthenticated user have the option to enter new database server name / username / password / database name / database prefix. This overwrites the existing values in zp-data\zenphoto.cfg.php file, meaning that even if the database server comes back online, Zenphoto will be non-functional until the correct values are entered.

The general scenario you describe is generally the fresh install where naturally no user to authenticate exists yet. However on existing installs this should not happen. So your fix may prevent that from happening. But I can't say without actually looking at it which I haven't yet.

**Comment by acrylian** [comment]
I had only short time to review but I don't think the fix is correct. This happens if there is incorrect or no mysql data entered at all. I tried to fake "mysql going away" by having `db_connect()` from the mysqli function set with

     $_zp_DB_connection = false;
     return false;

on line 27 before it can establish a connection. Being loggedin as admin I did only get a truncated setup page and no mysql data form. Getting that form unless its a fresh install seems to be the actual issue here. I did naturally test 1.5.8b and not 1.5.7. Not sure if that makes any difference but perhaps.

**Comment by wongm** [comment]
I've done some more testing, following the `mysqli_connect`  call I look at value returned by `mysqli_connect_errno` for various scenarios.

- mysql_user or mysql_pass incorrect = 1045
- mysql_database icorrect = 1049
- mysql_hostor mysql_port incorrect = 2002
- server down = 2002

So can't determine from code whether server is down, or incorrect config values.

I'm thinking Zenphoto could write a flag file system after successful database connection established. 
Then if Zenphoto has trouble connecting to database, look for the flag. If flag exists, treat as server outage. If no flag, send user to the setup page.
This would ensure out of the box install flow on a new server still works as expected.
However introduced complexity if MySql server details changed, user would not be automatically prompted to update settings via Zenphoto web UI. User would need to update settings in the config file, or navigate to setup page manually.

**Comment by wongm** [comment]
My testing is based on shutting down the mysql server on my development machine and trying to access Zenphoto.  Changing the  `$_zp_DB_connection` value in code doesn't appear to be a full simulation of the problem I'm seeing.

**Comment by acrylian** [comment]
Probably it would help if db_connect() returns something we can determine from what happend instead of just false. But we need a general solution as it also has to cover PDO and MySQL (although the latter is already deprecated by PHP and by us). And I just assume those might not use the same error codes (haven't looked yet)

**Comment by acrylian** [comment]
Sorry for the later reply. Actually @fretzl and me did test on our local MAMP installs and  turned off MySQL via the console. Sadly we were not able to reproduce the form appearing or the config file being cleared. It does not matter if on frontend with `autorun=gallery` or `autorun=admin`.

This is what we got to see and then it stop without happening anything else. Besides some debug notes about mysql not working.

![Bildschirmfoto 2021-01-25 um 17 48 59](https://user-images.githubusercontent.com/2474309/105748365-5694ba80-5f42-11eb-8ec2-c606ce299a65.jpg)
