### ISSUE TITLE
docs.zenphoto.org - > a minor correction

### ISSUE THREAD

**Issue by RolandTi** [zenphoto/zenphoto#1290]
Hello ! 
There is a minor "cell" error in zenphoto doc,
[https://docs.zenphoto.org/1.5.x/function-printAlbumMenu.html](https://docs.zenphoto.org/1.5.x/function-printAlbumMenu.html
)

After the line *$showsubs = NULL*, descriptions aren't in the good cell.

![Capture d’écran 2021-02-26 à 09 16 51](https://user-images.githubusercontent.com/28786873/109274095-60e0f780-7813-11eb-96c5-7136bf4dafe4.png)

**Comment by acrylian** [comment]
Probably typos in the source code documentation as the doc is generated automatically from that. We'll take a look.
