### ISSUE TITLE
Reinstall page doesn't continue or offer buttons

### ISSUE THREAD

**Issue by Espionage724** [zenphoto/zenphoto#1293]
![image](https://user-images.githubusercontent.com/2474309/105748365-5694ba80-5f42-11eb-8ec2-c606ce299a65.jpg)

Image came from https://github.com/zenphoto/zenphoto/issues/1286#issuecomment-767017157, but it's the exact same thing I'm getting. I'm not certain how to debug this.

I'm running from master branch with the latest https://github.com/zenphoto/zenphoto/commit/1b6a92f6b86586b8183a9f306e13fd8385732113 commit.

**Comment by acrylian** [comment]
What do the logs say?

**Comment by Espionage724** [comment]
On the Debug log, it says:

` EXCEPTION (0): Call to undefined method setup::secureServer() in /srv/www/media/zp-core/setup/index.php on line 623 `

Nothing on the Setup log

**Comment by acrylian** [comment]
Okay, that is the cause  and known but this should also be fixed in the latest master. Are you sure you are really using it?

**Comment by Espionage724** [comment]
I had to do a `git reset --hard` to pull in the latest master, but after doing that, the set-up page seems fine now.
