### ISSUE TITLE
Matomo plugin admin tracking

### ISSUE THREAD

**Issue by tiltX** [zenphoto/zenphoto#1294]
I think the Matomo plugin's admin tracking option is the opposite of what it's supposed to do. When the checkbox to track admin users is disabled, the Matomo code block shows up anyways. But when I **enable** the checkbox there's no Matomo code block in the html.

In matomo.php, there's this:
```
if (!getOption('matomo_admintracking') || !zp_loggedin(ADMIN_RIGHTS)) {
	zp_register_filter('theme_body_close', 'matomoStats::script');
}
```
Isn't the first "!" wrong here? The backwards-compatible fix is probably to rename the option's label to say "disable admin tracking".

**Comment by acrylian** [comment]
Indeed, it rather should be `if (getOption('matomo_admintracking') || !zp_loggedin(ADMIN_RIGHTS)) {?

**Comment by acrylian** [comment]
Please try the fix.

**Comment by tiltX** [comment]
thank you! it works.
