### ISSUE TITLE
If you move or rename your site, setup will not edit or warn you about your existing robots.txt file

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1297]
If you move or rename your Zenphoto folder, and rerun setup, it will not edit or replace your existing robots.txt file, leaving you with a robots.txt that is no longer valid. Setup should edit or replace the zenphoto values in the file. If you are worried about making changes to a file that someone might have customized, then setup should at least warn the user that there is an existing robots.txt file. Currently in 1.5.8RC it will give a green notice that a robots.txt file exists, but you have to expand the notice to read it, and it is easy to glance over. It does not warn you about any issues that might happen if you are moving or renaming your site, it only says, “Setup did not create a _robots.txt_ file because one already exists.”

![Zenphoto setup - robots txt notice](https://user-images.githubusercontent.com/82089671/114823476-72a53c80-9d78-11eb-8b95-468ca959d7ac.png)

It would be nice to change this to a warning that states something like-

“A _robots.txt_ file already exists. If you are moving or renaming your site, you will need to edit the referenced folders in the file to reflect the changes to your site, or else the file will no longer work with search engines. An example file can be found at zp-core/example_robots.txt.”

**Comment by acrylian** [comment]
I agree we should not hide notices in general.

**Comment by acrylian** [comment]
Notices etc are now not hidden anymore. We also added an additional sentence on the robots.txt.
