### ISSUE TITLE
Bar graph size broken for "Albums - most viewed images" in Gallery Statistics

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1299]
In Gallery Statistics for "Albums - most viewed images" the bar graph sizes are broken and will set widths over 100%.

![admin overview-statistics - Albums - most viewed images - bar graph size broken](https://user-images.githubusercontent.com/82089671/117120814-a86e8d00-ad48-11eb-9479-8119c998ebf0.png)

For example-
`<div class="statistic_bargraph" style="width: 219%"></div>`

It looks like the issue might be on line 305 of /zp-core/utilities/gallery_statistics.php

https://github.com/zenphoto/zenphoto/blob/9a400b554a95540268f4e133535ea8b1668bfaf9/zp-core/utilities/gallery_statistics.php#L305

It is the only $barsize that for some reason has a "- 10" on the end.

This is in both 1.5.7 and 1.5.8RC.

**Comment by acrylian** [comment]
I had seen that once as well but could see why that is so. Will take another look.

**Comment by acrylian** [comment]
The maxvalue was calculated on the wrong value. I removed the "-10" as well. Please try.

**Comment by JesseHC** [comment]
It appears to be working, though on my 1.5.8 local test server I'm having issues getting the statistics to update, so I don't have that many examples showing. I'll let you know if I come across any problems later.

Thanks for the fix!

**Comment by acrylian** [comment]
Thanks. I tried it with a manually raised really high value compared to other to really be sure it does not exceed then. I'll close this for now but feel free to reopen should it not be fixed.
