### ISSUE TITLE
Problem with French locale file with v1.5.8

### ISSUE THREAD

**Issue by yohan9999** [zenphoto/zenphoto#1300]
Hi,

I just updated my Zenphoto gallery from 1.5.7 to 1.5.8.

There is a problem with the fr_FR locale. Some "msgid" do not match the one in the php file.

For example in admin-edit.php :

v. 1.5.7 gettext('View')
v. 1.5.8 gettext('View image') but we still have msgid = View in the locale file.

Thanks.

**Comment by acrylian** [comment]
That's something @vincent3569 would have to look into as he sadly didn't update with all latest changes.
