### ISSUE TITLE
Fatal error from incorrect file name casing: ZenPhoto can't be installed

### ISSUE THREAD

**Issue by sam-19** [zenphoto/zenphoto#1303]
Hey,

I just whipped up a ZenPhoto docker image based on php:apache template, but ran into some major issues. Everything installs fine, but the server gives a 500 error when trying to run setup because the MySQLi functions script is reference with incorrect casing (file name casing on unix matters). The MySQLi functions are in a file called `/zp-core/functions-db-MySQLi.php`, but the basic functions script converts all database script file names to lower case here:
https://github.com/zenphoto/zenphoto/blob/35ab5d477fcab7265d3f0f529c2c8cb559cdb1f9/zp-core/functions-basic.php#L190

This will, of course, result in a fatal error when the requested file cannot be found.

I can get rid of this error by copying the file (and actually two other similarly named files)

`functions-db-MySQLi.php -> functions-db-mysqli.php`
`functions-db-PDO_MySQL.php -> functions-db-pdo_mysql.php`
`functions-db_NULL.php -> functions-db_null.php`

but then I run into warnings when setting up the server:

```
Perhaps there was a problem with the upload. This may not be critical at all as perhaps just the file times may be off compared to other files. You should check the following files:

    zp-core/functions-db_null.php
    zp-core/functions-db-mysqli.php
    zp-core/functions-db-pdo_mysql.php
```
```
You should remove the following files:

    zp-core/functions-db-MySQLi.php
    zp-core/functions-db-PDO_MySQL.php
    zp-core/functions-db_NULL.php
```
What actually should happen during the setup? Should the files with uppercase letters be renamed to lowercase versions at some point and if so, why does the setup script look for the lower case files? The installer does find something wrong with the files if they are merely copied, which makes me think they are supposed to be modified somehow during the install process, or maybe it is just that file time thing.

Removing the extra files during the setup did allow me to complete the setup and everything seems to be running okay. I get the feeling I did something wrong given that I can't find any mention of this (breaking) issue from before. But here you have it in case there really is a real issue behind it.

**Comment by acrylian** [comment]
Setup does not rename files, it warns if files of the package don't match the internal package catalogue. 

The lowercase files are new in 1.6a on GitHub but are not part of the official 1.5.9 release. I suspect you have mixed up both somehow.

**Comment by sam-19** [comment]
Thank you for your reply! My version seems to be 1.6a, but I don't think there is any way I could have mixed them up. The Dockerfile script simply downloads the source from https://api.github.com/repos/zenphoto/zenphoto/tarball/master (as that is the only branch available) and unpacks it, adding nothing extra. It always does this on a clean install as well, as docker containers do. So I suspect this may be a problem in your WIP branch.

**Comment by acrylian** [comment]
Yes, the master is always work in progress of the next release. The only thing I could think of is that you perphaps fetched files between commits and therefore didn't get all changes correctly.

Every stable release has an "release" on Github: 
https://github.com/zenphoto/zenphoto/releases 

itHub has a API to fetch these there you might want to use instead of just fetching the master: https://docs.github.com/en/rest/reference/repos#releases

**Comment by sam-19** [comment]
Okay, maybe that was it :) I could try pulling the latest release using that API, although I  don't completely agree with their philosophy of sorting the releases by latest commit timestamp. Even so, it should be less risky than pulling an incomplete dev version. Thanks for the tip!

**Comment by acrylian** [comment]
Not sure what you mean. The entry has a "created_at"" and "published_at" field. Actually we define what a release is so that package should match. Afterrall that is exactly the package you download manually via our site otherwise.

**Comment by sam-19** [comment]
Oh right, I misunderstood it! So that should be the best way to go about it. Thanks!
