### ISSUE TITLE
OpenGraph and Twitter Card image thumbnails for movie files with sidecar images not displayed

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1304]
html_meta_tags does not load the sidecar image _(if available)_ as a thumbnail for mp4 files for og:image and twitter:image. Instead it puts the mp4 file where the image should go, causing image thumbnails not to load.

This can be tested by turning on “OpenGraph (og:)” or “twitter:card” in html_meta_tags, then looking at the source code for video files with matching sidecar images, or by checking here-

https://www.opengraph.xyz/

or here for the official sites-

https://developers.facebook.com/tools/debug/
https://cards-dev.twitter.com/validator

For a cached image file I will get something like-
`<meta property="og:image" content="https://www.domain.com/zenphoto/cache/2021/imagename_w473_h630.jpg?cached=[long number]">`

For an mp4 file I will get something like-
`<meta property="og:image" content="https://www.domain.com/zenphoto/zp-core/i.php?a=Videos&amp;i=videoname.mp4&amp;w=630&amp;h=630&amp;cw=0&amp;ch=0&amp;q=85&amp;check=[long string]“>`

This also affects links posted on other sites like Discord and LinkedIn.

**Comment by JesseHC** [comment]
I should add that I've noticed this in at least 1.5.7 through 1.5.9.

**Comment by acrylian** [comment]
Thanks, I can reproduce that. But why do you report this now when you already noticed it in 1.5.7?

**Comment by JesseHC** [comment]
> Thanks, I can reproduce that. But why do you report this now when you already noticed it in 1.5.7?

I’m testing a bunch of different issues right now, and only submitting after I’ve had a chance to really troubleshoot them, to make sure the issue is not on my end.

Plus, 1.5.7 was only a little over a month ago.

**Comment by JesseHC** [comment]
Thanks for the fix!

**Comment by acrylian** [comment]
> I’m testing a bunch of different issues right now, and only submitting after I’ve had a chance to really troubleshoot them, to make sure the issue is not on my end.

Okay, hopefully you didn't find too much…

> Plus, 1.5.7 was only a little over a month ago.

True, it was ;-)
