### ISSUE TITLE
Suggestion: Disable ability for admins to run upgrade scripts

### ISSUE THREAD

**Issue by SubJunk** [zenphoto/zenphoto#1313]
There is a user flow that AFAICT leads any admin with access to the Overview tab to be able to run upgrade scripts, and is more discoverable if any `zp-core` file is updated:

If I update a zp-core file, all users see the message at the top of the screen like `a file was updated, it is recommended to run the setup scripts` which they can click to start the update. If the setup scripts are `protected` (renamed to `.xxx`) the user goes to the Overview tab and restores them, then runs the scripts. If the scripts are unprotected, the user does not even need access to the Overview tab.

Use of the `site_upgrade` plugin does not seem to affect this because it only deals with users who are not logged in.

That also means that there is always a time during upgrading where any logged-in user can run the setup scripts, because even if I remove access for all users except me to the Overview tab, I still need to restore the scripts to run them myself, at which point any logged-in user can also run them.

The suggestion is to make a separate user permission for running setup scripts so that it is possible to narrow down the users who can do it, on this page:
![image](https://user-images.githubusercontent.com/584228/150657383-f177c250-c05a-4e3b-8fc1-5fb93d85da3e.png)

Sorry for any incorrect statements I may have made, this is all AFAIK.

**Comment by acrylian** [comment]
Actually only users with admin rights can bypass the site_upgrade and run setup scripts. Normal users should not have full admin rights. Consider giving them only the rights they really need. If they must have admin rights or want them because they are the owner, they need to be educated  and learn about this things IMHO.

**Comment by acrylian** [comment]
All users will see the upgrade notices. If they don't have the rights to run setup it suggest to contact the site administrator about this because the upgrade may be important.

**Comment by sbillard** [comment]
It should be a requirement that a user have full admin rights to be able to run setup in all cases.

**Comment by acrylian** [comment]
Which it is of course.

**Comment by SubJunk** [comment]
You're right, I'm mistaken about this. I have some old code running in some cases and got confused. I can't reproduce on 1.5.9.
Thanks for explaining.

**Comment by acrylian** [comment]
Nevertheless we will move the site_upgrade functionality to core and make setup enable iit automatically.
