### ISSUE TITLE
Bug: Logout delayed

### ISSUE THREAD

**Issue by SubJunk** [zenphoto/zenphoto#1314]
On 1.5.9 I logged out and was redirected to this page which showed I was still logged in. On the next page load I was logged out so it seems to be a race-condition.

I couldn't reproduce it again but wanted to document it while I had it.

![image](https://user-images.githubusercontent.com/584228/150698355-82b4e628-b7da-44fa-ac40-cb93d5aff526.png)

**Comment by sbillard** [comment]
The URL showing in your image is to the index.php page. Is the page showing from the front-end of your theme?

There can be no race condition from the zenphoto code on logging out as the auth cookie is deleted by the script before it redirects. But there can well be caching issues where the page being served is one that was captured when you were logged in.

**Comment by SubJunk** [comment]
It's a vanilla 1.5.9 install with the built-in themes

**Comment by acrylian** [comment]
I have seen this in the past but not for a long time. Sometimes the overly persistent (aggressive) caching browser do nowadays play tricks on your. Try if a reload clears it.

**Comment by SubJunk** [comment]
If it happens again with the console open I’ll check if it was loaded from a cache

**Comment by acrylian** [comment]
I think we even added a header to force prevent loading from cache some time. But the browser cache is constantly drving me mad especially in Chrome where even several manually clearings don't actually clear it (really great fun if you trying to fix CSS or JS things…).

**Comment by acrylian** [comment]
Btw, please always test with 1.6a specially as there are quite some (internal) changes meanwhile.
