### ISSUE TITLE
Zenphoto 1.6a: Navigation in dynamic albums does not work properly

### ISSUE THREAD

**Issue by sphoto** [zenphoto/zenphoto#1317]
I made a dynamic album from a tag. It contains just 5 images. When I click on an image thumb, it opens the photo correctly (image page), but the navigation to the previous/next image is somehow broken. The first image shows just a prev button, the fourth shows no buttons etc. On my personal theme where I use `imageNumber()` to get an output like "image xx of xx", it shows numbers higher than 5 (e.g. "image 8 of 5"). I first tought this could be caused by my personal theme, but the same happend on the Basic theme. 

If you can't reproduce this issue, I could send you the link to my development installation.

**Comment by acrylian** [comment]
We will try to reproduce it.

**Comment by bic-ed** [comment]
It is there since v1.5.9. I'm still on v1.5.8 on my production site and the issue was not present yet. I guess it was introduced in this commit cc29ae49f07409955ee7bb65eb9297a201bd9820 or the following 2b93e7d0dffd43e48c537b0efdc9d5cbe5e1615c

**Comment by acrylian** [comment]
We did extensive work and tests on fixing non correct sort order e in 1.5.9 with those and especially dynamic albums since they quite different. The issue is somewhat related to that. We missed this side effect apparently. 

Actually tests by @fretzl so far seem to indicate that it depends on what you sort by. If you have a field that is really unique like ID seems to work. But if you use a field that may not be set for all or at least many items or may have the same value (like latestupdate date or similar) it breaks. Actually the sort order then is baiscally random and change constantly since there is nothing to really sort by. Which is normal behaviour for mysql or PHP array sorting. 

We're on it, sadly I hadn't time to dig into it yet.

**Comment by acrylian** [comment]
There is a possible fix in 1.6a now. Embarrassingly  a hardcode test value was forgotten so for dynamic albums the wrong album was used for calculation.  Let me know if that fixes it for you, too.

**Comment by bic-ed** [comment]
Seems fine to me, though I was unable to run setup (upgrading from 1.5.9 to master).

**Comment by bic-ed** [comment]
Nevermind, it was the old known problem whit setup script not updated

**Comment by acrylian** [comment]
Thanks. If you upload and replace the zp-core folder this really cannot happen. But if really  that would be another issue.

**Comment by bic-ed** [comment]
I know, but when I don't update for a while then I can forget. We discussed this some time ago, if one upload the new version over the old one, setup scripts are not overwritten if they are in "protected state", so when unprotecting them the old scripts replace the new ones.

**Comment by acrylian** [comment]
> We discussed this some time ago, if one upload the new version over the old one, setup scripts are not overwritten if they are in "protected state", so when unprotecting them the old scripts replace the new ones.

I really believe this is a setting of your FTP client, it should replace the entire folder and not try to add changes. I know because mine always asks about that. And we updated our instructions to make that clear as well. I think exactly because of our discussion.

**Comment by sphoto** [comment]
@acrylian: You fix works perfectly, thank you!

**Comment by acrylian** [comment]
@sphoto Thanks, awesome!

**Comment by bic-ed** [comment]
> > We discussed this some time ago, if one upload the new version over the old one, setup scripts are not overwritten if they are in "protected state", so when unprotecting them the old scripts replace the new ones.
> 
> I really believe this is a setting of your FTP client, it should replace the entire folder and not try to add changes. I know because mine always asks about that. And we updated our instructions to make that clear as well. I think exactly because of our discussion.

No, it's non my ftp client, but at the same time it's of course my fault not following the updated instruction properly.

The potential misleading behavior preventing the update of setup files remains though, so if you wish we could discuss this further by mail, as I'm totally off topic here, sorry for that.  ;-)

**Comment by acrylian** [comment]
> The potential misleading behavior preventing the update of setup files remains though, so if you wish we could discuss this further by mail, as I'm totally off topic here, sorry for that. ;-)

Sure ;-)
