### ISSUE TITLE
getAlbumPage not updated for the new thumb_transition min & max?

### ISSUE THREAD

**Issue by bic-ed** [zenphoto/zenphoto#1321]
I'm getting a wrong album page for images belonging to albums having subalbums, with the following settings:

albums_per_page: 20
thumb_transition_min: 20
thumb_transition_max: 20

returned page number is one unit greater that the real page.

**Comment by acrylian** [comment]
What is the thumbmail per page option value?

> I'm getting a wrong album page for images belonging to albums having subalbums, with the following settings:

**Comment by acrylian** [comment]
> I'm getting a wrong album page for images belonging to albums having subalbums, with the following settings:
Not sure I understand. The whole transition of course only applies if an album has subalbums and images? Have to review this otherwise.

**Comment by bic-ed** [comment]
Yes, I just wanted to point out that getAlbumPage works fine for albums without subalbums but fails for albums having subalbums, when a transition is involved.

**Comment by acrylian** [comment]
Okay, will try to check that.

**Comment by bic-ed** [comment]
Thanks @acrylian, apparently it's working fine now. Are you planning more editing/tests here or can we close this?

**Comment by acrylian** [comment]
I just kept it open until your confirmation that it is fixed. I will close it. We can re-open any time if we should have missed anything.
