### ISSUE TITLE
Search URLs are missing search terms if using modrewrite

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1323]
I noticed that Zenphoto site search keywords were not showing up in Matomo. The issue is how Zenphoto handles the search page URL results, both with mod rewrite turned on and off, but especially with it turned on.

The issue is that both Google Analytics and Matomo by default look for URL parameters when recording what was searched on a site.

For [Matomo](https://matomo.org/docs/site-search/#tracking-site-search-keywords)-

> “By default, Matomo will read the URL and look for a parameter with any of the following names: q, query, s, search, searchword, k, keyword”

For Google Analytics, [Google lets you put in your own five parameters](https://support.google.com/analytics/answer/1012264?hl=en#Setup)-

> “5. In the Query Parameter field, enter the word or words that designate internal query parameters, such as term,search,query,keywords. Sometimes query parameters are designated by just a letter, such as s or q. Enter up to five parameters, separated by commas.”

Matomo offers an alternative way to track site search using the Javascript trackSiteSearch() function, though I came across @vincent3569 having the [Zenphoto search issue on the Matomo forum](https://forum.matomo.org/t/unable-to-track-site-search/25379), and I’m not sure if they were ever able to get it resolved.

[Google has a suggestion](https://support.google.com/analytics/answer/1012264?hl=en#Post&zippy=%2Cin-this-article) for trying to get around it, but for both Matomo and Google Analytics the solutions are not ideal for an average user trying to get them to work.

I know that in [Zenphoto 1.5.9 and earlier versions](https://docs.zenphoto.org/1.5.x/function-rewriteHandler.html) that search page rewrite rules were located in zenphoto-rewrite.txt, and did the following in Rewrite Rules-

```
#### Rewrite rules for search
      
rewriterule ^page/search/*$
    index.php?p=search [L,QSA] 
rewriterule ^page/archive/*$
    index.php?p=archive [L,QSA] 
rewriterule ^page/archive/(.*)/([0-9]+)/?$
    index.php?p=search&date=$1&page=$2 [L,QSA] 
rewriterule ^page/archive/(.*)/?$
    index.php?p=search&date=$1 [L,QSA] 
rewriterule ^page/search/tags/(.*)/([0-9]+)/?$
    index.php?p=search&searchfields=tags&words=$1&page=$2 [L,QSA] 
rewriterule ^page/search/tags/(.*)/?$
    index.php?p=search&searchfields=tags&words=$1 [L,QSA] 
rewriterule ^page/search/(.*)/([0-9]+)/?$
    index.php?p=search&words=$1&page=$2 [L,QSA] 
rewriterule ^page/search/(.*)/?$
    index.php?p=search&words=$1 [L,QSA] 
```

It looks like in 1.6, the rules are now handled by tokens with options in the rewriteTokens plugin. I will focus on 1.6, since you are currently working on that, but the results are the same.

In 1.6 with mod rewrite turned on you get the following page when doing a search for “test”-
https://domain.com/zenphoto/page/search/

If there are multiple pages and you click on the page 2 link at the bottom you get-
https://domain.com/zenphoto/page/search/test/2/
_(which is at least a little better because you now get the search term in the URL)_

Clicking on the page 1 link to get back to the first page will get you-
https://domain.com/zenphoto/page/search/test/
_(which is better, and at least what the first page should show originally)_

With mod rewrite turned off in 1.6, you get-
https://domain.com/zenphoto/index.php?p=search

Again, no search term in the first page URL.

Clicking on the page numbers at bottom-
Page 2 - https://domain.com/zenphoto/index.php?p=search&words=test&page=2
Page 1 - https://domain.com/zenphoto/index.php?p=search&words=test

I’m sure the answer will be that search works, or that the search_statistics plugin already handles the info that Matomo or other analytics programs would show, or most likely, this is an issue with third-party software and not Zenphoto’s problem. There is a chance, however, to correct this issue so that others do not experience it in the future.

First, the search results URL should always list the search term in it.

Second, it would be nice if the “words” parameter was changed to a more standard version such as one of the five Matomo defaults, like “keyword” or “query” since “search” is already being used on the “p” parameter, and Google lets you set your own parameters.

It would be nice if rewriteTokens gave you the option to turn off search rewrites. In the rewriteTokens plugin, if you try to leave the search* field blank, it will not let you. There appears to be no way to turn off only the search rewrite.

It would also be nice if the option was also under Options-Search, or if there was at least an explanation there about the issue. Say-
_“Search result keywords may not show in analytic programs with mod rewrite turned on, due to them looking for URL parameters such as “?keyword=example“ in the URL by default.”_

If search results were shown as URL parameters, it is possible they might also start to show up in log file analyzers such as Awstats, under Search Keyphrases and Search Keywords, and in Webalizer under Search String, which they currently do not.

**Comment by JesseHC** [comment]
This issue is also related to how tags are currently handled by Zenphoto.

If you use the search box (with mod rewrite turned on) and select a dropdown keyword tag, you only get the generic URL-
https://domain.com/zenphoto/page/search/


However, if you click on a tag link for a person on an image page then you get-
https://domain.com/zenphoto/page/search/tags/%22Name%22/


Also, in search if you click on any image using the basic theme, it takes you to the page but the breadcrumb title at the top disappears and is replaced by a search title that is not helpful-

**Domain.com | Zenphoto | Search | image_name**

This should instead display the regular breadcrumb title links so users can have an idea where the search image came from.

**Comment by acrylian** [comment]
Actually I am not aware that we changed anything explicitly regarding search search from 1.5.9 to 1.6. That generic URL already is in 1.5.9 as well. I agree that we probably should have `s=seachword` in the the URL.  However I do remember a fix regarding modrewrite/non modrewrite links in some 1.5.x release that actually was meant for items URLs not being correct and this may be a nunwanted side effect as search URLs are always with queries. I will review that.

**Comment by acrylian** [comment]
I can confirm that this is an unwanted sideeffect/mistake of tthe modrewrite changes. a function does generate these wring. Thanks for letting us know.

**Comment by acrylian** [comment]
I took the freedom to change the ticket title.

**Comment by acrylian** [comment]
I did investigate a bit. It is in fact this way since way before 1.4.x  because the search form uses POST to submit the data as we otherwise would get a very crowded URL. You cannot really submit a rewritten GET url. On the results it is possible because there is no submitting of course.

Actually we need to do some additional internal redirection for search URL we normally only do for non rewritten URLs . And for search we need to do it on rewritten and non rewritten URLs if we want to have the search query in the URL Have to look into this a bit further.

----

Regaridng the image search breadcrumb. we probably should have both. The search breadrcumb so you know you are looking at search results and the actual album breadcrumb where the image is.

Domain.com | Zenphoto | Search | Parent Albums  | image_name

**Comment by acrylian** [comment]
There is a fix now in 1.6a for the search URL to include the search words. 

Regarding the breadcrumb for images: I did review this and there is an actual logical reason the album(s) of an image are not included.  The search breadcrum only includes what is part of the results. If the image is part of an album that is a result, the album is included. If the image is a direct result the album is not part of the search results and therefore not included.

**Comment by JesseHC** [comment]
I tested it out on the latest 1.6a build and the search terms are now included in the URL with mod rewrite turned on.

For example, if I do a search for “test”, I now get-
https://domain.com/zenphoto/page/search/test/

If I click on the page 2 link-
https://domain.com/zenphoto/page/search/test/2/
If I click back on the page 1 link-
https://domain.com/zenphoto/page/search/test/


So thank you for that. However, that will still not show up in most analytic programs by default, and there is still no way to turn off mod rewrite for just search to fix that.

You still cannot leave the search* entry blank or turn it off in the rewriteTokens plugin. It also shows listed under Development-Tokens-Rewrite Tokens:
`_SEARCH_	page/search `

If I manually turn off mod rewrite for the entire site (which I don't want to do), I get the following when I do a search for “test”-
https://domain.com/zenphoto/index.php?p=search&words=test

Clicking on page 2-
https://domain.com/zenphoto/index.php?p=search&words=test&page=2
Clicking on page 1-
https://domain.com/zenphoto/index.php?p=search&words=test


As you can see, it is still using “words” as the parameter, instead of a standard like “keyword” or “query”, or as you suggested “s”. 

___

For tags, clicking on them with mod rewrite turn on you will get the following URL-
https://domain.com/zenphoto/page/search/tags/%22First+L.%22/

If you turn on the tag_suggest plugin, I noticed a style inconsistency, it will convert all uppercase to lowercase, when they show up in the Tags section or on the pages fine with uppercase characters. The search box will also eliminate the “/tags/“ section.

Clicking on a tag suggestion from the search box-
https://domain.com/zenphoto/page/search/%22first+l.%22/

Ideally, this result would be consistent across the two.


With mod rewrite turned off for the site you get-

Clicking on a tag-
https://domain.com/zenphoto/index.php?p=search&words=%22First+L.%22&searchfields=tags

Clicking on a tag suggestion-
https://domain.com/zenphoto/index.php?p=search&words=%22first+l.%22

___

About the breadcrumbs, there might be some logic to it, but I’m still only going to get confused users that don’t see a way to click into the albums once they’ve found an image. The album right now only shows in the search breadcrumb if the search term is in it, and only that album. None of the other albums in the tree will show.

I like your original solution, show the regular breadcrumb, and then below it the search breadcrumb. The regular breadcrumb at top can exclude the image in it, since it will now show up in the bottom search results. That way it works for everyone.

Example-
Domain.com | Zenphoto | Album1 | Album2
Search – Album (if search term in it) – image_name (if search term in it, or if under Album with search term in it after clicking on it)

The search line can even be styled slightly different to show that it is for search results.

I’ve also noticed a bug with the current breadcrumb. If you click back after clicking on a tag the breadcrumb will change on the regular page to the search one-
Domain.com | Zenphoto | Search | image_name

**Comment by acrylian** [comment]
> So thank you for that. However, that will still not show up in most analytic programs by default, and there is still no way to turn off mod rewrite for just search to fix that.

I don't understand what you mean. The search page is a so called custom theme page technically and its URL is always`/page/<name of the custom page minus .php>` if using modrewrite. That's the same as for a contact page or archive page. Zenpage pages are an exception here. 

`https://domain.com/zenphoto/index.php?p=search&words=test` is the correct URL for a non rewritten page. If the parameter is  "words" does not really matter, this is what we always used for it (The mention of "s" was a confusion on my end with another CMS as I nearly never use non rewritten URLs with ZP so I didn't remember it correctly offhand).

I don't see why any analytics would not recognized any of those URLs.

----

Regarding the breadcrumb:  don't think we will change that. But you can do that on your site's theme yourself if you really need/want it. 

-----

> I’ve also noticed a bug with the current breadcrumb. If you click back after clicking on a tag the breadcrumb will change on the regular page to the search one-

Not sure what you mean.I I tested with the basic theme and on plain tag search results (`page/search/tags/…`) there is no tag in the breadcrumb. You click on "Search" to get back to the  search results.

**Comment by JesseHC** [comment]
> I don't understand what you mean. The search page is a so called custom theme page technically and its URL is always`/page/<name of the custom page minus .php>` if using modrewrite. That's the same as for a contact page or archive page. Zenpage pages are an exception here.
> 
> `https://domain.com/zenphoto/index.php?p=search&words=test` is the correct URL for a non rewritten page. If the parameter is "words" does not really matter, this is what we always used for it. There is no "standard" for query URLs. (The mention of "s" was a confusion on my end with another CMS as I nearly never use non rewritten URLs with ZP so I didn't remember it correctly offhand).
> 
> I don't see why any analytics would not recognized any of those URLs.

As I quoted and linked to the relevant documentation in my original post, analytics programs are looking for search terms following URL parameters, values specifically following these seven entries for Matomo (Google lets you put your own in).

- q
- query
- s
- search
- searchword
- k
- keyword

> For [Matomo](https://matomo.org/docs/site-search/#tracking-site-search-keywords)-
> 
> > **“By default, Matomo will read the URL and look for a parameter with any of the following names: q, query, s, search, searchword, k, keyword”**
> 
> For Google Analytics, [Google lets you put in your own five parameters](https://support.google.com/analytics/answer/1012264?hl=en#Setup)-
> 
> > “5. In the Query Parameter field, enter the word or words that designate internal query parameters, such as term,search,query,keywords. Sometimes query parameters are designated by just a letter, such as s or q. Enter up to five parameters, separated by commas.”

So using "words" in Zenphoto search URLs will not work. They should always look like one of these examples to work in Matomo and Google Analytics (since you are already using “search” as a value for “p”, and that might cause confusion)-

- https://domain.com/zenphoto/index.php?p=search&q=test
- https://domain.com/zenphoto/index.php?p=search&query=test
- https://domain.com/zenphoto/index.php?p=search&s=test
- https://domain.com/zenphoto/index.php?p=search&searchword=test
- https://domain.com/zenphoto/index.php?p=search&k=test

or

- https://domain.com/zenphoto/index.php?p=search&keyword=test

Think of it this way, how are the analytics programs supposed to know what search terms are in a mod rewrite Zenphoto URL and are not instead a subfolder? Especially since some tags, depending on how you click on them, follow /search/-

https://domain.com/zenphoto/page/search/tags/%22First+L.%22/
or
https://domain.com/zenphoto/page/search/%22first+l.%22/

While both analytics programs do offer some other ways to try to make it work, I also [posted a link to Matomo’s support forum showing that a Zenphoto theme editor was not able to get it to work](https://forum.matomo.org/t/unable-to-track-site-search/25379).

What I would like, so analytics programs work with Zenphoto, is for mod rewrite to be turned off for all searches. If you, for some reason, don’t want to do that, give us the option to turn it off for only search and change "words" to one of the other supported options.

___

> Regarding the breadcrumb: don't think we will change that. But you can do that on your site's theme yourself if you really need/want it.
> 
> >

I guess I'll have to do that. I was only trying to clear up confusion that users might be having with your default theme.

___

> > I’ve also noticed a bug with the current breadcrumb. If you click back after clicking on a tag the breadcrumb will change on the regular page to the search one-
> 
> Not sure what you mean.I I tested with the basic theme and on plain tag search results (`page/search/tags/…`) there is no tag in the breadcrumb. You click on "Search" to get back to the search results.

Yeah, it’s not doing it for me now that I’m testing it again, but I have noticed it in the past. Maybe it’s a bug with Firefox. If I catch it again, I’ll try to document it.

Thanks!

**Comment by acrylian** [comment]
Thanks for the clarification on the search query info. That indeed somehow escaped me. To be honest I did not really pay attention although we use Matomo…. There is no other way to tell such analytics what it should consider as searches?

I would consider to have plain search URLs likee `/page/search/?somekeyword=searchterm`. So a kind of "half modrewrite URL". We also already plan to shorten `/page/search/` to `/search/` by default which is already possibly with the rewrite tokens.

Btw, for tags URLS we consider just `/tags/` by default instead of `/page/search/tags/` from 1.6 on (also already possibly via the plugin, too). In ZP tags as a "taxonomy" are searches because they cover four separate content/item types but on other systems they would be "taxonomy archives" instead as well (like Zenpage news categories `/news/category/` are not searches because limited to articles). So I don't think we need to cover actualy tag URLs as "searches" in the above meaning as they are a bit outside of that, right?

> I guess I'll have to do that. I was only trying to clear up confusion that users might be having with your default theme.

That we have a search result context is quite special, other systems don't have that at all. I personally - especially on destkop - open search results in new tabs as I am used to that from Google and elsewhere.

The search context uses cookies to keep it so if you refuse cookies there is not search result context.

**Comment by JesseHC** [comment]
> There is no other way to tell such analytics what it should consider as searches?

Matomo has a way supposedly, but you have to [swap out the default piwikTracker.trackPageView() with piwikTracker.trackSiteSearch().](https://matomo.org/docs/site-search/#track-site-search-using-the-javascript-tracksitesearch-function)

> If tracking search results via the URL is not possible (for example if you use rewritten URL without query parameters, eg. /search/keyword) , or if you wish to also track the count of Search Results, you  may use the Javascript function piwikTracker.trackSiteSearch(keyword, category, searchCount). Calling the function will record the search keyword, search category, and the count of results on the search result page. This can be used on Search Results pages, instead of calling piwikTracker.trackPageView().
> 
> Check out more information in the [Javascript documentation for trackSiteSearch()](https://developer.matomo.org/guides/tracking-javascript-guide#internal-search-tracking)

[Google suggests two options](https://support.google.com/analytics/answer/1012264?hl=en#Post), but their Option 1 is to just add the query keywords to the end of the URL.

> If you're using a POST-based search engine, the search-results URL would look something like:
> 
> http://www.example.com/search_results.php
> 
>  
> 
> You have two options to use Site Search for POST-based search engines:
> 
> Option 1: Configure your web application to append the query keywords to the end of the URL (e.g., http://www.example.com/search_results.php?q=keyword) and then set up Site Search as described in the previous section.
> 
> Option 2: Customize the tracking code on your results page to dynamically specify a virtual page path that includes the query keywords. The tracking code on the results page would look something like:
> 
> analytics.js: ga('send', 'pageview', '/search_results.php?q=keyword'); 

___

> So I don't think we need to cover actualy tag URLs as "searches" in the above meaning as they are a bit outside of that, right?

That's up to you. I will say that the argument for them being treated similar is that they are suggested in the search box as a search term when the tag_suggest plugin is turned on, they can be searched for regularly, and the results look similar to a search. The last thing is that without them being treated like a search, they will show up in the regular page results, which is fine.

I know that for categories and tags to be shown in analytics with Wordpress you have to go through a bunch of extra steps.

I'm honestly not that familiar with all the possibilities of analytics, I just noticed that the search terms were not being recorded with Zenphoto and wanted to pass it along.

**Comment by acrylian** [comment]
> That's up to you. I will say that the argument for them being treated similar is that they are suggested in the search box as a search term when the tag_suggest plugin is turned on, they can be searched for regularly, and the results look similar to a search. The last thing is that without them being treated like a search, they will show up in the regular page results, which is fine.

There are actually two "search urls" here. If you search via the serach form it is always /page/seach/keyword. If you click on a tag link it is /page/search/tags/tagname. So tags have already an exception.

Besides the "keyword" name issue, Matomo etc should cover all kind of URls, just not specifically as "search" which I understand is something different.

**Comment by acrylian** [comment]
@JesseHC 1.6a now has a `?search=searchwords` query even with modrewrite.

**Comment by JesseHC** [comment]
> @JesseHC 1.6a now has a `?search=searchwords` query even with modrewrite.

Thanks for that, though tags are now broken with mod rewrite turned off. Both by clicking on a tag link or by using a tag suggestion in the search box.

Clicking on a tag you get-
https://domain.com/zenphoto/index.php?p=search&search=__25__22First__25__2BLast__25__22&searchfields=tags


Clicking on a tag suggestion you get-
https://domain.com/zenphoto/index.php?p=search&search=__25__22first__25__2Blast__25__22


In the source code for a tag link you get-
href="/zenphoto/index.php?p=search&amp;search=%2522First%2BLast%2522&amp;searchfields=tags"

It looks like it might be including a mix of both the encoded and unencoded version of % in the links.

Tags do work with mod rewrite turned on.

**Comment by acrylian** [comment]
Thanks, I can reproduce the tag issue. Will see what I can find here.

**Comment by acrylian** [comment]
@JesseHC I might have a fix. Please try.

**Comment by JesseHC** [comment]
> @JesseHC I might have a fix. Please try.

The tags and search now seem to be working with mod rewrite turned on and off. Thanks for that!

___

> > > I’ve also noticed a bug with the current breadcrumb. If you click back after clicking on a tag the breadcrumb will change on the regular page to the search one-
> > 
> > 
> > Not sure what you mean.I I tested with the basic theme and on plain tag search results (`page/search/tags/…`) there is no tag in the breadcrumb. You click on "Search" to get back to the search results.
> 
> Yeah, it’s not doing it for me now that I’m testing it again, but I have noticed it in the past. Maybe it’s a bug with Firefox. If I catch it again, I’ll try to document it.

I also wanted to let you know that I figured out how to duplicate the breadcrumb title changing to a search version. It only happens while viewing a gallery while logged in as an admin (it might be for other users logged in, but that’s all I tested). While logged in as an admin, view the gallery in a new tab, click an image page with a tag underneath it, click on the tag to view the search results, then click back in the browser. The regular breadcrumb title on the regular page will have all albums in the breadcrumb replaced with a "Search" link. It will keep the site name, gallery name, and image name.

All album links and album text are replaced with this-
`<a href="/zenphoto/page/search/tags/%22First+Last%22/" title="Return to search">Search</a>`

It happens in Chrome, versions 99.0.4844.84 (Official Build) (x86_64) and 100.0.4896.60 (Official Build) (x86_64), and Firefox 98.0.2 (64-bit), all tested on a Mac (10.14.6).

It did not happen in Safari, version 14.1.2 (14611.3.10.1.7), and most importantly, while viewing the gallery logged out.

Probably not a real issue, since regular users should not experience it, but wanted to make you aware of it.

**Comment by acrylian** [comment]
I just added another change but there is something not right with non rewritten tags urls now… Later…

I think I have not exactly understood the breadcrumb issue. A tag is a  search result so the breadcrumb also referes to the result and not the real location of an image as we discussed above. I will try breadcrumbs later…

Also since search context uses cookies opening results in a different window/tab may kill that context, especially if you use private windows/tabs naturally.

**Comment by acrylian** [comment]
Yes, appears to be an unwanted side effect due to the controller redirections since "locale" is not part of the actual search url… 
We also discovered that selection fields does not work anymore (or never did or did not for quite some, we are not sure)

**Comment by acrylian** [comment]
This is actually generally fixed. The search fields selection issue is not as we lacked the time and will have to wait for 1.6.1. probably. But that is actually another issue, so this is closed.
