### ISSUE TITLE
Plugin user_login-out, redirection after logout 

### ISSUE THREAD

**Issue by bic-ed** [zenphoto/zenphoto#1324]
https://github.com/zenphoto/zenphoto/blob/9773c21a44e5941afc04708dd6b71ad9ac2a3074/zp-core/zp-extensions/user_login-out.php#L52

Hi, it's not clear to me how this should work. It doesn't actually, after logging out with printUserLogin_out() generated link it always redirects to the gallery home page. The parameters supposed to be here
`$logoutlink = "javascript:launchScript('" . FULLWEBPATH . "/',[" . implode(',', $params) . "]);";`
are always empty, because they are generated under the `if ($_GET['userlog'] == 0) ` condition, that of course is not fulfilled before using the logout link.

I tried moving the parameters generation just before the `if (isset($_GET['userlog']))` condition and doing so the redirect works as expected.

Anyway, unless I'm missing something, like I probably am, all of that parameters generation thing can be removed if using an empty link for logout, like so:
`href="javascript:launchScript('',['userlog=0']);"`

I tested this way also, and it seems to work properly. The page from where the link is clicked gets reloaded and the user gets logged out.

What am I missing?

**Comment by acrylian** [comment]
Have to look admitting Iam rarely using thte plugin myself… I have to review why there actually is this (rather awful) `href="javascript:launchScript('',['userlog=0']);" js link  (which if should better be a button probably) and no actual logout link from the page itself…

**Comment by acrylian** [comment]
The redirecton params are always `userlog=0` usually, the others indeed cannot be setl until the link is clicked (npt sure why these are here as the global is most likely cleared everytime especially after a redirect). 

But the redirection happens with  if (isset($_GET['userlog']))  - unless a standard backend logout where handleLogout() method would take over-  does actually process the redirection and create them.

The actual issue seem to tbe the oontext checks. We are redirected to the homepage for processing  - (actually any page should do  as we proces before any page is loaded - I think the js launcher is not necessary at all here…) and then should be returned to the actual page. I think the `in_context()` checks are the issue as if we have `if (in_context(ZP_INDEX)) {` we don't have e.g. `if (in_context(ZP_ALBUM)) {` and so on, so we actually access the home page.

**Comment by acrylian** [comment]
My bad, you are actually right. The hardcoded FULLWEBPATH is the only issue here. Actually just`$logoutlink =`?userlog=0` (respectivel `&userlog=0" for non rewrite) as the logout link is all that is needed and no JS launcher at all.  The params are always empty anyway and can IMHO be removed from that function.

**Comment by bic-ed** [comment]
Ok then if you want I can fix it myself

**Comment by bic-ed** [comment]
I just would not change the link into a button to preserve layout of themes

**Comment by acrylian** [comment]
No need,  I can jus do it myself. Hope

> I just would not change the link into a button to preserve layout of themes

Since the JS launchscript is not needed at all there is no need to change it. But on lots of other occasions we will do that in the future, not in 1.6 thoug. (if you have links that have no destination but trigger JS only that is a old habit you don't do anymore nowadays).

**Comment by bic-ed** [comment]
> No need, I can jus do it myself. Hope

Of course you can, I just wanted to help saving you the trouble ;-)

**Comment by acrylian** [comment]
Thanks, but since I am already at it ;-)

**Comment by acrylian** [comment]
Actually I just realize that the trick only works with rewritten URL For this to work the same we we actually need to move the `$_zp_userlogin_redirect` create stuff or at least parts  to the  function itself to be able to generate the URL of the current page… Or we just decide it is time that rewritten is the standard way with some benefits (doest really any one does still not use that?)…

**Comment by acrylian** [comment]
Btw, seems we also don't even need the redirect in the user-loginout handling at all with this new fix.

**Comment by acrylian** [comment]
And probably we should also review the admin toolbox logout link as that also does not stay on the ceurrent page. For the logout link from the backend itself that is expected though.

**Comment by bic-ed** [comment]
Forgive me if not answering, I'm away from my pc at the moment. I'll have a look later in the afternoon.

**Comment by acrylian** [comment]
No problem, it's Sunday after all and I don't expect "initial replies" ;-) I meanwhile committed some fixes. Pease test.

**Comment by bic-ed** [comment]
It seems mostly ok to me, the only little problem is on a quite unusual but not impossible real world scenario:

if an user disconnects immediately after login and then tries to login again from the same page (i.e. the password page), it results in a disconnection again because of the `?userlog=0` parameter left in the url.

Even if it seems really weird for an user to do so, I can imagine at least one scenario were it can happens. An user is visiting a password protected album on which he has no rights, even if connected, but of which he knows the password. Then he has to logout before insert the album password, otherwise the login form is not printed. So he does it, the login form appears, he tries to login with album credentials but gets an error because of the `?userlog=0` parameter left in the url.

Before your fixes, the left parameter after logout was just `?fromlogout`, so it was possible to re-login immediately.

**Comment by bic-ed** [comment]
Ah, like you said it would be nice to apply the same redirect fix on the logout from admin toolbox.

**Comment by bic-ed** [comment]
> if an user disconnects immediately after login and then tries to login again from the same page (i.e. the password page), it results in a disconnection again because of the `?userlog=0` parameter left in the url.

Also, it's not necessary that he disconnects immediately after login, is enough that he lands on the password page of a protected object while connected but whit no rights for that object.

**Comment by acrylian** [comment]
I see what you mean now and realize that was the reason fro the redirection. I should be able to restore that.

**Comment by bic-ed** [comment]
> I see what you mean now and realize that was the reason fro the redirection.

Ah yes, that!
I'm trying to add support for this plugin to Multiverse and may be to a new theme I'm working on, that's why I'm on it these days, I never used it before.

**Comment by acrylian** [comment]
I just commited a fix/revertion for this with the return of the redirection. As far as I see it now has the proper ?fromlogout while staying on the original page.

**Comment by bic-ed** [comment]
Yes, I can confirm that now everything is ok.

**Comment by acrylian** [comment]
Thanks. I will keep this open as for the admin toolbox logout we will need to consolidate things. Probably the logout link part  will be moved to core as we really need only one for front end logouts.  Have to review as its been a while I looked at that.

**Comment by bic-ed** [comment]
> Probably the logout link part will be moved to core as we really need only one for front end logouts

Sounds logical indeed.

**Comment by bic-ed** [comment]
You forgot to re-add the line
`$params = '';`
before the `foreach ($page_params as $param => $value)` loop, so now an _undefined variable_ notice appears in debug log for line 208
https://github.com/zenphoto/zenphoto/blob/692e1c97ea98e47fddd65a4092baa9fcb6777477/zp-core/zp-extensions/user_login-out.php#L208

**Comment by acrylian** [comment]
Indeeed I did. Probably I sort of wanted to let the `getCurrentPageParams()` do it all already since the two times extra generation step is not really need but in already Sunday evening mode forgot both… Will fix later today!

**Comment by acrylian** [comment]
So I have centralized the logout url stuff and also the logout handling. The plugin indeed basically doubled what the auth.php core handler also does (and there were even some differences). Now auth.php does it all and even the admintoolbox redirects to the current page. 

Had to do it with logout urls using non rewritten query parts Staying on the page was not working with modrewrite because auth.php is acting quitte a bit earlier in the line. But result is the same.

Seems to work for me so far but I  would appreciate testing.

**Comment by acrylian** [comment]
Also no pressure ;-)

**Comment by bic-ed** [comment]
> Seems to work for me so far but I would appreciate testing.

Here too, everything works as expected. The non rewritten parts for logout links are not a problem for SEO, as search engines hopefully are never loggedin :-)

**Comment by acrylian** [comment]
Thanks. No rewritten URLs get rewritten/redirected on access anyway. However we sadly noticed a bug that Zenpage items are not properly redirected.

**Comment by bic-ed** [comment]
I can see it now but only if logout from admin toolbox, not from the plugin generated link

**Comment by acrylian** [comment]
Thanks, that is a very helpful clue since the toolbox currently creates the redirect part itself and not via the 2nd method internally. Probably should change that anyway as it doubles it

**Comment by bic-ed** [comment]
Seems ok to me too (and thanks for the tag suggest other fix also)
