### ISSUE TITLE
Custom MySQL socket path?

### ISSUE THREAD

**Issue by eisengrau** [zenphoto/zenphoto#1327]
Hello,

On the installation script, I would like to specify a custom UNIX socket path for the MySQL database, but for some reason it always fails to connect. For example /home/user/sockets/mysql.sock instead of a hostname.

Usually for other CMSes, it is enough to specify localhost:/path/to/socket.sock as a hostname, and leave port NULL, but this is not the norm, and I had similar issues previously with this.

Is there a workaround for this?

**Comment by acrylian** [comment]
I fear there isn't yet. Although there is a socket parameter for connections in the PHP methods it is not yet supported by Zenphoto. I actually never encountered the need for it using pre-setup servers.

I will see if I can add a socket option in the config file for 1.6a the next days. I'll let you know so you can help test it. I believe there may also a way to define the socket via server config. But I don't know enough about that.

**Comment by eisengrau** [comment]
Hello, that was quick! :)

Yes, I would appreciate if there would be a possibility for this. I would also gladly test it if it's working. I'll leave my installation un-configured until then. I have seen in the sample config file that is may be possible to define a socket, but I'm not sure how the core zenphoto will parse that, if at all. 

For ex., for Piwigo, I can define:

`$conf['db_host'] = '/path/to/sockets/mysql.sock';`

The user case would be, that even if the MySQL runs on a 'remote' machine, or more common, in a container on a local machine, it is better to connect using an UNIX socket and clear the TCP network overhead. Or for clustered setups, or where the listener is a single input where apps can pipe to.

I'll monitor the request.

**Comment by acrylian** [comment]
Zenphoto does not parse it yet even if you would add it to the config file. 

As far as I understand the PHP mysql stuff the socket is not the same as the host being a separate parameter.

You could try a hack to speed up this. If you are using MySQLi find in 1.5.9 the file zp-core/functions-db-mysqli.php (Note that in 1.6 db handling has been moved to classes) and edit this part:

![Bildschirmfoto 2022-05-26 um 11 02 04](https://user-images.githubusercontent.com/2474309/170455873-b084d0cf-5346-4d46-a4a2-78ad13956f31.jpg)

to include the socket as the last parameter

![Bildschirmfoto 2022-05-26 um 11 03 33](https://user-images.githubusercontent.com/2474309/170456040-c35c2149-84d7-4982-a5a3-c917d381fc9d.jpg)

(docs https://www.php.net/manual/en/mysqli.construct.php)
