### ISSUE TITLE
Can't install 3rd party themes

### ISSUE THREAD

**Issue by JosephBerman** [zenphoto/zenphoto#1328]
Hi, I launched a docker container on my server however I'm unable to install 3rd party themes. I attach the container and attempt to put a theme in the theme directory. The instance is able to see the theme however when I try to activate it it is only a totally white screen.

The theme I'm trying to install for reference.
https://github.com/RolandTi/collections

I don't know if it is an issue with the container or not but I tried with another theme and the same result occurred. Please assist if I'm doing something wrong.

**Comment by acrylian** [comment]
Besides not using Docker nor having knowledge about this, you just have to place the theme folder as the repo within the themes folder.

If you get a  white screen indicates an error. Usually a PHP fatal error but might also be a file/folder permission issue causing this. The first to do is always to review the debug log and if you have access - which you should - our server PHP error log.

**Comment by JosephBerman** [comment]
Looking at the exception its saying, 
"all to undefined function printLangAttribute() in /var/www/html/themes/collections/index.php on line 3"

Any ideas on how to fix this? I have no knowledge of php sorry

**Comment by acrylian** [comment]
Then you are probably using an older release before 1.5.7 where this function was introduced. Please upgrade to the latest.

**Comment by JosephBerman** [comment]
Was a version conflict. Thanks.
