### ISSUE TITLE
Password protected items errors

### ISSUE THREAD

**Issue by bic-ed** [zenphoto/zenphoto#1332]
I'm experiencing some problems with password protected items.

- Zenphoto items like albums are accessible after inserting password, but an error message is thrown at the same time, opening the colorbox popup when user_login-out option is set to "Colorbox".

![Immagine 2022-07-15 084115](https://user-images.githubusercontent.com/2939831/179166392-e77cbed4-4c83-4e4f-b672-912c2e2a35ca.png)

- Zenpage items like pages and categories instead are not accessible at all, even if the proper zpcms_auth_page_# cookie is present after inserting password.

**Comment by acrylian** [comment]
> error message is thrown at the same time,

And which is that?

We will try to reproduce this. But password handling is scheduled to be reworked anyway to use some now available PHP core password functions it does not yet. So perhaps we will push this for later.

**Comment by bic-ed** [comment]
The message is the one in the screenshoot above

> There was an error logging in.
Check your username and password and try again. 

Also, I forgot, for zenpage items the password hint is not shown.

**Comment by acrylian** [comment]
Is this only happening with the colorbox mode or with normal password forms as well?

**Comment by acrylian** [comment]
Also are we talking about individual passwords for items or general gallery/site passwords? 
Guest user login or actual user?

**Comment by bic-ed** [comment]
We are talking about individual items password only.

For zenpage items the error is shown also in the normal password form and items remain not accessible after inserting password, even if the proper cookie is stored and the password is correct.

For zenphoto items the error is shown only if colorbox option is enabled. Items are accessible after inserting password though.

Of course the individual item password is not inserted using the colorbox popup in any case, but from the form in normal password page that is shown when an user tries to access a protected item.

**Comment by bic-ed** [comment]
> Guest user login or actual user?

Guest user login only. For actual users all works as expected.

**Comment by acrylian** [comment]
Thanks, that's a clue as these are handled a bit differently.

**Comment by bic-ed** [comment]
Well, after a short holiday by the sea :-) I'm back whit a trivial fix for the most important part of this issue.
The function checkforGuest(), both in class-zenpagepage.php and in class-zenpagecategory.php,  was still using the  old cookie name. That's why:

> For zenpage items the error is shown also in the normal password form and items remain not accessible after inserting password, even if the proper cookie is stored and the password is correct.

Also, I found (and perhaps solved, but probably not in the best way) a bug preventing $hint and $show values to be passed to password.php page for categories and pages. In addition, for zenpage category only, once fixed the $hint issue, the password hint is returned raw, without get_language_string() applied, and this can be easily fixed too.

I'm unsure wether or not open a pull request though, because like you said password handling is going to be reworked.

Moreover, the weird error message thrown by login form (with colorbox option enabled) is still a mystery for me.

**Comment by acrylian** [comment]
Thanks, please just send a pull request. Good to have it fixed and working before any rework will be done.

**Comment by bic-ed** [comment]
Ok, but before doing so I'd like to take a short time more to investigate the remaining part of this issue.

> Moreover, the weird error message thrown by login form (with colorbox option enabled) is still a mystery for me.

**Comment by bic-ed** [comment]
Ok, I found were it came from:

https://github.com/zenphoto/zenphoto/blob/62170cf293d226647ce4660f2bcb9aa8bf3122ab/zp-core/class-authority.php#L736

We should find a way to set that error only if an user login has failed, not a guest one.

**Comment by bic-ed** [comment]
I mean, not if a successful guest login was done...

**Comment by acrylian** [comment]
From a quick look that is set if logging in was not successful. Guests are of course a bit different as they are technically not a real type of "user" like user groups are for example (which perhaps should be changed in the long run…).

**Comment by bic-ed** [comment]
Yes, it seems quite tricky to manage a successful guest login from handleLogon(), that is meant for managing registered users, not guests. Everything works fine if colorbox login is disabled and a normal password form is used. But whit colorbox enabled printLoginForm(), called from printPasswordForm(), gets the $_zp_login_error before the password check has been done

I guess I'll send the pull request for the solved part of this issue and investigate the remaining part later on...
