### ISSUE TITLE
CASE_INSENSITIVE test fails on open_basedir restriction 

### ISSUE THREAD

**Issue by Brucepimenta** [zenphoto/zenphoto#1337]
Testing for CASE_INSENSITIVE changes full path to caps, which hits the open_basedir restriction and fails further execution.

Suggestion for fixing it, is leaving the path with lower case letters and only use the filename with upper case letters. For example version.php needs to be available, so we can test it (exept somebody manually creates the same file with upper case letters): 

```

diff --git a/zp-core/global-definitions.php b/zp-core/global-definitions.php
--- zp-core/global-definitions.php
+++ zp-core/global-definitions.php
@@ -34,9 +34,9 @@
 define('THEME_PLUGIN', 1024);
 define('PLUGIN_PRIORITY', 1023);
 
 define('SYMLINK', function_exists('symlink') && strpos(@ini_get("suhosin.executor.func.blacklist"), 'symlink') === false);
-define('CASE_INSENSITIVE', file_exists(strtoupper(__FILE__)));
+define('CASE_INSENSITIVE', file_exists(dirname(__FILE__) . strtoupper('/version.php')));
 
 /**
  * Enables test release mode, supports the markRelease plugin
  */
```

**Comment by acrylian** [comment]
Thanks, sounds like a good idea.

**Comment by sbillard** [comment]
`define('CASE_INSENSITIVE', file_exists(dirname(__FILE__) . strtoupper('/version.php')));`
is a strange construct. Why not simply
`define('CASE_INSENSITIVE', file_exists(dirname(__FILE__) . '/VERSION.PHP'));`
???

**Comment by acrylian** [comment]
Indeed and the original was not really less strange either

**Comment by Brucepimenta** [comment]
Is it just an example, of how to test for it, regarding the difference lower - upper. "version.php" could be replaced by any file we know, should be there. It could also be: 
define('CASE_INSENSITIVE', file_exists(dirname(__FILE__) . '/VeRsIoN.phP'));

A more save approach would be, to create a file we know, isn't there. For example:
i=0;
tempfile="version" . i . ".tmp";
while (file_exists(dirname(__FILE__) . tempfile)){
i=i+1;
tempfile="version" . i . ".tmp";
}
touch(tempfile);
define('CASE_INSENSITIVE', file_exists(dirname(__FILE__) . strtoupper(tempfile)));
unlink(tempfile);

**Comment by acrylian** [comment]
I think that is really overhead. Testing for a file that is always is really enough IMHO.
