### ISSUE TITLE
Setup warning about skipped releases between versions 1.5.9 and 1.6RC

### ISSUE THREAD

**Issue by kochs-online** [zenphoto/zenphoto#1341]
Installing the current Master (1.6RC) and running setup I got this warning:

> Upgrade from Zenphoto v1.5.9 [11 releases skipped]
> Warning!
> 
> We do not test upgrades that skip releases. We recommend you upgrade in sequence.

But unless I missed something there are no releases available for download between version 1.5.9 and 1.6RC.

**Comment by acrylian** [comment]
Ah, I have seen this once but could not reproduce it. DId you once run setup but didn't complete page 2? My suspicion was that somewhere the signature containing the previous version so setup guesses the version (setup is a beast code wise and this is quite old code…).

**Comment by acrylian** [comment]
Btw, I even saw it once without the correct previous version number. Anyway, it is just a warning and nothing "bad" will happen actually… Will try to look into this tomorrow.

**Comment by kochs-online** [comment]
> Did you once run setup but didn't complete page 2?

No, I did an upgrade from 1.5.4 to 1.5.9 (in a single step skipping releases between) and completed the setup. Afterwards I (roughly) checked everything still worked and went on to upgrade from 1.5.9 to 1.6RC.

**Comment by acrylian** [comment]
Okay, thanks…

**Comment by acrylian** [comment]
Made some updates/changes to this that hopefully fixes this.
