### ISSUE TITLE
Gallery page blank: Exception when trying to parse time string

### ISSUE THREAD

**Issue by kochs-online** [zenphoto/zenphoto#1343]
After upgrading to current Master (version 1.6RC) the gallery page is blank.

`debug.log`:
> EXCEPTION: `DateTimeImmutable::__construct()`: Failed to parse time string (`locale_preferreddate_notime`) at position 0 (l): The timezone could not be found in the database in `/[...]/zenphoto/zp-core/functions/functions-i18n.php` on line 790

**Comment by acrylian** [comment]
Ah, I see these exceptions of the "preferred locale dates"…, will take a look tomorrow…

**Comment by acrylian** [comment]
Actually a format vs datestring confusing. Please try the fix in the master on this.

**Comment by kochs-online** [comment]
That partially fixed it. Now the first album is shown in the gallery.

`debug.log`:
> EXCEPTION: `DateTimeImmutable::__construct()`: Failed to parse time string (`1315639331`) at position 8 (3): Unexpected character in /[...]/zenphoto/zp-core/functions/functions-i18n.php on line 790

**Comment by acrylian** [comment]
Okay, so somehow we have a timestamp coming through here. I knew I should have just silently skipped the strftime() "locale perferred" option that has not direct equivalent…

I guess the $dateObj is skipped…  Could you try of changing line 793  from `$fdate = $formatter->format($dateObj);` to `$fdate = $formatter->format($date);` please. Actually we already should have a date object from above and don't need a 2nd one…

**Comment by kochs-online** [comment]
Still only one album in gallery. Exactly the same error message in `debug.log`.

**Comment by acrylian** [comment]
As the really final thing for today, quicky another fix committed.

**Comment by kochs-online** [comment]
Yes, I can confirm this fixed the issue. All albums are shown and no more new entries in `debug.log`.

**Comment by acrylian** [comment]
Awesome. Then I'll close this.
