### ISSUE TITLE
Album and pages reorder by dragging is broken after jQuery UI 1.13.2 upgrade

### ISSUE THREAD

**Issue by bic-ed** [zenphoto/zenphoto#1346]
Tested with the old UI version 1.12.1 it works again.
Image reording is not affected by this issue, so I guess it has something to do with the nested sortable plugin?
The error I get from the console is:
`Uncaught TypeError: this.dragDirection is undefined`

**Comment by fretzl** [comment]
Just updated jquery.mjs.nestedSortable.js for jQueryUI 1.13+. Seems to work fine.
Please test.

**Comment by bic-ed** [comment]
Yes, it works fine now, thanks!
