### ISSUE TITLE
PHP8 compatibility

### ISSUE THREAD

**Issue by mauriceKA** [zenphoto/zenphoto#1347]
Our webspace provider has updated the PHP version to PHP8 and has discontinued version 7.

This has broken our zenphoto instance.

Are there any plans to make zenphoto compatible to PHP8 in the near future? We have a lot of comments on our photos, so it would be a pitty if we had to move to another software and loose them.

**Comment by acrylian** [comment]
We are working on 1.6 with compatiblity up to 8.1 and hopefully are on the last steps. Also please see:
https://forum.zenphoto.org/discussion/1410922/php-8
https://forum.zenphoto.org/discussion/1411005/zenphoto-and-php-8

**Comment by mauriceKA** [comment]
Hi. That's great news. In this case we'll wait for the release.
