### ISSUE TITLE
1.6RC: RSS Plugin Doesn't Seem to work

### ISSUE THREAD

**Issue by MarkRH** [zenphoto/zenphoto#1351]
I can't seem to get this to work.  I have 23 images in one album so it should show something.  Usually it comes up blank:

![image](https://user-images.githubusercontent.com/8035962/204060748-2937a5df-812d-4a65-98d9-b4cfb3b3969f.png)

```
<?xml-stylesheet type="text/css" href="/zp-core/zp-extensions/rss/rss.css" ?>
		<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/">
			<channel>
				<title><![CDATA[Test Gallery  (Latest images)]]></title>
				<link>https://ztest.loc</link>
				<atom:link href="[https://ztest.loc/index.php?rss=gallery&amp;lang=en](view-source:https://ztest.loc/index.php?rss=gallery&lang=en)" rel="self"	type="application/rss+xml" />
				<description><![CDATA[Test Gallery for testing with PHP 8.1]]></description>
				<language>en-US</language>
				<pubDate>Fri, 25 Nov 2022 16:36:36 -0600</pubDate>
				<lastBuildDate>Fri, 25 Nov 2022 16:36:36 -0600</lastBuildDate>
				<docs>http://blogs.law.harvard.edu/tech/rss</docs>
				<generator>Zenphoto RSS Generator</generator>
```
Sometimes it will pop this up in the browser:

![image](https://user-images.githubusercontent.com/8035962/204060858-1eccae40-a49b-4962-80b3-46937220193a.png)

All the images are in a published state.  I am using the built-in Garland Theme (well, I made duplicate of it).  No errors are being generated. Just wondering what I should be checking if anything.

Thanks.
Mark H.

**Comment by MarkRH** [comment]
This looks to be related.  When I go to view the RSS feed, the debug log gets the following in it:
```
 {12100:Fri, 25 Nov 2022 23:10:53 GMT}

EXCEPTION: Failed to parse time string (1406149430) at position 7 (4): Unexpected character in C:\www\zentest\zp-core\functions\functions-i18n.php on line 785
```
Hmmm..

**Comment by acrylian** [comment]
That looks as if the check for timestamp (integer) vs datetime string somehow fails so the timestamp 1406149430 is used as a string. That naturally fails…. All again works on my test sites…

**Comment by acrylian** [comment]
I added a change that seems to work more reliable. Let me know if that fixes it.

**Comment by MarkRH** [comment]
OK.  It seems to be working now.  It's showing images and the Exception is not showing in the dialog.  I'm now noticing that it's showing the file system's modified date of the images at the bottom of each one.  Maybe it was always doing this an I just never noticed.  The first date is from the image's meta data.

> Bad Capacitors from Samsung LN52A650 HDTV (Home Theater)
> Thursday, April 29, 2010 11:25:04 AM
> Bad Capacitors from Samsung LN52A650 HDTV
> 
> Bad capacitors from my Samsung LN52A650 HDTV. These two had bulging caps and had little holes on top where they had started venting their contents. He also replaced two other capacitors to be safe. The replacements had higher voltage specs.
> 
> Date: 7/23/14, 4:08 PM

**Comment by acrylian** [comment]
The feed item itself uses the "normal" image datetime but the actual display indeed uses the mtime (filemtime). No idea why that is so but it was always that way. But seems to make more sense to use the normal date here as well.

**Comment by acrylian** [comment]
I will keep it as it is for now since it has always been that way.
