### ISSUE TITLE
1.6RC: PHP Deprecated Warning with no sub-album or image order set.

### ISSUE THREAD

**Issue by MarkRH** [zenphoto/zenphoto#1352]
I started noticing this when I would go to edit an album:
`PHP Deprecated:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in \zp-core\admin-functions.php on line 1466.`

Which is:
`$cvt = $type = strtolower($album->get('subalbum_sort_type'));`

If I change the "**Sort subalbums by**" from "*gallery album sort order" to something else. then the warning stops.  If I change it back to "*gallery album sort order" the warning still does not appear.  So my guess is that until a value is actually applied to the album then `$album->get('subalbum_sort_type')` has no value and throws that warning.

Same thing happens with line 1518 if no "Sort images by" has been applied.  Setting this one back to "*gallery image sort order" after changing it to something keeps the warning from appearing with this on.

I've got more issues that I've discovered but I'll put those in separate threads.  My webhost also throws out the PHP Deprecated stuff so that's why I've set mine to show those as well.

Thanks,
Mark H.

**Comment by acrylian** [comment]
Thanks, we know. PHP 8.1 is more type strict and we use `null` as the default for a lot of parameter values if nothing is set. We have fixed loads of similar ones already and surely might miss some of them. We pragmatically just type cast the values as it is impossible to fix the actual source of values.

No need to open tickets for each of these. These are not serious until PHP 9.

**Comment by acrylian** [comment]
Btw, if you get this one you are not on the latest 1.6RC as it is already fixed. The line you cited is already

     $cvt = $type = strtolower(strval($album->get('subalbum_sort_type')));


Please always make sure to use the latest master before reporting anything.

**Comment by MarkRH** [comment]
Ahh.. sorry about that.  Yeah, the latest code doesn't have any of these types of warnings I was seeing so far.  I'll be sure to get the latest code before posting again.

Thanks..

**Comment by acrylian** [comment]
No big deal, that happens!
