### ISSUE TITLE
1.6RC1 Images with no Exif dates show as Apr 30, 7687 2:04 pm

### ISSUE THREAD

**Issue by MarkRH** [zenphoto/zenphoto#1353]
I've noticed that if I add an image with no meta information it decides the datetime should be Apr 30, 7687 2:04 pm.  The 1.5.7 Gallery at my host puts in today's date it looks like.  Is there a default value we can set somewhere if it contains no meta information?

Now, pretty much any image I care about will have the meta information in it.  It's just something I noticed.  I am using code I got this morning at 9:05 AM Central Time.  

![image](https://user-images.githubusercontent.com/8035962/204925232-be3f89cc-8dee-405e-97e7-649f6f4aca5a.png)

I am also not sure what the intended behavior is in these cases.  Though.. almost kind of a feature showing you forgot to put a date in it. LOL

**Comment by acrylian** [comment]
That looks weird indeed. There is no default actually. I assume that is `printImageMetadata()` which just uses the value for the time presented and creates a timestamp:

    echo zpFormattedDate(DATE_FORMAT, strtotime($value)); (template-functions.php line 2696)

And your interesting future date is the result. Guess we need to add a check if there is a date in the meta data. Note: This is not the same as using the template function to print the date and therefore does not use that as a default.

**Comment by acrylian** [comment]
I just tried with null (which would cause a php 8.1 deprecation notice) and also an empty string. Both fallback to the current date. 

So I am assuming you have some sort of date set in the meta data respectively the db entry. 

I get the year 2848 with one image: 
![Bildschirmfoto 2022-12-01 um 11 04 06](https://user-images.githubusercontent.com/2474309/205024658-691c80a6-3096-4c51-9677-111be31e979f.jpg)

In my case it seems there is a date stored in a totally wrong format: `2021:03:10 11:40:48`  That is misinterpreted as a time and not a date with time and then PHP tries to make sense of it and calculates it wrong. Seems the image meta data is correct so this must be an import mistake somewhere. This must be something old since we haven't touched this area for ages I think…

**Comment by acrylian** [comment]
I am not really a photographer so I don't really look at exif data or it processing for a long time that much and never noticed any issue here. But it seems some images have this correct and some don't.

![Bildschirmfoto 2022-12-01 um 11 20 24](https://user-images.githubusercontent.com/2474309/205028788-bcfc999e-84a2-40cf-b2e9-976d7b312e8f.jpg)

Seems this is a bug in the image class updateMeta() method that seems to build the two full datetime values on the left from those on the right, with various fallbacks if one is not set.

**Comment by acrylian** [comment]
It seems it is really supposed to be stored like 2021:03:10 11:40:48 within the image meta data that is the exif datetime format (to each his own standard…): So it is not a bug of our older Exifer library especially because the native PHP exif_read_data() also gets it that way. 

So it is rather a very stone age old bug in our template output it seems…

**Comment by acrylian** [comment]
Ah even easier.  The reason for the failure is simply strtotime() generating a wrong timestamp. PRe 1.6 zpFormattedDate() required a timestamp, now it also accespts datetime strings directly. Without it seems the  native php classes DateTime and DateTimeImmutable can handle this format.

**Comment by MarkRH** [comment]
Well.. in my case, the images had no EXiF or IPTC data in them.  Also, the date it decides isn't always the same.  One image it used Dec 31, 1969 6:00 pm and another Oct 1, 2022 9:10 am.

If I do set an Exif date then it uses those fine.  Will see what happens with your updated code.

**Comment by acrylian** [comment]
The code really has a fallback if the date is empty (null or empty string) to use today's date. In my case that were EXIFDateTimeOriginal  and XIFDateTimeDigitized. 

If the update does not help there must be something else in that database field that is interpreted wrong otherwise…

**Comment by MarkRH** [comment]
Well.. the images I've been testing with no date information in the meta data have been coming up Dec 31, 1969 6:00 pm this time.  Not sure where it's getting that date from.  Wonder if it's related to the earliest possible PHP time?

**Comment by acrylian** [comment]
Yes, that's the earliest date in "unix time". What value do the database entries for date actually have? I would assume there is some value that is confusing the date handling. Also perhaps do a metadata refresh on some of the image, just in case…

**Comment by MarkRH** [comment]
On one image looking at the database, the **date** column has **(NULL)**.  The **lastchange** column has **2022-12-01 13:41:48**  The **mtime** column has **1,669,923,,701**.  All the **Exif** and **IPTC** fields have **(NULL)** values.  

When I go to edit this image, the date field is blank.   Refreshing the Meta Data doesn't change anything, which makes sense to me.  Doesn't add a Date to it.  

So I guess the ones with a NULL date show up as Dec 31, 1969 6:00 pm.

I still have this one image that causes a date of Apr 30, 7687 2:04 pm to be created with 7688-04-01 14:04:37 being put into the database.  No idea where it's getting the date from.  None of the Exif or IPTC fields have values.  Maybe it's reading some value in the file that nothing else can see.  Weird.

**Comment by acrylian** [comment]
> So I guess the ones with a NULL date show up as Dec 31, 1969 6:00 pm.

No, actually not. zpFormattedDate() respectively the new getFormattedLocaleDate() function used within it will use the current date if the datetime passed is null or an empty string. That function is used with the image meta time display.

If the date passed is a valid  string but a "nonsense" date PHP and its datetime or dateimmuntable class (depending if available on  your server) will try to interpret it. If you have for example "nonsense" day numbers like for example 2022-12-40 it will/may try to calcucualte/fix that resulting in a kind of 2023-01-09 (31+9) date as far as I understood the documentation.

So if you get such dates there must be some wrongn date stored probably in the image I would say.

**Comment by acrylian** [comment]
We can reproduce this with the standard template date functions like printImageDate(). The reason is somehow that the internal getFormattedLocaleDate() does not handle the resulting timestamp passed to zpFormattedDate() correctly although it is generated from a vaild datetime string… Will have to review it. The easy fix is to not pass timestamps anymore as in earlier version. But actually we wanted to cover that for backwards compatibility…

**Comment by acrylian** [comment]
I hope I got it now.

**Comment by MarkRH** [comment]
Okay. In my image.php file I have 

`<p><strong>Date: </strong><?php echo date("M j, Y  g:i a",strtotime(getImageDate())); ?><br />`

The `getImageDate()` function is returning a value of **false** because `$d = $_zp_current_image->getDateTime();` has an empty value.  Looks like the date function generates the date Dec 31, 1969 6:00 pm when it's fed a value of 0 or false.  So that's why it is displaying that.  In the database itself the Date field is Null after adding an image with no date in a meta tag.  

Anyway, since any images I'm actually going to use will have dates added to the meta tags beforehand, not a big deal.  I could in my image.php file is show the file's modified date or something instead if getImageDate() is coming back with false.  Or maybe within the code that processes new images to use the file's modified date for the Date value if no meta value is detected? 

One thing that did get corrected is that image that was getting the weird Apr 30, 7687 2:04 pm date is now getting Dec 31, 1969 6:00 pm instead.

**Comment by acrylian** [comment]
Ah, you should have mentioned that you are not using "official" zp functions. I looked at the official garland and that has the metadata output only as far as I remember. This "pure PHP" of course does and cannot cover our fallbacks… You should be using  the template function `printImageDate('Date: ', 'M j, Y g:i a')` instead.

That internally will use `zpFormattedDate()` which then uses `getFormattedLocaleDate()`.

**Comment by acrylian** [comment]
The behavour of `strtotime(getImageDate()` returning false if the date is empty is correct. It cannot create a timestamp form that. And `date()` therefore uses the earliest Unix date as a fall back.

**Comment by MarkRH** [comment]
Ahh..  `printImageDate('Date: ', 'M j, Y g:i a')` just outputs nothing on those images.  With `printImageDate('Date: ', 'M j, Y g:i a')` It's now outputting dates like: printImageDate: **Jan 2, 2011 2455564:22 PM** instead of **Jan 2, 2011 7:22 pm**

I'm just using `echo printImageDate('printImageDate: ', "M j, Y g:i a");` in the image.php file.

Not sure where it's getting these extra digits from. Looking at the code:
```
function printImageDate($before = '', $format = null) {
	global $_zp_current_image;
	if (is_null($format)) {
		$format = DATE_FORMAT;
	}
	$date = getImageDate($format);
	if ($date) {
		if ($before) {
			$date = '<span class="beforetext">' . $before . '</span>' . $date;
		}
	}
	echo html_encodeTagged($date);
}
```
It's doesn't seem like it's doing anything different as it's calling the same getImageDate() function.. unless I'm using out-dated code.  Still not sure where these extra digits are coming from for the Hour.

![image](https://user-images.githubusercontent.com/8035962/205385818-3e73a45e-c2c3-49df-93b9-1879dfb8bae9.png)

Hmmm..

**Comment by acrylian** [comment]
Your old code is in any case overcomplicated as `date("M j, Y g:i a",strtotime(getImageDate()));` uses a already formatted date to create a timestamp and then again a formatted date from that. `date()` is not locale aware so will not translate month names for example. Which zpFormattedDate() does (if the server supports it via locale and such).

Why you get such weird "hours" I have no idea. What is the actual datetime stored in the db so we can try to reproduce if there is still a bug some where. It's a bit complicated with converting strftime() formatting and date() formatting without breaking things…

**Comment by acrylian** [comment]
Also please note if you have the intl extension on your server or only the standard datetime as that might make a difference.

**Comment by MarkRH** [comment]
The Intl extension is enabled.  Version 70.1.  In the image I show above, the database has these values for it:
"Date": 2010-04-29 11:25:04
"EXIFDateTime": NULL
"EXIFDateTimeOriginal": 2010:04:29 11:25:04
"EXIFDateTimeDigitized": 2010:04:29 11:25:04
"IPTCDateCreated": (blank)
"IPTCTimeCreated": (blank)

**Comment by acrylian** [comment]
I found it. Since you are using a locale aware date with month names there was a conversion missing for the hours and "g" in your datetime format string specifially. "g" means "modified julian day" in the ISO date format and needs to be converted to "hh". 

Then it works:

![Bildschirmfoto 2022-12-03 um 10 59 15](https://user-images.githubusercontent.com/2474309/205435492-dc1a70ee-d11a-4866-aeea-56e2684a2a30.jpg)

I am getting 09.25 instead of the original 11:25 because of the different time zone apparently.

**Comment by MarkRH** [comment]
Ahh.. the Intl Date formatter uses different consonants for its format string.  I found some documentation of these here: https://framework.zend.com/manual/1.10/en/zend.date.constants.html but there might be a better place.  Which do you use?

If I just use "h" then it will display Jul 3, 2014 3:54 AM.  "a" in the regular date format would be a lowercase "am".  Not sure if the Intl one has a corresponding option or not.  At least this explains what's going on and it does look better now.

Thanks.

**Comment by acrylian** [comment]
Yes, it does butt we use actually the standard datetime format as for `date()` and convert it internally to the ISO/Intl format if needed. That had something missing. Here is a better list I think:
https://unicode-org.github.io/icu/userguide/format_parse/datetime/#datetime-format-syntax

It's a bit inconvenient especially as there are double chars and it is quite similar, so there is the danger of double converting… As mentioned the former simple strftime() way has been made more flexible but also overly complicated…

I will again check if and what I missed… The more you look at those the more it confuses being so similar…

**Comment by acrylian** [comment]
> Not sure if the Intl one has a corresponding option or not. 

The ISO format does not have a lower case equivalent for am and pm as it seems.

Anyway, I added one more conversion but unless I really mislooked I should have all now.

Btw, the link above does  not feature a comparison. You have to use that and this https://www.php.net/manual/de/datetime.format.php together..

**Comment by MarkRH** [comment]
> Yes, it does butt we use actually the standard datetime format as for `date()` and convert it internally to the ISO/Intl format if needed. That had something missing. Here is a better list I think: https://unicode-org.github.io/icu/userguide/format_parse/datetime/#datetime-format-syntax

Thanks for that link.  If I really want it lowercase, I can always change it to lowercase if I want.  Might just leave it in caps.

Thanks for looking at it.

**Comment by acrylian** [comment]
Sure, of course we like this to work properly!
