### ISSUE TITLE
Erroneous 'display_errors' setup message displayed under php 8.1

### ISSUE THREAD

**Issue by hazarjast** [zenphoto/zenphoto#1360]
Hello and Happy Holidays!
I recently spun up an apache2 instance under Ubuntu Server 22.04 using php 8.1 to play with Zenphoto 1.6. At setup I receive an error stating that 'display_errors' is enabled in my php.ini. However, this parameter is set to 'Off' in my php.ini.

After some troubleshooting of the .'../zp-core/setup/index.php' file which is responsible for generating the error message, I found that under php 8.1 the 'ini_get' function for pulling the value of 'display_errors' returns an empty/null value when the parameter is set to 'Off' in the php.ini. Honestly I'm not sure if this is truly a Zenphoto bug since I would think the expected behavior would be to return the actual value of 'Off' and not an empty/null value.

Regardless, if I add another case statement to the switch test for 'display_errors' returned value which handles a null value, this correctly removes the error displayed in the setup page output:
![image](https://user-images.githubusercontent.com/30390295/208144218-4c51e05d-e4fc-428e-a7e7-2a8fc8fb32a9.png)

Again, I'm not sure this is a proper 'fix' for the issue since I still think php 'ini_get' should not be returning null output for an 'Off' parameter value but as of yet I haven't been able to find any php 8.1 bug report or change log which documents the issue or design change to explain this behavior. Anyways, I hope this information is helpful and, even if this is immediately closed, I post it in the hope that someone else on php 8.1 running Zenphoto will not be driven crazy by trying to resolve this 'error' which is not actually a true error :)

Cheers and thank you for all your tireless effort on Zenphoto!

**Comment by acrylian** [comment]
Thanks! The others already were added as we stumbled upon this lovely PHP inconsistency before, so this new variant must be indeed new. We'll add that.
