### ISSUE TITLE
1.6: Not showing top admin bar and can't login to it.

### ISSUE THREAD

**Issue by MarkRH** [zenphoto/zenphoto#1361]
Trying to update on my Webhost and initially was getting a server configuration error.  Well, trying again today I am not getting that but for some reason it's not recognizing that I'm logged in and if I try to go to the admin section I get:

![image](https://user-images.githubusercontent.com/8035962/208196066-85acbfdc-ee8c-4f17-b62c-33335534567f.png)

For the moment I've reverted back to the previous version and just wonder what I might want to check out.  I'm just seeing one deprecated warning and looking in the debug logs perhaps something is failing because of it.

**Comment by MarkRH** [comment]
I took care of that deprecated warning.  I was an old plugin and replaced it with a newer one that works locally.  Still not seeing that I'm logged in or letting me go to the admin section.  Weird.

**Comment by sbillard** [comment]
Most likely mod-rewrite is not set any more or rewrite rules are not working. The other possibility is file permissions not allowing  the scripts to be loaded.

**Comment by MarkRH** [comment]
I don't know.  They are both using the same database and same zenphoto.cfg.php file.  Was never able to run the setup on the new version.  So, all the settings should have remained the same.  All I do is change the **themes**, **zp-core**, and **plugins** folders, as well as the main **index.php** file when going between versions.  I am also switching to PHP 8.1 when running the 1.6 version.  I put it back on PHP 7.4 when using the older version since it doesn't work with 8.1.

Something's different from my local install versus the webhost apparently.  Not sure what.. following the same process.  I may try re-extracting all the Zenphoto 1.6 files again in case something went wrong with the ZIP and Unzip process when I uploaded the files to the server.

**Comment by acrylian** [comment]
I seriously have no idea except the already mentioned ones Is the modrewrite option actually enabled? Do non modrewrite URLs work?

Just to general affirm that 1.6 is really generally compatible with 1.5.9:
if there is no actual error anywhere…. @fretzl and I have updated lots of sites on around 8 different hosts and didn't run into any similar issue. All sites were on 1.5.9 (one 1.5.7) and even using custom themes that only had some general ZP deprecations to fix.

One was even a site where the hist disabled PHP 7 before we could update. So I could not login before running setup on 1.5.9. I had to upload 1.6 but since it is generally compatible could login there first and then run setups successfully.

**Comment by bic-ed** [comment]
On my local server, I get a notice in general options tab: _Setup did not detect a working mod_rewrite facility._
Nevertheless, everything is working properly, but I'm wondering if  that can be related with this issue.

**Comment by acrylian** [comment]
> On my local server, I get a notice in general options tab: _Setup did not detect a working mod_rewrite facility._ Nevertheless, everything is working properly, but I'm wondering if that can be related with this issue.

This is a general issue that there is no PHP way to check if mod_rewrite is working. We have to use a cURL/JS request to test a rewritten URL. For some reason that is not 100% reliable. If you know you have it you can just enable it always.

**Comment by MarkRH** [comment]
I am updating over version 1.5.7.. the same as I did with my local install, which worked.  Currently at my webhost with 1.5.7 active it does have mod_rewrite enabled with a mod_rewrite suffix of .php enabled.   This seemed to work fine with version 1.6 as all my image URLs did end with .php like before.

Screenshot of the 1.5.7 General Options screen:

![image](https://user-images.githubusercontent.com/8035962/208247731-d8dbd34b-f390-41ba-8d8b-74d88b39918f.png)

Perhaps I'll try some of the direct URLs next time or perhaps disabling mod_rewrite before doing the upgrade?

**Comment by acrylian** [comment]
Yes, that is the option. It not related to the setup check if mod_rewrite is actually working. You can enable that even if not breaking your site then of course. As said the setup check is a general one and not always 100% reliable. I have seen it reporting a failure while it actually was. But it seems so random… 

To my memory we didn't change anything in this area at all with 1.6…  If really have the htacess file which is still the same even as in 1.5.7 and it is correct and sure your server has modrewrite it "should" work

> Perhaps I'll try some of the direct URLs next time or perhaps disabling mod_rewrite before doing the upgrade?
Disabling would be a way to try. Zenphoto still does not require modrewrite (although I admit we do primarily test with and only on actual issues without…)

**Comment by acrylian** [comment]
I did one update from 1.5.7 as well and it was a big hoster so nothing really specifc and without issues. Not saying you don't have this issue, just that somehow you (again) encounter some specific issues sadly.

**Comment by MarkRH** [comment]
Well, I tried it again after disabling mod_rewrite first and still got no bar on top and going to the admin page just displayed the main gallery page without error. Hmmm..

**Comment by acrylian** [comment]
The gallery page does show up without the error above now? It ist just not clear to me, are you able to access the backend itself and login now? Did you look at the php error log. As usual the ZP debug log may miss something if it occurs earlier.

If you haven't try to clear the cookies and the browser cache manually. I have seen it causing all kinds of trouble these days… (lacking any other ida)

**Comment by MarkRH** [comment]
I cleared the browser cache and cookies for the gallery.  When I went to `zp-core/admin-options.php?tab=general` I got this:

![image](https://user-images.githubusercontent.com/8035962/208252233-4a9c35f6-9020-4581-8079-8ca1bd4f27c2.png)

It's thinking the album is zp-core.  I'll try again with mod-rewrite off and see what happens.

**Comment by acrylian** [comment]
Are you sure file/folder permissions are really correct?

**Comment by sbillard** [comment]
To get the above failure something must be wrong with checking for a file to exist. 

If mod_rewrite is enabled then the .htaccess processor would check to see if the link provided points to a real file, in this case the zp-core/admin-options.php script. If it is present, it is loaded and executed leaving you on the back-end options page. If it is not present then the processor redirects to the front-end scripts which will interpret the link as an album/image request. Of course such an album does not exits!

So, in my estimation the most likely scenario is that file permissions are not permitting the web server seeing the scripts. This has been know to happen when the web server runs under a different user than the FTP server. Try making the file permissions 0x777 and see it things work.

**Comment by MarkRH** [comment]
Hmm..  the file does exist there...  looking at the directories using Putty they all have the same group and username associated with them and the file permission match everything else.  The username associated with the files matches what I use to FTP into the server with and the current user of cPanel.  I can try setting the permissions on zp-core/admin-options.php to 777 and see what happens.

**Comment by acrylian** [comment]
Perhaps try lowering rights on zp-core itself as well. If that is already wrong you of course don't get to the file in the first place.

**Comment by MarkRH** [comment]
Well, I set the permissions on zp-core and zp-core/admin-options.php to 777 and I also decided to enable the **user_login-out** plugin before switching over.  Anyway, this time when going to the Gallery I did get the login forum which did allow me to login; although, I should already have been.  This time I got the bar above and it presented me the option to run setup; however, I then got the following:

![image](https://user-images.githubusercontent.com/8035962/208311329-ec571ce7-add7-4c7e-ac26-fa09fd3a8429.png)

This time it was thinking setup was an image.  Mod_rewrite was enabled while this was happening.  

Hmmm...

**Comment by sbillard** [comment]
Same problem, the server does not think that _zp-core/setup.php_ is an existing file so it redirects to the index.php script which tries to interpret it as an image page request. Given that file permissions got you a bit further, I would suggest  you make sure all the scripts have the 0x777 permission.

**Comment by acrylian** [comment]
If you haven't already, perhaps try deleting zp-core completely and re-upload a fresh 1.6 one first. Sometimes FTP clients can mess things up when copying over existing folders… Sometimes that fixes/resets things already.

**Comment by MarkRH** [comment]
Whenever I upgrade, I backup the themes and zp-core directories to something like zp-core157 or whatever and the database as well.  I then delete the zp-core and bundled themes and extract out the new code.  So, I'm not over-writing anything,  Also, I generally FTP up a zip file which I then unzip at the host.

I was thinking... I might try updating to 1.5.8 instead and see what happens. If that works, then 1.5.9 and so on.

**Comment by acrylian** [comment]
I did at least one upgrade directly from 1.5.7 so I really don't think this is causing your problem. Perhaps try not to use unzipping on server in case for some unknown reason that messes up permissions.

All updates I did recently were direct replacements of the zp-core folder via FTP, so without deleting it beforehand.

**Comment by MarkRH** [comment]
Yeah, at some point I'll try again.  I never got it completely working so I just left it at version 1.5.7 running PHP 7.4 something.  Down the road I may try to update it again or just try and create a new gallery at my Webhost using PHP 8.1 and perhaps copying my images over to that one.  I just needed a bit of a break.  Thanks for your efforts.  You can keep this as completed if you want.  I can make a new post in the future if needed.

**Comment by acrylian** [comment]
You can also re-open this if you have new info instead of a new one. Besides some bugs in 1.6 I am still generally clueless besides what already mentioned as none of the 1.6 updates I did mostly from 1.5.9 and with custom themes had any of these issues
