### ISSUE TITLE
1.6 final Image rotation fail

### ISSUE THREAD

**Issue by githlp** [zenphoto/zenphoto#1365]
The image rotation is not working in zenphoto. It seems not to be caused by unusual exif info as all linux image viewers display these pictures with correct orientation.

Also pictures are shown with incorrect orientation on album/picture detail page but when i click on the picture it is presented in an popup with correct rotation.

Nevertheless, as said before, the detail page and the gallery do not rotate pics correctly (or at all).

I use the Imagick graphics library.

**Comment by acrylian** [comment]
Thanks, we already know but not why. Except that we reworked the handling ot  classes we didn't change this. But we had constantly issues with this over the years.

(Please try to use the official terms to avoid confusion and possible unncessary questions from our end:
In your case you are referring to the album page, image page and the full or original image. The latter of course display the original image which is generally not processed (if it is using a popup depends on the theme btw).
"Gallery" in general refers to either the index page - if the site has one - or the Zenphoto site in total.
https://www.zenphoto.org/news/zenphoto-glossary/)

**Comment by acrylian** [comment]
According to @fretzl this seems to be a PHP 8 / 8.1 issue and works correctly with PHP 7.4.

**Comment by MakoWish** [comment]
Any updates on this? When uploading hundreds of photos, it is a royal pain to go through and rotate them manually. As @githlp mentioned, it is not an exif info issue, as everything shows correct on my Android phone, my wife's iPhone, and my Windows 10 computer, but when uploading from any of those three devices, the images are incorrectly rotated.

**Comment by acrylian** [comment]
Sorry, not yet, we'll inform here.

**Comment by MakoWish** [comment]
What's the fix?

**Comment by acrylian** [comment]
Correct rotation following EXIF standards.

**Comment by MakoWish** [comment]
Can you provide more details on that? All photos do have the correct rotation on the several devices we have tested from (iPhone, iPad, Samsung S20, Samsung S22, Samsung Note 8). Regardless of EXIF data on the images on these devices, ZenPhoto always rotates vertical images to horizontal orientation.

**Comment by MakoWish** [comment]
>the fix is ... in 1.6.1a

That's what I was looking for. Thank you!

**Comment by acrylian** [comment]
All right! Don't forget to clear the image cache as otherwise nothing will change.
