### ISSUE TITLE
typos in de_DE translation

### ISSUE THREAD

**Issue by tiltX** [zenphoto/zenphoto#1370]
Hi,

I have spotted the following translation error in zenphoto 1.6.
I hope it's ok to open an issue for this instead of trying to find out how to work with po files...

The typos are in this translation (found in zp-core/locale/de_DE/LC_MESSAGES/zenphoto.po)

```
#: zp-core/setup/index.php:2438
msgid "Begin converting UTF-8 tables to utf8mb4 collation"
msgstr "BEgine UT8-Tabllene in utf8mb4-Kollationen umzuwandeln"
```

and the msgstr should instead read:

`Beginne UTF-8-Tabellen in utf8mb4-Kollationen umzuwandeln`

**Comment by acrylian** [comment]
Of course tickets are for this. Thanks for the note, will fix that. Let me know if you find more as there are surely with all those strings.
