### ISSUE TITLE
Hacked but still okay :-)

### ISSUE THREAD

**Issue by RolandTi** [zenphoto/zenphoto#1372]
This morning I show that one of my album was broken.

Looking to the zenphoto root folder, I saw new files and folders that weren't supposed to be here.

*removed by admin*

Here is the error log.
*removed by admin*

Maybe it's just my fault and it's something about chmod :-)

**Comment by acrylian** [comment]
From the screenshots it's all in the root folder of your webhost I would assume a general issue on your server. Zenphoto can only control its own files and folders naturally.

Glad nothing major happened. Be sure to contact your host as well and also check your database.

**Comment by acrylian** [comment]
You might very well have a general permissions issue. Btw, it is probably not rally a good idea to expose possible issues like this on a public ticket… I will remove your images and file for that reason.

**Comment by RolandTi** [comment]
Hello acrylian, thanks for your answer.

**Comment by acrylian** [comment]
Just to add: I recommend to re-upload fresh Zenphoto files in case there have been unwanted changes.

**Comment by acrylian** [comment]
Closed as likely not ZP specific.
