### ISSUE TITLE
Just a typo in IT translation

### ISSUE THREAD

**Issue by FilippoBoscarino** [zenphoto/zenphoto#1374]
"Azzera tutti i gudizi" should become "Azzera tutti i giudizi".
It is on since earlier version, and should be a good occasion to fix it ;)

**Comment by acrylian** [comment]
Thanks, I am pretty sure that there a a lot of typos in almost all translattions. Please take over @bic-ed

**Comment by bic-ed** [comment]
Sure, I'll fix this tomorrow. Thanks!

**Comment by acrylian** [comment]
Great, no hurry!
