### ISSUE TITLE
jplayer options bug

### ISSUE THREAD

**Issue by FilippoBoscarino** [zenphoto/zenphoto#1382]
I well know this extension will be left soon, but in the meanwhile there some sort of a bug in the options edit page, that makes it unusable.
In the definition of the options, the code still tries to search its own skins in the user plugin folder, not in the zp_extension wher it has been moved.
So the edit page appears blank.

Unfortunately I am obliged to use this extension instead of the alternative mediaelementjs_player v1.1.2, because this one stops my video and audio when reproducing after few secs.
I haven't analized the reason yet.

I have no news about reliable alternatives at the moment.

**Comment by acrylian** [comment]
Actually it searches for custom skins and should not break if there aren't any. I will take a look. As long as it is included we do fix bugs, we just don't add new features or improvements.

The alternative is to use the class-video plugin as it offers the native browser players. All browser that are not stone age do support these by now.

**Comment by FilippoBoscarino** [comment]
It breaks if you do not have the user folder, as it is rather normal because it has been moved to zp_extensions.
In my environments during years, I eliminate the user plugin's branch, after it was included in main core

**Comment by FilippoBoscarino** [comment]
> The alternative is to use the class-video plugin

Unfortunately it works rather fine for video, but gives no solution for audio's sidecar

**Comment by acrylian** [comment]
> It breaks if you do not have the user folder, as it is rather normal because it has been moved to zp_extensions.
In my environments during years, I eliminate the user plugin's branch, after it was included in main core

No, it has not been moved. As many plugins it generally supports custom things - here skins - that then need to be placed within the plugins folder. I will take a look why this might breaks respectively if I can reproduce it.

> but gives no solution for audio's sidecar

I don't understand what "sidebar" you are referring to? A plain mp3 or m4a file gets a native player like this (here the Firefox ones):

![Bildschirmfoto 2023-03-25 um 12 45 10](https://user-images.githubusercontent.com/2474309/227715585-01fab9bc-e89a-4025-8ae7-6e0b1c78f0a0.jpg)

**Comment by acrylian** [comment]
Sorry, somehow misread "sidecar" to "sidebar"……………………………. Blame on the age ;)

1.6.1a has fixes for the sidecar images now but may require theme customization. It should be possible to use the version from 1.6.1a with 1.6 for the time being.
