### ISSUE TITLE
By default the included themes register at least one image size in cacheManager that is unnecessary

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1383]
I know you have set all included themes as deprecated as of 1.6, so this is not that big of a deal.

The main issue is that the **_Basic_** theme is registering an image size in cacheManager under _Image caching sizes_ for a size that does not appear to be used in the theme (80x160). Which you can see by expanding the entry:

![cacheManager options - Image caching sizes - expanded](https://user-images.githubusercontent.com/82089671/228776516-e072bdaf-fd9a-4201-9f6d-a847b87d9c01.png)

If you then run cacheManager, it will automatically select “all sizes for _Basic_” (or whatever theme you currently have activated, if it registered an image size, which all included themes do at least one).

![Cache images default options](https://user-images.githubusercontent.com/82089671/228777161-034b990c-d877-467b-b16c-64b32fe0fccb.png)

It is only when you expand the item, and if you’re paying attention, can you see that it will create a thumbnail that is not necessary.

![Cache images default options png - expanded](https://user-images.githubusercontent.com/82089671/228777223-02e4e87d-44d0-4a99-8ad1-3823373dfcd3.png)

While this is not the end of the world, it can add numerous files that you don’t need, especially on a large gallery.

The size is registered on line 38 of _themeoptions.php_, in the if statement if cacheManager exists:
`cacheManager::addCacheSize($me, 200, 80, 160, 80, 160, null, null, true, false);`

Since the Basic theme sets `addThemeDefaultThumbSize()` and `addThemeDefaultSizedImageSize()` in _themeoptions.php_, and as long as the options are selected in cacheManager, there is no reason for the theme to register any other size.

The other three included themes- **_Garland_**, **_Zenpage_**, **_zpMobile_** all register sizes as well in cacheManager, though they are all set to disable the ability to change the thumbnail and image sizes. So they really shouldn’t have to register sizes if they only passed on `addThemeDefaultThumbSize()` and `addThemeDefaultSizedImageSize()`.

Garland does not use `addThemeDefaultThumbSize()` and/or `addThemeDefaultSizedImageSize()`, it instead creates custom sizes for both images and thumbs. The problem, besides being unnecessary, is that if you look at the Garland Theme options while another theme is activated, it will set that theme’s thumbnail size. Then if you were to activate Garland without going back to Theme options, the thumbnail crop sizes will be wrong, as you can see here:

![Garland entry with thumb size from active theme](https://user-images.githubusercontent.com/82089671/228777785-39e20f80-8bfc-4966-842b-b4c4f02f604f.png)

Zenpage does both, it creates a custom entry for the image, but uses `addDefaultThumbSize();` for thumbs.

zpMobile does the opposite, `addDefaultSizedImageSize('zpMobile');` for the image, and creates a custom thumbnail entry.

![Zenpage and zpMobile entries](https://user-images.githubusercontent.com/82089671/228778179-33f95ad5-de16-4c16-8de2-b6284a957ff1.png)

It looks like these issues were kind of looked at in previous bug reports, but never fully addressed-

**cacheManager: default sized image and thumbs issue** #1180

**cacheManager: Custom cropping issue** #1182

**cacheManager plugin does not generate uncropped thumbnails** #1141

**Comment by acrylian** [comment]
I don't remember why basic registers a custom size. Perhaps because of plugin support…

Zenpage and Garland being based on Zenpage generally use hardcoded sizes within the theme for layout reason (yeah all before responsiveness, we know…) so their registration makes sense unless they are wrong. The reason for default sizes is that they may be used by plugins at some point.

To my knowledge these issue were addressed.

**Comment by JesseHC** [comment]
> I don't remember why basic registers a custom size. Perhaps because of plugin support…

Plugins can, and do, already register their own sizes in cacheManager, so Basic shouldn’t have a reason to do it. On a pretty basic install I have sizes registered from plugins slideshow2 (cycle), html_meta_tags, and openstreetmap.

> Zenpage and Garland being based on Zenpage generally use hardcoded sizes within the theme for layout reason (yeah all before responsiveness, we know…) so their registration makes sense unless they are wrong. The reason for default sizes is that they may be used by plugins at some point.

Like I said, there is an issue with the way Garland handles thumbs, and can lead to them being cropped, and then sized wrong in the cache, if pulled from another active theme.

This is an issue _especially_ since their theme sizes are hardcoded, and even more the reason why they shouldn’t be putting entries in Image caching sizes. They should be using `addThemeDefaultThumbSize()` and `addThemeDefaultSizedImageSize()`.

Besides adding extra entries when not needed, a real issue is that a user can change the size entries in cacheManager, apply them, and then for a hardcoded theme all the sizes created for the cache will be wrong. Since the themes are hardcoded, the pages will recache on each page load, but it is unnecessary and can potentially create lots of extra files and confusion.

Here's Garland with a bunch of random sizes put in-

![Garland - random sizes](https://user-images.githubusercontent.com/82089671/228808866-d542d6b8-8450-4ce4-8073-b42072c58314.png)

and then being cached-

![Garland - random sizes being cached](https://user-images.githubusercontent.com/82089671/228808943-8726deeb-e384-4588-846f-345a1f2113a5.png)
