### ISSUE TITLE
Images will not be created in grayscale if they also have watermarks set when using Imagick, works in GDlibrary

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1386]
With Imagick set as the graphics library, images and thumbnails will not be created in grayscale, if the option is set under Theme options, and if they also have watermarks set in Image options (which you can easily test by setting to either “copyright” or “watermark-text”). They will be created in color with watermarks. The images will be created in grayscale when no watermarks are set. All versions work if using GDlibrary.

This was tested in 1.6.1a with the Basic and Garland themes, both by loading pages and through cacheManager (even though both themes create images differently in themeoptions.php).

Currently in themeoptions.php Basic adds addThemeDefaultThumbSize() and addThemeDefaultSizedImageSize(), Garland checks for grayscale and watermark options and then registers them as custom sizes.

Tested with:
- Zenphoto 1.6.1a
- PHP 8.2.0
- PHP Imagick library 3.7.0
  ImageMagick 6.9.6-2 Q16 x86_64 2022-12-08
- PHP GD library bundled (2.1.0 compatible)

**Comment by acrylian** [comment]
Thanks, that sounds like a bug that the setting is ignored somehwere

**Comment by acrylian** [comment]
Should be fixed now.
