### ISSUE TITLE
PHP 8.1: Deprecation warning when page does not exist (404.php)

### ISSUE THREAD

**Issue by sphoto** [zenphoto/zenphoto#1387]
Found this entry in debug.log (using latest zp from github):

`DEPRECATED: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /blah/zp-core/404.php on line 5
  explode called from include (404.php [5])
    from include (index.php [133])
      from index.php [79]
`

**Comment by acrylian** [comment]
Thanks, we fixed loads of these but there are probably still plenty hidden…  Btw, we test on 8.2 already.

**Comment by fretzl** [comment]
Fixed via 1fe15f8
