### ISSUE TITLE
MySQL PW's can not contain certain special characters

### ISSUE THREAD

**Issue by ember1205** [zenphoto/zenphoto#1390]
Discovered on a new installation in 1.6, MySQL PW contained a "$" character and the install kept locking up / showing a 500 error. Searching the setup log revealed what -looked like- a bad variable being encountered until I realized it matched a portion of the PW being used for the MySQL connection.

**Comment by acrylian** [comment]
I think this is a mysql limittation. I have never encountered mysql passwords witht special charrs on any host. Can't test it either because I cannot change them. 

Perhaps take a look here: https://www.infomaniak.com/en/support/faq/2559/mysql-create-a-password-with-special-characters

**Comment by ember1205** [comment]
MySQL can accommodate the special character as a portion of a password. The page you linked to discusses specifically how to be able to pass that password by enclosing it in quotes, escaping the character, etc.

Also, I have other MySQL db's that are using passwords that contain special characters without an issue.

**Comment by acrylian** [comment]
Yes, true, but that escaping is what you could try in the config file, The config file uses single quotes (so no $ should be executed) Code wise I don't see any limits. We use mysqli and pdo pretty straightforward. You need to help here a little.

Also, please post the exact error message you mentioned.

**Comment by ember1205** [comment]
I can't (won't) post the "exact" error message because it contains a portion of a password. Here is an example of the SORT of error where I've replaced the specific detail with a generic reference:

`Assume MySQL Password of "Pa$sw0rd"`

Error in the local apache log would be:

`WARNING: Undefined variable $sw0rd`

This occurs using the mysqli connection method. I suspect that the pdo method suffered the same issue but it was "elegant" enough to show an error on the setup page stating that the credentials didn't have access (like because the full password was not being used).

As far as manually editing the configuration file, that isn't unreasonable to have to do, but at this point I have the site up and running and I would have to change the PW and then experiment to see if I can get it working using the special characters. If I'm able to do that, it will take me a little bit of time.

**Comment by acrylian** [comment]
> This occurs using the mysqli connection method. 
Of course always an anonymized error message. I just wanted to know where it occurs exactly.

In any case you should always look at the logs as not everything is put out on the frontend and actualy error messages should not in any case of course.

Perhaps it was a submission issue with the form only? If directly entering in the config file works but via form not hat would be a clue.  Let me know if you find anything.

**Comment by ember1205** [comment]
The info I got was from the logs because the front-end only showed a 500 Error with no content.

As I mentioned, MySQL fully supports these characters in the password field, and PHPMyAdmin is able to access and pass them cleanly as well. That would meant that ZenPhoto either doesn't properly escape them in the configuration or pass them correctly somehow, or the Admin GUI isn't correctly converting them for storage in the configuration file. I don't see anywhere in the Admin GUI to "change" the MySQL password which seems to imply that I will have to completely set my site back up from scratch in order to try again.

**Comment by acrylian** [comment]
So you did try editing the config file directly so we can sort out a form submission issue from setup?

**Comment by ember1205** [comment]
I tried a variety of different ways to set the password, but only one worked - you have to escape the special character in the stream of characters.

So:
`Pa$sword`

Becomes
`Pa\$sword`

And the whole line becomes:
`$conf['mysql_pass'] = "Pa\$sword";`

Once the special character is escaped, the site goes back into a functioning mode and the 500 Error outputs stop.

**Comment by acrylian** [comment]
Okay, that follows the link info I had posted. Does that escaping work with the form as well?

**Comment by ember1205** [comment]
Short of setting the site up from scratch, how/where would I test this? 

Wouldn't it be simpler and more appropriate to provide a test in the form submission that detected special characters and escaped them before writing them to the configuration file? Once you type the password in, it gets written to the config file and "you're done." If it wasn't captured and written to the file correctly, the server is broken and can't be recovered without either starting all over again or manually editing the file - the user only gets the "500 Error" with no other text. For those users who don't have shell access and/or an ability to parse server logs, they will be completely dead in the water as they won't know where to start troubleshooting.

**Comment by acrylian** [comment]
Yes, escaping by code is probably better. I was just curious if that would work becauseI cannot test it myself. 

> For those users who don't have shell access and/or an ability to parse server logs, they will be completely dead in the water as they won't know where to start troubleshooting.

Besides access to server logs is always important if self hosting anything of course.

**Comment by acrylian** [comment]
> Create a configuration control that allows the user to change the MySQL information at any time

That is actually what the config file for. That is not that hard and if you install Zenphoto you need FTP access anyway. 

> Create a validation process around any password fields necessary to check for special characters and ensure they are written correctly to the configuration files

Actually I would not write the escaped password to the config file but rather escape it before using it.

> Update the process so that a hard error from something like an unknown variable will still render a page and not "brick" the server (a non-escaped $ character in a password field for MySQL in the configuration file renders every function of the server inoperable and the user has no way to even know of the problem let alone a straightforward way to correct it). Maybe the MySQL connect should be a spawned process instead of done directly within the setup page? That would seemingly allow for a return code to be used in rendering content to the user or similar.

Generally that is what the debug or setup logs are for. why access to server error logs is important. That unknown variable issue happens right in the mysql connection process and is too serious so we cannot log it. The connect methods of both handlers actually do log connenction errors if they can.

**Comment by acrylian** [comment]
Is it actually only `$` we need to escape or also any/some other chars? If you can test that please do.

**Comment by ember1205** [comment]
> > Create a configuration control that allows the user to change the MySQL information at any time
> 
> That is actually what the config file for. That is not that hard and if you install Zenphoto you need FTP access anyway.
> 

The best way to drive adoption is to develop for the masses not just for those with a deeper understanding of technology. While you're correct in needing FTP access, that doesn't translate to shell access, and neither guarantees the user will be comfortable in making a direct edit to a file even if they were able to troubleshoot the issue to know how, where, and why to make that actual change.

> > Create a validation process around any password fields necessary to check for special characters and ensure they are written correctly to the configuration files
> 
> Actually I would not write the escaped password to the config file but rather escape it before using it.
> 

So long as its use is done consistently and is well-documented for users and developers alike, then I suppose it does truly matter. However, having to parse the configuration to seek out specific characters that need to be escaped, then modifying the PW string to include the escaped characters... every time... ultimately results in reduced performance.

> > Update the process so that a hard error from something like an unknown variable will still render a page and not "brick" the server (a non-escaped $ character in a password field for MySQL in the configuration file renders every function of the server inoperable and the user has no way to even know of the problem let alone a straightforward way to correct it). Maybe the MySQL connect should be a spawned process instead of done directly within the setup page? That would seemingly allow for a return code to be used in rendering content to the user or similar.
> 
> Generally that is what the debug or setup logs are for. why access to server error logs is important. That unknown variable issue happens right in the mysql connection process and is too serious so we cannot log it. The connect methods of both handlers actually do log connenction errors if they can.

If the only way to troubleshoot an error is by having access to server logs AND being able understand them for troubleshooting purposes, this is another way of limiting adoption. The cleaner and more resilient the base code is so that it can detect errors and report something back to the admin about them, the smoother it will be for new admins to get the product up and running and continue using it. The issues I ran into were a hard stop right out of the gate for me. Had I not literally stumbled across the line in the access log and had an "a-ha!" moment with it, ZP would be deleted and removed from my server and I would not be looking back at it again down the road.

Creating a separate routine to at least -test- the connection during setup and report back on its status is significantly more valuable to admins than using only logging.

**Comment by acrylian** [comment]
Well, we cannot keep users from learning a few things like editing a config file. We are talking about selfhosting so you need to be able to learn and know a few things. It's even that way on a certain CMS that really is for the masses.

> However, having to parse the configuration to seek out specific characters that need to be escaped, then modifying the PW string to include the escaped characters... every time... ultimately results in reduced performance.

There is nothing to "parse" except the password right before the db handlers try to setup a connection.

**Comment by ember1205** [comment]
> Is it actually only `$` we need to escape or also any/some other chars? If you can test that please do.

Of the set of characters:
`! @ # $ % ^ & * ( )`

Only one needs to be escaped:
`$`

All others work fine without being escaped.

**Comment by ember1205** [comment]
> Well, we cannot keep users from learning a few things like editing a config file. We are talking about selfhosting so you need to be able to learn and know a few things. It's even that way on a certain CMS that really is for the masses.
> 

While this is very true for those that are self-hosting in their home or similar, they are not "the masses." If there is any interest in getting widespread adoption of the product, it has to appeal to those that are -not- tech savvy.

> > However, having to parse the configuration to seek out specific characters that need to be escaped, then modifying the PW string to include the escaped characters... every time... ultimately results in reduced performance.
> 
> There is nothing to "parse" except the password right before the db handlers try to setup a connection.

Except that it would be done every single time a db connection is required - that's where the reduced performance comes in. Compared to other photo library products, ZP is noticeably slower than many that I have used or am testing alongside of currently already.

**Comment by acrylian** [comment]
> ! @ # $ % ^ & * ( )

Good, only that one is pretty simple and does not really add much overhead. A simple search+replace will do. And storing an escaped password in the config file  would especially confuse those users not that tech savy in case they have to edit it  (and for a few custom things it needs to).

That Zenphoto may feel a bit slow is probably the result of image size generation. Zenphoto does not pre-generate fixed sizes as other products do as it allows themes etc use sizes as they need/request them.  They are generated then. There is a cacheManager plugin available to pregenerate sizes.

> While this is very true for those that are self-hosting in their home or similar, they are not "the masses." If there is any interest in getting widespread adoption of the product, it has to appeal to those that are -not- tech savvy.

Well, with all the convenient services out there we will never reach those "masses" you refer to. That ship has sailed anyway.

**Comment by acrylian** [comment]
The $ sign is now escaped if needed.

**Comment by wongm** [comment]
I've encountered the same issue when upgrading from Zenphoto v1.6 to v1.6.1 for a site that usages a MySQL password containing a mix of these special characters:

```
%+#}->]/$>
```

However the bugfix that addressed this issue only fixed the problems if only a `$` is found in the MySQL password.

I ended up working around the issue by rotating the MySQL password being used for the Zenphoto install.

**Comment by acrylian** [comment]
We of course tested the set as noted and reported above. Not really common mysql password chars, I would think. We could use e.g. addcslashes() with a catalogue of chars to escape. Not sure if that is a good solution…

**Comment by acrylian** [comment]
I still think this is perhaps sort of bug in PHP itself. Especially if it worked before 1.6. We just followed the docs basically…

**Comment by acrylian** [comment]
I found no actualy limit in the mysql docs but it seems to depend on server side encoding: https://dev.mysql.com/doc/refman/5.7/en/user-names.html
