### ISSUE TITLE
xmpMetadata exporting a:1:{s:5: plus additional text at start and end of description and headline/title in XMP files

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1393]
I noticed that xmpMetadata is exporting _a:1:{s:5:_ and additional text at the start, plus more text at the end of:

`<dc:description>`
and
`<photoshop:Headline>`

under
`<rdf:Description>`

The problem is that if you hit “Refresh Metadata” the a:1:{s:5: text is added to the metadata that then shows on the page under “Image Info”. It is sanitized from the main Title and Description fields, so it does not appear there.

I tested this on tonight’s version of 1.6.1, but going through my XMP files, the problem has been there for years.

For example, I get:
`a:1:{s:5:&quot;en_US&quot;;s:87:&quot;`
at the beginning of one entry, and 
`&quot;;`
at the end.

The last letter and number combo is always different, but the _a:1:{s:5:_ is always the same. You can see it in the database under the "desc" and “title" fields.

**Comment by acrylian** [comment]
If these are output on display of metadata it might be a but in the plugin itself not extracting the correct language string.

**Comment by JesseHC** [comment]
> If these are output on display of metadata it might be a but in the plugin itself not extracting the correct language string.

It is a bug, that's what I'm saying. I get how they are stored in the database, the problem is that they are showing in Image Info after being added on export with xmpMetadata.

I actually think I found the problem, and it also affects Album Location. It appears to be on lines 758 to 764 in xmpMetadata.php. You can see there that it is setting those three entries (Desc, Title, and Location) with the additional “self::to_string”. None of the other entries have it.

**Comment by acrylian** [comment]
Sorry, I read to fast apparently answering quickly inbetween. I don't know the plugin too well - rarely use it myself, too - so I don't know what the reason for this is. Our multilingual strings are of course serialized strings that need no conversion itself.

If I see right this part is doing the import into the album from an XMP file so perhaps an XMP file can contain data making this necessary? `to_string()` is also used on some image values.

**Comment by JesseHC** [comment]
The XMP file entries should never have, or need, this extra Zenphoto catalog info in them.

Here’s how you can easily test that this is a problem, with the xmpMetadata plugin active, go to any Album in admin. Make sure there is text in “Album Title”, “Album Description”, and “Location”. Then under the Utilities box click “Export metadata info to XMP sidecar”.

Look at the resulting XMP file. All three entries, and only those three entries, will have extra database info added. If you do a “Refresh album metadata”, none of the database extra info is added back into the album admin page. While you will have a messed up XMP file for your album, it’s not that bad, because the text is somehow sanitized or ignored when you import it.

The real issue comes when you try to do anything with images. If you try the same thing for an image (minus “Location” since that entry is not available in admin), the XMP file will again be messed up for those two fields. When you import the XMP by doing a “Refresh Metadata”, the text in Title and Description will again be sanitized, though the Image Headline and Image Caption under Metadata will now be messed up, with no way to edit it unless you manually edit the XMP file and do another refresh (while making sure to never export the metadata again).

So this can cause real problems with anyone using XMP files created outside of Zenphoto, or created inside Zenphoto when they use xmpMetadata.

The one difference I’ve noticed is with Location. On exporting from an image with a sub-location added, the Sub-location metadata field will not be messed up, even though the Album page and the Image page both use and write to the same `<Iptc4xmpCore:Location>` in the XMP file. Maybe that will help you in tracking down this bug.

**Comment by acrylian** [comment]
Thanks for the report.  

> When you import the XMP by doing a “Refresh Metadata”, the text in Title and Description will again be sanitized, though the Image Headline and Image Caption under Metadata will now be messed up,

This sound like the multilingual serizalized string may not be properly processed.  However methods like `setDesc()` to process multilingual fields normally.

Of course metadata is never multilingual, neither EXIF/IPTC or XMP. At least I don't know about that. If this multilingual data is an issue itself we to can use the language the user doing the export has active. This of course means the export would be truncated and not complete.

**Comment by acrylian** [comment]
Finally got to look into this. This is quite easily fixed. However it will not be possible to export multilingual data as it then is limited to the the current user's language.
