### ISSUE TITLE
setOptionDefault() creates new records on each page load

### ISSUE THREAD

**Issue by wongm** [zenphoto/zenphoto#1395]
Hello,

I've been debugging an issue with my ZenPhoto install, and have pinned it down to an out of memory error when MySQLi does a `fetch_assoc()` call.

The failing call is when MySQL queries the `options` database table, and it finds 290,811 rows. I have checked my old database backups, there are only 2000 or so records in that table.

I then ran this query to see what all of these values in the `options` table were:

```
SELECT creator, count(1) FROM `zen_options` group by creator;
```

Giving me these counts:

```
| creator                                         | count(1) |
+-------------------------------------------------+----------+
| zp-core/lib-auth.php                            |   140557 |
| plugins/nocaptcha_recaptcha.php                 |   132055 |
| NULL                                            |    16924 |
[snip]
```

With the `null` owner records look like this:

```
+--------+---------+-----------------------+---------+-------+---------+
| id     | ownerid | name                  | value   | theme | creator |
+--------+---------+-----------------------+---------+-------+---------+
|   1163 |       0 | Page-Hitcounter-index | 3252457 |       | NULL    |
| 621940 |       0 | Page-Hitcounter-index | 3252459 |       | NULL    |
| 621946 |       0 | Page-Hitcounter-index | 3252459 |       | NULL    |
| 621952 |       0 | Page-Hitcounter-index | 3252460 |       | NULL    |
| 622015 |       0 | Page-Hitcounter-index | 3252461 |       | NULL    |
| 622028 |       0 | Page-Hitcounter-index | 3252462 |       | NULL    |
| 622044 |       0 | Page-Hitcounter-index | 3252462 |       | NULL    |
| 622078 |       0 | Page-Hitcounter-index | 3252463 |       | NULL    |
| 622127 |       0 | Page-Hitcounter-index | 3252464 |       | NULL    |
| 622138 |       0 | Page-Hitcounter-index | 3252465 |       | NULL    |
| 622147 |       0 | Page-Hitcounter-index | 3252466 |       | NULL    |
```

From this it appears that each visit to my ZenPhoto gallery creates new records  in the `options` table, slowly filling up the table. 

I can see that the `lib-auth.php` class calling `setOptionDefault` twice in the constructor, and `nocaptcha_recaptcha.php` calling it three times.  And the Page-Hitcounter records are written from `zp-extensions/hitcounter.php`.

I've had a look at the implementation of `setOptionDefault` here:

https://github.com/zenphoto/zenphoto/blob/efdb574866915f6961922b3104b0e31c0b38898d/zp-core/functions/functions-basic.php#L458

However I can't see anything obvious as to why the records keep getting added to the database, rather than existing ones retained.

**Comment by wongm** [comment]
I did update permissions for the MySQL user in recent weeks, so maybe a cause could be database `UPDATE` calls being executed as `INSERT` instead. But user has `GRANT ALL PRIVILEGES` against them, so I don't think that is it?

**Comment by wongm** [comment]
And I think I know cause now - when I messed around with restoring DB recently I must've blown away the MySQL constraint that prevented duplicate keys from being inserted. 

So with that gone, every time page is loaded, a new record is created, rather than the existing record being updated.

Fix will be to work out what constraint ZenPhoto puts on the page, and reapply it.

**Comment by wongm** [comment]
And this is the DB constraint I was missing.

```
 alter table zen_options ADD CONSTRAINT `unique_option` UNIQUE(`name`,`ownerid`,`theme`);
```

After adding it, duplicate records are no longer being added to the `options` table.

**Comment by acrylian** [comment]
Good you fixed it. Did you try running setup to fix this, too?

Also, you also probably should update because lib-auth.php does not exist anymore since 1.6. and nocaptcha_recaptcha.php I don't even remember… The official plugin is reCaptcha for quite some time now.

**Comment by wongm** [comment]
I ran into this issue again today upgrading an old site from v1.5.9 when I went via v1.6 and v1.6.1.

The symptom this time around was that my configured thumbnail image size being ignored, with Zenphoto using the 100x100px square size instead.

I'm still not sure what the cause is - maybe just a very old MySQL database schema?

My fix this time was to just replace my database with my backup from before the upgrade, and things started working again.

**Comment by acrylian** [comment]
Check the setup of your options table. It should look like this (Sorry, in German mostly but you should get it):
![Bildschirmfoto 2024-03-18 um 11 02 17](https://github.com/zenphoto/zenphoto/assets/2474309/b33b779a-ef92-419f-8226-fb73914cb502)

As you see the "theme" is unique. Been some time I looked at it and I just wonder why we have "theme" and "creator" as that basically seems to be doubling each other, desspite one is just the theme name and one partly a path. Anyway, an empty value is also a unique value I would think.

Any custom queries outside usage of the official getOption()/setOption() and their variants perhaps that may do things wrong?
