### ISSUE TITLE
Sitemaps generation error in 1.6.1b: gallery pages

### ISSUE THREAD

**Issue by kuz-z-zma** [zenphoto/zenphoto#1397]
I have several sites, running Zenphoto.
2 of them use 1.6b version, one was updated to then current version on 25/11/23, another was updated to then current version on 28/11/23.

Thanks to Google Search Console, I've discovered that sitemaps-extended has an issue, that got worse in the latest release.

Earlier version (25/11/23) generates following links in sitemap-zenphoto-index.xml file: 
```
<url>
		<loc>https://www.mysite.net/page/gallery//</loc>
		<lastmod>2023-10-20T00:38:19+03:00</lastmod>
		<changefreq>daily</changefreq>
		<priority>0.9</priority>
	</url>
	<url>
		<loc>https://www.mysite.net/page/gallery/2/</loc>
		<lastmod>2023-10-20T00:38:19+03:00</lastmod>
		<changefreq>daily</changefreq>
		<priority>0.9</priority>
	</url>
```
Note the double of **//** in the first link, this will result in mere redirect flag for this page in google search console and might damage seo.

But latest version (from 28/11/23) does this:

```
<url>
<loc>https://www.mysite.net/page/gallery.php//</loc>
<lastmod>2023-12-01T18:09:59+03:00</lastmod>
<changefreq>daily</changefreq>
<priority>0.9</priority>
</url>

```

Link to gallery gets **.php//** at the end and this results in 404 page for one of the most important pages in site, which will damage SEO efforts.
I was able to catch this early on, but anyone with bigger number of 404 pages might not see it in time.

**Comment by acrylian** [comment]
I believe you that you see that. But I need to be able to reproduce it in any case. If you use a custom(ized) theme please check that you don't accidentally have something like gallery.php.php.

**Comment by kuz-z-zma** [comment]
The theme is identical, I've reuploaded theme folder to be sure and regenerated sitemaps.
Same distinctions in generated data.

I've checked with basic theme - with the same results.

**Comment by acrylian** [comment]
Okay, just trying to rule out a few things.

> I've checked with basic theme - with the same results.

Interessting, basic does not have a `gallery.php` theme page at all.

**Comment by kuz-z-zma** [comment]
I tried again with cleaning cache first, just to be sure.

Site with 25/11/2023 snapshot
Basic theme - No gallery page in sitemap! - Probably cache fault.
Garland - gallery// in sitemap

Site with 28/11/2023 snapshot
Garland - gallery.php// in sitemap

**Comment by acrylian** [comment]
> Probably cache fault.

I don't really think so as the sitemap generation is independent from the static_html_cache. Regarding the .php with Garland this is probably a problem with its home page option. Try resetting that option please. just to be sure.

At least from our side there have been no sitemap related changes in November so that can't be the cause.

I will try to look into it tomorrow.

**Comment by acrylian** [comment]
The double slash is fixed. I am sorry, I still cannot reproduce that `.php` suffix issue.

**Comment by acrylian** [comment]
Since we both cannot reproduce your other issue we have to consider this fixed.
