### ISSUE TITLE
zpBootstrap theme options gones with 1.6.1

### ISSUE THREAD

**Issue by mikael35** [zenphoto/zenphoto#1398]
No more options in the zpBootstrap options/theme tab.
Using [forked](https://github.com/zenphoto/zpBootstrap) , PHP Version 8.1.7 .

**Comment by acrylian** [comment]
Please open a ticket on the zpBoostrap fork repository itself instead. Please review your error logs please if you haven't yet before doing so. Besides, I cannot reproduce this on our demo site (currently PHP 8.1.22).
