### ISSUE TITLE
Sitemaps generation: news categories lists page 1

### ISSUE THREAD

**Issue by kuz-z-zma** [zenphoto/zenphoto#1400]
In generated sitemaps (file sitemap-zenpage-categories.xml) the first page of news category is listed as news/category/category-name/1/ while it should be just news/category/category-name/,  in 1.6.1 the similar issue was addressed concerning overall news page.

**Comment by acrylian** [comment]
Oh, indeed, thanks. Somehow we missed that with the other fix although we did check other page 1…

**Comment by acrylian** [comment]
Sorry, for the delay, busy with other stuff. Will look into this on the weekend. Been thinking if we actually need to include pagination besides the first page at all or at least offer an option to include/exclude pagination (being off by default). SEO tools for another "big wellmown CMS" don't include that at all.

**Comment by kuz-z-zma** [comment]
Usually, no - pagination is not included & these pages often closed from indexing, as their content changes with each new addition and indexing those won't help user to find specific info/article/content. Search engines are encouraged to index individual articles instead.
What we need is a list of categories & individual articles/blog posts in sitemaps.

**Comment by acrylian** [comment]
Yes, exactly what I have been thinking. Of course we already do have home/gallery index, albums, images, pages, articles and categories. We don't list tags however which those other tools do.

**Comment by acrylian** [comment]
Will see to extend html_meta_tags to always set "noindex" for page 2 onward pages.

**Comment by acrylian** [comment]
Fixed in the support build now. Pagination is excluded but options have been added to enable them just in case anyone needs it

**Comment by kuz-z-zma** [comment]
hm... I've installed fresh support build checked Sitemaps options - all pagination is disabled and what I get now is 

```
<url>
<loc>https://www.collector.private-universe.net/news/category/reviews/1/</loc>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>

```
for all news categories instead of just :
`<loc>https://www.collector.private-universe.net/news/category/reviews/</loc>`

**Comment by acrylian** [comment]
Ah, really? Then something must have slipped through, will check on that later.

**Comment by kuz-z-zma** [comment]
Albums work as expected though, no page 1 or other pagination for them.

**Comment by acrylian** [comment]
Yeah, albums were an earlier change before this. Anyway, will cover this later.

**Comment by acrylian** [comment]
Should be fixed now.

**Comment by kuz-z-zma** [comment]
Works great!
thank you!
