### ISSUE TITLE
Maybe dynamic album issue 

### ISSUE THREAD

**Issue by RolandTi** [zenphoto/zenphoto#1401]
Hello !
I updated my website here : https://collections.rolandtisserand.fr/ with the last version of Zenphoto.
The gallery homepage is now stuck in a loop. I got the error : 
`[03-Jan-2024 15:39:47 Europe/Paris] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 40960 bytes) in /home/xx/collections.rolandtisserand.fr/htdocs/zp-core/classes/class-searchengine.php on line 871`
So I updated the memory to **390M** and the first page now render properly. The second page is still blank : https://collections.rolandtisserand.fr/page/2/.

Here is the apache.log : 
```
[Sun Jan 07 14:18:07.138758 2024] [fcgid:info] [pid 2416046:tid 140512823125120] mod_fcgid: server collections.rolandtisserand.fr:/usr/bin/env(1881055) started
[Sun Jan 07 14:18:10.825870 2024] [fcgid:info] [pid 2416046:tid 140512823125120] mod_fcgid: server collections.rolandtisserand.fr:/usr/bin/env(1881497) started
[Sun Jan 07 14:18:14.097922 2024] [fcgid:info] [pid 2416046:tid 140512823125120] mod_fcgid: server collections.rolandtisserand.fr:/usr/bin/env(1881942) started
[Sun Jan 07 14:18:20.723670 2024] [fcgid:info] [pid 2416046:tid 140512823125120] mod_fcgid: server collections.rolandtisserand.fr:/usr/bin/env(1882227) started
[Sun Jan 07 14:18:22.954088 2024] [fcgid:info] [pid 2416046:tid 140512823125120] mod_fcgid: server collections.rolandtisserand.fr:/usr/bin/env(1882348) started
[Sun Jan 07 14:19:36.534439 2024] [fcgid:warn] [pid 2416047:tid 140507950860032] (32)Broken pipe: [client 2a01:cb08:9b5d:e900:691c:b57a:1304:b8e4:0] mod_fcgid: ap_pass_brigade failed in handle_request_ipc function, referer: https://collections.rolandtisserand.fr/
[Sun Jan 07 14:20:20.591913 2024] [fcgid:warn] [pid 2416047:tid 140510500996864] (32)Broken pipe: [client 2a01:cb08:9b5d:e900:691c:b57a:1304:b8e4:0] mod_fcgid: ap_pass_brigade failed in handle_request_ipc function, referer: https://collections.rolandtisserand.fr/
```
There is nothing in the debug panel. A tried also on MAMP, still buggy, whereas I can use ZP 1.6

Here is the code of the page : https://github.com/RolandTi/collections/blob/main/collections/gallery.php

Any clue ?

*edit : I should add that there is an existing cache folder with all the pictures.

**Comment by acrylian** [comment]
You certainly should not need 390M for running a site. I don't see any reason from the code of the page. What does the printCodeblock() call do?

We don't have the theme on our demo as I remember that it eitehr didn't work with 1.6. when we added more third party themes or not with PHP8+ at the time. Will check if I can reproduce any issue with it locally using MAMP.

First thing to check is also if this happens with a standard theme to rule out that it is something else within your theme.
Also check the theme options for the transition page as that internal handling changed in 1.6.

**Comment by acrylian** [comment]
Btw sidenote If you name your footer/header files inc-*.php or just footer/header.php they are excluded from any theme page selector e.g. for the homepage automatically with 1.6.1. inc-*.php may be the naming convention for  "partial theme pages" like these in the future.

**Comment by acrylian** [comment]
It works without any issue with my standard development installs using MAMP and PHP 8.2.0. using 128M memory which is the same our live server has and a quite common value for a proper hosts nowadays. 203 images in 41 albums - 32 of these are toplevel for the gallery index -  and I even freshly cleared the image cache to really force memory usage.

This and especially the `[Sun Jan 07 14:20:20.591913 2024] [fcgid:warn] [pid 2416047:tid 140510500996864] (32)Broken pipe: [client 2a01:cb08:9b5d:e900:691c:b57a:1304:b8e4:0] mod_fcgid: ap_pass_brigade failed in handle_request_ipc function, referer: https://collections.rolandtisserand.fr/´ warning from your log sounds more like a server side configuration issue. As if something is not setup correctly.

**Comment by acrylian** [comment]
I also added it to https://demo.zenphoto.org/ and it also works without issue. Of course the demo only has two albums at the moment.

**Comment by RolandTi** [comment]
Hello @acrylian,
thanks for being always that fast and sorry for not even thinking about switching theme :')

So, my Zenphoto was stuck because of a dynamic album who wasn't shown anymore in admin.
The file was called **all.alb** and here is the content  : 
```
WORDS=*
THUMB=1
FIELDS=desc,location,tags,title
CONSTRAINTS=inalbums=0&inimages=1&unpublished=0

``` 

I deleted the file and solve my problem.
Creating the same query again in the Zenphoto admin panel with a similar filename seem to work.

Maybe something with file permissions, I don't now the reason.

**Comment by RolandTi** [comment]
> Btw sidenote If you name your footer/header files inc-_.php or just footer/header.php they are excluded from any theme page selector e.g. for the homepage automatically with 1.6.1. inc-_.php may be the naming convention for "partial theme pages" like these in the future.

Ok thanks !

**Comment by acrylian** [comment]
Good you solved it. Actually the content of your all.alb is still okay and how the query is saved in the file. That query is also saved in the db additionally. Did you have the search cache active? If any things behaves weird always clear that cache or even disable it. 

There have been internal changes in 1.6.1 that should not affect existing dynamic albums per se but searches in general. This was because of some bugs regarding the search fields selection and the search urls itself (see the release post please). There was even a transition before 1.6.1 was finished  where this was broken

**Comment by RolandTi** [comment]
Hello,
I used a snapshot to reproduce the event. Deleting the row of the dynamic album solved the problem too. Whereas the re-generated one is exactly the same…

Anyway, I turned off the cache search.
