### ISSUE TITLE
Deprecated: strtr(): with zenpage plugin enabled.

### ISSUE THREAD

**Issue by RolandTi** [zenphoto/zenphoto#1405]
Hello !
_I now it's just a depreciation_, that happen only on PHP 8 (tested on PHP 7),
with the zenpage plugin enabled. It appear on top of Zenphoto when the debug mode is active with de markRelease plugin.

```
Deprecated: strtr(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/roland/Sites/24_zenphoto-161-FR/zp-core/functions/functions-rewrite.php on line 130

Deprecated: strtr(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/roland/Sites/24_zenphoto-161-FR/zp-core/functions/functions-rewrite.php on line 130

Deprecated: strtr(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/roland/Sites/24_zenphoto-161-FR/zp-core/functions/functions-rewrite.php on line 130

Deprecated: strtr(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/roland/Sites/24_zenphoto-161-FR/zp-core/functions/functions-rewrite.php on line 130
```

https://github.com/zenphoto/zenphoto/blob/adc35f95493cb39e24441adbbbbbe9dc38034cbb/zp-core/functions/functions-rewrite.php#L130

**Comment by acrylian** [comment]
PHP 8+ is more type strict regarding variable types. We have already fixed loads of these and there are surely still plenty existing within the code since former PHP version just silently ignored them.

**Comment by acrylian** [comment]
I cannot reproduce this issue with the markRelease plugin or without. If you have used the rewriteRules plugin to rename something please check that and/or reset to defaults.

**Comment by RolandTi** [comment]
Hello @acrylian, 
I also tried to reproduce this issue on a fresh install without success, whereas it still hapening on another instance.
As I'm not gonna to try every option of zenphoto to trigger the error, I'm closing this issue :smile:

**Comment by RolandTi** [comment]
It's happening on the virtualhost I use for translation. 
So a blank Zenphoto without any special configuration (as I remember of course…).
The `mod_rewite` option was set to off.

But well… after all you were right, 
I activated  `rewriteTokens` and ticked `reset` and all the warnings are gone…

**Comment by acrylian** [comment]
Great, thanks, I love it when solutions are actuall simple ;-)
