### ISSUE TITLE
Sitemaps-extended plugin: dates settings and lastmod dates issues 

### ISSUE THREAD

**Issue by kuz-z-zma** [zenphoto/zenphoto#1406]
I'm back with 2 issues for sitemaps-extended plugin.

Minor issue: 
Currently, there's a setting in plugin options for Albums and Images to choose what will be set as lastmod date, but no explanations are provided for existing options. 

Major issues:
- No matter what options I choose for the Albums, sitemap is generated with the date of album folder created on server, and not a date of Last Change or Last Update that's listed in Admin section for this album. Upload of new images and even renaming a folder doesn't change this date, as you would expect if "Last change date" option is selected. 
This is obviously extremely bad for seo and can lead to problems with indexing by search engines.

- Settings for Images do alter the result, but in a confusing way. 
Date & Last Change Date - gets lastmod to use a date of Image Taken from metadata, mtime - time of upload. I Think Last Change should use "Date modified" of a file or "Last change" shown in Admin.

- There are no settings for Pages and almost everyone will assume that lastmod of pages will be set to date of last change, but it's not. Despite Admin showing "Last change" date, sitemap uses a date of page creation (not even publication!)
This is also very bad for seo.

**Comment by acrylian** [comment]
Thanks, images/albums historically indeed use the folder/filed dates indeed as the images was always considered  the "main content" and not the last change date (which btw is newer for images/albums).

> date of page creation (not even publication!)

The "Publish date" on gallery items is never used except for scheduled publishing because it is not set if not used. It is separate here because the date generally comes from the image. Zenpage items only have one date, there is no "publish" date.

**Comment by kuz-z-zma** [comment]
I think "Last change date" option should take into account changes made to image "page" as adding "Description" for example can alter the page significantly and revisit by search engines would be necessary, so alerting them via sitemap can expedite the process.

**Comment by acrylian** [comment]
> I think "Last change date" option should take into account changes made to album/image "page" as adding "Description" for example can alter the page significantly and revisit by search engines would be necessary, so alerting them via sitemap can expedite the process.

Edits on the backend is what the last change date is about on all items. If there are none yet thte normal date is used. I will check what the sitemap uses and if there is anything wrong.

**Comment by acrylian** [comment]
Made a few changes, now the latest date of normal date, lastchange date and updated date (albums only) is used. Please give it a try.

**Comment by acrylian** [comment]
News categories don't get any lastmod since they currently don't have any date. I guess it might make sense to just use the current day.

**Comment by kuz-z-zma** [comment]
I've tested it and "Last change date" setting works great for albums and images, news and pages also now show the last change date (without time) and not the date of creation. 

So, now it works as expected and can be played with according to one's needs:
date option: 
- albums: date of album creation
- images: date of image taken (from metadata)
last change date option
- albums: last change date
- images: last change date
mtime option
- albums: date of album creation
- images: date of image upload

Thank you!

Categories - I think correct one would be to use the date of last news item in this category, but current date can work too.

**Comment by acrylian** [comment]
Great, thanks. 

For categories I had now added last change or the current date. But indeed the date of the latest news article could be thrown into the mix as well. Will take a look.

**Comment by acrylian** [comment]
Added something for the category and latest article.

**Comment by acrylian** [comment]
Great, then I guess we have it ;-)
