### ISSUE TITLE
In 1.6.2, video sitemap thumbnails use shrunken thumbnail instead of original sidecar poster image. Thumbnail links are also not encoded.

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1413]
In **sitemap-extended** with _Enable Google image and video extension_ enabled, video sitemaps referencing video thumbnails in `<video:thumbnail_loc>` use the shrunken cached thumbnails instead of original video poster sidecar images. If they haven’t been cached, they also reference the i.php version. Pointing to the original poster image instead would eliminate that.

[All Google says on the matter of thumbnail size is](https://developers.google.com/search/docs/appearance/video#video-thumbnail):
_**Size:** Minimum 60x30 pixels, larger preferred._

Why it also might be a good idea to reference the original video poster image, depending on the Zenphoto theme used and the search engine, the search engine might generate a higher quality video thumbnail if using the poster image.

Last thing, the thumbnail image links are not encoded, unlike `<loc>`, `<image:loc>`, and `<video:content_loc>`.

**Comment by acrylian** [comment]
That must be an old issue because although we worked on the sitemap there have been no changes to this area.

> they also reference the i.php version. 

Only until they are cached and the sitemaps are re-generated of course.

**Comment by acrylian** [comment]
I can reproduce it. The video/image extension part ignores the setting for using the full image which "normal" images use.

**Comment by acrylian** [comment]
Furthermore I think we should generally use the (or a) sized image size instead of the thumb size even without the full image option being enabled.
