### ISSUE TITLE
Issues with search URLs in version 1.6 onwards

### ISSUE THREAD

**Issue by wongm** [zenphoto/zenphoto#1414]
In Zenphoto version 1.5.9 URLs such as this used to return a search results page:

https://railgallery.wongm.com/page/search/test

After upgrading to version 1.6 and beyond, these URLs now result in a 404 page being loaded, with search results pages now being exposed here:

https://railgallery.wongm.com/page/search/?s=test

I've checked the changelogs for v1.6 and v1.6.1 and can see that changes have been made to how search works, but I can't get to the bottom of how to make the URLs from older Zenphoto versions continue to work.

In addition , the 'Sort albums by' and 'Sort images by' options under Search > Options don't appear to be having any effect on how the search results are being ordered - newest items are always appearing last.

**Comment by wongm** [comment]
An update for the Sort albums by' and 'Sort images by' options:

- I had been ordering by date
- if I change from date to title as the ordering column, the search results are now ordered by title instead of date
- but changing the 'descending' tickbox doesn't reverse order of items by title
- I then switch back to ordering by date, and ordering of results then follows date
- but changing the 'descending' tickbox doesn't reverse order of items by date

**Comment by wongm** [comment]
As an interim hack, this `.htaccess` rule makes my old URLs work:

```
  RewriteCond %{QUERY_STRING} ^$
  RewriteRule ^page/search/([^/]+)/?$                /page/search/?s=$1 [L,R=301,NE,B]
```

Take any request to `/page/search/something` without a querystring, and redirect the 'something' to the querystring, removing any trailing slashes, and ensuring any spaces between works is passed through correctly to Zenphoto search.

**Comment by wongm** [comment]
And the plot thickens in regards to broken search ordering - on my https://zenphoto.wongm.com/ test site, changing the 'descending' checkbox does change how the results are ordered. So either issue with my site configuration, or my custom Zenphoto theme.

**Comment by wongm** [comment]
For broken search ordering - turns out Zenphoto settings are getting saved correctly - this debugging code says so:

```
if (zp_loggedin())
{
		echo "---";
		echo getOption('search_album_sort_type');
		echo "---";
		echo getOption('search_album_sort_direction') ? 'DESC' : '';
		echo "---";
		echo getOption('search_image_sort_type');
		echo "---";
		echo getOption('search_image_sort_direction') ? 'DESC' : '';
		echo "---";
}
```

Cause of my issue is custom code in my theme:

https://github.com/wongm/wongm-rail-gallery-theme/blob/master/search.php

Which does this:

```
$_zp_current_search->setSortDirection(true);
```

That is no longer compatible with the method signature:

```
setSortDirection($val, $what = 'images')
```

So something for *me* to fix.

**Comment by wongm** [comment]
And I think I've gotten to the root of how the Zenphoto rewrite rules are configured - default rules are here:

https://github.com/zenphoto/zenphoto/blob/0e66798e76ea97a80a92bd213342c12fa408b5f4/zp-core/rewrite-rules.txt

While on my server, I have this orphaned `zenphoto-rewrite.txt` file - with these additional rules inside:

```
	RewriteRule ^%SEARCH%/(.*)/([0-9]+)/?$    						index.php?p=search&words=$1&page=$2 [L,QSA]
	RewriteRule ^%SEARCH%/(.*)/?$     										index.php?p=search&words=$1 [L,QSA]
```

Note the old `words` querystring parameter, not the current `s` param.

So it seems that my options ar:
- hack them back Zenphoto core files and have it break on the next upgrade
- implement these rules in my own `.htaccess` file (which I have partially done already) 
- or implement them in the `$conf['special_pages']` variable in the `zenphoto.cfg.php` file.

**Comment by acrylian** [comment]
There are reasons why the search urls changed. This is partly to follow general query names (also Google likes) and because of the the search fields selection. Please see the release posts for more info.

Hacking is not recommend usually. Better make your theme work with the new urls as the old ones will not come back.

**Comment by acrylian** [comment]
You need to se the sortdirection quite early if you change it via the class as otherwise search results will not honor it. I don't remember exactly but I think from own older tests setting this on search.php may be too late.
