### ISSUE TITLE
The html_meta_tags plugin creates duplicate cache images, when only one image is necessary

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1415]
The html_meta_tags plugin creates a cached image size (for this example, 1200x630 or wMax1200_hMax630) that cacheManager recognizes. The problem is, for our example, that it creates both a `_w451_h630` and a `_w451_h630_thumb` version that are identical.

The issue is that `meta property` `og:image` and `twitter:image` in image.php both use the "_thumb" version, while album.php uses the non-thumb version.

The problem is the image cache is double in size for `html_meta_tags` images for no real reason. This might seem like a small issue, but it adds up fast on a large site.

It looks like lines 340 and 371 in `html_meta_tags.php` is where the different thumbs for album.php and image.php are created.

**Comment by acrylian** [comment]
Technically the thumb and sized image (as we call them) can be different because the thumb does not have a watermark. But I agree this is unnecessary here.  Will look into this.
