### ISSUE TITLE
cacheManager doesn't register two admin images, _h110_thumb and _h135_thumb

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1416]
With *“all sizes for admin”* selected in cacheManager, it only generates two images `_40_cw40_ch40_thumb` (which is used on the Albums - Edit Gallery admin page) and `_80_cw80_ch80_thumb` (which I haven't been able to find used on anything).

However, it doesn't generate the `_h110_thumb` image used on the *Albums - Image order* page, or the `_h135_thumb` image used on the *Albums - Images* page.

This is a small issue, but it makes those pages unnecessarily slow to load when first opening them.

**Comment by acrylian** [comment]
Thanks for noting, we must have missed that.
