### ISSUE TITLE
Sitemap-extended: date for generated sitemap has wrong time in Admin

### ISSUE THREAD

**Issue by kuz-z-zma** [zenphoto/zenphoto#1419]
When using Sitemap tools page, there is a list of Available sitemap files with the time of creation.

This time is wrong for the Minutes - instead of listing actual Minutes it uses Months.
If you check lastmod time for files in sitemapindex.xml - it shows the correct time.

March:
![Screenshot_38](https://github.com/zenphoto/zenphoto/assets/75898540/9aa8b1a6-9c61-4410-8ac8-ba0ce0f5b754)

April
![Screenshot_40](https://github.com/zenphoto/zenphoto/assets/75898540/964338ec-dbe1-445f-ac08-adba7113bb6d)

Correct time listed in sitemapindex.xml:
![Screenshot_41](https://github.com/zenphoto/zenphoto/assets/75898540/c7650825-59d9-4f60-b299-f6e007c6968e)

**Comment by acrylian** [comment]
Thanks, great catch, never noticed!
