### ISSUE TITLE
register_user plugin: adds space in register link

### ISSUE THREAD

**Issue by kuz-z-zma** [zenphoto/zenphoto#1420]
Plugin register_user, register_user.php file

function printRegisterURL, line 622 - unnecessary space before closing </a>

**Comment by acrylian** [comment]
Thanks, remove the space.

**Comment by bic-ed** [comment]
There are more missing spaces before set name in class-favorites.php, along with some other things to be fixed, one of which could lead to a fatal error if working (but it is not working at the moment). When you have time, I can open a pull request or show you the proposed fixes on my fork.

**Comment by bic-ed** [comment]
Sorry for wrong ticket, I found your cosmetic fix for set name referenced here

**Comment by bic-ed** [comment]
Anyway, the fatal error does not even happens because is under a wrong condition that is never fulfilled.
