### ISSUE TITLE
Paragraph returns in image metadata are not displayed in Description field, but add &#xA; or html tags in Image Info - Image Caption

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1422]
Paragraph returns in metadata are not displayed on the image page, and in Metadata\Image Info they show up as an [HTML Encoded Line Feed character](https://www.fileformat.info/info/unicode/char/000a/index.htm), using the hexadecimal value- `&#xA;`

For example, if you have a few paragraphs in the Description field, they will show up as one long string of text with `&#xA;` showing where each paragraph should be under Image Caption in Image Info.

I found a [16-year-old forum post asking for a fix to the issue](https://forum.zenphoto.org/discussion/2482/line-breaks-in-exif-data), but with no solution added to Zenphoto.

You can always edit the text for each image that shows on the page, but it doesn’t change the problems with Image Info.

I know this is not a major issue, but deals more with polish that would be nice to have.

I also know you’re not using ExifTool, but here’s how it can handle new lines-

[21. "How do I read/write values containing newline characters?"](https://exiftool.org/faq.html#Q21)

If you do try to edit in the paragraphs for the description in Zenphoto, or add any styling for that matter, and then export to an XML file using xmlMetadata, it does not fix the issue. When you hit *Refresh Metadata* the Image Caption will still be one long text, but will now show all html tags added for styling. Which, depending on how much styling you’ve added, can be worse.

This issue was first mentioned in [another post](https://github.com/zenphoto/zenphoto/issues/1417#issuecomment-2076684189), which has some more info.

**Comment by acrylian** [comment]
Thanks for the new ticket :) I think the issue might be that we import metadata more or less "as is" to the metadata fields but actually only process line feeds when setting to the description field. We'll take another look.

**Comment by JesseHC** [comment]
**Image Caption** now displays paragraphs (though only appears to add them, does not actually add them in the source code), and no longer displays `&#xA;` or html tags, so thanks for that.

Some issues I have still noticed:

* **Description** still does not recognize paragraphs, and reverts to one line if you *Refresh Metadata*.

* If you manually add the paragraphs to **Description**, export the changes to an XML file with *Export metadata info to XMP sidecar* and then later hit *Refresh Metadata* the `<p>` tags added by TINY will be read into **Image Caption** and it will also add extra `<br />` at the end of each `</p>` tag, causing there to now be double paragraphs.

* **Image Title** still does not display paragraphs. My recommendation is that you delete **Image Title** as an option for Metadata. It’s really for a longer discussion on the topic, but as it is, it duplicates everything in Image Caption, and has a confusing name (it’s not the Title, it’s the Caption/Description (I know it’s based on the EXIF spec, but I don’t know a single image program that uses it like that, and I’ve even seen an image viewer that has an option to ignore it).

* If you export to XMP and then click *Refresh Metadata* so it reads from the XMP file, **Image Title** will disappear.

**Comment by JesseHC** [comment]
I noticed this, and it is not a real issue, though it makes dealing with source code difficult. If you read in a **Description** from an XMP file, the XMP file is fine, viewing the source code in Admin and TINY is fine, but if you view the source code for an image page, the **Description** will be broken up one word per line. The text is also fine for **Image Caption**.

**Comment by acrylian** [comment]
We only can turn the linefeeds into `<br>`, creating actualy <p></p> constructs is way too complicated and error happy.

I will take a look at the description, perhaps I missed that focussing on the meta data part.

the image title does not display paragraphs because usually "titles" don't have any specific formatting. (I do know that the exif descrioption is the title/caption for some weird EXIF naming reasons…)

Let's move anything XMP related to a separate ticket as it is a independent plugin from EXIF/IPTC.

**Comment by acrylian** [comment]
> Description still does not recognize paragraphs, and reverts to one line if you Refresh Metadata.

I cannot reproduce that. Linefeeds do work for me as `<br>` and also on metadata refres. But of course only if you have the option enabled.

**Comment by JesseHC** [comment]
> > Description still does not recognize paragraphs, and reverts to one line if you Refresh Metadata.
> 
> I cannot reproduce that. Linefeeds do work for me as `<br>` and also on metadata refres. But of course only if you have the option enabled.

You're right. I didn't have it turned on for my test server of the latest build, though it was turned on for my live server. It is creating `<br />` for both the **Description** and **Image Caption**.

**Comment by acrylian** [comment]
Great!
