### ISSUE TITLE
Search cache issue storing criteria/serialized arrays

### ISSUE THREAD

**Issue by kuz-z-zma** [zenphoto/zenphoto#1423]
I'm working on adding support for Related Items plugin to my theme Paradigm and have encountered a strange issue.

Tested with todays 1.6.3a (Official build) on my test site and 1.6.2a on live site.

Issue: when adding printRelatedItems with any parameters execution causes unexpected end of file for browsers. 
On desktop browsers this is often forgiven and content is rendered regardless.
But on mobile - part of the page is not rendered which causes loss of functionality (tested with Chrome, Vivaldi)
In validators - this causes errors "Error: End of file seen and there were open elements." and everything related to printRelatedItems and afterwards is flagged as "Unclosed element"

There is some inconsistency though:
All Pages get this issue with unexpected end of file

News items - not all, for example on my demo site first (oldest) news item 
https://demo.private-universe.net/news/2023-07-06-new-theme-in-works/ - passes all tests in mobile and validator whatever I do, and all other news items - sometimes show related items, sometimes don't, and their results on mobile and in validatior vary

Albums and Images - the same variation, but I was unable to locate a single exception.

Removal of printRelatedItems restores full rendering and passes validators.

Validator results, see Error #3
![Screenshot_8](https://github.com/zenphoto/zenphoto/assets/75898540/b1c03c0a-6fbb-4360-be7e-1a0891f5e6df)

**Comment by kuz-z-zma** [comment]
Error log is full of 

`[Sat Apr 27 05:19:24.084987 2024] [fcgid:warn] [pid 1445008:tid 118858550814464] [remote 217.182.175.162:39906] mod_fcgid: stderr: PHP Fatal error:  mysqli Error: ( INSERT INTO `[prefix]search_cache` (criteria, data, date) VALUES ('a:5:{s:4:\\"item\\";s:6:\\"albums\\";s:6:\\"fields\\";s:4:\\"tags\\";s:1:\\"s\\";s:110:\\"a:7:{i:0;s:3:\\"CMS\\";i:1;s:1:\\"|\\";i:2;s:8:\\"Paradigm\\";i:3;s:1:\\"|\\";i:4;s:5:\\"theme\\";i:5;s:1:\\"|\\";i:6;s:8:\\"Zenphoto\\";}\\";s:4:\\"sort\\";s:12:\\"`date` desc \\";s:4:\\"user\\";s:5:\\"guest\\";}', 'a:0:{}', '2024-04-27 15:04:24') ) failed. mysqli returned the error Duplicate entry 'a:5:{s:4:"item";s:6:"albums";s:6:"fields";s:4:"tags";s:1:"s";s:1' for key 'zp_search_cache.criteria' in /home/kuzzzma/demo.private-universe.net/zp-core/classes/class-dbmysqli.php on line 83`

similar reported here: https://forum.zenphoto.org/discussion/1411175/related-items-in-1-6.
I've tried disabling Search Cache and clearing it and it seems to solve the issue.

Maybe it should be included in info for Related Items plugin as a known issue and mandatory setting?

**Comment by acrylian** [comment]
I looked at thte plugin and the usage on our own site and it appears to create the proper elements. Are you sure this isn't an issue with the theme itself? Validators often note errors on lines that actually are in other lines.

**Comment by acrylian** [comment]
The fatal error would explain the broken content/undisclosed elements. I do remember an older report about that but the problem was we couldn't reproduce it. The search cache often causes trouble regarding results itself (I personally always have it off anyway). I will try to take a look at it again why this duplicated entry error can happen at all as such should of course either get blocked respectively just overwritten…

**Comment by kuz-z-zma** [comment]
The code was unchanged, all properly closed and triple checked, the issue was created by processing printRelatedItems, when it failed - it caused abrupt end of file and stop of rendering/validation issues (I've checked with Libratus theme too, same issue, completely different code).

It seems, that desktop browsers more readily abandon the task and close tag, surrounding the printRelatedItems function and go on to render everything else, while mobile versions stop at fatal error.

**Comment by acrylian** [comment]
My first comment was before I saw your error report which causes the wrong tags as a follow up.

**Comment by acrylian** [comment]
I looked at the searchengine class method cacheSearch() and I can't spot anything wrong. Please take a look at your search_cache table. It should be setup like this:
![Bildschirmfoto 2024-04-27 um 16 15 49](https://github.com/zenphoto/zenphoto/assets/2474309/047636a9-ab5f-4c9b-8494-82f8aec02057)

**Comment by kuz-z-zma** [comment]
Mine  for demo site (after enabling search cache)
![Screenshot_11](https://github.com/zenphoto/zenphoto/assets/75898540/eea890cc-d4cb-4b22-a756-ae8195e81788)

Error in log file for one of the pages:
`[Sat Apr 27 11:06:19.637986 2024] [fcgid:warn] [pid 1659231:tid 118858073413376] [client 54.83.75.11:45026] mod_fcgid: stderr: PHP Fatal error:  mysqli Error: ( INSERT INTO `[prefix]search_cache` (criteria, data, date) VALUES ('a:5:{s:4:\\"item\\";s:4:\\"news\\";s:6:\\"fields\\";s:4:\\"tags\\";s:1:\\"s\\";s:111:\\"a:7:{i:0;s:3:\\"CMS\\";i:1;s:1:\\"|\\";i:2;s:8:\\"Paradigm\\";i:3;s:1:\\"|\\";i:4;s:5:\\"theme\\";i:5;s:1:\\"|\\";i:6;s:8:\\"Zenphoto\\";} \\";s:4:\\"sort\\";s:11:\\"`date` desc\\";s:4:\\"user\\";s:5:\\"guest\\";}', 'a:1:{i:0;a:3:{s:5:\\"title\\";s:48:\\"a:1:{s:5:\\"en_US\\";s:22:\\"New theme in the works\\";}\\";s:9:\\"titlelink\\";s:29:\\"2023-07-06-new-theme-in-works\\";s:6:\\"weight\\";i:4;}}', '2024-04-27 21:04:19') ) failed. mysqli returned the error Duplicate entry 'a:5:{s:4:"item";s:4:"news";s:6:"fields";s:4:"tags";s:1:"s";s:111' for key 'zp_search_cache.criteria' in /home/kuzzzma/demo.private-universe.net/zp-core/classes/class-dbmysqli.php on line 83`

**Comment by acrylian** [comment]
Okay, table matches mine. I still don't get how the duplicate entry can happen. The method cacheSearch() checks if an entry exists and should never reach the INSERT statement and use the UPDATE one.  

Please add `debuglog($result)` before the `if($result)` on line 1963 in class-searchengine.php and report what it tells.

**Comment by kuz-z-zma** [comment]
I flipped through several pages and news items, some were ok, as before, some not and resulted in failure to load content on mobile.

```

{2197039:Sat, 27 Apr 2024 19:04:51 GMT}

Array

(

[id] => 83

[data] => a:0:{}

[date] => 2024-04-27 22:04:47

)

{2197039:Sat, 27 Apr 2024 19:06:27 GMT}

Array

(

[id] => 83

[data] => a:0:{}

[date] => 2024-04-27 22:04:51

)

{2197039:Sat, 27 Apr 2024 19:06:30 GMT}

Array

(

[id] => 79

[data] => a:0:{}

[date] => 2024-04-27 22:04:38

)

{2197039:Sat, 27 Apr 2024 19:06:35 GMT}

{2197039:Sat, 27 Apr 2024 19:07:47 GMT}


{2197039:Sat, 27 Apr 2024 19:07:47 GMT}


{2197039:Sat, 27 Apr 2024 19:08:38 GMT}


{2197039:Sat, 27 Apr 2024 19:08:38 GMT}

USER ERROR: mysqli Error: ( INSERT INTO `[prefix]search_cache` (criteria, data, date) VALUES ('a:5:{s:4:\"item\";s:6:\"albums\";s:6:\"fields\";s:4:\"tags\";s:1:\"s\";s:110:\"a:7:{i:0;s:3:\"CMS\";i:1;s:1:\"|\";i:2;s:8:\"Paradigm\";i:3;s:1:\"|\";i:4;s:5:\"theme\";i:5;s:1:\"|\";i:6;s:8:\"Zenphoto\";}\";s:4:\"sort\";s:12:\"`date` desc \";s:4:\"user\";s:5:\"guest\";}', 'a:0:{}', '2024-04-27 22:04:38') ) failed. mysqli returned the error Duplicate entry 'a:5:{s:4:"item";s:6:"albums";s:6:"fields";s:4:"tags";s:1:"s";s:1' for key 'zp_search_cache.criteria' in /home/kuzzzma/demo.private-universe.net/zp-core/classes/class-dbmysqli.php on line 83

trigger_error called from dbMySQLi->query (class-dbmysqli.php [83])

from SearchEngine->cacheSearch (class-searchengine.php [1969])

from SearchEngine->getSearchAlbums (class-searchengine.php [1460])

from SearchEngine->getAlbums (class-searchengine.php [1480])

from getRelatedItems (related_items.php [71])

from printRelatedItems (related_items.php [156])

from include (news.php [123])

from include (index.php [128])

from index.php [79]

{2197039:Sat, 27 Apr 2024 19:08:43 GMT}


{2197039:Sat, 27 Apr 2024 19:08:43 GMT}

USER ERROR: mysqli Error: ( INSERT INTO `[prefix]search_cache` (criteria, data, date) VALUES ('a:5:{s:4:\"item\";s:6:\"albums\";s:6:\"fields\";s:4:\"tags\";s:1:\"s\";s:110:\"a:7:{i:0;s:3:\"CMS\";i:1;s:1:\"|\";i:2;s:8:\"Paradigm\";i:3;s:1:\"|\";i:4;s:5:\"theme\";i:5;s:1:\"|\";i:6;s:8:\"Zenphoto\";}\";s:4:\"sort\";s:12:\"`date` desc \";s:4:\"user\";s:5:\"guest\";}', 'a:0:{}', '2024-04-27 22:04:43') ) failed. mysqli returned the error Duplicate entry 'a:5:{s:4:"item";s:6:"albums";s:6:"fields";s:4:"tags";s:1:"s";s:1' for key 'zp_search_cache.criteria' in /home/kuzzzma/demo.private-universe.net/zp-core/classes/class-dbmysqli.php on line 83

trigger_error called from dbMySQLi->query (class-dbmysqli.php [83])

from SearchEngine->cacheSearch (class-searchengine.php [1969])

from SearchEngine->getSearchAlbums (class-searchengine.php [1460])

from SearchEngine->getAlbums (class-searchengine.php [1480])

from getRelatedItems (related_items.php [71])

from printRelatedItems (related_items.php [156])

from include (news.php [123])

from include (index.php [128])

from index.php [79]
```

**Comment by acrylian** [comment]
Thanks the debug output might have given me a clue what is happening. I let you know when i have something to try.

**Comment by acrylian** [comment]
It is a generally search cache issue with storing the search criteria as a serialized array. I got the error even with normal dynamic albums now. Since it also contains an array this apparently broke the query. Probably an unwanted and missed follow up of the search changes a while ago. Seems that double serializing fixes it. Please clear the search cache and try.

**Comment by kuz-z-zma** [comment]
Tested after search cache clear and with 10 min of cache expiry time: everything works and no errors are reported in logs for search cache.

thank you!

**Comment by acrylian** [comment]
Great thanks for pointing to the issue again.
