### ISSUE TITLE
Openstreetmap: Longitude/Latitude not shown --> no map

### ISSUE THREAD

**Issue by kuz-z-zma** [zenphoto/zenphoto#1425]
Updated today my demo site with latest build (1.6.3a, from earlier today) and got a regression from 1.6.2 and previous build of 1.6.3a.

If Longitude and latitude are not selected to be **Show the field and import data** in Option->Image (Metadata) - Openstreetmap wont show a map for Image of Albums, previously **Hide the field but import data** setting was enough.

Code is similar
`<?php openStreetMap::printOpenStreetMap(); ?>`

First with Imported, not shown
![Screenshot_12](https://github.com/zenphoto/zenphoto/assets/75898540/b11664bc-5a37-491b-8290-24bcd82a4b8d)

Shown
![Screenshot_13](https://github.com/zenphoto/zenphoto/assets/75898540/90b66f9f-48be-4b52-a420-aa8c6f4d850e)

**Comment by acrylian** [comment]
I did change/restructured internally a bit but it shouldn't have changed. Will take a look naturally.

**Comment by kuz-z-zma** [comment]
Can confirm as fixed .
