### ISSUE TITLE
html_meta_tags & french translation

### ISSUE THREAD

**Issue by RolandTi** [zenphoto/zenphoto#1426]
https://github.com/zenphoto/zenphoto/blob/811b40f6e3a2a98a82dd58c6589780b1bcb9f17f/zp-core/zp-extensions/html_meta_tags.php#L241

Hello !
Maybe two typos : 
- "paginatied" > paginated
- "dissallow" > disallow

And for the french translation, I don't understand the meaning of: "Following links will still be allowed." as I'm supposed to Disable indexing in this section.

thanks !

**Comment by acrylian** [comment]
Thanks, typos are fixed now.

> "Following links will still be allowed." as I'm supposed to Disable indexing in this section.

It refers to disabling indexing of a page itself but allow following of links within that page (-> "noindex,follow").

**Comment by RolandTi** [comment]
Ok, thanks !
