### ISSUE TITLE
Abandoning Exifer library

### ISSUE THREAD

**Issue by acrylian** [zenphoto/zenphoto#1428]
We intend to remove the Exifer library (zp-core/libs/exif/) which is pretty old and has its origins in PHP 4 days when the native PHP exif reading war pretty bad.  1.6.3a now uses the native `exif_read_data()` function and according to our tests with various files there is no difference.  See line 2470 of `read_exif_data_protected()` in`functions.php`  for manually switching back to Exifer.

This only affects the base EXIF data. IPTIC is and was always read by native PHP functions and the XMP plugin does its own importing besides using a few functions from Exifer that can easily be migrated. Before we remove everything please test if we didn't miss anything.

@RolandTi @kuz-z-zma @JesseHC @wongm

**Comment by RolandTi** [comment]
Looks good to me.

**Comment by kuz-z-zma** [comment]
Found no issues seemingly (checked with images including metadata in russian, japanese, georgian etc)

**Comment by acrylian** [comment]
Great, that matches our tests. Thanks for testing.

**Comment by JesseHC** [comment]
Same here. I tested it on various JPG, PNG, and MP4 files with the xmpMetadata plugin turned on and off, just to be sure. I did not notice any behavior different than with the previous Exifer library.

**Comment by acrylian** [comment]
Thanks. PNG files may not be supported officially as they don't specifially have EXIF data. The PHP docs refers to "typically jpg/tiff files" (while tiffs are of course not a web format browsers can display at all). 

Btw, multimedia files are not and never were handled this at all but by a third party library named getID3 that is part of the video-class plugin currently.

**Comment by JesseHC** [comment]
While PNG does not support Exif, it does [support text fields for many of the same basic values](https://www.w3.org/TR/png/#11textinfo), and it does [support XMP metadata](https://exiftool.org/TagNames/PNG.html), which many programs write IPTC data into. Which is why I was testing between the native support and the XMPmetadata plugin, to see if there were any new problems getting the IPTC values in that I use.

For the MP4 files, getID3 does not appear to be reading in any of the metadata. Currently, and also with the XMPMetadata plugin turned on (bear with me for a moment), the only thing read in is the ***Video File Size*** for both. [MP4 metadata](https://kdenlive.org/en/project/adding-meta-data-to-mp4-video/) that I have added in [MetaZ](https://metaz.maven-group.org/), [Mp4Autotag](https://github.com/muttsnutts/mp4autotag), or [Subler](https://subler.org/), and also tested in VLC, QuickTime, and [MediaInfo](https://mediaarea.net/en/MediaInfo). This includes embedded image previews, that I was not expecting Zenphoto to use, though it would be amazing if it did, getting rid of the need for an extra sidecar image.

On top of that, there is also XMP IPTC metadata, which [MP4 files support](https://en.wikipedia.org/wiki/Extensible_Metadata_Platform#Location_in_file_types), and that I’ve added and tested in Adobe Bridge and Lightroom. None of it is read by Zenphoto.

The one workaround that actually works, and that I’ve used for years, is to export the IPTC fields to an XMP sidecar file from Adobe Bridge. Using XMPMetadata, all important fields will be read in, including keywords for people. This allows MP4 files that are truly portable with Zenphoto.

Here’s where things get inconsistent. XMPMetadata will read the the XMP IPTC fields within a PNG file, but it will not do it for MP4 files. I know you said getID3 does that from video-class, but maybe it would be better if XMPMetadata was allowed to try since getID3 is not doing it now.

**Comment by acrylian** [comment]
> This includes embedded image previews, that I was not expecting Zenphoto to use, though it would be amazing if it did, getting rid of the need for an extra sidecar image.

Not really if you want to be able to resize it according to image sizes a theme requests.

The metadata support for non EXIF/IPTC is a bit rough I fear and its all seems quite complex which each file having it's own structure: https://www.getid3.org/demo/
Probably we need to review it another time how getID3 exactly reads those. It was back in quicktime days and I believe it does read mp3s more or less properly. But that's not really part of this ticket.

**Comment by JesseHC** [comment]
Two small issues I have noticed-

1. All metadata names have an extra period at the end when displayed in Image Info.

2. ***Date Created*** and ***Digital Creation Date*** fields have the same info, which is correct. The issues is that ***Time Created*** and ***Digital Creation Time***, while also having the same info, actually display the date and time the file was added to Zenphoto, so maybe the names should be changed?

**Comment by acrylian** [comment]
I am not really sure if our plugin actually reads XMP from files. I admit it's one of the plugins I basically never use myself…
I just looked at getID3 and it seems to also support XMP. We only use a subset of its modules and missing mp4 might be a result that it seems to list that with the quicktime module we don't include since quicktime is actually dead and no native "web video format".

----

1. Will look at the period, that might be a display thing if that isn't accidentally in the db column itself.
2. I think we can't/shouldn't rename the fileds because the follow the metadata field names, don't they? That the time includes the date might be a mistake on importing. Also don't know what the EXIF/IPTC specs say in case these are sort of aliasses…

**Comment by acrylian** [comment]
Okay, I see we have several EXIF and IPTIC date and time fields. 
![Bildschirmfoto 2024-05-06 um 15 49 13](https://github.com/zenphoto/zenphoto/assets/2474309/cc780563-eae1-4bff-b667-2e4b06efbfbb)

I will dive into the code to see if these are that way already on reading the data or if we do set them that way for some reason. I guess this is not related to the removal of Exifer itself as the import part is ZP code.

**Comment by acrylian** [comment]
The library itself  and its dependencies has been removed now. Two functions the xmp plugin used have been moved to its class.

**Comment by kuz-z-zma** [comment]
@acrylian I have the same for this photo (I've enabled all date-time fields to be shown in options to test)
https://www.photo.private-universe.net/travel/uk/london/st-pauls-cathedral.jpg.html

28.08.2013 21:17:16 is a correct date and time taken, local time and the one set on camera (to adjust for time-zones)

Date Created and Digital Creation Date seem to be using 24.00.00 as a default stand-in if the import ignored actual time the image was taken.
Time Created and Digital Creation Time though... 21:17:16 seems to be imported from file, and 6.5.2024 is an another stand?
Not the date of zenphoto update or a database refresh (my last ones for that site was on 3.06.2024) or import, seems to be just using current date.

**Comment by acrylian** [comment]
> Fields were supposed to store and display just dates or just time, and are forced to show both.
Thanks, I think that makes sense. Surely a bug in the import code just treating everything as "datetime". Will look into that the next days.

**Comment by kuz-z-zma** [comment]
> Surely a bug in the import code just treating everything as "datetime". 
maybe not on import, just db field or actual display of this value on frontend (can't check what's in db right now)

**Comment by acrylian** [comment]
Values are stored correctly respectively most field store a time stamp.

It's indeed a display issue that results in the metadata fields definition which sets all as "time" instead of differing between "time" and "date" respectively "datetime". That's an pretty old mistake I guess. This result is that all date/time fields are treated as "datetime" on display, both back and front end. Will look into that.

**Comment by JesseHC** [comment]
> I just looked at getID3 and it seems to also support XMP. We only use a subset of its modules and missing mp4 might be a result that it seems to list that with the quicktime module we don't include since quicktime is actually dead and no native "web video format".

Looking into it a little bit, while getID3() does claim to support MP4 on their [homepage](https://www.getid3.org/) and [Github](https://github.com/JamesHeinrich/getID3)-

> getID3() is a PHP script that extracts useful information from MP3s & other multimedia file formats:
> 
> * Audio-Video formats:
> 	* Quicktime (including MP4)

From *module.audio-video.quicktime.php*:

`module for analyzing Quicktime and MP3-in-MP4 files
`

It appears that while, yes, Zenphoto does not include the *module.audio-video.quicktime.php* module, even if it did, it might only work if the MP4 MIME type for the video was set as QuickTime. Which is not [the standard](https://www.rfc-editor.org/rfc/rfc4337.txt), and I’m guessing most servers aren’t setup like that now.

You can see in *getid3.php* that is only lists quicktime, not MP4, and it only has QuickTime or the older MPEG, as registered formats.

`Return array containing information about all supported formats.
`

For the [MP4 demo on their site](https://www.getid3.org/demo/Quicktime.mp4.html) it shows the example as `mime_type string (15) video/quicktime`

From their README and [Github](https://github.com/JamesHeinrich/getID3)-

> ## Future Plans
> 
> Better support for MP4 container format

So maybe the answer is to use [another option](https://stackoverflow.com/questions/34689518/get-mp4-file-tags/34689928#34689928) for class-video, something like [php-reader](https://code.google.com/archive/p/php-reader/).

**Comment by acrylian** [comment]
@JesseHC In general I would always recommend to use video services like Youtube (you can use them even via the textobject plugin within albums). Simply because these can serve videos in the correct size matching the visitor's device and connection speed. That is virtually impossible to build yourself and not really worth the work.

php-reader seems to have had its last release in 2011 so surely not an alternative for the frequently maintained getID3… A problem parsing videos is of coure that their file size is larger to do so… Anyway this is not really topic of this ticket and a change in library will surely not happen in 1.x . I will try to look at getID3 and mp4 a little more sometime.

I will close this ticket now because Exifer is now gone and it's purpose is complete. I will open a new one for the metadata stuff.

**Comment by JesseHC** [comment]
Never mind about getID3() not supporting MP4 files. I just tried it by installing getID3() and putting one of my test videos in the demo folder. It was able to pull all of the important metadata, including the preview picture. It did throw a warning, about “Unknown QuickTime atom type: "xid "” but it still worked.

**Comment by acrylian** [comment]
Sounds promising at least. Anyway new ticket if needed please.

**Comment by acrylian** [comment]
Last sidenote: The quicktime modules seems not necessary for mp4 at all, works on my ZP to get the general metadata even without it.
