### ISSUE TITLE
fediverse integration

### ISSUE THREAD

**Issue by dmrzh** [zenphoto/zenphoto#1433]
integrate with [fediverse](https://en.wikipedia.org/wiki/Fediverse) using[ activitypub protocol](https://www.w3.org/TR/activitypub/)

**Comment by acrylian** [comment]
Sorry, no plans due to lack of current personal need. If you need and want it third party plugin solutions would certainly be welcome.

**Comment by kuz-z-zma** [comment]
@dmrzh I'm curious what kind of functionality you want from such implementation?
Cross-posting of news? Images? Albums?
User-Authorization?
Any specific scenarios you have in mind?

**Comment by dmrzh** [comment]
I want my images to appear in fediverse

**Comment by acrylian** [comment]
Did you look into additional tools that can publish on Fediverse like Mastodon via RSS feeds?

**Comment by acrylian** [comment]
Great. Let us know if that works. Also review the feed options you can set via URL (or via the various RSS template functions):
https://docs.zenphoto.org/1.6.2/classes/feed.html
Normally the image within the feed is rather small but you can use the size parameter to adjust it for sharing. Also enable the html_meta_tags plugin and the opengraph meta data so probably previews are fetched automatically.
