### ISSUE TITLE
Deprecated messages in php 8.1 from getCategories()

### ISSUE THREAD

**Issue by bic-ed** [zenphoto/zenphoto#1445]
I get deprecated messages in log coming from this line:
https://github.com/zenphoto/zenphoto/blob/f1e261c3fdbb0cc90d15b3e45ee42f36a7f07f79/zp-core/zp-extensions/zenpage/classes/class-zenpagecategory.php#L234

The log says:
` DEPRECATED: stripos(): Passing null to parameter #2 ($needle) of type string is deprecated in C:\wamp64\www\zenphoto\zp-core\zp-extensions\zenpage\classes\class-zenpagecategory.php on line 234 `

and

` DEPRECATED: stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in C:\wamp64\www\zenphoto\zp-core\zp-extensions\zenpage\classes\class-zenpagecategory.php on line 234 `

So both haystack and needle are null under some circumstances.
This can be solved by using the strval() function on both items, but is that ok?

**Comment by bic-ed** [comment]
Looking better into it, the needle there is a boolean value:
`$this->getSortOrder() === 0`
so are we looking for a _true_ or _false_ string into `$cat['sort_order']`?

**Comment by acrylian** [comment]
No, null or string in this case. Sort order columns are strings (like 000 or 000-001) if set or null if not.

**Comment by acrylian** [comment]
I don't remember about why there is `$this->getSortOrder() === 0`  but a string like `000` is `0` as a number.

**Comment by bic-ed** [comment]
Ok but I mean the needle is the result of a strict comparison operator (===), so it can be only true or false, am I wrong? Hence what are we looking for in the `$cat['sort_order']` when using stripos()? 
`stripos($cat['sort_order'], $this->getSortOrder()) === 0)`

**Comment by acrylian** [comment]
>  I don't remember about why there is $this->getSortOrder() === 0 but a string like 000 is 0 as a number.

Forget my comment above, that's of cousre nonsemse. 0 is the value stripos returns of the sortorder starts with that string so we know it is a sub category we want to get.  The strict === is needed because stripos returns false if it does not find anything and 0 means otherwise also false wrongfully.

**Comment by acrylian** [comment]
Adding strval() is the best as on null values it twill result in an empty string and return false properly. Newly created items (or frist) may not have any sort_order until the list is saved and sets an actual one.

**Comment by bic-ed** [comment]
Sorry, forgive me, I mispositioned a closing bracket in my mind. The needle is actually  just $this->getSortOrder() of course and the comparison is outside stripos()

**Comment by bic-ed** [comment]
> Adding strval() is the best as on null values it twill result in an empty string and return false properly. Newly created items (or frist) may not have any sort_order until the list is saved and sets an actual one.

Ok, I have already done so in my local installation and seems to work, if you wish I can push the commit

**Comment by acrylian** [comment]
No problem, I misread it myself thus my nonsense reply first… I committed the fix being simply and pragmatic ;-)

**Comment by bic-ed** [comment]
Ok, thanks
