### ISSUE TITLE
featured_image: selection dialog album list issues

### ISSUE THREAD

**Issue by kuz-z-zma** [zenphoto/zenphoto#1450]
Zenphoto 1.6.4a and later - found an issue with album list in featured_image plugin selection dialog.

I have several layers of sub-albums, prior to move of featured_image to the core extensions had no issues with those.
Now album list in featured image selection dialog has multiple issues:
- messed-up hierarchy of albums and subalbums, mostly owning to ->
- duplication of deeper-level subalbums entries

The most top-level albums are fine, but 1 level below is displayed correctly, but 2 levels-down and further get duplicate links, that appear numerous times at different levels.

Example from one of my sites and how it affects generated list below

**Albums in admin**
![image](https://github.com/zenphoto/zenphoto/assets/75898540/8ddc90f5-ed34-41a4-b31e-3807c4b6f466)

**vs. generated list of this section**
![image](https://github.com/zenphoto/zenphoto/assets/75898540/58dee250-98ce-49dd-8e61-812b96861f7e)

This is a mild example, my main photo site, which has more sub-levels gets INSANE duplication, but with mix of russian and english in titles of albums, I fear it will be harder to make sense of.

**Comment by acrylian** [comment]
I will take a look if I can reproduce that.

**Comment by kuz-z-zma** [comment]
I've tested this on my demo site - you get duplication of entries starting from level 3 with following template:

- 1st level - ok
  - 2nd level - ok
    - 3rd level - duplication starts on a 2nd level
   - 3rd level dupe
   - 3rd level dupe

**Comment by acrylian** [comment]
Yes, we sadly can reproduce that. We'll look into that.

**Comment by acrylian** [comment]
I committed an update that should fix this.

**Comment by kuz-z-zma** [comment]
I've tested it and all duplicates cleared up, thank you!

**Comment by acrylian** [comment]
Great, thanks.
