### ISSUE TITLE
I can't get anymore published articles from password protected categories

### ISSUE THREAD

**Issue by bic-ed** [zenphoto/zenphoto#1451]
Also, published but password protected categories are not shown anymore in the menu with the _has_password_ class, though such a class is still assigned in printNestedMenu (line 1517).
Articles from protected categories are missing both in news loop and in search results.

**Comment by acrylian** [comment]
There have been no changes since 1.6.1 when all this was extensively and consistently updated:
https://www.zenphoto.org/news/zenphoto-1.6.1/#--item-visibility
https://www.zenphoto.org/news/user-rights/#--rules-of-protection-and-visibility-for-objects

**Comment by acrylian** [comment]
I can reproduce that top level published but password protected categories are not in the menu. I think indeed they should if albums protected in a similar way are.  Sub elements of protected items never are listed since they are protected by its parent (see the links please, especially 1.6.1 release).

We had extensively talked about this (I was sure you were involved, too…) and it was quite complicate and a bit mind buggling what when should be visible…

**Comment by bic-ed** [comment]
I was involved indeed at the beginning, then I had to quit...

**Comment by bic-ed** [comment]
The key could be here:
https://github.com/zenphoto/zenphoto/blob/60f99aa66dafc03733197708520f1fab26a354e9/zp-core/zp-extensions/zenpage/classes/class-zenpage.php#L447
as hacking the below by forcing to return `true` I get back articles from password protected categories and such categories in the menu.
https://github.com/zenphoto/zenphoto/blob/60f99aa66dafc03733197708520f1fab26a354e9/zp-core/classes/class-themeobject.php#L167
Of course it would break many things elsewhere, this could be  just a clue about the condition to work on?

**Comment by bic-ed** [comment]
It seems to work by adding isPublished()
```php
if (($currentcategory && $article->inNewsCategory($currentcategory)) && ($article->isPublished() || $getall || ($getUnpublished && !$article->isVisible()) || $article->isVisible())) {
	$result[] = $item;
} else if ($article->isPublished() || $getall || ($getUnpublished && !$article->isVisible()) || $article->isVisible()) {
	$result[] = $item;
}

``` 

I'll make more investigation tomorrow.

**Comment by acrylian** [comment]
I think it should work similar to 

- Password protected toplevel categories should be in the menu. No sublevels as they are protected content of their parent.
- No articles that are assigned to password protected categories because they also are protected content. Although articles are not childs of their categories as images are of their unique album this probably should behave similar. 

I personally are not really convinced anymore about keeping the concept of password protected categories at all. Since an article can be in protected and non protected this is always a bit of a mishmash… Currently protected take priority.

In any case we have individual passwords for articles, pages and images on our long list.

**Comment by bic-ed** [comment]
> No articles that are assigned to password protected categories because they also are protected content. Although articles are not childs of their categories as images are of their unique album this probably should behave similar.

I don't really mind about this, it is ok for me, but keep in mind that the code still takes care of such a case, so I didn't realize it was an intended behavior. For instance here:
https://github.com/zenphoto/zenphoto/blob/60f99aa66dafc03733197708520f1fab26a354e9/zp-core/zp-extensions/zenpage/zenpage-template-functions.php#L336
And it was working like I was expecting before the 1.6.1 release. Anyway, since we have protected pages in search results, I would expect to have protected articles as well, as they are similar items and the categories are not real parent containers like albums are for images. But like I said, I don't care that much about it. 

> I personally are not really convinced anymore about keeping the concept of password protected categories at all. Since an article can be in protected and non protected this is always a bit of a mishmash… Currently protected take priority.

I see and use this feature as a fast way to protect articles by adding them to a protected category. This can be changed of course, but it could create confusion to existing users. At least, I would wait the new "password for articles" feature before changing this.

**Comment by acrylian** [comment]
> And it was working like I was expecting before the 1.6.1 release. Anyway, since we have protected pages in search results, I would expect to have protected articles as well, as they are similar items and the categories are not real parent containers like albums are for images. But like I said, I don't care that much about it.

It was not working as expected and not consistently which is why we changed all this :) Pages are listed if protected and published and toplevel. Subpages that have a protected parent should also not be listed. If they are this would be a bug. 
Again, articles don't appear if their protected "parent" category protects them. If you protect something you expect its content to be protected and in this case childes are the content already.

>  see and use this feature as a fast way to protect articles by adding them to a protected category. This can be changed of course, but it could create confusion to existing users. At least, I would wait the new "password for articles" feature before changing this.

Probably we will keep both side by side also for backwards compatibility anyway.

**Comment by bic-ed** [comment]
I remember that in our old long talk we pointed out that protected and unpublished could live together as different approaches, where unpublished is for items not meant to appare anywhere and protected but published for items that can be found but not seen without a password. From my point of view, this should apply to images as well, but I still see articles more similar to pages than to images, so I'd like more to have them listed even if in a pp category.
For instance, you can use this kind of approach to invite users to register to your site, but if protected content is hidden (or at least a part of it) you can't do that (or in a more limited way).
That said, I don't want to bother more on this, it is not so important to me as long as protected categories get back in the menu.

**Comment by bic-ed** [comment]
And of course it is my fault to have been away for such a long time, so I apologize again for that, tough there was nothing I could do to avoid disappearing. ;-)

**Comment by acrylian** [comment]
Again, I agree completely that protected but published toplevel items should be listed and therefore categories.  All else is the "parent" inheritances (album -> images, pages -> child pages, categories -> child categories and articles as "fake" childs). You can still access unpublished items via direct link no matter if protected or not.

**Comment by bic-ed** [comment]
Meanwhile I found a missing height attribute for err-passwordprotected.png image, can I push the fix directly?

**Comment by acrylian** [comment]
Yes, but make sure you have the latest master first. Your last commit/PR did confuse something and I now always have to pull although there is nothing to pull before I can commit. Guess I have to do a fresh check out…

**Comment by bic-ed** [comment]
Weird, I was sure to have update to latest master before last PR...

**Comment by bic-ed** [comment]
Sorry, I committed a wrong fix, I'll correct it asap

**Comment by acrylian** [comment]
At least I noticed it since the last PR, might be just another git glitch…

**Comment by bic-ed** [comment]
Then, for later, and possibly for printNestedMenu() as well, I would skip useless code execution, which is now printing just an empty ul list element, by changing this line:
https://github.com/zenphoto/zenphoto/blob/19fbb3a4d0085cff00eb49b524245a6f5b558aad/zp-core/zp-extensions/print_album_menu.php#L295
with something like:
```php
if ($process && !$has_password) { // listing subalbums
``` 
or an explicit condition if you think that using the already available  $has_password var is too dirty.

**Comment by acrylian** [comment]
Cannot tell, first lets fix the categories. Might take a few days, won't get to anything today and perhaps the next few days.

**Comment by bic-ed** [comment]
Yes, I was aware of it and I knew you wouldn't like it that much, so we should apply the reverse condition used for defining that variable. 

> Might take a few days, won't get to anything today and perhaps the next few days.

No hurry at all, It was just a reminder, for me as well.
