### ISSUE TITLE
A forgotten typo in zp_load_gallery()

### ISSUE THREAD

**Issue by bic-ed** [zenphoto/zenphoto#1454]
https://github.com/zenphoto/zenphoto/blob/f58c5a6a62400ca80b8870e141de5780f4fcb46d/zp-core/functions/functions-controller.php#L141

Isn't that a typo?

`$_zp_current_zenpage_new` instead of `$_zp_current_zenpage_news`

How come this one seems to break nothing?

**Comment by acrylian** [comment]
It's a typo. It does not break anyhing as that just pre-defines a bunch of globals. Whenever the actual $_zp_current_zenpage_news is used it is defined then

**Comment by acrylian** [comment]
Of course it should be fixed if we already found it ;-)

**Comment by bic-ed** [comment]
So the fix will not have any practical effect.
Just to say, I'm not looking intentionally for this kind of issues, they came to my eyes when looking at the code for some reasons and are highlighted by the editor.

**Comment by acrylian** [comment]
Fix is primarily for consistency since we just know it.
