### ISSUE TITLE
Upload issue

### ISSUE THREAD

**Issue by hy29lam** [zenphoto/zenphoto#1456]
Hi,

We have recently upgraded to 1.6.2 (Official build) and are testing on the Images http and jQuery upload.   

We have an issue that users were able to see all albums in the Zenphoto on the "upload to" dropdown box, even for those they do not belong to.  Luckily, they cannot upload to those albums with error prompt.

It works fine on an earlier version (1.5.8 (Official build)).    All the album permission is correctly set.  Is there anything I have missed? or a bug?

Thanks in advance.
Joyce

**Comment by acrylian** [comment]
1.6.2 is not the current version. Please try 1.6.4 or better help test 1.6.5b.

**Comment by acrylian** [comment]
Also please post the exact rights these users have assigned.

**Comment by hy29lam** [comment]
Thanks for your response, we will upgrade to 1.6.5b.

In this example, the user "hro" only granted HRO albums.  However, when I login as their account, in Images (Http) and Images (jQuery), both the drop down displayed all albums existing on the zen photo.  HRO only has one album.

Is there anything I have missed?

![2024-07-11 12_20_10-Greenshot](https://github.com/zenphoto/zenphoto/assets/136549056/211440ba-7f05-48f5-a360-ed9fcbda08c9)
![2024-07-11 12_21_08-Greenshot](https://github.com/zenphoto/zenphoto/assets/136549056/5c3bb1f0-62da-48ae-9bb1-3bf2a566becd)
![2024-07-11 12_21_42-Greenshot](https://github.com/zenphoto/zenphoto/assets/136549056/37c4c469-8868-491f-b170-bc32d602d30a)
![2024-07-11 12_2
![2024-07-11 12_26_21-Greenshot](https://github.com/zenphoto/zenphoto/assets/136549056/0656ddd5-e5a7-461e-ad7a-abdb6e9783b8)
2_10-Greenshot](https://github.com/zenphoto/zenphoto/assets/136549056/949320fd-65e1-4eb3-8d22-345b17f09e05)

**Comment by acrylian** [comment]
Thanks that looks indeed as if there is something wrong. That probably didn't change then from 1.6.2. We'll check on that.

**Comment by hy29lam** [comment]
Many thanks.  Please do advise if there's a fix on this.  Cheers, Joyce

**Comment by acrylian** [comment]
Please try 1.6.5a - not recommended on a live site! - as there should be a fix now.

**Comment by acrylian** [comment]
There is a new and tecnically better fix available now in 1.6.5a @bic-ed @fretzl

**Comment by acrylian** [comment]
That's why it needs to be tested everywhere. I didn't spot anything yet but that does not mean there isn't anything. Normally on all front end related things we don't test for these backend only rights directly (I think at least off hand). If there is anything not working, we have to switch back to an extra check respectivly have to introduce some isMyManagedItem() extra methods for albums specifially.
