### ISSUE TITLE
 Published nested albums for "scheduled to be published" album

### ISSUE THREAD

**Issue by kuz-z-zma** [zenphoto/zenphoto#1460]
The issue: 
If one sets an Album to be Published on schedule + sets nested albums to be published (but without scheduled date) - those nested albums will start to appear in Related Albums and Search in general before their parent Scheduled date.

They are not treated as "Unpublished by parent" in Related albums and Search, but probably should be.
Those sub-albums are correctly NOT included in sitemaps, for example.

Example: I have an top-level Album "Jane", set to be published on August 02,  it has 1 sub-album, which also has 1 more sub-album.
Both sub-albums are set to published, but without scheduled date, as it's tedious to add again and again (and sometimes those settings seem to disappear, but that's a separate issue I'm still investigating).

Scheduled:
![image](https://github.com/user-attachments/assets/b5a1415c-a405-41f6-8ae1-b95ccfe0264e)

Sub-album is set to published:
![image](https://github.com/user-attachments/assets/67a6771c-a18c-49dd-b8ab-1d8d285fa776)

Sub-albums already appear in Related Items and Search for non-admins, but top-level "Jane" does not: 
![image](https://github.com/user-attachments/assets/bba8592a-c03a-43c4-be57-75f655745362)

![image](https://github.com/user-attachments/assets/5908e7a0-178e-4906-bd07-e44f4b2793d7)

**Comment by acrylian** [comment]
Perhaps I  missed it but you did try that while not being logged in (and properly logged out) as any user with possible rights to see these? Anyway, we will try to reproduce that.

**Comment by kuz-z-zma** [comment]
Yes, I mentioned that I've tested it in a separate browser, where I'm not logged in.
Also, those links get indexed and crawled by search engines, via related_items links, that's how I first became aware of this issue.

Right now 2 sub-level albums are displayed here, you can check for yourself: 
https://www.takara.private-universe.net/jenny-friend-dolls/erika/
And here is search: https://www.takara.private-universe.net/page/search/?s=Jane

**Comment by acrylian** [comment]
Ah, I missed "appear in Related Items and Search for non-admins" indeed between the screenshots indeed.

I see it on your site. As said we will try to reproduce this

> Also, those links get indexed and crawled by search engines, via related_items links, that's how I first became aware of this issue.

You seem not to use the html_meta_tags plugin as that should set these to noindex, nofollow. Unless we have a general issue with core checks.

Anway, we'll try to reproduce it. May take a few days as I am sadly busy with "real work" right now.

**Comment by kuz-z-zma** [comment]
> You seem not to use the html_meta_tags plugin as that should set these to noindex, nofollow. Unless we have a general issue with core checks.

I think, linked Related Items (as they are albums, images, news and pages) should be followed as those are not duplicate content, like tags or paginated news excerpts, but some actual main content.

**Comment by acrylian** [comment]
> I think, linked Related Items (as they are albums, images, news and pages) should be followed/indexed as those are not duplicate content, like tags or paginated news excerpts, but some actual main content.

Yes, but I was referring to items itself. as you can access any unpublished item by direct link if you know it. Be it wrongfully printed as here or otherwise.

As far as I can see Paradigm just duplicates what the plugin already does. Probably from very old times.

**Comment by kuz-z-zma** [comment]
> Yes, but I was referring to items itself. as you can access any unpublished item by direct link if you know it. Be it wrongfully printed as here or otherwise.

Ah, got it. Basically, that's the problem - Scheduled to be Published of a parent doesn't affect sub-items, they are seen as Published (if they are), so they get displayed. 
I think, Scheduled status of a parent should exclude them here, as it does in generation of sitemaps.

**Comment by acrylian** [comment]
Actually that the isPublic() method of all objects should cover. But the "published" status for scheduled items is set temporarily internally so there might be an issue down the way somewhere we missed. I suspect that  as thats not simple and quite nested stuff. We will look into this.

**Comment by kuz-z-zma** [comment]
Maybe, that's somehow related to another issue I've mentioned.
 I'll write it up separately now, but I don't have much to report, it's quite illusive.

**Comment by acrylian** [comment]
There are fixes now that perhaps fix also #1461 as I found code mistakes that affect both. Please try!

**Comment by kuz-z-zma** [comment]
Finally got to test it - display of sub-albums of a scheduled album in related items and search results seems to be fixed (they are not shown for not-logged users), currently I am testing if scheduled status will disappear, will report in a few days.
