### ISSUE TITLE
Scheduled to be Published Items loose their published status.

### ISSUE THREAD

**Issue by kuz-z-zma** [zenphoto/zenphoto#1461]
If Album is set to Scheduled+Published - sometimes, seemingly randomly, prior to publication - Published status is reset to Unpublished, while Scheduled Date is preserved.
This result in Album not to be published on scheduled date.

I was unable to detect any circumstances, that might affect this, but I see it most often when there are several Albums with scheduled publication dates. Some might loose their status, while others are ok.

This never occurs with Zenpage News and Pages, just Albums.

**Comment by kuz-z-zma** [comment]
Nothing in the debug logs or server logs.
Doesn't coincide with publication dates of other items.
All items, that lost their Published status in this manner, had quite a lot of time prior to their publication date.

**Comment by kuz-z-zma** [comment]
@acrylian I've tested latest version and had no problems with scheduled albums losing their published status, so this issue can be considered resolved.
Thank you!

**Comment by acrylian** [comment]
Great, thanks for confirming!
