### ISSUE TITLE
Download Link Error in Zenphoto 1.6.4 with downloadList Plugin

### ISSUE THREAD

**Issue by tobifra** [zenphoto/zenphoto#1463]
**Zenphoto Version:** 1.6.4  
**Plugin:** downloadList (included by default)  
**Environment:** Private gallery with a gallery password, individual albums not further password-protected.

#### Description
I am encountering an issue with the `printDownloadAlbumZipURL();` function in my custom theme. When a user accesses the gallery with the gallery password (but is not logged in) and clicks the download button, they receive the following error message:

```
Page error: Forbidden (403)
```

This issue did not occur in Zenphoto version 1.6.

#### Suspected Cause
I believe this problem may be related to the changes made in [commit f02109e]([link-to-commit](https://github.com/zenphoto/zenphoto/commit/f02109ea18118bfe697b617be1878b129a5ed0a8)), specifically in the `zp-core/zp-extensions/downloadList.php` file. The change involved line 549, which was updated from:

```php
if (!$album->isMyItem(LIST_RIGHTS) && !checkAlbumPassword($albumname))
```

to:

```php
if (!$album->isMyItem(LIST_RIGHTS) && !$album->isProtected())
```

#### Proposed Solution
I think an error should be displayed if the user does not have list rights to the album and the album is protected. Therefore, I believe the line should rather be:

```php
if (!$album->isMyItem(LIST_RIGHTS) && $album->isProtected())
```

This condition should ensure that the correct error message is displayed under these circumstances.

**Comment by acrylian** [comment]
Thanks, that seems indeed wrong.
