### ISSUE TITLE
MAMP 7 PRO, gettext and CGI mode *wip solution*

### ISSUE THREAD

**Issue by RolandTi** [zenphoto/zenphoto#1469]
Old but new, I know goodfellas :-)

So since MAMP 7 PRO, you can't set anymore PHP as "module mode", it's now only on CGI.

<img width="1160" alt="MAMP 6 PHP Module / CGI" src="https://github.com/user-attachments/assets/1ce5f59f-9f9a-4ebb-8c3d-0796ad8f4523">

_This is not possible anymore_

So, how to get Zenphoto running again ?

The **quick and dirty** solution I found is to add `putenv('LC_ALL=en_US');` in `index.php`, something like that : 
```php
<?php
define('OFFSET_PATH', 0);
putenv('LC_ALL=en_US');
```

Why not adding `setenv LC_ALL en_US` to `<virtualhost>` ?
![Capture d’écran 2024-09-24 à 09 57 07](https://github.com/user-attachments/assets/bc17d52e-25f2-4eb0-8969-0a1f0100a08f)

I don't now… whereas `getenv('LC_ALL');` give me `en_US`, (proof that works) Apache is still crashing.
If you don't set anything, LC_ALL is blank.

But i think we are really close to something.

Somebody reported this to _https://bugs.mamp.info/_ for a different CMS,
the anwser seems to set an LC_ALL from the MAMP team.

![Capture d’écran 2024-09-24 à 10 15 21](https://github.com/user-attachments/assets/776d4581-52fc-45f5-82c9-3fb7f97feb4c)

NB - I used `en_US` as a dummy value, fr_FR.UTF-8 is also good. The issue is the blank value.

**Comment by acrylian** [comment]
Sorry , not sure what issue this is about and what it has to do with Zenphoto. Zenphoto always worked in CGI mode as that is what you get on almost all standard hosts anyway. 

Not using MAMP Pro and due to an older Mac/macOS I currently cannot use MAMP 7. According to @fretzl who can run it MAMP 7 is  buggy so he reverted to 6 currently, too.

Even on MAMP  6 you have to disable mod_perl in the httpd.conf manually to get gettext working properly.

**Comment by acrylian** [comment]
We also have a artilce about that for quite some time: https://www.zenphoto.org/news/translations-gettext-not-working-on-some-servers/

**Comment by RolandTi** [comment]
Hello @acrylian, Github Issues is maybe not the right place to talk about this. Sorry.
As I m not the only one using MAMP for Zenphoto, I was looking for a place to talk about it. Maybe the forums is a better place.

**Comment by fretzl** [comment]
Take a look here: https://bugs.mamp.info/view_all_bug_page.php
Lots of issues with MAMP 7 and MAMP Pro 7

**Comment by fretzl** [comment]
Sorry, may bad. You need an account for this forum.

**Comment by acrylian** [comment]
I'll close this as it is not really ZP matters as discussed
