### ISSUE TITLE
tinymce4 settings (several small issues)

### ISSUE THREAD

**Issue by kuz-z-zma** [zenphoto/zenphoto#1473]
Several issues with tinymce4 plugin settings on most recent zenphoto version (1.6.5 rc):

- Reset button seems to do nothing
- Links to TinyMCE docs have changed and current links end up on their new main page:
  - https://www.tinymce.com/docs/configure/content-filtering/#entity_encoding to https://www.tiny.cloud/docs/tinymce/latest/content-filtering/#entity_encoding
  - https://www.tinymce.com/docs/configure/content-filtering/#entities to https://www.tiny.cloud/docs/tinymce/latest/content-filtering/#entities

- 2 options in settings for Raw character encoding
![image](https://github.com/user-attachments/assets/42134ae4-1bed-41b3-a0e1-8a1734c2780a)

**Comment by acrylian** [comment]
> Reset button seems to do nothing

Not sure we can solve this as that is a tinymce core function.

> Links to TinyMCE docs have changed and current links end up on their new main page

We are not on the current version (we are on v4, they have v7) and therefore cannot link to the "latest" docs as they may not match anymore. The oldes doc they provide is v5 on their site. https://www.tiny.cloud/docs/tinymce/5/

We have not yet upgrade because last time we checked tinyZenpage would have to be reworked quite a bit for work.  With the recent changes we probably re-investigate this now. Actually the plan exists to make the tinyzenpage functionality standalone, editor independent and tie that to a general admin functionalitly. But that's for later.

> 2 options in settings for Raw character encoding

Not sure why there are two list as there is only one defined but "raw" is also the default if not set ("null_selection").

**Comment by acrylian** [comment]
> Reset button seems to do nothing

Totally sorry, somehow was off here and thought you were referring to some tinymce plugin. You mean the general reset button, right? 
![Bildschirmfoto 2024-10-13 um 14 00 37](https://github.com/user-attachments/assets/816ef364-a4c4-4468-a224-90ffec0956c3)

That works for me and @fretzl as intended by HTML standards.

**Comment by kuz-z-zma** [comment]
> You mean the general reset button, right?
Yeah, those in the plugin settings.
But now I'm trying those with other plugins and browsers, maybe that's a something on my end, some browser issue...

> We are not on the current version (we are on v4, they have v7) and therefore cannot link to the "latest" docs as they may not match anymore.
Current links get redirected to their main page, so they are useless. Maybe just update to the most suitable link for now, so people don't have to search for it.

**Comment by acrylian** [comment]
> Yeah, those in the plugin settings.
But now I'm trying those with other plugins and browsers, maybe that's a something on my end, some browser issue...

Must be as of HTML it resets changes made to the form after it loaded. Not really aynthing we do from our end.

> Current links get redirected to their main page, so they are useless. Maybe just update to the most suitable link for now, so people don't have to search for it.

Yes, @fretzl meanwhile has updated them already.

**Comment by bic-ed** [comment]
> Yeah, those in the plugin settings. But now I'm trying those with other plugins and browsers, maybe that's a something on my end, some browser issue...

Are you looking for a "revert to default" behavior? That is not implemented for plugin options but only for theme ones.

**Comment by kuz-z-zma** [comment]
> Are you looking for a "revert to default" behavior?

Yes, that's the one.
I just remember, that TinyMCE plugin had default options listed in settings, so I expected it to work akin to themes.

**Comment by acrylian** [comment]
Okay then this ticket can be closed. The two other things are fixed. We never had such an option for plugins.  Some plugins do set default options, some even via setup but there is no general reset facility for this (nor planned).
