### ISSUE TITLE
make a responsive colorbox

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#682]
hi
in https://github.com/jackmoore/colorbox, I create an issue to request a responsive colorbox : https://github.com/jackmoore/colorbox/issues/158

colorbox doesn't implement yet it in core code, but there is a workaround to allow a responsive colorbox, share here : https://github.com/jackmoore/colorbox/issues/158#issuecomment-27061139.
you can found the same code in stakoverflow (http://stackoverflow.com/questions/12182668/how-to-make-colorbox-responsive).

could you implement this workaround for colorbox slideshow ?
with that, even if the theme is not responsive, the slideshow will be.

**Comment by designinsist** [comment]
@acrylian this only work when we resize window and does not work when try to open webpage in mobile. how can it work on mobile ?
