### ISSUE TITLE
1.4.6 beta improvement of tinyZenpage and cacheManager

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#809]
hi
with i.php, we are allowed to create a cropped picture with these parameters:
`i.php?a=[album_name]&i=[image_name]&w=[width of final picture]&h=[hight of final picture]&cw=[cropped width]&ch=[cropped hight]&cx=[width offset]&cy=[hight offset]`.

If I insert these value in a news, zenphoto create a cacheImage and replace the link with cacheImage URI:
`/cache/[album_name]/[image_name]_w[width of final picture]_h[hight of final picture]_cw[cropped width]_ch[cropped hight]_cx[width offset]_cy[hight offset].jpg`

but:
- TinyZenPage doesn't allow to insert this cropped picture in a news or a page, I have to generate it manually, by editing html code before saving my news or page.
- If I delete my cache, cacheManager doesn't want to refresh the cache with this picture.

It would be nice improvements if TinyZenPage and CacheManager could manage these cropped pictures.

one example here:
http://www.vincentbourganel.fr/news/nd-400-filter?locale=en_US
in html code, you could see these URI to a cropped pricture:
`<img class="ombre" src="/cache/20110721-vacances-ete-pays-basque/img_5671_w800_h189_cw1100_ch260_cx0_cy40.jpg"
alt="Cote Basque I">`

I have to insert these code in my news to generate this cache link:
`<img class="ombre" src="/zp-core/i.php?a=20110721-vacances-ete-pays-basque&i=img_5671.jpg&w=800&h=189&cw=1100&ch=260&cx=0&cy=40&wmk=!"
alt="Cote Basque I">`
and if I delete the cache, cacheManager (cache stored image tabs) doesn't recreate the cache image and I have this note:
`Note: the following objects have images that appear to no longer exist.
ND 400 filter (20110721-vacances-ete-pays-basque/img.jpg)`

**Comment by acrylian** [comment]
I will close this as it can be considere as part of #817 in general. We might not add visual cropping as TinyMCE itself allows cropping images and more as well. It does not cache them as we do but adds them as a data resource url then. https://www.tinymce.com/docs/demo/image-tools/
