### ISSUE TITLE
segfault in apache child process in libphp5

### ISSUE THREAD

**Issue by jlaba** [zenphoto/zenphoto#859]
On ubuntu 14.04.1 LTS (apache 2.4.7-1ubuntu4.1, php 5.5.9+dfsg-1ubuntu4.3) zenphoto (1.4.6) produces segfaults sometimes (e.g. gallery mainpage). Most times it works, but refreshing it a few times, an apache child is crashing.

The crashdump is attached, but the only thing I could extract is:
#0  0xb5134828 in ?? () from /usr/lib/apache2/modules/libphp5.so
#1  0xb515cc1c in _zval_dtor_func () from /usr/lib/apache2/modules/libphp5.so
#2  0xb5188937 in ?? () from /usr/lib/apache2/modules/libphp5.so
#3  0xb518a377 in execute_ex () from /usr/lib/apache2/modules/libphp5.so
#4  0xb514d3dd in dtrace_execute_ex () from /usr/lib/apache2/modules/libphp5.so
#5  0xb5214ba5 in zend_execute () from /usr/lib/apache2/modules/libphp5.so
#6  0xb5216012 in ?? () from /usr/lib/apache2/modules/libphp5.so
#7  0xb518a377 in execute_ex () from /usr/lib/apache2/modules/libphp5.so
#8  0xb514d3dd in dtrace_execute_ex () from /usr/lib/apache2/modules/libphp5.so
#9  0xb5214ba5 in zend_execute () from /usr/lib/apache2/modules/libphp5.so
#10 0xb5216012 in ?? () from /usr/lib/apache2/modules/libphp5.so
#11 0xb518a377 in execute_ex () from /usr/lib/apache2/modules/libphp5.so
#12 0xb514d3dd in dtrace_execute_ex () from /usr/lib/apache2/modules/libphp5.so
#13 0xb5214ba5 in zend_execute () from /usr/lib/apache2/modules/libphp5.so
#14 0xb5216012 in ?? () from /usr/lib/apache2/modules/libphp5.so
#15 0xb518a377 in execute_ex () from /usr/lib/apache2/modules/libphp5.so
#16 0xb514d3dd in dtrace_execute_ex () from /usr/lib/apache2/modules/libphp5.so
#17 0xb5214ba5 in zend_execute () from /usr/lib/apache2/modules/libphp5.so
#18 0xb515f55e in zend_execute_scripts () from /usr/lib/apache2/modules/libphp5.so
#19 0xb50fad35 in php_execute_script () from /usr/lib/apache2/modules/libphp5.so
#20 0xb5218a48 in ?? () from /usr/lib/apache2/modules/libphp5.so
#21 0xb773a6b6 in ap_run_handler ()
#22 0xb773ac37 in ap_invoke_handler ()
#23 0xb775233a in ap_process_async_request ()
#24 0xb7752611 in ap_process_request ()
#25 0xb774eb5f in ?? ()
#26 0xb7744c96 in ap_run_process_connection ()
#27 0xb6ae3e31 in ?? () from /usr/lib/apache2/modules/mod_mpm_prefork.so
#28 0xb6ae40c1 in ?? () from /usr/lib/apache2/modules/mod_mpm_prefork.so
#29 0xb6ae412d in ?? () from /usr/lib/apache2/modules/mod_mpm_prefork.so
#30 0xb6ae4fff in ?? () from /usr/lib/apache2/modules/mod_mpm_prefork.so
#31 0xb771f296 in ap_run_mpm ()
#32 0xb771805b in main ()

I do not really know, whether it is a zenphoto problem or a apache and libphp5 problem, but on another php5 site on the same host crashes had not appeared until now.

Regards,

Joachim

**Comment by acca** [comment]
I've discovered a very similar error using this vagrant environment based on Ubuntu 14.04 LTS: https://github.com/acca/zenphoto-vagrant.

Steps to reproduce (Apache2 Segmentation fault) the crash are:
1. Deploy locally with Vagrant
2. Complete installation
3. Go to Admin -> Plugins -> Try to enable a plugin -> Apply

The only solution I've found is to update php to 5.6, using this: https://github.com/acca/zenphoto-vagrant/blob/master/functions.sh#L66
```
cd zenphoto-vagrant
source functions.sh
upgrade_php
```
