### ISSUE TITLE
contact_form honeypot does not work with confirmation

### ISSUE THREAD

**Issue by fretzl** [zenphoto/zenphoto#885]
To test the "honeypot" I changed `contact_form/form.php: line 31` 
from
```php
<input type="text" id="username" name="username" size="50" value="<?php echo html_encode($mailcontent['honeypot']); ?>"<?php if ($_processing_post) echo ' disabled="disabled"'; ?> />
```
to
```php
<input type="text" id="username" name="username" size="50" value="SOME SPAM TEXT" />
```
* Plugin option `Require confirmation:` OFF<br />
Result: mail is not sent (= correct)
* Plugin option `Require confirmation:` ON<br />
Result: mail is sent (= not correct)

**Comment by acrylian** [comment]
The question perhaps is does a bot recognize the 2nd form to confirm after the page loaded again at all?

**Comment by fretzl** [comment]
Forgot to mention something important.

When the Plugin option `Require confirmation` = OFF, I get this notice:
```
NOTICE: Undefined variable: err_msg in .../zp-core/zp-extensions/contact_form.php on line 372
printContactForm called from include (contact.php [36])
from include (index.php [129])
from index.php [28] 
```

**Comment by acrylian** [comment]
Please try now.

**Comment by fretzl** [comment]
Yes, that works :-)
