### ISSUE TITLE
Brackets in tags

### ISSUE THREAD

**Issue by SubJunk** [zenphoto/zenphoto#887]
It would be cool to be able to use brackets in tags, for example "zenphoto (software)"

**Comment by acrylian** [comment]
A lot of things would be cool ;-) We'll put it on the list.

**Comment by SubJunk** [comment]
@acrylian if this helps, it is supported in zenphoto20, so it's probably a trivial addition. I can try looking for the commit/s tomorrow.

**Comment by acrylian** [comment]
Might be, we don't review or use code from the other zp though for various reasons (we did once months ago). If you can provide a fix yourself via a pull request that is always welcome.

**Comment by acrylian** [comment]
Just tried. Tags with brackets like your example do work for me actually. Where exactly don't they work for you?

**Comment by SubJunk** [comment]
Fixed in #888

**Comment by SubJunk** [comment]
In the admin panel I mean, adding tags to images. I verified both the bug and the fix in a fresh install of 1.4.6.

**Comment by acrylian** [comment]
I guess I am blind. I just assigned a tag name "testtag (test)" with no problem both via the checkbox list and the bulk actions on the images tab.

**Comment by acrylian** [comment]
Ah, now I got where you mean it doesn't work. Good catch. Thanks.

**Comment by SubJunk** [comment]
Cool! :)
