### ISSUE TITLE
jPlayer pause button does not show nor work

### ISSUE THREAD

**Issue by fretzl** [zenphoto/zenphoto#893]
When a video is started the start button in the controls-bar should change into a pause button.
The pause button can be made visible by adding these lines to the CSS:
```
.jp-state-playing .jp-type-single button.jp-play {
	background: url("jplayer.zenphoto.png") -108px 0px no-repeat;
}

.jp-state-playing .jp-type-single button.jp-play:hover {
	background: url("jplayer.zenphoto.png") -108px -31px no-repeat;
}
```
However, when you click the pause button the video doesn't pause.
This is the same for all skins.

**Comment by acrylian** [comment]
Indeed. Probably a typo since the template structure of jPlayer changes with the last update a bit.

**Comment by fretzl** [comment]
Committed a fix but still needs some CSS tweaks.

**Comment by acrylian** [comment]
I see the outlines in Safari as well (those are actually an accessibility default if you use tabs to navigate).

Strange is that now jPlayer refuses to play mp3 and demands a flash player update in Firefox and Safari In Safari mp3 is for sure natively supported … Could be a css sideeffect or Flash ist just annoying me…

**Comment by acrylian** [comment]
Because of the new JS config stuff added a comma was missing for single audio players. Needs to be tested with playlists.

**Comment by fretzl** [comment]
Fixed for now
