### ISSUE TITLE
No login box in zpMobile

### ISSUE THREAD

**Issue by wurzel555** [zenphoto/zenphoto#896]
Here is a screenshot taken of the login form I see on my site using zpMobile.

http://steveluther.de/nologinbox.jpg

As you can see there is no login box so I can not type my username in.

This has been tested on 2 seperate android devices. 4.2.2 and 4.0.4 aswell as IOS 6.x and windows phone, the username login box is missing on all of them. 

Cheers
steve

**Comment by acrylian** [comment]
As noted on the forum it was a general theme issue. The function call apparently used variables as parameters that were actually never set. Should be fixed in the master build

**Comment by wurzel555** [comment]
This is great thanks it now works, however once you log in it does not redirect you to the index page it takes you back to the login page and you have to select Gallery to go to the gallery. Where as if you click logout at the bottom of the page you get redirected to the index page.

**Comment by acrylian** [comment]
That is the default. If you wish another page you can set that on the `printPasswordForm()` call: 
http://www.zenphoto.org/documentation/functions/_template-functions.php.html#functionprintPasswordForm

**Comment by wurzel555** [comment]
Well I appear to be far to stupid to change it from NULL to index.php.

**Comment by acrylian** [comment]
Great!  Something like `printPasswordForm('', true, false,getGalleryIndexURL());` works for the index, just in case you tried something else ;-)

**Comment by acrylian** [comment]
Guess I can close this then.

**Comment by wurzel555** [comment]
This is what I did.

function printPasswordForm($_password_hint, $_password_showuser = NULL, $_password_showProtected = true, $_password_redirect = '/index.php') 

Your way looks neater but I can't find where you are referencing.

**Comment by acrylian** [comment]
What you apparently did you really never should do. You changed the function - the define of it - itself in a core file. You need to change the function call on the theme's `password.php`  page instead.

**Comment by wurzel555** [comment]
OK Changed it back and modified the theme password.php file.
Thanks for the help.
