### ISSUE TITLE
v1.4.7: Gallery Statistics generates fatal PHP error

### ISSUE THREAD

**Issue by MarkRH** [zenphoto/zenphoto#897]
When viewing the Gallery Statistics of the Overview section, I am missing sections such as the Most Viewed Albums. I checked in my PHP error log and saw:

[13-Feb-2015 22:28:58 America/Chicago] PHP Fatal error:  Cannot use object of type Album as array in /(path)/zp-core/utilities/gallery_statistics.php on line 223

Albums Latest is the last section to be generated. 

Looks like acrylian knows what it is: http://www.zenphoto.org/support/topic.php?id=1361970

**Comment by acrylian** [comment]
Thanks again. Should be just fixed in the master build.

**Comment by MarkRH** [comment]
The newer gallery_statistics.php file seems to work fine.  Thanks!
I noticed a few other newer files from 1.4.7 doing a windiff so I'll copy those over as well.

**Comment by acrylian** [comment]
Thanks! Generally we recommend to install the complete master to avoid issues of dependendies. But whatever works for you, especially if you know what you do :-)
