### ISSUE TITLE
Rating plugin not working on zpMobile

### ISSUE THREAD

**Issue by wurzel555** [zenphoto/zenphoto#898]
The star rating system is not displayed on the theme zpMobile, all you get is a o in the place where the stars should be. If you login you get an additional submit button under the o but still no stars.

You can see this at http://steveluther.de

Cheers
Steve

**Comment by acrylian** [comment]
Indeed, this seems to be a js and/or css conflict with the jquerymobile script that attaches its own classes to the elements. You actually get the stars if once you reload the page.

**Comment by wurzel555** [comment]
Thanks, you are correct they do appear once you refresh the page and work, but are gone again on the next page until you refresh.

**Comment by acrylian** [comment]
I quickly tested even to disable jquerymobile's attaching on the rating form elements but it simply doesn't work. All I could get is the unstyled radioboxes to show up which makes their use not really clear. Sorry no idea.

**Comment by wurzel555** [comment]
OK no problem, I will just use the theme bootstrap as it works on there. 

Thanks for looking anyway.

**Comment by acrylian** [comment]
We probably won't fix this as jQuery mobile prevents everthing we tried so far.
