### ISSUE TITLE
colorbox_js always loads on every page.

### ISSUE THREAD

**Issue by fretzl** [zenphoto/zenphoto#899]
It doesn't matter if the plugin is enabled or disabled or what options are set, it still loads on every page.

**Comment by acrylian** [comment]
For me as well. Strange is that the option check returns true although I can see it is set to 0 in the database.

**Comment by fretzl** [comment]
Seems to be caused by the `user_login-out.php` plugin but I can't figure out why.
Disable the plugin and you'll see that the colorbox_js files are not loaded everywhere anymore.

**Comment by acrylian** [comment]
Ah, but I can. It has an option to open the login form in Colorbox. If that is set it is loaded for all pages since the login form appears on all.

**Comment by fretzl** [comment]
Of course! Just pretend I didn't open this ticket ;-)

**Comment by acrylian** [comment]
Well, I didn't think of those dependencies either ;-)
