### ISSUE TITLE
Portrait photos appear upside down in 1.4.7

### ISSUE THREAD

**Issue by unrealdtc** [zenphoto/zenphoto#900]
After updating my existing ZenPhoto gallery from 1.4.6 to 1.4.7, I noticed that many of my pictures were being displayed upside down. I had to go through the painful process of rotating manually hundreds of incorrectly orientated photos. Then I noticed that new picture were too being incorrectly displayed.

Here is an example from my Xperia Z smartphone: http://files.slashorg.net/temp/IMG_20150214_220933.jpg -- however, photos from other makes and models of smartphones are also being displayed incorrectly.

**Comment by unrealdtc** [comment]
Additional information: images are detected as having "270 degrees" rotation in admin settings.

**Comment by fretzl** [comment]
Please try the support build. Automatic rotation should be solved.
Admin settings still under investigation.

**Comment by unrealdtc** [comment]
I've reverted zp-core/lib-GD.php and zp-core/lib-Imagick.php as of the following commit:
https://github.com/zenphoto/zenphoto/commit/355eb8bed980a04074083e37c9e6e70bed1f28f3

I'll tried it with one picture and the orientation is OK, and the admin is also OK (90° rotation).

**Comment by acrylian** [comment]
The master should now have all back to "normal". At least in my tests with GD and Imagick rotation was correct now.
