### ISSUE TITLE
1.4.7: Edit Image on many images launches batch edit mode with wrong images.

### ISSUE THREAD

**Issue by MarkRH** [zenphoto/zenphoto#901]
I created a thread here: http://www.zenphoto.org/support/topic.php?id=1362855

In order for the Single Image edit to work for all images, I have to set to Batch Images count to the highest value. For example, in one gallery this is 135.  If I set the value to say 5, then most images in my albums past the 5th image will open in batch edit mode with the 1st album image at the top.

I used a cookie editor to change the value in the imagesTab_imageCount cookie value so I didn't have to try and load 135 images or whatever.  The single image edit should work regardless of this value.

**Comment by MarkRH** [comment]
The problem appears to be in admin-edit.php around line 810. I added code to print out the value of images:

		$singleimage = NULL;
		if (isset($_GET['singleimage'])) {

                  $simage = sanitize($_GET['singleimage']);
                  echo '<pre>';
                  print_r($images);
                  echo '</pre>';
                  if (array_search($simage, $images) !== false) {
                     $allimagecount = 1;
                     $singleimage = $simage;
                     $images = array($simage);
                  }
               }

In the cases where it doesn't work, the image I am trying to edit is not shown and thus the if check fails. When I make the batch edit count larger, well the images list gets long enough to have the image I want included.

**Comment by MarkRH** [comment]
With more testing, it seems that with some albums the list of images is correct if the bulk value is 5 and in some the list of 5 images is not correct and doesn't contain the image I am wanting to edit. Weird.  Well, I don't know how it is exactly determining which 5 images will get stuck into the list. Depending where in the album I am, my photo will be in the list of 5 or not. LOL  I'm babbling.

**Comment by acrylian** [comment]
I can indeed reproduce this. It seems to be related to the order set on the backend which should really not involved here.

**Comment by MarkRH** [comment]
Cool. Glad it was reproducible.

**Comment by acrylian** [comment]
Please try the master.

**Comment by MarkRH** [comment]
That does indeed seemed to have fixed it.  Thanks!

**Comment by acrylian** [comment]
Great, thanks.
