### ISSUE TITLE
new-OR-dynamic-OR-album as album name for dynamic album (backend)

### ISSUE THREAD

**Issue by fretzl** [zenphoto/zenphoto#902]
Create a "New dynamic album".
If you do not supply a specific album name, the name of the new dynamic album will be:
*new-OR-dynamic-OR-album*

![new-dynamic-album](https://cloud.githubusercontent.com/assets/2480231/6269854/4718669a-b856-11e4-9566-4433dc973053.png)

**Comment by acrylian** [comment]
How do you do that exactly? If I click on the button and delete the default name in the dialog window I don't get to the create page at all. If I keep the default name I just get an album with that. 

If I don't enter a name on the create page I get an error about that on saving.

**Comment by fretzl** [comment]
I have the Search option *Treat spaces as*  set to *OR*
If I set that to *space* everything looks normal.

**Comment by acrylian** [comment]
That issue actually must have existed before. I did not change anything in the actual creation part.

**Comment by fretzl** [comment]
Not really an issue but it just doesn't look good.

A simple solution might be to just change the initial name from *new dynamic album* to
 *new-dynamic-album* (with hyphens) in admin-edit.php line 520.

**Comment by acrylian** [comment]
Ok, please try the fix.

**Comment by fretzl** [comment]
If the *Search criteria* field should look like this then it's ok I suppose...

![new_dynamic_album](https://cloud.githubusercontent.com/assets/2480231/6273623/3e346694-b871-11e4-9ec5-2fa985883465.png)

**Comment by acrylian** [comment]
Yes, if you set spaces to OR "new dynamic album" translates to that. If you set to AND you get ANDs.
