### ISSUE TITLE
Search issue with backslash in search term

### ISSUE THREAD

**Issue by bobatkins** [zenphoto/zenphoto#904]
Take the following scenario. You have 3 images in your gallery which were taken with a 50mm lens and for which the LensInfo EXIF data reads "50mm f/1.8". If you enter "50mm f/1.8" in the search function (and you've enabled it to search LensInfo) you get all three image thumbnails and the search page URL is ../zenphoto/page/search/"50mm+f/1.8" If you click on one of them you get the corresponding image page. At this point, if you click on the "search" tab at the top of the page you do NOT go back to the search results. You get a "page not found" error and the URL of that page is ../zenphoto/page/search/"50mm+f%2F1.8".

It seems to be the "/" character that's not being handled properly in the second search. I think it's searching for the literal string "%2F" rather than a "/" because if you replace %2F with the backslash character the URL is now what it was originally for the search, it works fine and it goes back to original search results of course.

**Comment by fretzl** [comment]
I can confirm this.
Seems like the forward slash is not an allowed character in search strings ?
See *class-search.php* line 128.
