### ISSUE TITLE
tiny improvement for German translation

### ISSUE THREAD

**Issue by tiltX** [zenphoto/zenphoto#905]
I have no experience with the gettext tools to create a patch for this, so I'm submitting this here:

I've just restored a database backup and the yellow note on the backup_restore.php page was a bit misleading. 

The English original text ist "Each database table is emptied before the restore is attempted." but the German translation corresponds to "Each database is emptied" which made me reluctant to click the restore button because I'm sharing my database with a Wordpress blog :-)

The better translation for this string would be:

Anmerkung: Jede Datenbanktabelle wird geleert bevor eine Wiederherstellung versucht wird. Nach einer erfolgreichen Wiederherstellung wird die Datenbank den selben Zustand wie zum Zeitpunkt der Backuperstellung haben.

**Comment by acrylian** [comment]
Yes, indeed, of course only the tables that belong to Zenphoto. Thanks ;-)
