### ISSUE TITLE
Admin menu styling issue in 1.4.7

### ISSUE THREAD

**Issue by wongm** [zenphoto/zenphoto#906]
The admin menu in version 1.4.7 generates invalid HTML, which breaks some themes.

It appears that this div is opened:
<div id="zp__admin_module">

Then this div:
<div id="zp__admin_data" style="display: none;">

zp__admin_data div is closed, but zp__admin_module never is closed.

Code is found here:

https://github.com/zenphoto/zenphoto/blob/c933ce65b3cb607a6b8a8c9531064ec9ab677842/zp-core/template-functions.php

**Comment by wongm** [comment]
See this pull request:

https://github.com/zenphoto/zenphoto/pull/907

**Comment by acrylian** [comment]
Thanks, indeed that got lost.
