### ISSUE TITLE
Gallery Articles Multilingual

### ISSUE THREAD

**Issue by RalfKerkhoff** [zenphoto/zenphoto#909]
Hi,
something goes wrong with the Gallery Articles Plugin.

I have enabled 'publish vor images only.

Settings in the plugin are:
New Album: %1$s

New Image: [%2$s]%1$s

If a new image is published, an article will be published, but it has the title:
New Album: %1$s

And the text:
s:0:"";

May it be possible that the despription in the plugin settings are wrong?
Seems like the plugin uses the settings made for an album when a image is published.

**Comment by acrylian** [comment]
Please try, at least in my tests so far it worked correctly in single and multilingual mode.

**Comment by RalfKerkhoff** [comment]
I will test in the next days.

**Comment by RalfKerkhoff** [comment]
Hi,
article will now be published correct.
But in english and german versions with the german title.
Setting in the Plugin is:
New Image: [%2$s]%1$s
Neues Bild: [%2$s]%1$s

Published is only the german title:
http://en.ralf-kerkhoff.de/kategorie/neuigkeiten/
