### ISSUE TITLE
1.4.7: Returning to first page of generic word search shows no results

### ISSUE THREAD

**Issue by MarkRH** [zenphoto/zenphoto#910]
Here's what I mean. On my gallery at http://gallery.markheadrick.com if you search for "snowstorm" which is not a tag and look at one of the images on the first page of results and then click on the Search link above to return to the results, you get a page that says no search results found. Looking at an image that's on the 2nd or 3rd page and then clicking on the Search link to go back to the results, works fine. Just the ones on the first page of results does this.

Searching actual tags does not have any problem.

Actually, just clicking the "next" link to go to page 2 and then the "prev" link to go page to page one, get a page with "Sorry, no matches for your search."

A bug I suspect.

**Comment by sbillard** [comment]
Works for me:

At http://testalbum.sbillard.org enter "slb" and you will get lots of images. If you can reproduce your failure, please describe the exact sequence of events.

**Comment by MarkRH** [comment]
I went there and I can't click on the "next" link to get to the second page of images. Just shows the same 1st page. The "2", "3" and other links also don't work.  I'm running into to other issues with the search as well. I need to document/reproduce them and get back.

**Comment by MarkRH** [comment]
After downloading the latest zenphoto-master and changing one of my .htaccess rules, it's working properly.  So, uhm, nevermind. :)  I also had to clear browser cache and cookies to get the correct stuff being shown.
