### ISSUE TITLE
Image pages from search results using the theme of the album to which they belong.

### ISSUE THREAD

**Issue by bic-ed** [zenphoto/zenphoto#915]
At least until v1.4.5, image pages from search result were displayed using the main theme of the gallery. Now, in v.1.4.7, they are loading the theme of the album to which they belong. 

Note that the above does not happen with dynamic albums, that use the theme choosen in their own options.

**Comment by acrylian** [comment]
We will take a look asap. Have to admit I never really use this feature myself but the multiple_layouts instead.

**Comment by bic-ed** [comment]
Probably I should switch to multiple_layouts too. I'm using album themes since before multiple_layouts was introduced. However I'm wondering if the same may happen with multiple_layouts too.

**Comment by acrylian** [comment]
It might indeed if assigned to an specific image. But generally this sounds like a bug.

**Comment by bic-ed** [comment]
I'm unsure if the following is somehow related to this issue, but note that, with master version of **paged_thumb_nav**, if (and only if) thumbs from different album are simultaneously present in an image page a fatal error occurs.
 ` trigger_error called from Image->__construct (class-image.php [145])
from newImage (class-image.php [52])
from pagedThumbsNav->getThumbs (paged_thumbs_nav.php [233])
from pagedThumbsNav->printThumbs (paged_thumbs_nav.php [248])
from printPagedThumbsNav (paged_thumbs_nav.php [475])
from include (image.php [126])
from include (index.php [129])
from index.php [28] `

Again, this does not happen with dynamic albums.

With 1.4.7 version of paged_thumb_nav, the one fixed in commit 73e6c47f5681efe9579d5a9bd937fe61ab9e2792, no error occurs.

**Comment by acrylian** [comment]
I think I don't understand the part " if (and only if) thumbs from different album are simultaneously present in an image page" ;-) 
I just tested it with the master in the Zenpage theme with a normal album and all works as expected for me.

**Comment by bic-ed** [comment]
With image pages from a single album it works, even if the album is dynamic.

Here I'm talking about image pages from a search results. In this context, it may happen that all the thumbs present in an image page are - even so -from the same album. Then it works too.

The problem with paged_thumb_nav occurs only if the thumbs displayed in an image page are from different album.

**Comment by acrylian** [comment]
Ah, now I got it and I can even reproduce it.

**Comment by bic-ed** [comment]
I was about to open a new ticket, then I saw your fix. I've tried the fixed file but I get the same error.

**Comment by acrylian** [comment]
Hm, I did try in normal and dynamic albums and search context without getting any. All in the Zenpage theme.

**Comment by bic-ed** [comment]
Don't know what's going on then. I still get the same problem. From the log, it seems that the function giving the *file does not exist* error is `getThumbs()`, instead of `getNextThumbsLink()` where you made the changes.

**Comment by fretzl** [comment]
I noticed I had both activated *paged_thumbs_nav.php* and *bxslider_thumb_nav.php* 
(which should not be possible or at least throw an error ??)
When I made sure that only *paged_thumbs_nav.php* was activated I got the same fatal error.

**Comment by bic-ed** [comment]
@fretzl, I tried activating bxslider too but the error is still there. Be aware that this is a really hidden problem, because it happens only when thumbs from different album are printed on the same image page from search results.

**Comment by acrylian** [comment]
I cannot reproduce the bxslider/pagedthumbs error with the recent changes
Normal album:
![bildschirmfoto 2015-03-19 um 10 24 38](https://cloud.githubusercontent.com/assets/2474309/6727451/4ec406f6-ce22-11e4-9bb8-14a758be4702.jpg)

Dynamic album:
![bildschirmfoto 2015-03-19 um 10 24 53](https://cloud.githubusercontent.com/assets/2474309/6727454/552bf850-ce22-11e4-9f54-d0e341beb817.jpg)

Search results:
![bildschirmfoto 2015-03-19 um 10 24 27](https://cloud.githubusercontent.com/assets/2474309/6727459/5ac463c4-ce22-11e4-9514-5204a0a88a87.jpg)

What I do notice is that there are several thumbs selected if they have the same file name but are from different albums (this is btw something that does NOT work with dynamic albums anymore since they now have the url of the dynamic album instead the original - you have to use unique filenames).

I hope I get to test regarding the album theme issue today.

**Comment by bic-ed** [comment]
Uhm, and I also see that thumbs in your last screen shoot are from different album, because, as you said, they have the same filename (several are selected). This is really strange, I still get the error in that context, even with zenpage theme. I'll try to figure out what's going on, thanks for your help.

**Comment by bic-ed** [comment]
And this is really, really super weird: I've tried a search giving as results two images with the same filename from different album. Both are selected (in my layout they have the same opacity) but no error happens:
![untitled-1](https://cloud.githubusercontent.com/assets/2939831/6728216/936a5c96-ce28-11e4-81b2-2c197e28e82b.jpg)

The error is present in a *real life* situation: different filenames from different album
![untitled-1](https://cloud.githubusercontent.com/assets/2939831/6728347/8350362c-ce29-11e4-8bba-b31229a44948.jpg)

No error in another *real life* situation: different filenames from the same album.
![untitled-1](https://cloud.githubusercontent.com/assets/2939831/6728418/0a2ca496-ce2a-11e4-9cca-982f321f067c.jpg)

All the screen shots above are from search context.

**Comment by acrylian** [comment]
Sure you don't have an html cache or browser cache interferring? Or search cache? Please try the Zenpage theme, too. to exclude any issues in this rather new theme (which is "half offcial" actually since by a team member)

**Comment by bic-ed** [comment]
No, no caching whatsoever and I tested also with zenpage theme.
Anyway the theme in the shoots is my own very old theme, derived by *zenpage*, that I update after every upgrade of Zenphoto, and at the moment has still some deprecated functions to replace. That's way I always make my test with official themes too. 
![untitled-1](https://cloud.githubusercontent.com/assets/2939831/6728712/06248df8-ce2c-11e4-8802-9bb5967ac188.jpg)

**Comment by acrylian** [comment]
Hm, strange, no idea if I cannot reproduce it …

**Comment by bic-ed** [comment]
I can't figure out either, it's a very strange issue. Please, if you can and have time, just try a search without images with the same filename in the results, but still with thumbs  from different albums displayed in the same image page.

**Comment by acrylian** [comment]
That should really not make any difference … And I just tried successfully …

**Comment by bic-ed** [comment]
Tank you. It made difference on my tests however, for some unknown reasons. That's why I asked.

**Comment by acrylian** [comment]
Yes, of course and I appreciate that you "insist" on it as I/we of course do miss issues as we surely miss testing special circumstances. We keep an eye on this …

**Comment by bic-ed** [comment]
Well, it seems I found a way to make it work, by changing the `getThumbs()` function too. But my knowledge of zp code is just too weak to make me aware of possible different issues generated by my solution. I'll make more tests and then I'll show this candidate fix.

**Comment by acrylian** [comment]
I guess you are right, that needs the same change even though I don't see the issue right now.

**Comment by acrylian** [comment]
You were right and it was my fault and oversite. Thanks for insisting on the issue again.

**Comment by bic-ed** [comment]
Oh, that's great! Now everything is ok, thank you!
Can I ask you what you mean with oversite?

**Comment by fretzl** [comment]
Haha, that should be oversight ;-)

**Comment by bic-ed** [comment]
Ah ok, thanks fretzl.

PS
I didn't test bxslider and I don't see any changes on it in the commit. Be sure that the same is not needed there also.

**Comment by acrylian** [comment]
@fretzl: Not in the commit text though ;-)

@bic-ed: bxslider is a different setup and has no similar function. That's why I missed yesterday it worked there but not in paged_thumbs_nav.

Back to the actual ticket issue :-): I can reproduce that and I am looking into it right now.

**Comment by bic-ed** [comment]
Argh! now I realize that in your screenshots the plugin enabled was bxslider instead of p.t.n, was it? That's why it was working!

**Comment by acrylian** [comment]
Yep, we just have confused each other since before the update both threw the same error ;-)

**Comment by fretzl** [comment]
The fix works for me. No more *paged_thumbs_nav* errors either.

**Comment by bic-ed** [comment]
Same here, everything fixed. Thanks again.

**Comment by acrylian** [comment]
We have to thank as well. Maybe you like to become regular tester? ;-)

**Comment by bic-ed** [comment]
Thanks for the offer, I really appreciate. Sadly I can't do this on a regular basis at the moment. As you may know, I barely manage to update my own web site, my theme and the plugin thumbsZoom every 18 months or so.
What I can do is to keep updated the italian translation for the main releases of Zenphoto, if you wish.

**Comment by acrylian** [comment]
No problem, everything you can contribute is appreciated.
