### ISSUE TITLE
Feature suggestion: Filter images in administartion by published state

### ISSUE THREAD

**Issue by tw2003** [zenphoto/zenphoto#916]
At the moment (1.4.7) one can sort images by several criteria like Title ID etc. I would find it easier to find and edit unpublished pictures if there would be a filter on the image administration page. The normal practice (at least for me) would be to upload an image in unpublished state, then edit it (especially when multilingual option is used) in title, description, tags and so on. The filter would support in easier editing.

**Comment by acrylian** [comment]
I just tried to refresh myself and think it is already there basically. If you set "Display images by:" to "Published" you get all unpublished images followed by the published ones.

**Comment by tw2003** [comment]
Yes that's right but then sort order is always ID. I would find more practical to sort by title (or whatever you want - like it is at the moment) and additionally filter by unpublished. Especially when you have large albums it would make it easier to work on newly uploaded files. Maybe it's only interesting for my case however it would be a nice feature :-)

**Comment by acrylian** [comment]
I do see the purpose, it is however a far more complicated change than it sounds. I will keep it in mind for the next bigger release.
