### ISSUE TITLE
User registering with same email addresses

### ISSUE THREAD

**Issue by haroon310** [zenphoto/zenphoto#919]
Hi, using 1.4.7 support build - Zenpage Theme. Found the following problem:

Users with different Users ID but with same email address can both register. e.g.

If there is already a user who has registered with a user id of "user1" and an email of "user1@testmail.com" then a second user can register with a user id of "user2" and the same email as user1 i.e. "user1@testmail.com"

However if the second user also uses the same user id e.g. user1 then the "Registration Failed" Message comes up saying that user ID user1@testmail.com is already in use.

Moreover if the second user uses the same user id i.e. user1 but a different email address e.g. user2@testmail.com then the "Registration Failed" Message comes up saying that user ID user2@testmail.com is already in use which actually is not the case. It should give the message that user ID is already in use.

**Comment by acrylian** [comment]
An mail address can be the user id which I am not sure why this was introduced anymore and without any check for unique mail addresses. This will take a while as that is all code by our former colleague.

**Comment by haroon310** [comment]
ok thanks, waiting

**Comment by haroon310** [comment]
roughly how much time is required for this

**Comment by acrylian** [comment]
Can't say exaclty, whenever I find the time to look into it.

**Comment by haroon310** [comment]
thanks, is it ok to copy and paste these three files from github

**Comment by haroon310** [comment]
Its not working at my end, giving this error:
"Registration failed. Your registration attempt failed a register_user_registered filter check."

i even downloaded the three changed files from support build and updated but no help.

**Comment by acrylian** [comment]
You need to install the support build itself. As said before downloading individual files is never recommended and on your own risk as we don't test that. 

In my tests all worked as intended otherwise I would not have committed it. Please review your error logs.

**Comment by haroon310** [comment]
ok I just edited my own files with the new code and it's working. I believe replacing the whole files would run only with other support build files. Thanks.

One more thing, i recently started a project on wordpress (first time) and saw a very interesting feature i.e. child theme. Whenever the update comes you dont have to change your design again. 

Does Zenphoto has anything like that? If I install the support build again then I will have to customize from all over again. How can I avoid this?

thanks

**Comment by fretzl** [comment]
Everything works for me too.

@haroon310  Best you ask that question on the forum again as it is not related to this specific issue.
Thanks !

**Comment by haroon310** [comment]
fretzl you were 4 mins late :)

**Comment by haroon310** [comment]
the following also need to be upadated

zp-extensionz/register_user.php - line 442

<?php printf(gettext('The user ID <em>%s</em> is already in use.'), $admin_e); ?>

<em>%s</em> displays the email address instead of user id

**Comment by acrylian** [comment]
The "problem" is that if you set the related option the email is the user id. This originally was not my part of the code (and I personally almost never use this I admit) and I don't remember why this was introduced and if I actually like itI like this concept at all. We probably will change it in the future that a user account is always required to have a unique user id and unique email (just like it is basically anywhere else that I know).

**Comment by acrylian** [comment]
I made a small change. If you could try with both normal user id and mail as id setting that would be appreciated.

**Comment by haroon310** [comment]
1) normal user id = works perfect

2) mail as id setting = does not work (it registers with an email which is already registered)

**Comment by acrylian** [comment]
Ok, 2) I can confirm that. The field is not the mail field anymore then so it is not check. What a mischmasch … I am quite sure we will get rid of these two options in the  future.

**Comment by haroon310** [comment]
since i dont need the "mail as id" option anyways, i am done. thanks a lot.

do u have any write up on custom/child theme? in which i can update to new versions without having to redesign every time

**Comment by fretzl** [comment]
If a custom theme is properly made then updating is not needed, apart from an occasional change in a function.
If you modified files in the core (zp-core) you'll have to apply the same modifications with every new version. That's why we never recommend it.
Recommended reading :-)  http://www.zenphoto.org/news/theming-tutorial

**Comment by acrylian** [comment]
@haroon310 To the theme question as fretzl said please don't mix unrelated topics in the future. It gets really inconvenient. In short: We don't have child themes like WP.

**Comment by haroon310** [comment]
thanks and sorry
