### ISSUE TITLE
Unable to update user profile info

### ISSUE THREAD

**Issue by haroon310** [zenphoto/zenphoto#920]
Hi, using 1.4.7 Support Build - Zenpage Theme.

In the control panel under user tab, if i try to change the info of a particular user (including my own admin profile) e.g. changing city or street info in the address field. Clicking the apply button shows as if changes are applied but when the profile is viewed, there are no changes.

**Comment by acrylian** [comment]
Fixed meanwhile in support build

**Comment by haroon310** [comment]
do i have to update the complete thing again with support build or I can edit the code in the concerned file?

**Comment by acrylian** [comment]
You can but we don't test separately so best is always the whole thing.

**Comment by haroon310** [comment]
regarding this issue can I know which files have changed and what has changed?

**Comment by acrylian** [comment]
See GitHub for that or do a file compare.

**Comment by haroon310** [comment]
New in github so not very sure how this works, I believe you have done the following changes:

1) zp-core/admin-users.php

After This: $userobj = Zenphoto_Authority::newAdministrator($user);

You Added This: markUpdated();

2) zp-core/zp-extensions/common/fieldExtender.php

Replaced This: if (isset($_POST[$field['name']])) {

With This: if (isset($_POST[$field['name'] . '_' . $i])) {

Is that it? Its working now.

**Comment by acrylian** [comment]
You can review any commit and its changes on GitHub.I have done other changes meanwhile so I don't memorize exactly what I did when but I think that might have been it.

**Comment by haroon310** [comment]
ok thanks a lot for the help, much appreciated
