### ISSUE TITLE
unable to change title of a dynamic sub album

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#921]
hi
few months ago, I opened a thread in zenphoto forum about this issue.
http://www.zenphoto.org/support/topic.php?id=1318926
with 1.4.7 master, the issue is still here and I can't rename a dynamic album with a lot of picture in it.

**Comment by acrylian** [comment]
Here you have the reason why you should open a ticket because forum threads get lost ;-)

Sorry, I cannot reproduce it as I just renamed a dynamic album successfully. Keep in mind that the name must include the suffix in any case. Also the reason might be permission errors.

**Comment by vincent3569** [comment]
as you have told that the issue had been fixed, I didn't opened a ticket on github.
but I hadn't tested it yet.

of course I am talking about the album title and not the filename of dynamic album which stays the same.
as told before, in fact, all data of dynamic album (album title, description) are not saved (album title stays with the album filename, without suffix)

**Comment by acrylian** [comment]
Sorry, double misunderstanding, I looked at the forum post I didn't remember afterwards and if you say "renaming" I refered to the name and not the title.

**Comment by vincent3569** [comment]
hi,
I don't undesstand why you closed this ticket.
with last support build, I still can't change Album Title and Album Description for a dynamic album with 500 pictures.

If may be usefull, I can give you admin login, to see the issue on my website.

**Comment by acrylian** [comment]
It was closed because I cannot reproduce it. It works for me as intended. Sorry.

**Comment by fretzl** [comment]
I can't find any problems either.

**Comment by vincent3569** [comment]
so, WTF ?
how namy pictures have you in you dynamic album ?
can you help me to set some debug log to demonstrate the issue ?
what should be the rights on filename "dynamic.alb" ?

**Comment by acrylian** [comment]
I had setup a dynamic album with 500+ images although the number of images should really not be important. Title etc. are stored in the database, on the search query is within the file itself and the name of course.

Rights to the file should be 644 generally.  Is there really no error? ZP, server, browser logs?

**Comment by vincent3569** [comment]
I have a look on database and my dynamic album isn't stored :-s

**Comment by vincent3569** [comment]
some screenshot

with an existing dynamic album : all going well
I can see Portfolio album in admin pages
![capture1](https://cloud.githubusercontent.com/assets/1224809/6988938/56bb1d00-da56-11e4-8c4e-cee8e0321f64.PNG)

I can see it in admin database (images/porfolio.alb, and title is Porfolio
![capture2](https://cloud.githubusercontent.com/assets/1224809/6988976/9320be9e-da56-11e4-9045-b674c4a7fecc.PNG)

I can rename it Portfolio2
![capture3](https://cloud.githubusercontent.com/assets/1224809/6988983/a629d692-da56-11e4-8252-6017b1e63a0c.PNG)

 I can see it in admin database (images/porfolio.alb, and title is Porfolio2)
![capture4](https://cloud.githubusercontent.com/assets/1224809/6988997/d09ecf18-da56-11e4-80fe-75512bd30ab7.PNG)

**Comment by vincent3569** [comment]
when I create an new dynamic album with a lot of pictures.
![capture6](https://cloud.githubusercontent.com/assets/1224809/6989038/43094e5c-da57-11e4-9454-a6b95f694e33.PNG)

I can see images/geolocalized album in admin pages
![capture7](https://cloud.githubusercontent.com/assets/1224809/6989061/6e41ed86-da57-11e4-8152-cc798786cbb8.PNG)

and the album file exists
![capture11](https://cloud.githubusercontent.com/assets/1224809/6989073/b9a8632c-da57-11e4-9314-24864641b415.PNG)

but the album doesn't not exist in database
![capture8](https://cloud.githubusercontent.com/assets/1224809/6989077/ce456172-da57-11e4-8bfb-c85553b37c2c.PNG)

when I try a rename album to "geolocalized images" : zenphoto agree the renaming
![capture9](https://cloud.githubusercontent.com/assets/1224809/6989089/041fa6b8-da58-11e4-9c85-e5c791f5a9e1.PNG)

but the album isn't not renamed and still doesn't exist in database
![capture10](https://cloud.githubusercontent.com/assets/1224809/6989098/23c71118-da58-11e4-9f0d-58f4e74ddc0e.PNG)

**Comment by acrylian** [comment]
You should have mentioned in the first place that this is sub album. Now I can reproduce as well.

Btw, please use the right Zenphoto terms to avoid confusion. You are not "renaming" but "re-titling".

**Comment by fretzl** [comment]
I may have finally narrowed it down to the function `setDefaults()` in class-album.php line 78.
There is no parent-id set. If I hardcode the parent-id for the new dynamic album I can change title, description, etc without problems.

Note that there is a second `setDefaults()` function on line 1227. There a parent-id is set.
Unfortunately I have no idea how or if both functions interact.

**Comment by vincent3569** [comment]
hi
I have this issue again with 1.4.10!

**Comment by acrylian** [comment]
Sorry, works for me, quickly tried both with a toplevel album and a subalbum.

**Comment by fretzl** [comment]
If I create a fresh dynamic album as a **top**level album I can change the title.
If I create a fresh dynamic album as a **sub**level album I cannot change the title.

If I move the dynamic **sub**album to **top**level I can change the title.
If I move that same dynamic album from **top**level to a **sub**level again I can still change the title

**Comment by vincent3569** [comment]
Hi
I discover the issue yesterday.
when I updated zenphoto to 1.4.10, the dynamic abum called `Portfolio` has been renamed in `images/Portfolio`.
if I try to rename it with `Portfolio`, it remains with this name `images/Portfolio` after saving.

so, with your feedback, I delete this 'old' dynamic album and create it again from scratch.
now, I can do what I want with it (rename, deplace,...).

I don't know where is the matter

**Comment by acrylian** [comment]
A bit confused: Are we talking about changing the name or the title? I only tried the title.

**Comment by vincent3569** [comment]
I was talking about the album title .
