### ISSUE TITLE
fatal error after deleting picture with bulk action

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#922]
hi

tested with support build of 1.4.7.
I don't know where is the issue, but I give you the way to reproduce it.

I add 3 new pictures in an album, created in 2015.
I visit the album in the front end: all is ok, I can see the 3 pictures.
I make a search with 2015: all is ok and I can see the 3 pictures.

now, I edit the album (image order tab) and I delete this 3 pictures with a bulk action, and after that, I don't go albums/images tab, neither on album in my front end.
on my front end, I make a new search with 2015 and I have a fatal error:

```
    {3887:Sun, 22 Mar 2015 09:11:03 GMT} Zenphoto v1.4.7[2f43bf5f78147f7b97b6e4245692067e2f830a53]
    ERREUR GÉNÉRÉE PAR L’UTILISATEUR : Instanciation invalide de l’image : le fichier n’existe pas dans /home2/avbo7291/public_html/zenphoto_test/zp-core/class-image.php à la ligne 145
    trigger_error called from Image->__construct (class-image.php [145])
    from newImage (class-image.php [52])
    from printSlideShowLink (slideshow.php [613])
    from include (search.php [65])
    from include (index.php [129])
    from index.php [28]
```
and html flow is broken.

if I go to albums/images tab, or on album in my front end, before making new search, the error disapear.
I suppose it's an issue of garabage collector in image order tab.

**Comment by acrylian** [comment]
Please try the same but disabling the search cache.

**Comment by vincent3569** [comment]
If I disable search cache, I don't have the issue.

**Comment by acrylian** [comment]
I guess we could add both a "clear search cache" utility button and maybe something to clear it on deleting items.
