### ISSUE TITLE
Libratus theme Locale/language issue

### ISSUE THREAD

**Issue by wurzel555** [zenphoto/zenphoto#923]
Hi, 

I have a slight issue with the libratus theme. When I change the language to anything except English the only text that changes language is Login and Register.

See screenshot. http://steveluther.de/locale_error.jpg
You will see I have selected German but everything is in English except Login and Register which is in German.

This happens no matter which language I choose. All other text stays in English.

**Comment by acrylian** [comment]
Please see my forum reply: http://www.zenphoto.org/support/topic.php?id=1384986#post-1950611
