### ISSUE TITLE
Adding albums via file system: problems with special chars (German ä, ö, ü)

### ISSUE THREAD

**Issue by mindhaq** [zenphoto/zenphoto#924]
On a Ubuntu 12.04 server, files in the /albums folder with non-ascii special characters cannot be parsed by Imagick.

ERROR: unable to open image `/var/www/zenphoto/albums/Berlin/A100 Baustelle 2015/2015-02-27 14-02-48 Hinterhaus BeermanstraÃe 22.jpg':  @ error/blob.c/OpenBlob/2587 in /var/www/zenphoto/zp-core/lib-Imagick.php on line 412

The charset check during setup went fine, everything is set UTF-8 (server and zenphoto options).

Renaming the file so it does not contain the umlaut anymore helps.

Disabling Imagick in php, and using gd helps a little, at least then all images are added to the album, although those with umlauts are broken.

The umlauts break in the following way:
"Brückenbau" turns to "BruÌckenbau"

MySQL, Linux and Zenphoto are all configured to use UTF-8

I have seen that there was a similar issue in 2012: #131

Zenphoto 1.4.7
PHP 5.3.10-1ubuntu3.17
PHP Imagick library 3.1.0RC1
ImageMagick 6.6.9-7 2014-03-06 Q16

**Comment by acrylian** [comment]
Does it work with the GD libary? This might be just a server issue as often special chars still do cause issue although they shouldn't. I still always recommend to "clear" filenames either before uploading or using the seo plugins included.

**Comment by acrylian** [comment]
I can reproduce the issue.

**Comment by mindhaq** [comment]
With gd, the images are also not read correctly, but at least zenphoto continues to work.

When imagick crashes (continously), all albums, in normal and admin view, do not display correctly.

I'll try the SEO plugin, which might help with broken URLs. But still the Umlauts are there for a reason, and get displayed as image titles as well.

**Comment by mindhaq** [comment]
updated the ticket description a bit

**Comment by acrylian** [comment]
GD does work for me (of course the url looks bad).

> But still the Umlauts are there for a reason, and get displayed as image titles as well.
Sure they are there for a reason but file names and titles are independent with Zenphoto.

**Comment by sbillard** [comment]
Surely the problem is with the line 
`		if ($ping->pingImage(filesystemToInternal($filename))) {`

I would presume the Imagic expects the filename to be in the character set of the file system. This code will convert it to [presumably] UTF-8. Unfortunately I do not have an installation that supports Imagick so I cannot test. Please remove the `filesystemToInternal()` function call and see it that fixes the problem.

**Comment by mindhaq** [comment]
I will try, but the problem seems not so much related to Imagick, but more to file reading in general.

The following image was parsed (from disk on server) without Imagick, and there's still a problem with the Umlaut:

http://zenphoto.2rue.de/Berlin/A100%20Baustelle%202015/004+BruÌ%C2%88ckenbau.jpg#view

Uploading such Images with http or jQuery is no problem, with or without Imagick.

**Comment by mindhaq** [comment]
I will take a look at that problem during the weekend, and will hopefully find a solution :)

**Comment by sbillard** [comment]
On further examination, there are multiple instances of use of `filesystemToInternal()`. All but the one in `zp_getFonts()` are likely wrong. The only explanation for this use would be if Imagick used UTF8 internally. Even then, there is the possibility that the internal character set is something other than UFT8 (but not likely.)

**Comment by mindhaq** [comment]
as far as I understand, these calls to filesystemToInternal() were provided as a fix of #131, weren't they?

**Comment by sbillard** [comment]
There are some issues in PHP regarding folders with characters with diacritical marks. We have worked around the ones we are aware of. As well, on reviewing #131, the comment suggests that the fix was a "shot in the dark". If we really do not know what character set Imagick wants we do not have a consistent fix.

It would be interesting to know the value of the function `mb_internal_encoding()` on your server.

**Comment by mindhaq** [comment]
`mb_internal_encoding()` results in ISO-88591-1

The files are read ok at least in some part. All the EXIF data is there.

http://zenphoto.2rue.de/Berlin/A100%20Baustelle%202015/004+BruÌ%C2%88ckenbau.jpg#view

But along the way to using the filename as title and passing it to gd or imagick, the filename breaks.

**Comment by sbillard** [comment]
Ok, then this is the issue. 
Check the character set option on your general options tab. That should normally be UTF8. If it is then check your PHP configuration. You should find `default_charset` in your PHP.ini file and set it to "utf-8".

Zenphoto will try to set the PHP character set to the option, but of course some servers might reject this setting.

**Comment by mindhaq** [comment]
I changed `default_charset` to utf-8, checked via a phpinfo() script. That's also more for a default `Content-type` HTTP response header, AFAIR.

Anyway, `mb_internal_encoding` is still ISO-8859-1, and I have the same problems as before. With Imagick or without.

**Comment by sbillard** [comment]
For you, then the `filesystemToInternal()` calls must be removed, at least until we find a better solution.

**Comment by mindhaq** [comment]
I did some more debugging with the charset conversion code, and found out that my FILESYSTEM_CHARSET was set to ISO-8859-1.

The message in the setup script is:

> The Zenphoto filesystem character define is ISO-8859-1 [assumed]

So I added the following line in `zp-data/zenphoto.cfg.php`:

```php
$conf['FILESYSTEM_CHARSET'] = "UTF-8";
```

So it had nothing to do with gd or imagick, but there seems to be bug during setup which is not setting that configuration correctly.

Should I open a follow-up issue for that?

**Comment by acrylian** [comment]
I get the same on my test server. And setting the filesystem charset manually fixes it indeed.

The problem is that getting the charset from the filesystem is not reliable as we just encountered. I guess we can set UTF-8 by default and offer an option to switch next to thte internal charset option if it doesn't work out.

**Comment by mindhaq** [comment]
UTF-8 default surely would be a better default.

BTW, just by grepping through the code, I found nothing actually setting FILESYSTEM_CHARSET anywhere...

**Comment by acrylian** [comment]
It is set in `/zp-core/setup/setup-primitive.php` (default) and `/zp-core/setup/index.php` (setup selector)

**Comment by acrylian** [comment]
I have now added a new default option for it so you can set it there as well additionally to the define in the config file. (btw, on the local Mac MAMP server special chars don't work regardless of settings).

**Comment by sbillard** [comment]
If you had originally placed the appropriate `charset` file in your zp-cata folder as setup suggested then zenphoto could have determined the filesystem character set. Otherwise it would just guess. On most servers the character set is ISO-8859-1, so that is the best guess.

**Comment by acrylian** [comment]
I did use the charset file and it determines `ISO-8859-1` (Debian linux based live server). But it is not correct apparently:
Image used is without exif data so the filename is imported as the title:

GD lib, works but chars are imported wrong and the url looks encoded:
![gd-with-iso](https://cloud.githubusercontent.com/assets/2474309/6851912/0f6aeb08-d3e2-11e4-82ce-34f4ec4608e3.jpg)

Imagick crashes completely:
![imagick-with-iso](https://cloud.githubusercontent.com/assets/2474309/6851952/3d22b5da-d3e2-11e4-8d6f-064b1b872617.jpg)

But if the default define in functions-basic is set to UTF-8 it works for both GD and Imagick:
![imagick-with-utf8](https://cloud.githubusercontent.com/assets/2474309/6851961/47497788-d3e2-11e4-9d6e-b58c884c710c.jpg)

**Comment by mindhaq** [comment]
My observations were the same as @acrylian above, including the botched charset detection via the charset file.

Also, when imagick crashes like this, it does so in a way that the whole zenphoto is behaving strange (albums not showing up at all, even in admin mode, etc.)

**Comment by acrylian** [comment]
Thanks, then it sounds good to me to keep UTF-8 as the new default filesystem encoding instead of ISO-8859-1. That probably will help a lot languages with more special chars than English, too. Especially since you now can choose another encoding afterwards if it doesn't work out for some reason that should not be a problem. 

Best you try the master build.
