### ISSUE TITLE
Admin -> manage pages error

### ISSUE THREAD

**Issue by mearas** [zenphoto/zenphoto#925]
Manage Pages seems to be broken;

![screen](https://cloud.githubusercontent.com/assets/11654723/6835814/84ed1716-d33d-11e4-8c53-6a8bc49a118f.jpg)

Happens when I tick one or more checkboxes and save.  After the page refresh only one is checked with wrong name (see above). When I untick this one and save, everything is fine.

This does not happen when I tick "manage all"; default theme also tested

**Comment by acrylian** [comment]
Fixed in the support build (master) already.
