### ISSUE TITLE
Wrong attribute title for album link in breadcrumb.

### ISSUE THREAD

**Issue by bic-ed** [zenphoto/zenphoto#926]
The title of the album link, as made by getAlbumBreadcrumb() function, contains the entire album description. The reason is in line 1224 of template-functions.php : 
`return array('link' => $album->getLink(), 'text' => $title, 'title' => $album->getDesc());`

**Comment by bic-ed** [comment]
Hi @sbillard, so you are working on this new version of Zenphoto now? I've tried it on my local server and it seems a lot faster than ZP1.4.7, about 50% less processing time according to the "processing time" note printed at the end of the html generated page. Will ZP20 replace the current project in the next future?
About this issue, it would be nice to have an option for a custom link title, like the one present for the custom link text.

**Comment by fretzl** [comment]
@bic-ed This article will hopefully clarify a few things: http://www.zenphoto.org/news/response-to-zenphoto-team-change

**Comment by fretzl** [comment]
The title should probably be in plain text and limited to something like 50 characters.

**Comment by acrylian** [comment]
Actually I don't know why the description is used in that place so it should be switched to the title anyway.

**Comment by fretzl** [comment]
Ha, of course.

**Comment by bic-ed** [comment]
Oh, I'm really sorry, I was not aware of the team change and that ZP20 was a separate project. Thanks @fretzl to make me know, and forgive me for my ingenuous words. That said, I've experienced a consistent speed loss coming from ZP1.4.4, after the upgrade to 1.4.7. Probably a slimming down of the core code is actually needed at this point.

Back to the issue, yes, it is really very unusual to have the album description as title attribute for a link, even if shortened and cleaned up.

**Comment by bic-ed** [comment]
@acrylian, have a look at line 1234 too:
`@param string $title Text to be used as the URL title tag`
Now we have the same parameter $title both for title attribute and for the text of the link. This might create some ambiguity. For instance, an user could try to set a title like "go to the album page", and doing so he gets the same text for the link.

**Comment by acrylian** [comment]
I see what you mean. But does anyone really do that? The title attribute is not visible so of course a screenreader might use it or a search engine. No "normal visitor" hovers to see it and on mobile devices you even can't. Just a general thought so we don't overload any functions with rarely used parameters.

**Comment by bic-ed** [comment]
I totally agree with you. May be just a new, clearer, description for that parameter is needed, to avoid misunderstandings.

**Comment by acrylian** [comment]
I am open to suggestions ;-)

**Comment by fretzl** [comment]
How about changing the $title parameter to $text ? That way it's more obvious what is meant.
For me $title is much more associated with the title attribute.

**Comment by acrylian** [comment]
It is a "custom title" for both the link text and the title attribute since if not set it the album title is used for both …

**Comment by fretzl** [comment]
Ok, just leave it as it is.

**Comment by bic-ed** [comment]
Or might be
`@param string $title Text to be used as the URL title attribute and text link`
Anyway it doesn't matter that much anymore, now that we got rid of the description. ;-)

**Comment by fretzl** [comment]
Thanks. It's changed.
