### ISSUE TITLE
Again on paged_thumbs_nav, random fatal error from getPrevThumbsLink() in search context

### ISSUE THREAD

**Issue by bic-ed** [zenphoto/zenphoto#927]
I'm opening a new issue because the previous topic (#915), were we talked a lot about paged_thumbs_nav, was actually opened for another issue.

I was still getting some random fatal errors in search context. Then I looked again into the code, and I noticed a difference between getNextThumbsLink() and getPrevThumbsLink() functions. The latter was missing the search context conditional statement. To make it short, with the conditional statement added, getPrevThumbsLink() function became like this:

```php	
function getPrevThumbsLink() {
	global $_zp_current_album, $_zp_current_image, $_zp_current_search, $_zp_gallery;
	$this->prevpageimage = ""; // define needed for page list
	if ($this->totalpages > 1) {
		$prevpageimagenr = ($this->currentpage * $this->imagesperpage) - ($this->imagesperpage + 1);
		if ($this->currentpage > 1) {
			if (is_array($this->images[$prevpageimagenr])) {
				if (in_context(ZP_SEARCH_LINKED)) {
					$albumobj = newAlbum($this->images[$prevpageimagenr]['folder']);
				} else {
					$albumobj = $_zp_current_album;
				}
				$this->prevpageimage = newImage($albumobj, $this->images[$prevpageimagenr]['filename']);
			} else {
				$this->prevpageimage = newImage($albumobj, $this->images[$prevpageimagenr]);
			}
			return $this->prevpageimage->getLink();
		}
	}
}
```

and no more random errors occur.

**Comment by fretzl** [comment]
@bic-ed I just changed your comment a bit for better readability ;-)

**Comment by bic-ed** [comment]
Very nice @fretzl, I wasn't aware of the php tag. :-)
Thanks!

**Comment by acrylian** [comment]
Ah. thanks, indeed forgotten.

**Comment by bic-ed** [comment]
I'm afraid the code I posted is wrong, I've used two times $albumobj, instead it should be used only the first time.

**Comment by acrylian** [comment]
Gee, indeed and I just believed you without checking ;-) Probably need another coffee ;-)

**Comment by bic-ed** [comment]
Me too ;-)
