### ISSUE TITLE
downloadlist-userstats plugin throws error and breaks page when NOT logged in

### ISSUE THREAD

**Issue by fretzl** [zenphoto/zenphoto#928]
I have this call `<?php printDownloadAlbumZipURL('Download album', $_zp_current_album); ?>` within the *next_album()* loop. (zenpage theme - gallery.php)
When the `downloadlist-userstats` plugin is enabled and you are NOT logged in the page is broken and this error is in the server log:

Fatal error:  Call to a member function getUser() on a non-object in .../plugins/downloadlist-userstats.php on line 126
Stack trace:
1. {main}() .../index.php:0
2. include() .../index.php:28
3. include() .../zp-core/index.php:129
4. include() .../themes/zenpage/index.php:10
5. printDownloadAlbumZipURL() .../themes/zenpage/gallery.php:54
&nbsp;&nbsp;&nbsp;&nbsp;(*line 54 is the line where the printDownloadAlbumZipURL() call is placed*)
6. DownloadList::addListItem() .../zp-core/zp-extensions/downloadList.php:560
7. zp_apply_filter() .../zp-core/zp-extensions/downloadList.php:182
8. call_user_func_array:{.../zp-core/functions-filter.php:149}() .../zp-core/functions-filter.php:149
9. downloadListUserstats::addItem() .../zp-core/functions-filter.php:149

**Comment by acrylian** [comment]
The downloadlist-userstats plugin is neither officially included nor released at all since it is not final at all. I only sent it to you for testing once. I think this ticket is probably not about an valid ticket.
