### ISSUE TITLE
Problem with website - Zenphoto News

### ISSUE THREAD

**Issue by michgagnon** [zenphoto/zenphoto#931]
Hello,

As I was looking around for new elements, I just stumbled on a problem with the Zenphoto.org website.

If one clicks on the main menu items in top bar and select News, one is forwarded to http://zenphoto.org/news
The page displays 3 news items from February 2008.

If one looks in the right column, under Categories, "All News" also refers to this defective link, but "News (268)" refers to http://www.zenphoto.org/news/category/news/ which shows everything, including current items.

I think the solution likes in an update to .htaccess (or the script that is now used for that), so that http://zenphoto.org/news displays everything.

All other menus items seem OK. I would probably send the "Demo" in a new window because there is no easy way to come back to the main site, but that's just a personal preference.

**Comment by acrylian** [comment]
Thanks for noting. It should now work correct again, The reason for this was the static_html_cache plugin that somehow does weird things here. I had switched that on yesterday to try if it speeds up as we normally don't use it at all. I don't know right now why that causes this issue, might be our quite special theme.
