### ISSUE TITLE
getAllTagsCount called with checkaccess = true prints debug spew

### ISSUE THREAD

**Issue by amalani** [zenphoto/zenphoto#940]
I'm guessing pull request #939 didn't get looked at because there isn't a corresponding issue. Starting an issue for that.

The method returns an array and it is printing html content. I'm guessing that got added as debug spew at some point.

**Comment by acrylian** [comment]
No, just didn't get to it somehow because of other things. And yes, you are right.

**Comment by amalani** [comment]
Aah ok, I thought maybe an issue was required per pull request which is why this got missed. Sorry, just getting started with contributing code to public repos. Thanks!
