### ISSUE TITLE
1.4.8 Search options gets applied, but Apply-Button stays green...

### ISSUE THREAD

**Issue by tw2003** [zenphoto/zenphoto#941]
.. and if you leave the page the "leave page dialogue" asks if you want to leave, which normally indicates that your changes are not applied.
It's on my test environment with a WAMP-Installation. Could you please verify that it's a WAMP bug not a Zenphoto bug.

**Comment by fretzl** [comment]
Can't reproduce that on OS X MAMP nor on a live install.
Sure your browser cache is not playing tricks?
Happens to me all the time.

**Comment by acrylian** [comment]
I cannot reproduce this either.

**Comment by gjr-osweb** [comment]
This is most likely due to your browser autofilling the hidden password form?

**Comment by tw2003** [comment]
No, it appears to be a WAMP Problem on my machine. I just wanted to make sure that it's not a bug before I do a life update. You may close this. Thanks for checking.

**Comment by acrylian** [comment]
Ok, thanks for the update.
