### ISSUE TITLE
Search is not setting the correct order by title

### ISSUE THREAD

**Issue by tw2003** [zenphoto/zenphoto#942]
I have problems with search settings. I use 'Title' in the options page to set the sort order but the result is not in any visible order. I'm using 1.4.7 but it appears to be the same with 1.4.8 on my test system. If I change it to 'filename' it is more what I expect but the title is what really counts for me. And I tried it with some of the standard themes where the result is the same. Check on http://www.paledog.de , use one of the Tags and see that it does not order by the displayed title.

Content, Description, Tags and Title are enabled. I have pictures where only the title differs but the rest is the same. Shouldn't they be displayed side by side? 'Filename' in 'Sort Images by' is working better. I have the feeling that 'Title' is somehow getting ignored. 

The search result itself is ok (all tagged pictures will be found) but I supposed that the sorting of the result would be applied according to the settings in the Options - Search. See this forum discussion in addition: http://www.zenphoto.org/support/topic.php?id=1409074&replies=5#post-1975890

**Comment by acrylian** [comment]
Please give it a try!

**Comment by tw2003** [comment]
Sorry for replying that late, I have been busy the last days. I just did the update to 1.4.8 on my production site today. I adopted the changes in class-search.php but the issue still occurs unchanged.

**Comment by acrylian** [comment]
Since I could reproduce what you reported and it was fixed for me after the changes I don't know. As always we don't recommend just applying the changes, although it should work here probably ;-)

But be sure you cleared or disabled the search cache to be sure to get fresh results.

**Comment by tw2003** [comment]
5 years later and I found that it reappeared :-o.
But I can't find how that got fixed.
I'm running version1.5.7 now with the same results described in my initial post.
Strange.

**Comment by acrylian** [comment]
I don't remember that anything changed in handling here for years. As it is a usual issue: Do you have the search cache enabled respectively cleared it?

**Comment by tw2003** [comment]
Cleared the  cache right now. Result is the same. Appearently my site seems to be a bit slow at the moment (provider related).
But you may want to check the behaviour on my site.
For updating I always follow the instructions (delete the files and folders rather than overwriting them via ftp).
I'm curious why this reappeard and i recognized exactly 5 years after my first post. Spooky.

**Comment by acrylian** [comment]
My colleague already mentions he can reproduce it. I have not time right now but I will try to later. I really have no idea where this comes from again. Perhaps an unwanted side effect of anything else…

**Comment by acrylian** [comment]
Although @fretzl said he could reproduce it I sadly was not able so far. Both title descending/ascending seem to work as intended for me…

**Comment by acrylian** [comment]
Meanwhile @fretzl had sent me some guide how to reproduce. So hopefully I can and then we'll perhaps have a clue.

**Comment by acrylian** [comment]
So now it should really be fixes. Actually typos were the issue…
