### ISSUE TITLE
seo_locale and dynamic-locale is weird if the site is already a subdomain

### ISSUE THREAD

**Issue by BimbaLaszlo** [zenphoto/zenphoto#944]
### Works (almost) fine

For example if the site is the http://www.localhost.com/gallery and _dynamic-locale_ and _seo_locale_ plugins and the multilingual option are enabled, then flags for language selection are visible on the bottom of the site. The `href` attribute of the English flag for example is http://www.localhost.com/gallery/de/, but the alternate link is `<link rel="alternate" hreflang="en" href="http://www.localhost.com/gallery/en">` **without slash on the end**. Clicking on the flag (http://www.localhost.com/gallery/en/) works fine, the site appears on the selected language. But if I trying to open http://www.localhost.com/gallery/en, the browser drops `ERR_TOO_MANY_REDIRECTS` - I think it **makes Google crazy when tries to make a map of language alternates of the site**.

### Not works

If the site is http://gallery.localhost.com/ with the same settings, then the `href` of all flags is http://gallery.localhost.com/, so the user cannot switch the language, but the alternate link is `<link rel="alternate" hreflang="en" href="http://gallery.localhost.com/en">`. The link of the albums contains the language codes, for example: http://gallery.localhost.com/en/album/ and those works.

### System Information

**Zenphoto version**
1.4.8 [3e3fac42b5]

**Theme used**
gjr-osweb/zpbase@aaced5b0ec

**Plugins used**
deprecated-functions
dynamic-locale
html_meta_tags
legacySpam
rewriteTokens
rss
security-logger
seo_locale
site_upgrade
tinymce4
tinyURL
uploader_http
uploader_jQuery
userAddressFields
zpCaptcha

**Server configuration**
May i copy the PHP info?

**Browser and which version/system**
Microsoft Windows 7 Professional
Mozilla Firefox 39.0
Google Chrome 43.0.2357.132 m

**Comment by acrylian** [comment]
Actually we generally recommend using a subdomain to differ between different language site:  http://www.zenphoto.org/news/multi-lingual-sites#seosearch-engines
I am not sure if it would work with another subdomain like `en.gallery.yoursite.com` added.

The language in the url is indeed a redirection as it is not possible otherwise. Zenphoto itself does not require any language in the url to switch languages (that is done via cookies), that all was just added afterwards for SEO purpose. Originally no one thought of that when this was implemented some years ago.

**Comment by BimbaLaszlo** [comment]
Thanks for the quick reply.

I can use the http://www.localhost.com/gallery/en/ format since it works fine, but differing of the flags and the `<link rel="alternate" ...` should be fixed. I searched the code for it but can't find the right line to make the fix by myself. Can you look after it, please?

**Comment by acrylian** [comment]
Sure, we will do of course.

**Comment by fretzl** [comment]
Looks like something is not correct. On the zenpage theme, the URL's of the flags now have double slashes at the end ???

**Comment by BimbaLaszlo** [comment]
The fix of @sbillard is working fine. Thanks! (i just switched to Zenphoto20)

**Comment by acrylian** [comment]
Goodbye then.
