### ISSUE TITLE
Plugins don't check if cacheManager class is loaded

### ISSUE THREAD

**Issue by sphoto** [zenphoto/zenphoto#945]
In several plugins (bxslider_thumb_nav, galleryArticles ...) there is no check if cacheManager class is loaded. This leads to errors like this, when the cacheManager is not in use:

<pre>Fatal error: Class 'cacheManager' not found in /homepages/89/a81264008/htdocs/zp-core/zp-extensions/bxslider_thumb_nav.php on line 37</pre>

**Comment by acrylian** [comment]
Indeed, must be that way for ages … Good find. Thanks!
