### ISSUE TITLE
Segmentation fault (11)

### ISSUE THREAD

**Issue by DasPflanze** [zenphoto/zenphoto#946]
I installed Zenphoto (1.4.8 [3e3fac42b5) some weeks ago and uploaded some Pictures (~2000) and everything went fine. But in the last days I often can't access the backend (Chrome: Err_Emtpy_Response) and I found some of these lines in my Appache2 error.log:

[Sat Jul 11 16:15:51.304719 2015] [core:notice] [pid 25361] AH00052: child pid 28359 exit signal Segmentation fault (11)

That's my first reported issue, so if you need more information, just ask!

**Comment by acrylian** [comment]
Never seen that before. I think this is because of a server configuration issue as of a quick Google search: http://www.webhostingtalk.com/showthread.php?t=950165
Best you contact your webhost about that.

**Comment by DasPflanze** [comment]
I already contacted my webhost and he said I should open an Issue...
I had the same problem in two other zenphoto installations on the server...at first I disabled imagick and it helped...but now it was never enabled in this installation and I get those errors...

**Comment by acrylian** [comment]
All I found googling for this error indicates this being related to server configuration. Being no server admin I fear I cannot help. 

I primarily use Zp on various standard shared hosts and as mentioned never encountered this. A possibility is that you just overload your server with too big images: http://www.zenphoto.org/news/problems-with-albums-and-images. 
Although that would result in different errors.

**Comment by DasPflanze** [comment]
ok, both links I also found googling...I also upgraded my RAM from 1 to 2 GB...

**Comment by acrylian** [comment]
If you have that much memory you must have your own server or a very good host ;-) Zenphoto generally runs fine but as alway with RAM the more the better.

**Comment by DasPflanze** [comment]
yeah, vServer from http://qloc.de/ ^^
