### ISSUE TITLE
Album description stripping out HTML

### ISSUE THREAD

**Issue by JatB** [zenphoto/zenphoto#949]
This used to work. I copied the exact text from a previous install into the album description on a new install of 1.4.9 and it breaks the HTML every time.

So this:
![zp 1 4 9 album description - before](https://cloud.githubusercontent.com/assets/10157440/8762573/f08c21bc-2d31-11e5-9cb0-0d3b32997150.png)

becomes this:
![zp 1 4 9 album description - after](https://cloud.githubusercontent.com/assets/10157440/8762574/f8378f6e-2d31-11e5-9661-1f644f2cb5d4.png)

**Comment by acrylian** [comment]
Check Options > General > Allowed tags that the `href` attribute for `<a>` is allowed.

**Comment by JatB** [comment]
Yup, it's the first entry there under allowed tags. I tried hitting the "reset to default" button and it would still not work.

**Comment by acrylian** [comment]
I just looked a bit closer and it appears your `mailto` usage is invalid, that's why it is cleared. It is `mailto:firstlast@test.com` plus option queries:
https://developer.mozilla.org/de/docs/Web/Guide/HTML/Email_links

**Comment by JatB** [comment]
I actually looked it up because I’ve been using this for years with no problems (including in ZenPhoto). The mailto URL scheme (https://www.ietf.org/rfc/rfc2368.txt) references RFC# 822 on the matter, which says it is fine to use (https://www.ietf.org/rfc/rfc0822.txt).

Now it all depends on browser and email client support, but again, I’ve never run into any problems with it.

On top of that, I’ve found out how to get it to work with the recent tag cleaning added to ZenPhoto, so I’m posting this for anyone that might come across this particular issue. You just need to make sure the < > are converted so it validates.

    <a href="mailto:First%20Last&lt;firstlast@example.com&gt;">First Last</a>

There are other examples out there, but I got the working example for ZenPhoto from here (the # 2 sample)- http://4umi.com/web/html/mailto.php

**Comment by acrylian** [comment]
Ah, ok, I generally use the mailto link just with the address or query appended. Apparently the Mozilla doc was not complete. But makes sense that those need to be escaped since `<>` always break html otherrwise. On the front end you could just use `html_encode()`. On the backend you could enable the TinyMCE 4 texteditor that also does some escaping of its own.

**Comment by JatB** [comment]
Thanks for the fast response, and as always, all your hard work.
