### ISSUE TITLE
Tag search with space followed by bracket not working as expected

### ISSUE THREAD

**Issue by tw2003** [zenphoto/zenphoto#950]
Maybe it's something special again. On my website i use tags like "Ford (D)" and "Ford (USA)" to tag pictures for regional car makes. However when clicking the tag the search returned says "Search for Ford(D)..." deleting the space between it and giving me all pictures that start with Ford. I tried several settings in the search options but none give me the right result. On the other hand tags like "Natur Nature" (I did that for dual language support ;-) in tags) will be treated correctly with the space while having no brackets in the search term. I would expect the search result to resemble the exact tag. Website www.paledog.de

**Comment by acrylian** [comment]
I just tried to reproduce and with this settings clicking on such a tags works fine:
- String matching: Partial
- Tag matching: exact
- Treat space as: AND

It also works entered in the search form if enclosed in quotes.

**Comment by tw2003** [comment]
String matching: Partial
    Tag matching: partial
    Treat space as: AND
comes closest. It works for the search but not from the tag cloud with "Ford (D)". Maybe it's theme related as it works from the search menu where i activated the tag_suggest plugin. I guess changing the tag to "Ford (DE)" could help :-)

**Comment by acrylian** [comment]
Just tried the basic theme and the cloud on the archive page and it did work for me. Please try a standard theme to check if it is theme related maybe, too.

**Comment by tw2003** [comment]
It's a theme error. The tag cloud link looks different than in the basic theme.
The result is: ...page/search/tags/"Ford+(D)" from basic theme while the theme produces: ...page/search/tags/Ford+(D). I'm going to check the theme code and will try to fix it there. Thanks again for your help.
