### ISSUE TITLE
zenphoto breaks redis session handling (with a socket as session.save_path)

### ISSUE THREAD

**Issue by HungryFeline** [zenphoto/zenphoto#951]
I use Redis (see http://redis.io/) in combination with phpredis (see https://github.com/phpredis/phpredis) for sessions. Because of this the session.save_path is a UNIX socket.

Relevant php.ini configuration
```
session.save_handler = redis
session.save_path = "unix:///var/run/redis/default.sock?timeout=10&database=0"
```

The error messages that appeared by visiting the ACP
```
[23-Jul-2015 15:35:04 Europe/Berlin] PHP Warning:  file_exists(): Unable to find the wrapper "unix" - did you forget to enable it when you configured PHP? in /srv/www/[...]/htdocs/zenphoto/zp-core/functions-basic.php on line 149
[23-Jul-2015 15:35:04 Europe/Berlin] PHP Fatal error:  Uncaught exception 'RedisException' with message 'Connection closed' in [no active file]:0
Stack trace:
#0 {main}
  thrown in [no active file] on line 0
```

The first error is pretty self-explanatory, the second one is probably caused by line 151 when the session_save_path() function is called.

Zenphoto 1.4.9
PHP 5.6.9
phpredis 2.2.7
Redis 2.6.14

**Comment by acrylian** [comment]
Did you try to enable the wrapper using `stream_wrapper_register()` as http://php.net/manual/en/wrappers.php suggests so `file_exists()` possibly works? 

Otherwise I guess I have to suggest to hack the file to skip the `if` check for now to see if that works.

**Comment by HungryFeline** [comment]
No, I didn't. I temporarily fixed the problem by commenting out the whole if-block. `stream_wrapper_register()` would just be an alternative local workaround, I guess.

I reported this problem because Redis seems quite popular to me, hoping you could add an exception for a case like this into the code. If not, editing the zenphoto.cfg.php seems to be a good idea to implement a more permanent local workaround.

However you decide, thanks a lot for zenphoto!

**Comment by acrylian** [comment]
Ok, thanks for the report in any case. I admit I had never heard of Redis before. But I am not a server admin and I don't configure my own server. I let hosts do that for me ;-)

We will probably indeed go the way of adding to the config file so you can set your own session path manually if needed. This is an rather advanced requirement so that is probably best.

**Comment by HungryFeline** [comment]
Could you add a checkbox in the installer and acp to enable/disable the check mentioning something about non-standard session handlers? This'd be a good compromise imho.

**Comment by acrylian** [comment]
We will probably just add a line like  `$conf['session_path'] = "";` to the config file you have to edit manually if you need a special path (just like with external album folder etc). If you can configure your server to require that, editing a config file is probably no real problem either ;-) Most "normal users" will probably never need this.

**Comment by HungryFeline** [comment]
Well, the path already is set correctly in the php.ini file. The problem is the code checking the path so a `$conf['check_session_path'] = true` (which is written into the config when installing and has to be changed there manually in cases like mine) would make more sense.

After that you'd just need to add something like `if(!array_key_exists('check_session_path', $conf) || $conf['check_session_path'] !== false){` before zp-core/functions-basic.php#L148 (and a `}` after L153). The code I provided should be the most compatible one: the setting has to be set to false and only to false to skip the check. Anything else does nothing.

Sorry for discussing this further. I just couldn't imagine setting a path would fix this. Hopefully this code compensates my poor explanation.

**Comment by acrylian** [comment]
No problem discussing this ;-) My thought was much more pragmatic actually that you set the path in the config file. `$conf['check_session_path'] = "unix:///var/run/redis/default.sock?timeout=10&database=0"`

Then if that var is set skip the file_exists() check entirely and just use it, assuming whoever set it manually knows what he did. But I see that this is doubled since it is already set via php.ini …

Another way could be to check for available wrappers and skip the check if the path does not use one of those. That of course only if the "stream" extension is availble at all.

But wouldn't just registering the wrapper needed be the most clean way actually?

**Comment by acrylian** [comment]
Sorry, we have decided not to make any exception or override here. If you need to use a path with a specific wrapper make sure you have it enabled on your server. Unless anyone can provide a good reason beyond "convenience" and "I would like to have that" ;-)

**Comment by himbeere** [comment]
Hello everyone.

I'm not sure right now how to deal with that issue. How can i run zenphoto with redis session handling? Whats the suggested solution by the devs?

thanks and cheers
t.

**Comment by acrylian** [comment]
You need to register the file wrapper on the server you want to use (see the link above). Zenphoto checks for the path using `file_exists()` and if it fails it uses a fallback location for saving. But if `unix:` - as above - is not registered as a file wrapper that check fails in any case. So the fallback will not work with your session handling.

**Comment by HungryFeline** [comment]
@himbeere As far as I understood the devs, their suggested solution was to register the wrapper (first comment from @acrylian) or use the workaround you like the most.

I made it work by commenting out line 148 through 153 in `zp-core/functions-basic.php`. This keeps zenphoto from verifying the session_save_path. You need to comment it out after every update so if registering the wrapper in a config file that stays after an update works, you should use that.

**Comment by himbeere** [comment]
Hi alll.

Thanks for your answers. I'm not quite sure i'm following. Where should i put stream_wrapper_register ()? Is there a more complete example?

thanks and cheers
t.

**Comment by acrylian** [comment]
There is no complete example as this is a so called "edge case" we never had before. I will take a look.

**Comment by acrylian** [comment]
We reviewed a bit and change our mind so we will skip the session path check entirely to "trust" the server configuration. The change is in the support build (master) here on GitHub.

**Comment by HungryFeline** [comment]
Glad to heat that, thank you.

**Comment by himbeere** [comment]
Cool!
