### ISSUE TITLE
Creation of user album removes others personal albums from managed albums

### ISSUE THREAD

**Issue by mricric** [zenphoto/zenphoto#952]
I create a two users : UA and UB.
From admin panel I create a new personal album for UA. It appears in the list of UA's managed albums.
Then I create a new personal album for UB. It appears in the list of UB's managed albums, but the personal album of UA has been removed from UA's managed albums.
Both UA and UB still have link to their personal albums. Both album still exist.
But only UB can manage its own.
UA has lost access to his album.

I use Zenphoto 1.4.9 [36167d6556]
PHP : 5.4.7
I do not know if that is regression since I did not use prior to 1.4.9.

Here are some more details :
list of user extensions :
email-newuser    (i also tested with this one disabled, same result)
quota_manager     (i also tested with this one disabled, same result)
register_user 
userAddressFields     (i also tested with this one disabled, same result)
user_groups
user_login-out 

UA and UB are members of group : "photographers"
This group only has 1 right : UPLOAD_RIGHTS

By the way $_zp_loggedin = 1081345
== ALBUM_RIGHTS | MANAGED_OBJECT_RIGHTS_EDIT | NO_RIGHTS | UPLOAD_RIGHTS

On that group I also has granted access to a private album protected by password. There is no issue with that album, it is not removed from list of managed albums when a personal album is created.

**Comment by acrylian** [comment]
Actually the "personal album" is just a convenience feature to assign a managed album to a user on its initial creation. If you assign albums manually to a user it is not really needed and you can always re-assign albums to a user manually afterwards.

**Comment by acrylian** [comment]
Technically this is not a bug but as intended. The user group setting sets everything for each user which includes the managed albums. The primary album is not part of that group setting so it is removed. That it still shows up as linked is because the primary album assignment is saved in another place.

There is now a fix that should overrides the group setting so primary albums should be kept always.
