### ISSUE TITLE
Seach button does not work in zpmobile theme (computer)

### ISSUE THREAD

**Issue by pled** [zenphoto/zenphoto#953]
On a computer, using zpmobile theme, and opening the search page :
- enter a keyword
- click on "Search in the gallery" => nothing happens => bug.
(reproduced on Linux and windows, using MSIE, Firefox or Chrome)

1) Search is performed if you type "Enter" key after entering search keyword => workaround.
2) it works on mobile devices (tap).

**Comment by acrylian** [comment]
I can reproduce that. The constant annoying behaviour of jquerymobile taking over all elements on a page …
