### ISSUE TITLE
ImageMagick creating negative images when dealing with CMYK

### ISSUE THREAD

**Issue by JatB** [zenphoto/zenphoto#954]
ImageMagick is creating negative images when dealing with JPEGs in CMYK. The thumbnails and preview images are being converted from CMYK to JPEG in ZenPhoto (which makes sense). The problem is that the resulting images are negatives.

Using ImageMagick (the image on the left is natively RGB, the one on the right is CMYK)
![zenphoto imagemagick cmyk to rgb negative error](https://cloud.githubusercontent.com/assets/10157440/9001253/e604dc16-3709-11e5-966f-338007ad7f8a.png)

Using GD
![zenphoto gd cmyk to rgb](https://cloud.githubusercontent.com/assets/10157440/9001256/edcc650e-3709-11e5-9b70-883ab78a4fce.png)

Doing a quick search this appears to be a known issue with ImageMagick and certain versions of PHP. The User Contributed Notes here have solutions for the issue: https://secure.php.net/manual/en/imagick.setimagecolorspace.php

My version info if you need it:
Zenphoto version 1.4.9 [36167d6556] (Official build)
PHP version: 5.6.10
Graphics support: PHP Imagick library 3.1.2
ImageMagick 6.8.9-7 Q16 x86_64 2015-07-06 http://www.imagemagick.org
supporting: bmp, bmp2, bmp3, gif, gif87, jpeg, jpg, png, png24, png32, png8, tiff, tiff64
PHP memory limit: 512M (Note: Your server might allocate less!)
MySQL version: 5.5.42

**Comment by fretzl** [comment]
I can reproduce that. We will have to look into it.

**Comment by acrylian** [comment]
> from CMYK to JPEG

You of course meant CMYK to RGB since JPG supports both color modes ;-) Regardless of the issue we will investigate it may make sense to upload RGB in the first place anyway (smaller files, less color conversion issues).

**Comment by JatB** [comment]
Yeah, missed a word there. Meant to say "RGB JPEG". The gallery contains older images used mostly for print, so many are in CMYK. We are trying to keep them all in RGB going forward.

**Comment by acrylian** [comment]
As said just a general thought, we will take a look asap.

**Comment by fretzl** [comment]
We're sorry but we tried all possible solutions we could find (thanks for yours btw) but the best result was this:
![cmyk-to-rgb](https://cloud.githubusercontent.com/assets/2480231/9023522/7dd784da-389f-11e5-8d31-d1854621a2d6.png)
We hope you understand that a result like this is simply unacceptable.
Unless someone steps up with enough knowledge about Imagick, ImageMagick and its color conversions there's nothing much we can do.
