### ISSUE TITLE
Update jQuery

### ISSUE THREAD

**Issue by thany** [zenphoto/zenphoto#955]
Currently, zenphoto by default spews out an include for jQuery 1.11.0. It's outdated, and adds unnneccesary weight for modern browsers (which for most implementations is nearly all browsers).

Suggested include goes like this:

```
<!--[if lt IE 9]>
<script src=/zp-core/js/jquery-legacy.js></script>
<![endif]-->
<script src=/zp-core/js/jquery.js></script>
<!--<![endif]-->
```

(yes, the `type` attribute is completely unneccesary, and so are the attribute quotes)

This will load jquery-legacy for fossilized browsers, and a leaner version for all others. The legacy one would be 1.11.3, while the normal jquery would be at 2.1.4. Or whatever the latest versions are at the time this gets implemented.

**Comment by acrylian** [comment]
We have some jQuery plugin dependencies that would  need to be checked first. We will think of this on the next big version we plan behind the scenes (no, that is not public on purpose). So not for the 1.4.x branch anymore.

**Comment by thany** [comment]
Or just ditch jQuery completely now that we have modern browsers. You generally don't actaully need jQuery for most things. The browser can do it on its own these days, and as for the rest, I already use Bliss in most of my projects whenever I can. And avoid third-party plugins.

**Comment by acrylian** [comment]
Nope, you and me may have modern browser but not everyone else.

**Comment by thany** [comment]
As for the admin side of zenphoto: screw old browsers. You can't keep supported old crap forever. Just as a game or application has system requirements, so can zenphoto. Require the latest of the big five, and done. You can sleep easy, code more happily, and provider a leaner codebase.

As for the frontend side: that's up to the theme. Since themes are basically php files, they can do whatever, including supporting IE4 and Netscape 3 if they so wish. I wouldn't, but it's not up to you. It's up to whoever makes a theme.

**Comment by acrylian** [comment]
The next major release will use the latest jquery so we will not "support old crap browsers forever".

**Comment by acrylian** [comment]
The next major release will use the latest jquery so we will not "support old crap browsers forever". IE4 and Netscape 3  is really old and surely will not work anyway already.

**Comment by thany** [comment]
I was exaggerating of course ;)

**Comment by acrylian** [comment]
I know ;-)
