### ISSUE TITLE
Remove zenphoto.js when not logged in

### ISSUE THREAD

**Issue by thany** [zenphoto/zenphoto#957]
zenphoto.js is not needed when not logged in. It contains some ugly and global functions that look like they belong to the admin panel. It also saves one more HTTP request. The two generic ones `toggle` and `reveal` are so ugly and error-prone that they shouldn't be used by themes in the first place, so I vote for removing this.

**Comment by acrylian** [comment]
Those are quite old things we didn't get around to update. Sometimes back and front end functionality are used mixed so that needs to be check.

(In case you notice that next: we also have a lot bad inline js and styles that work but surely should be removed some time … although since they work that is not direct priority).

**Comment by thany** [comment]
If you dynamically build inline javascript, especially html event handler (like `<a onclick=...>` and such), the code become prone to XSS attacks one way or another. Separating functionality from presentation using a friendly small library like [Bliss](http://blissfuljs.com/), will help prevent creating such issues in the first place.

Also, sorry for the late reply. I noticed this just now :)

**Comment by acrylian** [comment]
We don't exactly build inline events dynamically, those are hardcoded and mostly tied to js functions. Anyway, things that basically work have low priority and are changed on occasion only.

**Comment by thany** [comment]
Closed means it's fixed?

**Comment by acrylian** [comment]
Yes, don't know why the commit reference comment doesn't appear here ;-)
