### ISSUE TITLE
1.4.9 - Slideshow using wrong style by default now, color choice should be plugin option

### ISSUE THREAD

**Issue by JatB** [zenphoto/zenphoto#959]
Slideshow now has light and dark options for buttons and text, but changed the default to a dark theme, meaning buttons are hard to see on any light themes besides Basic.

Slideshow used to have only one option, dark buttons, when used in the jQuery Cycle mode. It now has two, light or dark, which is great. The problem is that it does not offer the user a choice to pick which one they want to use. The other problem is that it also changed the default from dark buttons to light. Slideshow.php now checks for which to use, but it only checks against the Basic theme color options. So if you are using a different theme that has a light background color, the slideshow is now almost impossible to use. If you also upgrade, as we did, it now appears to be broken for no reason.

Slideshow2 fixes the problem with the button colors by using the link color, but it is still pulling the wrong style class for other themes, so the h4 text color is off. 

Previous slideshow (buttons and text worked fine)-
![slideshow - previous - worked fine](https://cloud.githubusercontent.com/assets/10157440/9150050/9c8c369c-3d7b-11e5-8dbb-d0d91e50da67.png)

Current slideshow (buttons and text hard to read on light themes)-
![slideshow - new - hard to read text](https://cloud.githubusercontent.com/assets/10157440/9150055/ba6e2896-3d7b-11e5-82d1-af2c442f11ab.png)

Slideshow2 (buttons okay, but text hard to read)-
![slideshow2 - text still hard to read](https://cloud.githubusercontent.com/assets/10157440/9150057/e47b37a0-3d7b-11e5-9896-4eac89e9af4c.png)

The solution for both seems to be to move the check from slideshow.php to instead be an option under the plugin.

(It would also be nice if the text styling came back (bold for the gallery title, normal for the image title), as well as the image count (3/11), and even the slide duration option. That was a nice touch.)

Thanks as always for your time working on this cool program.

**Comment by acrylian** [comment]
Curious from where you upgrade since there hasn't been changed anything recently to my memory. Slideshow in my memory always had two button types. 

But you can easily override its styles yourself either place a `slideshow.css` within your theme's folder or place a folder `slideshow` within your root `plugins` folder. Slideshow is sort of decprecate as slideshow2 is the repacement already.

Slideshow2 is entirely CSS so you can override that via the theme css.
