### ISSUE TITLE
Function 'sortByMultilingual' does not work properly

### ISSUE THREAD

**Issue by sphoto** [zenphoto/zenphoto#960]
I had an issue with the order of a search in the archive. While the order was correct in the thumbnail view of my theme (search.php), the order of the images mixed up later in the image view (image.php). The images were not shown in the right order (index) 1,2,3... but in 1,7,12,4,...

After some hours of investigations and reverse engineering I found the reason in <code>sortByMultilingual</code> within <code>functions.php</code>. The order of the image array was changed there, but not the array keys!

The line:
<code>$result[$key] = $dbresult[$key];</code>
hast to be changed into:
<code>$result[] = $dbresult[$key];</code>

I also found that the variable <code>$descending</code> (as input for sortByMultilingual) sometimes contains the whole image array, but it should be a bool.

Regards

**Comment by acrylian** [comment]
That looks like a good find! Thanks for working on that.

Regarding the `$descending` var I will try to find why that would be an array, althought that would "work" as a bool true, too.
