### ISSUE TITLE
Gallery 3 dynamic module problem

### ISSUE THREAD

**Issue by ivo2hristov** [zenphoto/zenphoto#962]
Hi everybody! I`ve problem with my dynamic module in Gallery 3 site. It`s worked nice but then i decided to make some changes in the names of Dynamic Albums and i`d make big mistake. I`d make the changes in the code from Advanced Settings(Admin-Settings-Advanced) and after that my dynamic module stop working. Several times i installed and re-installed the module but still not working. The panel "Dynamic Albums" is visible but links under below  called "Recently Changed" and "Most Viewed" are not visible yet! I just dont know what to do to fix it!  Help!

**Comment by fretzl** [comment]
I hope you realize that this is not the Gallery 3 repository or forum ?
