### ISSUE TITLE
search returns html tag content

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#965]
hi
on news and pages (and probably on albums and picture but I haven't tested yet), if content is formated with some html tag and attributes (div, class,...), you can make a search on these values, and search engine returns items.

as example, if you insert a picture, tiny_MCE plugin may add class="zenpage_imagelink".
if you make a search on imagelink, search engine returns all news and pages which have this class value in html code.
same thing with div tag.

**Comment by acrylian** [comment]
I am not sure I understand. Search loops do work like any other loop. It is actually up to the theme how it displays these results. The Zenpage theme for example uses `shortenContent(getBare(getPageContent())`for pages results that should not contain any html elements.

What theme are you referring to?

**Comment by vincent3569** [comment]
hi malte,

I am not refering to the display of results, but to the results themselves.
You can have a test on my website http://www.vincentbourganel.fr/.
Try to make a search with  "zenpage_imagelink" keyword.
You will have a news as result (because I cleaned the content code). This keyword is not displayed because this is a class on a <a> html tag in news content.

**Comment by acrylian** [comment]
Ah, now I understand what you mean. The search engine just searches the text of the main content fields and any code there is also just text. This has benefits probably since you could technically search for an embedded  image within the content that way (its filename or its alt attribute for example). Would have to look at the code if it is possible at all to avoid that.

**Comment by vincent3569** [comment]
search on "title", "name" or "alt" attributes (maybe some others) is, of course, a good idea.
search on HTML tags and attributes other than those above, I do not think it is very relevant...

**Comment by acrylian** [comment]
Well, this is a database search that cannot make any difference as text is text. It dodes not understand if this is an attribute value or a element name. That would have to be parsed and filtered to find that out before you can actually look if this might be a match. Sounds like a lot of overhead to me. Sorry but I don't think I will work on this.

**Comment by sbillard** [comment]
The search engine has a property named "pattern" which can be setup to do preg matches in the search. To do what you wish you would need to create a preg pattern that excluded html and set the property to it.

See the searchengine constructor for examples used by "partial word" and "word"

**Comment by acrylian** [comment]
Hadn't looked at the code yet but good to know.
