### ISSUE TITLE
Extension tweet_news not properly setup

### ISSUE THREAD

**Issue by fretzl** [zenphoto/zenphoto#966]
Running setup I get a red x icon for the *tweet_news* extension.
Enabling the extension gives a blank page.

The server log shows this error:
```Fatal error:  Cannot redeclare class OAuthException in .../zp-core/zp-extensions/common/oAuth/OAuth.php on line 8```

**Comment by fretzl** [comment]
So I Googled a bit and found that similar issues were reported for WordPress, Drupal, etc.
If I use this solution: https://wordpress.org/support/topic/fatal-error-cannot-redeclare-class-oauthexception (see bottom of the page) and change .../zp-extensions/common/oAuth/oAuth.php accordingly, the issue is gone.

**Comment by acrylian** [comment]
That makes sense. Though this is a third party library we generally don't touch. Interesting would be why and where it might be redeclared. Does the error really not say anything about that?

**Comment by fretzl** [comment]
No other and/or descriptive errors.

I think it's some bundled PHP extension that is enabled on MAMP by default.

**Comment by acrylian** [comment]
Then I should get that as well, shouldn't I?

**Comment by fretzl** [comment]
For me the extension is enabled in PHP 5.5.26 and 5.6.10
MAMP 3.4
