### ISSUE TITLE
Sort order of an image search in archive

### ISSUE THREAD

**Issue by sphoto** [zenphoto/zenphoto#971]
Image titles (and other fields) are stored serialized in the database. When searching in the archive for a certain date range (e.g. "2015-10"), the results are sorted by image title (ORDER BY `title`).
But since the array size, its type and length are also part of the title now, the sort order is wrong.

<code>a:1:{s:5:"en_US";s:4:"Test";}</code>
<code>a:1:{s:5:"en_US";s:7:"Picture";}</code>

In the example above, the title 'Test' comes before 'Picture', because of their different string lengths.

For date range searches I would prefer a sort order by date/time not by title. Photos taken or upload on Oct, 1st should be shown before pictures taken before Oct, 2nd and so on.

Regards

**Comment by acrylian** [comment]
Hm, that sounds familiar from a similar issue we once had. Actually titles should not be sorted by db query itself therefore.

**Comment by fretzl** [comment]
Try setting Options -> Search -> *Sort images by* to **date**

**Comment by sphoto** [comment]
Thanks, in the meantime I also found this option.

Nevertheless sorting by title does not work properly.

**Comment by fretzl** [comment]
I can confirm this. 
When titles are not serialized, the sort order is correct.
