### ISSUE TITLE
Use personnal thumbnail cropping in admin

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#972]
hi
in admin>albums>images, it is possible to set personnal thumbnail cropping --> very well :-)
but the thumbnails in admin>albums>images does not show this personnal cropping.
so we have to see this personnal cropping. 
could it be possible to use personnal cropping for the admin thumbnails ?

**Comment by acrylian** [comment]
Probably but I personally don't think the backend should follow settings that are meant for the frontend.

**Comment by vincent3569** [comment]
of course you're right.
by example, my albums thumbnails are not squared as picture ones are, so it can't be the same in FE and BE.
but, if I decide to change cropping (the crop is centered in the middle of the picture, and the most important things are maybe in right or left side of the picture), I'll prefer so see the the cropping result in FE (of course :-) and BE too.

**Comment by fretzl** [comment]
I agree with acrylian that the backend thumbs should be no more than an indication of what can be seen on the frontend.

**Comment by vincent3569** [comment]
Consider this: you do a custom cropping in admin.
When you validate your action you are back to admin of picture.
Then, you can't see your action.
The first time I did that, I thought that I have cancelled my action.
It's very disapointing.

**Comment by acrylian** [comment]
Well, you have to validate what you did on the frontend. That applies to anything you set on the backend.

**Comment by vincent3569** [comment]
Bad news
I think it is just a basic item
We do not understand...
