### ISSUE TITLE
1.4.10 album.php design error in Basic theme

### ISSUE THREAD

**Issue by pintsel** [zenphoto/zenphoto#973]
Hello,

Latest Zenphoto 1.4.10 album.php seems have some coding problem in "credit" div at the bottom. The pipe character (|) is missing after the "Archive View" link!
Using the correct credit div contents from image.php seems to work..

**Comment by fretzl** [comment]
That has already been fixed in the <a href="https://github.com/zenphoto/zenphoto/archive/master.zip">Support build</a>
