### ISSUE TITLE
dynamic-locale displays flags although option deselected

### ISSUE THREAD

**Issue by reine-k** [zenphoto/zenphoto#975]
Well, it's all in the title...
I did *not* check/select the radio button "Use flags" in the plugin's options, but flags are displayed (actually I also would prefer simple text to a selector (if that's a drop-down menu) but that's another story ^_^)
The appearance does not seem to change whether the option is selected or not. Or should that be supported by the theme? (but zenpage claims to support dynamic-locale...)

Here my configuration, from the html source of the home page:
zenphoto version 1.4.10 [3d5be820ca827b321606d1d77df1e4286c8c170b] THEME: zenpage (index.php) GRAPHICS LIB: PHP GD library 2.1.1-dev { memory: 128M } PLUGINS: dynamic-locale html_meta_tags rss security-logger seo_locale site_upgrade sitemap-extended tinyURL zenpage zpCaptcha

**Comment by acrylian** [comment]
We will take a look.
