### ISSUE TITLE
watermark fails to apply with imagick php extension

### ISSUE THREAD

**Issue by bts368** [zenphoto/zenphoto#976]
I've tested this fairly extensively- cleared both ZP's cache (and refreshing the DB) as well as my local (browser) cache, deleting the image and album and then adding as new, adding a new theme, switching to it, and then trying, but in all cases it seems that when gd is used, the watermark is successfully applied. However, if imagick is used, the watermark is never applied. No output is sent to debug.log.

occurs on Arch Linux:
[root@dandylion ~]# php --version
PHP 5.6.15 (cli) (built: Nov 10 2015 20:22:58) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
[root@dandylion ~]# pacman -Qe|grep magick
imagemagick 6.9.2.4-1
php-imagick 3.1.2-4
[root@dandylion ~]# pacman -Qe nginx-devel
nginx-devel 1.9.5-2

ZP version 1.4.10 [3d5be820ca]

**Comment by fretzl** [comment]
I can confirm this. No errors in any logs.

**Comment by fretzl** [comment]
`lib-Imagick.php` (function *zp_copyCanvas()* line 288)

When I remove `$imgCanvas = $imgCanvas->coalesceImages();` I get watermarks.
(even with animated gif's)
http://php.net/manual/en/imagick.coalesceimages.php

Also the statement `foreach ($imgCanvas as $frame)`seems wrong as `$frame` is not used anywhere in it. 
And if I do use `$frame` like this:
```php
$result &= $frame->compositeImage($img, Imagick::COMPOSITE_OVER, $dest_x, $dest_y);
```
it seems to have no effect at all.

Actually, function *zp_resampleImage()* looks a bit strange too:
```php
$src_image = $src_image->coalesceImages();
foreach ($src_image as $frame) {...etc.
```
occurs twice.

**Comment by acrylian** [comment]
The first loop indeed looks strange. The `$src_image = …` is probably indeed doubled but the two loops do different things possibly the 2nd based on what the 1st did (haven't really looked yet what that is at all yet).

**Comment by acrylian** [comment]
The master now has the changes @fretzl suggested. That seems to fix the watermark issue for me and all else seems to work as usual, too.

**Comment by fretzl** [comment]
Yep, no problems so far with this fix.
