### ISSUE TITLE
How to install a ZenPhoto Plugin - do not find the backend

### ISSUE THREAD

**Issue by AlexL777** [zenphoto/zenphoto#979]
Hello Developers,

I have a question and although I'm installing a ZenPhoto plugins not right. I have the plugin ez-cookieconsent 1.0 loaded from https://github.com/acrylian/zp_cookieconsent/releases here and have it uploaded via FTP to the directory /plugins.

In the backend of ZenPhoto I can not find it under Plugins.

How to do it right?

Thanks for the help in advance.

**Comment by fretzl** [comment]
You will have downloaded a ZIP file.
The ZIP file contains a folder called `zp_cookieconsent-1.0`
Within this folder you will find a folder called **`zp_cookieconsent`** and a file called **`zp_cookieconsent.php`**.

You have to upload both this folder and file (and nothing else) to the /plugins directory.

**Comment by AlexL777** [comment]
Thanks for the quick help and I was able to realize it so precisely.

The Cookie Bar of hand involved coming but better advantage, I think.

Then I have to do is decide how I want to have that.

**Comment by fretzl** [comment]
Glad it works ;-)

**Comment by acrylian** [comment]
Just to note for completeness we also have a user guide entry on this: 
http://www.zenphoto.org/news/using-plugins-and-third-party-features

**Comment by AlexL777** [comment]
Thanks for the link reference. I look it to me gladly.
