### ISSUE TITLE
Full image does not load when using HTTP server on a different port

### ISSUE THREAD

**Issue by ludgerh** [zenphoto/zenphoto#980]
Using Zenphoto on a server with different port (like meinserver.de:8080) works fine, except showing the full image by clicking on the reduced image. On my system, I was able to fix that by altering full-image.php starting from line 31:

/* Prevent hotlinking to the full image from other domains. */
if (getOption('hotlink_protection') && isset($_SERVER['HTTP_REFERER'])) {
	preg_match('|(.*)//([^/]*)|', $_SERVER['HTTP_REFERER'], $matches);
	$checkstring = preg_replace('/^www\./', '', strtolower($matches[2]));   //this line is new
	if (strpos($checkstring,":")) {$checkstring = substr($checkstring,0,strpos($checkstring,":"));};   //this line is new 
	if (preg_replace('/^www\./', '', strtolower($_SERVER['SERVER_NAME'])) != $checkstring) {   //this line was changed
		/* It seems they are directly requesting the full image. */
		header('Location: ' . FULLWEBPATH . '/index.php?album=' . $album8 . '&image=' . $image8);
		exitZP();
	}
}

**Comment by acrylian** [comment]
I can actually reproduce the issue if "Full image protection > Disable hotlinking" is enabled. We will take a look.

**Comment by acrylian** [comment]
Seems to look good to me. I will add it.
