### ISSUE TITLE
suggestion for menu function printNestedMenu

### ISSUE THREAD

**Issue by rb26** [zenphoto/zenphoto#981]
bonjour
actually (1.4.6) a page (or news or album) with password acces is displayed with the printPageMenu() function. It's good for the non logged visitor information and must be preserved, but the logging page is opened, that is not very welcoming.
It would be nice to add a parameter for add to this function a little icon before the link for alert that this page requires a password.
rb

**Comment by acrylian** [comment]
I have chosen a bit different way I think is more flexible regarding theming. It is available in the 1.4.11. master build from GitHub. 

There is no fixed icon shown by default but instead protected items have now the class `.has_password` attached. That way themes can choose individually if and what they display via CSS. Official themes have no support for this yet though.

**Comment by rb26** [comment]
perfect for me
simple but efficient!
