### ISSUE TITLE
unable to install with redis session

### ISSUE THREAD

**Issue by Bodenhaltung** [zenphoto/zenphoto#983]
Doing a fresh install:

```
23-Dec-2015 13:15:02 Europe/Berlin] PHP Warning:  file_exists(): Unable to find the wrapper &quot;tcp&quot; - did you forget to enable it when you configured PHP? in .../zp-core/setup/index.php on line 27
[23-Dec-2015 13:15:02 Europe/Berlin] PHP Fatal error:  Uncaught exception 'RedisException' with message 'Connection closed' in .../zp-core/setup/index.php:32
```

php sessions are in redis with the "tcp://..." wrapper.

php 5.6.14
php redis 2.2.7
redis 3.0.6

How can i solve this issue/bug?

**Comment by acrylian** [comment]
Really trying to install Zenphoto 1.4.11? Because that actually should have been fixed in 1.4.10 already. Before that the error message would be correct because if redis is not enabled as a file handler wrapper it will not work with file_exists().

See #951 for some discussion on that.

**Comment by acrylian** [comment]
Have to correct myself. Apparently we missed to remove a check in the setup routine and only.

**Comment by acrylian** [comment]
There is a fix in the master on GitHub, please give it a try.

**Comment by Bodenhaltung** [comment]
Wow, fast, installer works fine now.

Thank you.

**Comment by acrylian** [comment]
We try to be fast but sadly often don't manage it ;-)
