### ISSUE TITLE
garland : issue with gallery page number

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#984]
hi
step to reproduce:
- have a gallery with 2 or 3 pages (tested with 3) of albums
- in gallery page, go to page 2
- then, visit an album
then, in album page, the link for gallery is 'http://servername/page/gallery/3'
it should be 'http://servername/page/gallery/2'

**Comment by acrylian** [comment]
Sorry, but I cannot reproduce this.

**Comment by fretzl** [comment]
Can't reproduce it either.

Very sorry for the late reply but somehow the issue escaped our attention.

**Comment by vincent3569** [comment]
hi
they are some screenshot to show the issue:

- in gallery page, go to page 2
![album](https://cloud.githubusercontent.com/assets/1224809/13913301/970a7996-ef45-11e5-9264-72cc5fb93572.JPG)

- then, visit an album of this 2nd page of albums (vacances en bretagne in my example)
![gallery page 2](https://cloud.githubusercontent.com/assets/1224809/13913303/970f46ec-ef45-11e5-9efb-7edc6eee9417.JPG)

- then follow the link "gallery" : it is 'http://servername/page/gallery/3' rather 'http://servername/page/gallery/2'
![gallery page 3](https://cloud.githubusercontent.com/assets/1224809/13913302/970bd62e-ef45-11e5-8427-103194f4a5fa.JPG)

**Comment by fretzl** [comment]
Thanks for the pictures Vincent. I can reproduce it now.

Looks like line 43 in gallery.php is the cause of this (`setOption('albums_per_page', 12, false);`)
Not sure why it's there and apparently it conflicts with the theme's options.
If I remove that line, all is well.
