### ISSUE TITLE
With Libratus theme, home page script also displays protected images (getImageStatistic bug?)

### ISSUE THREAD

**Issue by michgagnon** [zenphoto/zenphoto#986]
Hello,

I posted this bug on the Github page of the theme:

I removed the image-display code on the home page, using a tip provided by Fretzl on the Zenphoto support forum: http://www.zenphoto.org/support/topic.php?id=1409305 (I actually put "$_zp_page == 1000" instead).
Apart from personal preferences, there is a bug that allows the script to display photos from published but password-protected albums too, even for unlogged users. 

**************
GJR replied to me, saying:
I think this would be a bug with the getImageStatistic function, not the theme. Best submit a ticket with Zenphoto so we can look at it.

***************
See the original bug filing here: https://github.com/gjr-osweb/libratus/issues/27

Thank you.

**Comment by acrylian** [comment]
Hm, actually that function does check for access. Will take a look.

**Comment by fretzl** [comment]
I cannot reproduce this. Sorry for asking but are you really sure you were not logged in ?

**Comment by michgagnon** [comment]
I was not indeed. Same thing happens whether I'm not logged in or logged in as a user allowed to see only 2 of 3 folders.

I have the issue on my "trial server", which is XAMPP running PHP 5.4 on a Windows machine. Zenphoto is version 1.4.11 [26c78176cf] (Official build) (downloaded from Github 1-2 days ago).

**Comment by acrylian** [comment]
I am sorry I also cannot reproduce the issue with `getImageStatistics()` so far.

**Comment by michgagnon** [comment]
I definitely have this problem on XAMPP (with PHP 5.4). I'll see later this weekend if the problem persists when I install it on a "real" Apache server and I'll post my findings. Anyway, I have decided against posting rotating images on the first page, so if I use that part of the script, it is more likely to be on an album.

**Comment by acrylian** [comment]
I am testing primarily on MAMP as you know so I doubt it is a local server issue. We really need to be able to reproduce it. So any further info you have would help.
