### ISSUE TITLE
1.4.11: Bug reading iPhone 6 EXIF info in specific image

### ISSUE THREAD

**Issue by MarkRH** [zenphoto/zenphoto#988]
After uploading and working with an image captured from an iPhone (an image a relative sent. I do not have access to the phone) I noticed some errors in my debug log. I cleared the log and then edited the image and did a Refresh Meta.  This is what the log then shows:

 {22293:Mon, 25 Jan 2016 00:21:25 GMT}
NOTICE: Undefined index: Make in /home/markhead/public_html/zenphoto/zp-core/exif/exif.php on line 751
read_entry called from read_exif_data_raw (exif.php [1025])
from read_exif_data_protected (functions.php [2213])
from Image->updateMetaData (class-image.php [335])
from admin-edit.php [223] 

Looks like the camera is: Lens Model	iPhone 6 back camera 4.15mm f/2.2

![img_1765](https://cloud.githubusercontent.com/assets/8035962/12540117/770b03d0-c2c8-11e5-85df-795987290495.JPG)
Going to attach the image.

**Comment by MarkRH** [comment]
Well, maybe it's not a bug persee as it would seem this iPhone doesn't create the same tags or exif spec that expected.

**Comment by acrylian** [comment]
Just tried the attached image and I didn't get any notice. But it might be that GitHub modified the uploaded image but the meta data seems to be there:
![bildschirmfoto 2016-01-25 um 12 36 58](https://cloud.githubusercontent.com/assets/2474309/12549859/63d03676-c360-11e5-8747-ea66953a3609.jpg)

**Comment by fretzl** [comment]
Not tested the fix yet. I'm sure it works ;-)

I noticed something else.
Because it is a large file I decided to make it smaller to see what happens.
Well...nothing happens. No errors.
