### ISSUE TITLE
image uploading errror

### ISSUE THREAD

**Issue by dinezh** [zenphoto/zenphoto#998]
sir i upload image its comming error is > 01.JPG 	128.61 KB 	Error: true 
i tried more times its comming true error pls solv it thanks

**Comment by acrylian** [comment]
Not much info to try to help. So please review the Zenphoto and PHP server error logs.  If it is a specific image only re-save it via an image editor. Maybe the meta data (exif etc.) is corrupt or something.

**Comment by dinezh** [comment]
thanks acrylian :+1:  i got an idea 'zp-core/zp-extensions/uploader_jQuery/uploader.php'  file missing now it works good ....

**Comment by acrylian** [comment]
Ok, great!
