### ISSUE TITLE
issue on printParentBreadcrumb()

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#999]
hi there is an issue on printParentBreadcrumb: pagination is uncorrect when there are 3 levels of subabums : root/sub level1/sub level2/

step to reproduce:
- under the root level of gallery, have a subalbum level1 with 2 pages (or more) of albums
- go on 2nd page of this subalbum (1st picture)
- go on a subalbum level 2
- then the link on subalbum level 1 is correct (goes to 2nd page of subalbum 1) (2nd picture)
- go on a subalbum level 3
- then the link on subalbum level 1 is uncorrect (goes to 1st page of subalbum 1) (3rd picture)

![capture1](https://cloud.githubusercontent.com/assets/1224809/14834497/07c700a6-0c05-11e6-91d9-33a03514ec99.JPG)

![capture2](https://cloud.githubusercontent.com/assets/1224809/14834498/07c72cb6-0c05-11e6-904e-60743ed877d9.JPG)

![capture3](https://cloud.githubusercontent.com/assets/1224809/14834499/07c7e85e-0c05-11e6-82a9-2cff2282febe.JPG)

**Comment by fretzl** [comment]
I can reproduce this.

**Comment by vincent3569** [comment]
some others comments:
if subalbum level 2 has 2 pages (or more) of albums, when you follow an album on the 2nd pages, the links are correct:

![capture](https://cloud.githubusercontent.com/assets/1224809/14852448/9ea2f224-0c86-11e6-8a1a-aef6c6fa94ab.JPG)
